---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: matrix-synapse-signingkey
  namespace: synapse
spec:
  encryptedData:
    signing.key: AgAQXkycKx3AdAwKdLZ6nwloNiQDa+GIhZpGAkPx2w607o7s9pJAdST8qWFSWDcaKf/WJj/NtkfisjwVM+H1NNgXwHzO4uepOiOrti77f3I4oyLjFkizezPtSh2EGqf2e4oR5n0uyQKjLUeWbv++V0RZ78M4bTYZvT+4YivzjwjVCEnX2F8Zxm3+TL4WEgatFK1+yLsy64f4ZjRDscaPX2OxqA1dcnZWSeSgW3A3j9JYHP5FufMnkKW1q5NvOcMiHZSJJfONj0o0rjFdfXhfP5mMmLGesVQA7AsnC0gVKdwMrJwS1FNuNfrQuaAYeFzli1z+JlU70d99BiIAuSC2MmM2gjB4SiwmDG8Jv+hh6vrSzQC34ZTze+OrYisK8CLLgQ+B9aLBP8viwre/15aT5enE6Wu8+up1yZKsijmcDc952axQmYDFqokuBq0/LUb3ZSIom8dHYsdk6AZlrikIEP9swvpgVUK0cm8j+H/hwDDp+rCUPHe95DFNu1MxhXwc7O9ZcwP7gAFdG+NKDxgjp8lIcJNONT5K+OXe97MRe+ShlDln7eWDZ/kNd/FY9yMkgGiHyeAX0Ona3DlnBYjMGHwoO9Rle+6GuvT5zrtZvY+gXInpFb5z/oNCyPN/bfbOx8xmTfRvAu9bhd1qSPqyyfzZZJedeAB2nnN3aROY2q607os9nOLRdX/ZGsBJeewA2+uRi/aBn9XmHbgSOtUejy7u6D24juVuFt63/MroRBsXt5foGsX6Gaxi81cTjSVkQoMDB6aYb0KZTuMfOw==
    signing.old.key: AgBE+k/J0yvxA3TsNyxyYyn8PbiWEhywr43hYPBgaZJ5ZlcVn+5mUERP8jQ77wCZpaX3TX+BNdyBEMHERNs7qsvj//HJ3bEzrn2FYJI72l7M9bB+fcHxQwgLznu00vuZoxn2zwfg3H/JBYZGi7UmqsLyIhV4zhlY4WsvVlS/sqhsHD+3W/IIfO9WOeK/oJyylae9glNdqSDJo1w3/4IUqWU6aF//mQE9SHlGij7079DyTLJ6wVhr3ndafNzbgrDhX4jy8ILuWRL2nLyibfpT1tROtsB1wxZP1TjhWU0d8lDNZpVTqydR6+xCj7nFnux/4SBlJZz+CcTd0WKMdEV5/Hm/6kO/EXHirXQ5wxN7lDWF1ceC01za9XNz7Z0/J9wE71h+rgjj4isxmx6OsocDhhcT/5D4G+sJ6ER9aj8TkqueH66Kq6WIAf+IqSJIAGIi62QNxnQyeYnY1arUafxHlWj++gVROCi6LIaonjYTIWVvHxD0mLElPIWvbQho3mdsYct1NpTq7HxuX9s3Ok34th2mZSRJniKXXk4i9g7TipwbyzzlpzbRkn03VwrOEGSTkEQoIoMriZutjvd1ynYvxRDg7LqsG21Y6+Aou/hnW0JuTrX/5NkBYZBwjArVeXLCTc6v2qZ0H8FYVU0p3wRXe39VWzGQ2x7ciUctm2qDyvR+4WWFWBbUc0bBfofqB23R557izsWkpJqIpbskIHPh8cL2ec5Q8K8zLxDuJsptf5iVIdF+zC64ssdI/yZ7vQvLs3wUkdggMAhtoteFZA==
  template:
    metadata:
      name: matrix-synapse-signingkey
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-synapse
  namespace: synapse
spec:
  encryptedData:
    password: AgBDpypxlWdjyWYyy8qRrj2Fu6ndf4Xb8fhwq5ITiUh0ePAmtWNMvDYnr4MyKA/Nw6bOwx91KVadgC0WVuzwq7NeE+2PJVbdopfPwAXQ83kKOpGwJD4n1RgQfZt1RG2kc1supdP05Zy8Rd80SsyGhkkC6eX/ndU96NbK8H42YnJMRNtJAi8C3u92bXclnPJyLduJl+O33V4k9NAyUys2xFyL2uJWkkF9iH8gQnWFX2DKeMQolzvXY2PeFE2Isk9zKLDID6U1yOHluzf3PGx09t1+D4/urfsX0WJCvNB0unP2/HXGngC6FNTfVTANJEH391JqCHDu9ICnhen38ZRcAkGMJ1o5hgCKqdFsJ1+nT2rjBjN2P50UhkXzDNGx8vhL1TeNS3fZYWPbDFWpNylFbB97ZwdZOvp0kGQtpvipP4xHX+YnJSqo11UcTQUVot+q+2pNF/zEhyi5HwqoUPsF3vf8u3F37X+++UXv+/YTtiARIbj/7UDkcB+X67yN4fK5m8iAlM2gIIHwkv2oBJuer6UN0gHvG8VuZlL+jfGmAvksesPgMyA9ufS4//1IacaGcRYQErFVV57aSyvvh7ZGC7+IO73F786f32XIQO/q+VXQz5rtlfFC+tpC7aVUXGRz2q03I+UYC5mcsjYXa23Qf0HDTVvleTXplzGoJJJGlzx/vMCCLxGDR2FEoEk+lZs++l9x/SzPI1IwHNSG9Nw=
  template:
    metadata:
      name: postgres-synapse
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-synapse
  namespace: synapse
spec:
  encryptedData:
    password: AgCfRzsD4eU7ruECK/XCW3fnkovL5ftxng5JVPUCjdPvwpiOf1Rq7Jl/2q38bteuY4wEVr6M6wcdWuM8y7gKUBnC5lQwMdJ4TNkQgGiDCqV0pVl8bBXe7GmVVVmgnAuwOZ9qIF2flsnJlMASgw+DjeD81VEYCzZGjsbxxGA8rzUfIJGPamQVI/Dt4z1O+RNC9k+BXqknuz9IS7/pPUXLelP1bijY1s50gZY146medDe8yKgIVV6vAjgmtYSteEEhNuowkHg9iJ90SuBpc9dJ5BMXct8csc4P+nzvmQO2fg/tNunzJZ1diMoEaUGr5AJa9g720WkDpyY8jQklxkKKNJM+62t2wKQfJgjdGF2k93sBjlEfog2OSPDvcvssAVz5KSZOAoYCW2fq3VMqnPTYZtWDdcwdTPds/lYlXz55o9xPdra7SvvnakicflUz/qYh0ovgn6KSR6MlFeOzC1YYnC1exVLrxe/qgN/1+Uh3K/1D6ydfCB17QRDGD3GCwLII+Lg56c+dJ3QmBPgaj+pTJd3tn9tutVl0bfI45E+tuV4PsY9vepHfJCl4PnxVRqUq8DKu3WurFl7GI37TUI9T6nBIra+zmfKTR7PnirU8epNLq6/eh9LEsUSmwgmCtVtcapC6oFOsBVgSeBiOc/ahBzFpiomzBjT1pYBD0CI/0pyVyGKvoJVbeYbg4eNahYCDg8BCPa10IRubXPBSyLzHZ8j24ueGHQ==
    username: AgBsvRkTFsgrkEPI4cQedF0dnNY9BXqF4WLGJwY5U0IPALoho6zFoXb9xtMQHBUGHtUmyv/eQNEnnzK/8GUTMFMPm1VpnifpEIfegRmRGyJL6ayRhl6AMTXpzMAJNDsBEPZa9ctQe/DfSMTPCzbITU0/Xn96mWXX5iQhy/7K8VwqdczdPrI6SC2F2zKwoJD0cWzIuPimhtSnFL81kycEwdfjbq8hNQW06Q4syfRvQlvoCaDyZwwH+DLmcL0QKDqWqubmDtkDezpXHsU4vPpptLb24IqSee8/aUOdomuAy1MjvBOP0MytRuXxpVOir+mD8ZPLKqgAE8nfGB6JnW3qhQj0z9mPxYXqOPlsYIyIVe4a/G76tLgveVMY2+2Ek0/HIHISGeUXviIBdPOUSHAxFPSD0WUo/nq6NkzQViMadIJiqEM7wg83iymbwI2am3+liuYvgQ5BmlDCjUqH334sFtsfuuuuqoND+7oituwIuWTevBSQl185BiQqnE1RUoZ3Xw/83odc/VlRYX7FGrWQOm8jl9Uxianb1gvSguppXHSE6nAmZdgPufTKRRGJf8VjbBbOeP2HjPzWG1p/ypAXGKOpmcpmmzwQGXHmQuCdWaE5E+weR5mjdY8qr+orgZxB+XqLmare54w5RsUkWq9FHmpi1QX4DFRNIEIDTy2JBEgRmO+hpWibvcPcuFjtmmUlz7zswX6EvLfT
  template:
    metadata:
      name: synapse-postgres-user-synapse
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mas
  namespace: synapse
spec:
  encryptedData:
    password: AgDK0Mlph9MozKgMvAuSmExb/3e8jcu32aIvO60WBZE9hoQDeiMUZ25FQTAtMp2yc5v+LxrOYpz/GbrdmKDSoY6PeT559C8vFaOTVqIMzfnnI4wzxAsM0QubDAzZHXRtkjnO9J1E/HLJfDIZSo1bngnQPOnINJ46p2obtbsinJBzXE6cUEVNahRPq8CSdoJblMnh4VdIjGORIrHc9MNuBKqStgTkRHKceLPkI3A8I8Hmz8DtavHYPTx1tR02S5LDhDCiqhD5TFYvV0FvlMZYINSldGZPeJ6TMEEQTfzjF16L2Uat39Epa9y088FMAYZcN/vfiE18EHo7Z6dxQSUslr7eEcxR0zGAhLT1jqX1X7CeJW4ckYX7YzG9MDu6mhhY1IWziO8ypJ4XcrR10tt2Wmh9eQ3ctTzigrMoNHa0EtmOeOEAF3ItOy8WdMDSLruyMFiyP+vtjUd56HLqmfWKLhUGYtxYVx5zXFSTIwubUeXxALFrmNcxm9jK2B2HUsn9yt06iXq70pCi1veVU9yVZiWf2R2On0CHwzW50usF1k12GCGXuaEYOODAWJVr/vBw/wKy75i704HII1ePOW6XH1YPMws0f2Uus1ZyGKLuSQxSl/Coz4OXOUeVHasLlOpH/RYjonYR1o+hJ2pYRGhgBAnJv9tGF4OOjLKLrwhO6B/Bk/fl6Ak8TnC+F4S3qMh1Q86exMwxdyMkR7RSGLy0Q7yUprAgRw==
    username: AgCHrGbJvgeNokwI+AzXaKDNvKSPeGXr7ZPKnt2eRxXBuNpiu16MV2pVntdIBeSBjW0/eFixJ6W/M1D2WmqPkzZrRdnzXoeaUZ+FBPsVtU1W/syaYTatk2KbRw3BCSjJhjM/NS2BpK86jmYwduZh1bX+Mwd/JZDArLrwP/RSNdsvFDbis4SUxZV5XP+p0GdIx/6ugKJXXsLokodctXeqTMLo2+CMQGxxghWolYt0hp24M0ve9qUckhhfeZN1gNz6oEccVRR74FJxt6aob/pCDJJKM9LMX4IQ12QwKKAGUPk/C7y9eHcjlRJEFlCDMZ3rO7MrZHJRQXeaUOxMw6xK8i1rUMWawO8bp2vb+hXsCdumaxNBZfdFbUdeoTCkUxtT9IELaIO09B/HyI0UdexDEjTknCSp4seMDlOBR/0V554irejq/H+iPW9VU0iznImx+dJ/czOprUT+5FboMmfvuWeV9eP76+EnGP1S+QYB5PKNKeDlhTPTzAMwbc99UYzOkDFieBWfAeLRYd54QmgMCdDyoIbo8S+9/CfcPqnNm4gr1rn6+cmBhULH/KnF4ACnf5R2OuOdXM7Ac/32fFBAf1+OJHOKDFuc4EOoO56il68y9dYH1DbKVPtoPFAS/rmJh8p+gqlRn+hfbiBaNMmohO69JoCJC3E+SkabhtpIvNiswXIb/+5nnvj9Z3JNb+DAhjyPohU=
  template:
    metadata:
      name: synapse-postgres-user-mas
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-gmessages
  namespace: synapse
spec:
  encryptedData:
    password: AgB3jcpf+raRM4o8HPQUdj9BT0godOlbuwsy9WlNjANr0Qs/k4eJ+/IDyJH3yuLIyGnU8AFk1W9OhEkvuQYgEHwIf0XwV9c9SP6XgDLVl1IUSb9tfQv9qkE9KYxOadujzAVZ0IXDtsUxdu5DZ+Umc7TV6o9I3C4GMTo2HpPA+aI3pAjkC5du7xy46G4XV2C4QWGLO4vuqvVbv5W6xecaZgyY14/hHbxhk8TYECdnDiTTEmCQuGnxmDvyzbgbDSlvKIMPHulkqocBTrd9aK9m1Lbwh9fV20suUDhca8efiO2UGCy86d1hxGl1vlnazBaJtS3EWFATu2ek15vARS2C/Qo8i71LvQXtZf/1p1M5c69s8EvX0XdZFGDhiDzr1QZkUHAh3wHgQdx93NgP6ypZ6V/5SwAgefCY6q9APrCwnRCjBr5GvIQhkE/qvUUc239AGvBOZD5MKLFctEZIYh4MetcnAECW6Bqf5bgvjiFFpe5vVkMLgyAY3wOKYpO8ZjhidRhfBlbe0NiXn8Gvgy6fTY7oRp1M+rQe/6tBkJl9h0WwCGVHxNhIkqWoQSRekVezh8zuF3+vLsiPbZ10OfVBO+mP+Sfb2QWg8waCGNwJw+8K9O/VVhQg90LXYNSI1Uj21DwB4Vm7nOK2UqAAZTJWVeDpNPQ67CHxK6VCH8f6fNTIwJsqbDkIV7E0Nw0FO7DMj5Taixye8Jckm6ul1uoHFTuzRtw1IUhk8CY=
    username: AgBn1LiIW6ZzJahjOuKLlMC9YJ17nl9rP7RviiJDvMw8QRry/BtYqaM584TVanaEoqVW0traaKWTKH4BQWiwS2AvdrKr9elVsAxyaQVEFyYhpJFETQszWtxLQvktURm+ElP0D9sMeRRPaV1n4Di9D3lgBMe0t3WMA2UaHjpOjxG/1RFCBtvykivEAz70GgRSe3eDWXjRpTZb+sj4mG0Dk2NSb78mrl5JDKrc0EIv5Bjn1SDYCyAPlyO5yXg/42YG6MXWYYHJb0uNhKrkzhOoK9aPM40Qf+5PinQLyxoYP/wNwIn5IU6C7pBEJvIwSLcdYsdNcQVDYOL7FC65Lt35p35vJNU2esPBKf7HuTpxyUxQ9GqsF4pb7GG68+mLWxWWeT3Br14CCwo/3V+WreNK1kaqAVWufigk+5oYxAMvxjHc3GVUglTxPVEl7NNvSL3q7Qf8451mAAyJJzR3o9EbJ/wz1ncfyRQFtGQJNVGBOk3obM67FzHJV+VQhJM7TUvwqYsV7B6ew5HSx81SezJWL8Jn19JCS+rTW1AmAIDTjJyPGHK9EoIoqMi9BQA/zQyaqFkFWTwQe25N9D+5WEqmrhJovB/NPTK4kFuMTtGT91XvagvVrJ3PQLm7jvEoKYXcjnR+hlNFmeCd3jLc2YybxruEwaYImBXqrB6pKrATSdYOowimL8csxgGjnXmeY6s3Q590VkXjvxMWJFWj6pwf+QdAjw==
  template:
    metadata:
      name: synapse-postgres-user-mautrix-gmessages
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-signal
  namespace: synapse
spec:
  encryptedData:
    password: AgCTJnA7GYGUvoKLKN//592cKUplrhySoqMmxEnyPQqa2WfCPMwpTEEEM3vpHycyqUoOCgW3ORsA8xuXue9MQWwrS2Y4DHK+o0rC3FyNL9Xp8cWLc+iqK73hffbA6GYfcmh+XW46iqqqSOJWi1nHXVOrGByHq9tHVxvQdzvRybCy+ZaouZbgY4F8+3G0PtF4yMT0PVLcy/IoEKqms1V5VXpGtPf6xS2hfj2ZFo8mTKIzq0vAGeTJNR4hOOGN5gjo+tUyDjNq3mzGTbcyZ59kxa6Fb6yYHmFMNSZBlNj40NCkuwcleUnRnNxnrTXDzI4wCbkTp2o59ssY8ulkHtlPFiyMf+zEy5rA+2r2wYHlfyJbiqA4IXFg9+QR9Aj80/TUPRoPocJOARpL3he6QTmLLuDHwdmHcPyASSoxPbOl9qwbSeK7lUMMmGfh72opgOIS1Bk5a0QREKJaTFwZmZLVDrwidx7XQh3QWSFjVkD0dduJ1iRKxwSgFjukn790Al+xKj44c/YgY9/yXBQzLVsGX6W/xQk+Uvfdr0m1Gn1SxPTzD/ODNwSxgAgAToW91sxlnzYUcpC1MElEmpl0bMFIDy4XkpkkTn8ZXwjJQv9PB1MJjhoCLh6IRsMfcivnQ18lXJ1FvE+4hYWhi89iMDYe2sQ/p9tkpS524iZCZtG57cWG3T40oFZ3bisEievrebXmRuJGBUTYMYWnWDEbmzWeyu1/+czan1QGNlY=
    username: AgDEpz7LmqxFcEZ0Hc+5SXcIdxbQuOtFO3ZWUbVR2uIAnbMpLm4hQpcHxt1YYd1M6cOI0fzYF60SaKEYWQLDpVEjIxifFxKHQox84GgIIU1vVm7h2TyEV9GdRLKDRW5V977DnSriL72m0WjWotOv66LXF10qTIMZZsiTn5H+a0JWGF3kHNN5dW7A6sTBpocddp+8b7KrwSUme/MDMr/Zji5paWK3hKMUeTbsKu9HcFwgohKXlBmyEo1u2DclOJB5Piti1SL0f83Nzg1/z3EEkGBDgmlzsRkrTZrCdCjt+qAcvgEL7uK/ZMxWqWFWWYWBTwGbOvpg+Fhk75yadhj75TKFqF+3RNTBqdMhTCm6gjRZtIcqa7yawoFQ9chOmIibvNgiASJbjhgnXPk0cfq5LRO3JfehCXTvJrMMsAM+dNDRawgjOG4/qaERzmLqIskMvCvq4AR7N8RoVCdKZ72enQ2tHIzL7kgAFaW0E/As9kS8VTUwWWQWpuE5PWQ7qmjK2aBzpD1tMUxszxBJx7YU0+t1RH/RRZm82vGZOzV480cx5rQBJVgUJ7v0idOoV/fB7vNw/77uzLxq76fbyTCtsRvFlM5Anf2GK5osmJDvIhCtAxe4TqusM+hUoiL68I1gqpALJdcnFKQocCGvNBPChgVEIL3ML6w7smOv0EJuOnF8HqhfU8U6yyopvBwX3Eefx6GmN1M4TDYOUgwcaciV1g==
  template:
    metadata:
      name: synapse-postgres-user-mautrix-signal
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-discord
  namespace: synapse
spec:
  encryptedData:
    password: AgB+E8WUc8qfJERk63ikTS1daWszUtevEwyvcOFD9zZqs6MEkUactSAd/WBNW1+cRDYXXNYf1MI0DYLPfBK21f1xQZVW0WB+a2D3uNiox4isjnWWe9NUSyxSmHGuO+bXTX17+Se6daNkxkRsQ9KKOL+RYiZSMq+f9V/XEmw1wtVcBITDXadkoaYeYNTWV75cQPkW8EVal+zP7m9yxfq7mFYVNmi46ah45YT6c8sCZAlRXYkXzVkFceYBWGHKUajRfFwXwLUST5LkdZ9rxXB4vlwFz5YRF0o4OOunTfyQ0Vfh+6PhDOUunGVBPYELom3DXPCPBDunrSgw6LOflYkW2M8avT3jwDFlOsiwpMSegyTfxGvNoIcermKIF69vKWGhn7EZqNQEr0giAkqLutfTpRyVn1XUShnTD4B6VsushseRXyIcoZ4kMEewjMZ/PQ5p+M2PymU8US21znqJsgX6/wnLy647lcODjrSME3hRLXQs3a8F6mw85WQvwu+SHVM7YzWH7EZebvYAfMdTOF9iXU1gXYPex04Ocd6sJ6IrP4FYD6lae9RpOUa/R4GKEzgUuDHkuzLO6xIMjoOhxhfYWCfvRkb1dJEaulFpsdEJhGlcCL9DMjGZx4EwgO85dORCEx5yDkiHvOPh3t0pVCTZAJgdDqphFRFiWAZfKFbXmijWcY3gYHxmJ1TpvKCS5gdBz4nacPDH9tQ56vVcNCo=
    username: AgBOxqmBcoR+/0ZO86YYj6kv1SMtZjOvALhxYfInIQY1O4dk53XrSK2fiPHJmYNIECR+/7tFdiszROpp3vXCho8FKkEXmT6Lsns591NA5r0wWhJvJRV7LjndTbBrv//k9dlBwJnY+ee+zfHgeoI6i1eTdyvsurwBvB1mtfwLzvGqi/fm8J5q5RVFwu30NfUDzGMdeX+l2PpRkxkwwQXGjzz0e9WIg8ju3YP/Wx2N5lzC+53GjTsdDB/s3w4aXRCX+y1zfeTUJi+sfbLF2mvjMULQVhZwAES06O+F4MB1jsKihoFUSUyUMV4BH2AGmObEoX8126l8yE2B9eDPFN2if+94a3BfPWOBPkfjHJMXjf+qV+iItSuVmtDw/N3CWSdkbGAAvigEF6p+Uw4zm2HjiFGvQQtvn/7ZBWGj725HE/6+Ctmsp+TcmGe1V9OS1wPG/xmQQnz5W6A8f/QfGhBQhU+TsipCQ5ePMMJGbXT6Dl6yb5p/4az8iOIu1ndxXHyTKSHVa6ZJaD7k1+IyLP6vMe5129Uumt43+kGMSOGNDN9FcClZbSqIq2fzk9znGiBTrmQgswdg2253wXja2ipyk0o/Fmo7vN6HG915c7i9fvHWFZ24sQ2fByaR82QAIJYOhGB+kNjFOiMTKDtpDenG6WWjxJBx7jfNMfk/12molxuH4Qy1hoU2hiGejNGOzbiNS+Y4a8kXH2XymmtvtqnrS8E=
  template:
    metadata:
      name: synapse-postgres-user-mautrix-discord
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-telegram
  namespace: synapse
spec:
  encryptedData:
    password: AgBSxGqbolZwhoVURgM/Gk8nH0qCzsZ1l61Po9xrSqs+PYCWGYqaAZaZgXLANMaZPOnUKAyvAECobG9BL29ydIFczldXialiFvqB8Glpw6XeP29BgQaQNXik1MBAmmzeMclCCdaIjAeZyDvHUEoDto6MYGL7PX0gFgsak/B8wq5ly/vO7LNcKgcvYTK0zIrE6V6i2ePP54qLA6M72/iDDbKNdPrqDYVf5J+twBpgOsR5rggLxI3e44ygE9r6U520WU0WjA3rFx0jdIhg1XFor5Lb+//Zb17uZc9d+ZRfBTPAUo6QfnCJ1naoscZn/gwWqe8we1aKAT13xIPFybYd0quzNExhsaSHffzT1IzQ6AZpOBD8dYUakU9lKhtTm3K3oDl2nvIao8KKPLjuT0CYda0/kIh/b9CHm6h97m+QjzYYlCSbeNyPvDB47oWWcRqmiy6INlSRsjoSZs44Rhu6fA4AlrgAn46Uq1zV29r+ibgIP47e6ZXk9NTPshp6uU70VHEonemdsfHGfmZPEDTkeDHMTnJEhULeCPxIpFDUDV06awLHJDWG8JYiBHtQDUy6Usjek8LA60rskEymWujf2s3MSfnd0LgyvtnxyJFv8Wfr7JMyvHIEUY8xPtJl4c2HKkT4TQ+kgr4gdlXaQf2rg8/XLYfibx/6SbPqXXIrAWdOOC9lQb5wX2DbAwsR1iJ+rbuIzRHpc778ZoIK/gk=
    username: AgCP+iDYUAC1UaI0cSmh1q0mYS5bZC8eKiH7SUjv3W40sFeU9WJ4eaw2EPzJi+6haCFlxVj/NYEJMZzvzkTBV6sl0FxAz6C8q+LlyJQiKhaM97LsRfG7KA9FW7/aNOSmFyFfTXto035IYRAxviDEv/DSs7rEJ0Uy84ei7Q52T+cRSNLAwOPiPsOdFsDWji4yqXdW/d6mSdGfBkX/HwhpbW1ME6FmgdAP79hyNIRGWfICex6rWG3ei21q6Filt3gxm7C13XuktJQhbwwQa9P2ZNQghXVp9rSBm3i4OqXZPw3tvwz4at8xTy2SeiBJpy85JIKYWRS+lzbzNgy17ZXqBPGuRKxGl5pOnTaMnmBSpuQTPugrapZDPhnqgkoOEE1z3+8eTqDeH7SHHF9NS07ROf+Sti2j3fddQq9fwEJiXKk0Aa7hyk5AEww+B+ehcECpaixF01a1iSyfg0rtFLX57m7GXohMdNvO4ePXKNBNElDblPS8HMzHIBVOSN2hltHIi0v6+SpDi5kaLfx+p5Z/ch4dZawvR5iHqDblQiYW+55+cIDr07/BsddBEbeHJAg/l2QRyU3LZz/g53UYrDJnl/BuSgw9u3XCpYb8bNzmh3TkFICsVXVby4sofbtzeeIYSiC1haYdqVF338KBkFn8rESABvBpzIw6q5w05rfULNj2TieO0M/H4m+yaU5j+I+mVIXGy59Eq2SwRMJwz1LZM0Cz
  template:
    metadata:
      name: synapse-postgres-user-mautrix-telegram
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: synapse
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCTYZRfXvows2w6zrpc74QLSoAKzEuw+HPJxvPKdt6eLaUSpk5zhJw94qZtu2bKXPRbeZrlma2yX/c12BNjtgrYpEND8FpJsT2IZE9RoswMMrfFWpKAR0nS7xP5eNiKLIiEo1SWEluYo7nSY/4J03XDNuAR/3ca/3sz2A8b1M3rDM00Vtb/hhLpd7g5PmO8sApUtGrnYjaqEYEstGd9MuVWsnlDNU8PTbvZQ/vWxvTgDAZnwqXp+VCYHpzUXdpDpq2vf0Zt1WqAn2y42a8FC78HeuAeOvhWAHArbSgLe22JWO/R0P4rkbeyHKe1AEaVuwHjq8pVUUoSER5/0/iX1TujvDhiMmXB8LCbLEd7gdRr/8WAMuKE3cdPaxbsS6yfh7Xjb/OrEU4LAJwt+fujcVEBeIi2rUu7ccj+AOHtAbxyewElnZyL0TRAVtF6XXnFEgzKcJcSepA+6mbsxrgLlwocco76Su92ENBCc3qYUjSyQr48HhS+2kmt/w11ZpFfJ7SY2Q5AUNUKQxssw+e5o/HdbWGRHAwzP24TMnwwOkRRGT8VpDtzK4d22EzIs4gdt10vJEzuWHpYgA8MQOs3nPeb3YScPRvul41lCTVALBrqp/Y6IgwL4mp3oARnA6C8v3dSMM+FEI68PeKPeqBOEOlU/9f9//KeN7Ufe6DVarSAjKKHG5/Qiz/3V5P3u/AJJpUxf+K2OsvinD/PwJwKcz0IYzD4QNTDXaN5
    ACCESS_SECRET_KEY: AgBbXWiq3bPfetKHbNrQIY38J7j4F//DFwwP5xTIq17+irjUo2qVDf9tLzmSB0kIuN2bmJNXqoSR5MIhpDm9NhBLfRbzJ1knVoZgo9P0GTIvL6kyaxdEUr1DMT+x0E77PulyZYEEcYF3uJnavmMfAV7kWnpQNGNU18v8sQmdYI3LA15cfdP17jIpgz47M84LqXfau5nbl5swv69IFy5w+cuB4O/4C4Bw6izp6mdW6czUTyVXT1JCrxJeHOx8fBRRtPTawEM8WcN+0ELAgsxnYA82moTl6nX3ldt1+bx/ldSfHykOKd3JNLXRzHuiyWDOPUeJR4j5sOgfmxwumtsWkj9gZMwXPgEXv/RjnI0BZ/67GE0K26ly2pFaRXw19Nu/zM72i6kZG4wX6ry3cjoE6evZh5VVDIDn8zdRIXnvQ6VaEjZnFuEMRQfe0pLYPRzbjJjcdjvN1OiVQTWE4UdffIti9tw+sb8fEP9ft0BfP904aO0SD66M8ptdjv40uVznIofHIXfya420J7lXAT8XqGZNTsBmqtEyN72d6BRcM9Gh6S8xJPIGCuENzDYo7PpI24aXgL7mC82kvANICfq0lBo5vn80pMCDO2TeKwZXr6S0XdKMePC0/kmhFLA0tGwTAYE61qVN8vWjK+aQUlvnZsJJ9b8JhETIBmAPIVKYaYeSylBDiBRsv6vLYgGUWxhYi79im/XAiRUxW5TblQcQhlQNmo4Gvv3z2EqyDpjZDGR5
  template:
    metadata:
      name: backblaze-creds
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: synapse
spec:
  encryptedData:
    password: AgBGRtLBNLxG4kbzOaKrZNlgNAlWkT111yRtgdfmv87vUBfTV0W9ixB5cUG/SVxWPKOLWObtC/3R92ns/ANPZBDGH0RE4TCN9hHRskzguWEZjuJUO/hOvv8Un+SKQBcHydIHtxZUncJrjf+OLxAi5Pe7pkzG0l//yVRWBSx5asZxiqiisxb0CSqA++nNnZK+8W+WGQtHG1Yym4sZUS6X5cFf+bgydkjK33j7tmQgKoNQirHAA0AoRpIHgpGRsK5YxMjQOXR4PqygEqH1jLqZijBmQBp1G/39UxHqneh18RLGOPZi49oQm/WWkgmd8KBo+z25aaYwvYGRNNWgby4dvv8QeSy1lfNmZmbNVScUYZsHVLqC8x3isulBQChcvm5fQZWQubwLLielHiIs/FHcYqAZFQWK/X1W6KEwbrgtSob8lDFJWHHd4EeqdnI+SNuqJaF5SKhVEbeO3e2tUDZae3YTQ0eqzR2OKGidF7NxXhml+ztSz4y1HlZNy0gjIUEwZG/L7ThqQtJP2wUyCBbVtRnPNhaMfXb7DrIxOp24DChn847TEneUwazu1Xr8qGWPmVhwPi4Wocc+RFlrb5n0K49GKy/CtNMN1pstkkpi3aedwqNTjqhD6h+R7JLFoT/okeEKVrRN2AUgSG4TRrhAaBH/c/vMCEgCKLwdOe5b6gl6hUnf31fv7NlZgdAC7HGMFBWnNWcSTSI3Vyjxaf8=
  template:
    metadata:
      name: redis-password
      namespace: synapse
    type: Opaque
