---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: matrix-synapse-signingkey
  namespace: synapse
spec:
  encryptedData:
    signing.key: AgBrdKpE4hBF2Lm78Q8W+t2iFtXapPL5dw5ZZNvoATuYZRipKCxYItjQztJRt5f5zPGYyXqzVg5zqS+ZBpyKhVWVgARkqEI+7PbwQFw3uANJ1yXxtiTLArtCFhBzam++32voEwit/P1zXzkLWfO97Z0gVW3fZebfsOBVXV5q3hxvlSkEn7oOCWaUFFgCc5Ymmdpl0/E4IP2nlY8Qj399L48yvYjMAvaFCmndKoMBvL6/FDsyR5w4OZshnlvVmr5n74//wuSDHyb+OnJ//VxhXRmmMv146Dms9mzBZZB01DDf3wy8Er4cyGP0poE+K1jmUZgmOq8d7HNXJ2ce/OTiTjaFoqFDNDRToDjH5uMFrKZSc1SUAHgRpBhXvuvV664CUJwn1Po1M81YbrqsFPwiCI2b4UCxKb1KEhcoNTPgZJwGqbpNd0IomU7NBwxWlUpkYdegu7f3KJDIVeXjQ86GtXArnMd8y7g0bEPOLbwn5RuCoRW+SZwsePnUk9en8A+rtuGQs3subkZulc4UW9eQWKdO56ccBC5V2a2Re7K5wjThS3Gu6UVzg+lHmXfGNdkrSwpQyf3B0FnOTXFK5///Fy+kGotDEoqY3HNkpIAu15+44iFjCQj4reHYPv+R/9bgPl/wbloKa7ayUKZvoRbpyM7ZM2ADkgwzIFW7mCQOCwADHnZ5ORP+dwVHymWw6mzosE/7Hi2pVY/NOpBf6/H1cWJMtiGzq2MkvaFCu5oX7sndAXaKrRc28pluNC5uy/BO6g9WRRjFz2h7yc7TgQ==
    signing.old.key: AgBIWYOgc52fzmDLZS3VjH8/PNz4gErwwVR7a6G3chyQ4TBF0yXGegnwP8UQ+54Yq2Gulgu0o1ddMDSWT67YB0UfKjkS1EHI5kHDjKdLGrSu78w2hw3c5IU5bwCzw2uV5234itRT1+pLkbC3FDTNpdQAxJrxZKSHYid+SV9oixbV1DjIKN0oBw7WAQQJYGXZ084zPGoCjPCRWoxFkRypA4K14DBlEbbRqfUNBMV/Ypgf4F37mifoAml7rB76hhZVf51k5jgfIPe4SSnbdZy/6+064hfV6w6N5PNH1y0GoiyaanLococrI+Dc8nZ8knV9Fxg8TQM94JOeLlYWzcDVQcoisrUKxqqUNJmEs5tOJzh3j8JVYrt8CXJih8PTAxo2TjX1W83YNzRpbAtR7e3QA2N6y2N1RU4nFKHbuea/px2JwdTutx+nfmCJqzK2PAGX7f+l8RKg8+IccX0x/JtZ6h/4MDBgVtNd5E/Q4SkXGDt1fwyjUTwvNEBESfzPPWFm2doX7qIgE1IQE5wNWA4ISRsfkrU4H4iUzYz5S1Irggdyx0LFwRc8mJpFFruHiYIuqcyvIzt3CowPybJQ3pdTRoTzSmFaiVx8dQXSq0+dsCaR9ouQ3qgiHAF7WDeQC8UpknmBLRWbX4R5VgrLaBowgZUA77WooIMvF0QOTIZQ2TCisFqpJkOcRvb71d3zMwsc+kKouGohLZwHjH/n8QtMDySjEQ9nNdWA2mSVnLTv+GqQGCbeBaUZ2IEoD+7Q4kD/II2v0YR0ORfx47/zgQ==
  template:
    metadata:
      name: matrix-synapse-signingkey
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-synapse
  namespace: synapse
spec:
  encryptedData:
    password: AgBZiPtGyFNIFfogir6eI3M8Kmx/ziv29lDDfZbvDtw7EETgmZHjYv1A/eLwQic1N1NSZXZGiuO+8uS0ZLbu3doeoxlzUvGoXi0JAjUnyyvzPbBYAJ+MfLERvIzKJjVG20xYun/dGoUdQezIyKXBs+THTqFBWxO1mqIwwVJVplt0BNKLKntXm6nKwxQS5ctwp6fEPjvw9296FbrRXJ0glnUpeZ5yxiSm2MCChdSBX/T1i5bfXwmRkARPKvrH6t0GpSpPwG745TJk9GNhHKLRe+Cd2FKPsojWqcy7q8JEgCWntZtmSIAKqDWGlNf5WECfY0DMbm4cbXIw83DoEIzhdt5zGZ9eqgaNrkny+J14PS7GOhyXLef7vNBu4Ad4Ary6TZPZ74Vq9gH8vXoTZmTqNjgvv2mj62Lq2HqyVpAkCbyeW6Cui8ZQ237j6VmrJ7etPdNp+Db6wG7Kfx69yjo1oPfZIUyfg6lO6D9mDjEtnCOX+xuoIRiMtVjNsxUTuSx0eI+FhgG/bFRP15hleWoR0pazD/oNv8aBK0zTGwlergm1wa8T9QikrpG6cDa3IStCkIaCuw6LO6wuGdKxlCvrbvSj8y9Dlf9QIcoBhlMYudVnI4NpwtPG056w3MVSA65hJ82iHMF+z02k+mpKphEepGkQU9KgUWBJ9pjhV8KrZeUNY2e6M8CGqvCO4soE+a6m7tFnfX9cbpsUAZU9YbM=
  template:
    metadata:
      name: postgres-synapse
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-synapse
  namespace: synapse
spec:
  encryptedData:
    password: AgBCgMqGa0iyLK0oFmK2wnpIo7Ti+1r4vCphkO9LWDA2Fccgh1oVqf9JiKfmgQX6LLk7dP0P9BAEFjk2sSzDdRXhAvOYg51WYr0y9G1H9A7QEtuenNXMShchqdz3Blxtl3nftfM4s/VTwNUM4sjJoGPA4PsuJm3h4wG54rus8XVwuyOBPnO60XmoeKbQV5SCKR7leeBic4JQoKmZE3yV4K32cpJMgTmhNIO+vajACitEaf3kDstiXb7S7yWMQXCEKhQ5niFmXnsQt8/jMPTWsAj+ATsRivV+bog3Qt6Pcqw+GSA7pdmUQVd5zzqMFzf+s1VMLQw8MX0VhnsBg5VxqZ5eGpYs8jdrma6ApcNGUZ3cdJlcNhUDRWJevNYrk6Ql/Rhn3u0hfzFFibk/lWPmNRON7VnzflgI8FIpszM2uB44m1iA7wUK6h4T+C+7+Vr/+FS7C8rqn7DEResH5k9OstmKoH1pXRPtntmBTgBl1x4+8hAdN50BEG0IvuWozTKApIZ9dAlx0IS2dXBdntFd8KoOrnmkEn/QBaqskZskhpZ/6j8HMLtqVBpA5z2IWEqVPApvbyngA8IOMfXLKcBmDvmnB73i1rbjHgJFmVWLX9ATjaZMj0Palw1S/Mj1ysb4Zes5vp6hB8WIt4t20NGGPT7kEn4x11Z4mjZod8q4ySO/Np6XL8Zb/lutEzesyyefi2hfbH1FY2QB6KTU7Kx1335RZlXv+w==
    username: AgBWwV57AswOC/Of8FWqc0wIoE0XTOsDP/7zNoTwv4LHwgbqHEGogNdRj9Kh+KxxBtOfqo6vrEUmuX3ud4rk4g6d2SVdydci98NX2lnr+wVYIvszjVIOP8+/Wh/nH9eYeINpTygeWUSDkGUMqusLTSicF/WZjHiBSDNNT1P2FZFti+ZBcC8YQzk9pHMcrZo5xA1fKSw0cGMjvQ5LybpAToeww5Qg7zOx+14bSAtJTkrzpcDxuH2MkN8fKOgb6OMNLd2am/WqNHK2iC89YJgD+7kc23M8FB2GqQhES4vAVPBSvFnCcs3DVgIiGzZu6/MTF2gRvjAVzIyT5yeUnstl2bkhRtQRb25ojUGc9Y+TNN/buSGICGFDqA8RRoZ2yiZtWq7uu/GK5kMI1YGCk83rzz040M7pXoSY+Tdc4aP308aCQBkZyRnofi6zHl9xFKKd2raDxcuY+Ojb3G5mGi7zLfiYJlLzdcH/kPXQdI02DjAj20DUknjepr1hXDdrwW9ijdJfW4L7L0e68HRUND8ErEp0TnqxJuhwwCOnLkjx6XIxVHNzRDKx8HQpPLHNMCoInGQdwkqnBDPHem0aWu+23tzlqdC3FIZBe0Uq+CJ72XkUkKsutLfGCh/WGhphCi0uLsgF3vGud9wm/kdJawZHJfcXm3fxQpodDY4TmJtBjEvi1LoUl0UzBzXbEfb1AUnUZ1vg1GkDJD/D
  template:
    metadata:
      name: synapse-postgres-user-synapse
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mas
  namespace: synapse
spec:
  encryptedData:
    password: AgBwBRBuKsI2peufOjn+BvgZQmIDSZcY+WS5OXF8y6aFMmcTve6x9iysfo2rEBOoWH6nJL/qOk4CLw1jYP3GZGD6RXEEsAp4tImlE/uWqkAie1w1y/2/ftURfi9Vvb3T1GNw80EKzYFVapgf/wHe6k6D3/LNRNGhgVWoIVIENPiu4qZpom8em4rGMTNICEwuFV2c63jdGYIjuV78XVD9+dRykfhpXnULkSO0P8q6id8SrjuJj8/LmFFyVkhIRf9o0RVi8FSnnr1ubzHrWjz4Dm1ZGZ+bNb1D0ZRmcAoEHZ4Zw7ZaH8/Fq3YFJn9dpy1hXh/ln42lVNzt1MGQQce6XGeq0VF4O4Qm7k2HrLlWKzqTfS1FbWflqDD3QG8tDwHo5wZ7Tw9v2zb5Wh/FquH4VJdPe630zTPIEG3lBqj0AgWNcOmVGb6IYMHIKdh6WOg9hpDSJd5Q5rVX15ZjtMe+lZcos8mRWRZMKAvg08qSZW/QxmYuZHsaENaL0EekklBN0WyVdd3RhTsuRA1VQoo9c24NSjjmA9Jsd7mv600Aw1VCyUsVYKvVpgk3sU+NqQRUTUGmcLHapTBZV4jjejvmLjNs0cdTYRatkgouRYHln2R2OQTLLd7zXqxA8OOLjMZUlOs/9E2LF9TSMwt/X6XluXLUFQ+j/2G8W9XAzLjlWsNN8PZ4yq/i2UN82LdMF++Bdl70mZ5+IsVvb4/n6eFmOvk6aXl0Sw==
    username: AgBpr3QYAlIeDBKlnTnIkeANpdkNrGAb8kZqbs1uKqKzv4WzcCgcWfJtPLmaqAcAUX5ZeOe45YY5G5ddJT3NMDgI6PEYUQUSy/Shlp3ZJt/ZNQwcxWyjkZVDPauOfltS8wLhNrd3NaSi5TCZjorG0CtXUADFnhQCfvDpwu+yeJeWUMtW+T/cVqRadX9Lc2oDeHwTx6QOaWoLZMuT62+/1npour/ExttUkdwBPRz9n33Wz9tVZ4rzJr0VYkjndFEiGJHEQdCDD8jz0ibVYZHO6/uW5ZJJjXvu4D+c48YSz6GJ4+FTrWP2AylgVbmgWP8xO88AE3SkoUO5LA+5WYRn1+G8GzFhcSPHrsFipn9ZLmehldfBwmSNl6g2qF4j0Ium5j8o+MzQvRVSsn7JgcrsiJjW841S9oyMt69S7b2CTbcuzXX4Oag582YWxx1O0WoZuqupbz0sSMSK4u165iCTBcomq4+6/g9zoSJ45qsRJ+2KMUdoeRctOjh5rLuiuPop5l58uTVzDGSh0xxU4dm/OZNq8aRPw6aha2Uvqd3E+3eDbHkUSydwwCYPFqCbfTYgsI/eIZxspQUWbwbd1yy5liY3J0XgsKt1qP48xKqUe/2IqlXA73MJYNraP37jgt5JXUepy1+Y5e0L5Y5MNvGr/3TkLCzs78rMI8K4dNIQiv/Lp/uaQcUEJn+j1LoBdji7gFkDTf8=
  template:
    metadata:
      name: synapse-postgres-user-mas
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-gmessages
  namespace: synapse
spec:
  encryptedData:
    password: AgCnNvuf5ynBML5RfZJV2klJ9LSyELr6JDLW/+33Id6EEQ03jQtoOBr0sByWhdqfr1/DYgJwjDnhB7mwrm3zEaETNwXbobNqJYpJdr23SN06tyQ8IYf3uhPkr+kXRQX8WnhO7SAE10yAoEzOOZAq9HwhGLp2IPEQztl/v0KIPAMhibC7dinzf1WlJUmd+DgW/YvGvNUhTVpBSmpHvuS3r0CDdNetEPV/w1sDWnyz4fboEcO+mFEyRos9fOBltdauNgT4ICKnXZ3vQ/2Gk+UbzfSFUQtovp7f5lAWN67Rn19+B2gr+e20drogMlE6s9T7mnNNwmSR+D3X1GVkUIODaM8FBm/frlSffUylmNHo4S54PwXT+BFYGRO1F3uBqV0+dajwzI+YZQSfHEpEZAXD7kCBFIznhhy5etQsMNxx44lVK+3GkhccYzxlwNmGsNRlPvF9dshnJXRTP0poZZ3OgLGZQ2lSYsz0SXay9orQsBa2dFEIFgBMFxFSTrIF/I7Ifr21z3DUauJrjMnVNqIKe+g1h+yerXCl3W0NpD6/YCbg76N1JwN77dx82TltcLmUG69p2MI1YEleKbVQlJQGEvnLwyA1NcgyoQDAPY29UhpFMfjqmMjRBRJjaVnZnb710ar1A1tBBgLOINRpGZzTZRJ/JqRWOLXcVMVtYKqlgSPln6vS8Cnsz82nkEK6ulosoad1i5vpvFyY5g0vJ+lHAs+li6uYCzYArPU=
    username: AgB+ANBNCU59ovuTkEaOqmAXbZ0zmR6usH4sOTFDnLY86fuD/Wtuo23TNMG0SeX3j0LczKaWgZbLebR+HFqhV8TbuNTPE+zw68GCDd/vWWYat1FEmQcp5ZmoldO3y4ZCztH5l6Ts/7DhG1uJW2QvBBSsOrPHcIovgGRtkAL9/63084O48IEkHEMvjOr6yKbrOSHx2rYotRD1pVvuTGtKgGHojmDfgiqK9xZBevS6RwLRgFA2iLQJYzrt7CubakL4t69152Dj/Kl6SphsL3cb5fqdY29olGxpqVXZ7i3oZsHV6Xot5CoGXhcBT1Zc+VPyWrJRZDpeyJwSy3YJ2o7wrjX1ON/H5aR6P4XaYGIGc7N3tdokB3lT3DE4+5s48PDQFc0COfApeEati8gsEEScj0OHT0yL+in8z2lWSJDlcXECRKcENEmAO95UTZdH3rR6ykygqQoI1ejltk7xS8DfYcK4cUpdS+N0JA0vnt3+t9LJcsMyLCr6Mnkz+5f1PD6iD2Gkq7JQGvQmjMjyjPH9rMAqXYVCvAjEoK6xpsbt0DqQhMtDABJCQJa3zKBKDmwXZSzhfI9Q6Yfm29CkmhWI+25tm4G629WZOPA/8AIizuNexwQgr0geWGQJlhsba+IWfx/dT5L2fePQ25jn8WKv5q5TlWBDpO+LjCrPiJeoAG6vd2uM0QzXE0stPfim10cM9jLOrqylXUBzDe8IolOZYFCKsw==
  template:
    metadata:
      name: synapse-postgres-user-mautrix-gmessages
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-signal
  namespace: synapse
spec:
  encryptedData:
    password: AgDHJQJRd8507iU8b7hucFDB+zzshMtD4JBp43ZMOS3HLPN/S0qDxHt3B9mSq917V6FbTl3MEkan5A04AsXv0xEFP/tpbLP7TGJkmG7QQTvsGlRgn5FfY6F8jSIx0Ksgagyswzom+A3cPNIA9PJjH1fxop6eU+72lC+a77amLLBpVdHK4pt+3uIknjH9bvZV++vv1Q6qMxa61EJGRDeoH4lxctuXrQOC2Jorj8VWeTfNgFebpOSddKJvSvE9BCHdwRzCgR/XJurF3sSEpYHLzKKiQBX0nadz9MZdEnRSf6nZMs2vffPb97u2wvVFRzwq5cIxuIUIjKcoG5dMpNf3rlteNX/OnlG9Vj48C50HsI2dtGqof//D1EaBn8CNcKcFmBapxzGxCGNpKz6WZjCj/2gh7gZ7LqlVG5ZnUXZgkM6CbD1FDltyu5xzbTYaq2pcepFrbUtuoIFh2L6lPjrURghhAaSOcfTETq59Ji6biCnePhIH2gza69cpADZmuXENB5UZVvPVth1ha7H9AHAXNly3t9o8JXvWNYRC77XMt3yKy2TkWGZ143m8y6I5LW+ZkNLZfHieeJu/mdostKUCMNnA62GKlkrNw3mVE2Igz01BAKKIMvEemtlQ0Ob8JQE+IcNXbUyPTfL4OQw4SQxLJwzYu/7BTavQF0mQpozOeaAR1kIVubgDqv4hTP5i0RD/AChPTbdc2hL1fass1ldMcX+wZKS3suYaHIc=
    username: AgDK01UOtndypdwAjuLnUcA4U7HxG1g6k0f55ZZfyrr6kKXeJX6QPS56CV1tGjZbXGUJR11EupDsI3a+euTr76nhmg1N+Iw9b3hA0kRRIN6+D55nsOjnhzt8XmVSbec5robdROakhlYm5TWTDhmBgZiTAhXdv/xgZp2MIWoEoLm42iYD7jun2/q4nX1+ACZz0SuYQiXqiTjO8Sx2VwnCkvde6eb5su1658zr0zxsX30X8ulSXmb0hPazao1WKX3/iHDIu7MQkDnZU8ZoE5vnKXt9qj3vsVuc3YkVZh9DfYYQmrmyZq9558Z7TZnRJ8aUrUpXSCs7b9wFWFLS7FzI1HJzi19ls50fToBdQCXeva2ZfZfSOu9CFG7qMNtz0M7HOzzB6onf0eQXIWfKkgGGt4U0kzglNccx+FIxzfBbAzkHHWTYXXUHWV2nDTE97RprZ6L9rl83mBoW7el+ojpDEo1xdSzRJg1TFVGUum4bHj6X8EpClo3kWWXGKI45WA/iQ2hYAiLpWTiE15NC//3f84K/IB7xokIoeh7Np7QYD3wj/MOl0uTzPU16WEatgf0CteR3sVeadU4uksjoMoNNmkEDfSLXQzB7hFkI7F9t8syxGtxZi3V9TR2nwKiZEGz3sRa68ACZvW9lWd4wK2+85d5L4drackgxLgLjahYWsGzKYrKItcgUbDVDjZIhMUJkuA+l7xDh4pITZxl8THXi0A==
  template:
    metadata:
      name: synapse-postgres-user-mautrix-signal
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-discord
  namespace: synapse
spec:
  encryptedData:
    password: AgCauYC9/uIQtLF5h1IsZRDkc33bDICbu847ok2oTma9PRA8Bs8glnfyIYldHjP013x1l1tZaLs2HAyIC7XVWHSbFD9+02+iiaagl2d7XC9iWuP9ElCSp/tTr09uB0SLJUKcW863G6dPkgzXC+vDiq9bC1fVR7Oljpc9Dtk0uK6SC+gCeQwRE7xW4pFCIKumHa9ov+3znygkDfcIaWPxyuW2Wmwsnokrz7qIvsyPgUFNe8wqL5H/1wv93gHsbgMyzj1ePKcPbFPJdTFozDpEXNVMWWlYufTLXUwf8sMWt3I6HuOwk7n+01JzLTwhKKRLPYiu6qSbjmAnKoHxL7O5yRDyqHa2mrFAzKIjwdclx/D+cPt+kln+XiSn9C4fT2MKZnFfreG/qly7DzbN4/27VQmoVNJB9ui+Yj0BDZ3LM78RylmpIsRJeJJFb6rge4ie3UAMXhy1f635zpwAAstMngOcDTcmCgifMHhmAeXn2bKlrGHYaqvxQ+I4ULPA+wxfVmWkgT5vfSvuebwVKFZUCru+9Cdh0ovzDCKKP9tXkEmZOb9ay5mlkqea0+0u0Mrn13lJjr9QbwvczcB0UwG7AVpNS5Kz2ENgghyTAg7cTQL9Z/Y5du2eyFrfxn5d0sX4Aiybe4IQIdRsLWV8Iz4Qt9oAGJa7199c23afyUzXt/vcB8qnKbHGNjFUUs1h0cPZlV1Z/Yw+WzpZAu72Etg=
    username: AgCsVWJSX4PETsRTWmRzk9Z3Evxr+5TFqf8YOeHyLmqDp0FSw2EvVo1MzNUfhL3sIxNx3BTStUpmppak3trZs8Msl57PIsfzUs1AQAwoDueao+s6aUxi5/WTxpajfDKmYJ6cF0xKkY+2fXeXF2In1sy6S4G/U1OxzIabbsYn87nsRr+pa1LAhmFFOPfq79ldEkVe0vvvtiLVvyXKoVpO63jYgO1Og2rkuxZQpSjReHfLCfK9jL3ZO6/rfU3IsQIqH43bPhMIT+XbjetH7ECQdMeyk7ryi/kocplheyNMpk9HDZgfJ3YNpcMHX7lgTHZjb0dJ3ggOaXBYJ6LAyzYTf1BJoxqjlZzuL/hiMl+Ix9+/QqETXowmJHdHOwbE6pmNwb0ZPmMQLyyrgFzmS3XXCJH/AhvE0JKoNh+hm4gBuxoduqHzv1wNOQrGQTZp+WoYAPFonG9tOphEGKI3A17ntDWYT9yeqdbwmt1JyQZPDDV6V+w3T4G76kKSQJ3INNwlWjCfrZGJ1gMON9hNGU9W+Xl7Fd5Xg91lVVNTSV4pKA7LFSt9+s1QCP3EELO8o1nZpx0L5ZwBx5OeW8/BzhM7eSmrptumZ9ya+6ha6ijEmkE5Hv33RCDK3bwKSqhiBQrfeRv/ZUxEeyQZuKh3iXTir6pQVwTr76SmnIUV1vnShWY+yYH0l02c25Iyoh4min1pfNzIUp78rIsqSiXBN0d08MA=
  template:
    metadata:
      name: synapse-postgres-user-mautrix-discord
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-telegram
  namespace: synapse
spec:
  encryptedData:
    password: AgDB9teuJfEI6UeZQBWcs8gwy+SNTeRTs3AKShJEk6BzxLPCZxgQaJEfvPYPrED4NY1TTzG8vr3c9QZNp8iihGn1Iek8aga/OuF5IjBLA4lhoNg+q9LN47Ys2CHCGPXRHYrvQwcNeIhOv7EWRUvfvXdEd+rghk3/MGhSU0sQXxIWmbLNNW0/qLhfZWqL1DByM7U2l6twUXsRpSqniwkgW/orw9t24Svv4Gy//RyoiQAxRZ70RlmVwkbPCMmWQb8uSwwG/D5wHrK669RUVB0xzSQLXkr2LAEhMkg16GXvkD5qC8XuctqvvQbX7kg+UCGaKFoRPoTtrP3aC/heH/K8HkLc6eFUtntUzTDa+0ghjf+fARIleQh/6yqkUuHOtIyzGWm5nmfy1g+OufX3GLHGnWV8tJG/4KR5a+0YTevbKqY6fgRDoxdPfePKbLWP/Wz00Lf69ElvlA8F9nix541x4Alw4yTCEmiyHxTaZzOmxOhehVPJLF882f1ie4ubqRZ/RiNVpGYJNMMMp4yETVoPFaUr9DEfupG8NvBMdT7NBCVeWz9U3F/ZFrCJzPe9upSmD0qHLrkyFszLb17HqtRM6trGYLk2pZyuwOHpJK0Ustao7r69RUCuFCRkxbat9ig+fJn0+zw3KIwOiC47G2n24ea8C8eKr1Mkf8vywTcsWLFZS1tn+oG7nu4clKZ398ZNGkI++vLyuTukrH+c5Ws=
    username: AgACfhyB3V+Lk37X/E+fPXXPikdkGhDELiXN7fJlwaYa3jlBjjrXUJhXVGF1z2YehAL7YdHjC4r5lt3GNhF0XdeYRIzqSTO9ozTz2543J9Ricrs8z7EtsXIMIUT8fyewMRYrdrA8LHEu11jOZ3TvZbRhvpPhQUVGyrpdwPQ6GfprmxUu7w3K+le793JVKCv4E3ccsaNU6PZ070GEpEIsaKIECq5XEZavVB3RRGMtiovypwhOnR9KFfII2SYrSso2nQSE/8hPm/ZAlFbGV2wFnOZ1GrGYuo9tfhreazO+1EE/65MHcxOEdZv1McbdAhXKyHTaNQQV7imxbMv6iYq8+KEE9MS4Dk4DyPLcqWECHpy8aKkr/nD7WFW3I0JvkY27jmO5IN0bqd/0+wb2NwgHkQUcVOJky55uxl8rfZC/9mgG4e/46M06W4XePE5XMMaAxvodIAmXC//Wh9jvU38LwXAUgQWxL3MxrG3cofv5/r6DHSUjpTAWkoDVf0QoJ5OssZiB+2TTe1I4dX8ca7J3uEwHkVKmd4joN6zYeulhOT7h45ukgMvOP8GI1ZkXaYCcc+8l9YHcHE+E26zv/bxh/HAvgpBLt4EwXVY1mU/H++kdyAkDVtYfpl1va3MVITyr/XrtcryVUF2qAL/tdAvb2MpF8lcQc1vMdViAW0D2qDTTEyzpaU7eBUvIyTWWe8KsuICy1RJlW8jb8KMBMnmloUM+
  template:
    metadata:
      name: synapse-postgres-user-mautrix-telegram
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: synapse
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAM5D+mBCtMndtpBuC7w/kA6O9f09MhQ2J2q0WvvhSU3N9xHqfg44ePLUttDlQ71AMpBop6okZTWCYwoUPhbN6MuRVOnOGZiQen8piCuw1dl0tMlAjXJZu41MpDtNKtNLni8SrhbwNFAQWIqY/qVmJVgfamjg6SlkrfoKMP8oJT3cMx2kAfMF/1BkKEPH1eOcPtyr//D8nvU6uYa/gJpltDvAddFT0+6Z8f4SrqTJSH0DkLANutxRnpVGsYKOYn4Ojp0U/J9WrswyYjkeES9OxZWinnreKmhUrBVfSu96R+c0W1Gb9XludHiZlbEQdAcjhuAtosD8G+6ID9YYzPPDhe6N0FWc9gm/B7Cd+LLiKP7nikmCgaoj98XDjm2IBOy91fYig0mRVmpN6QrvcTzJFNOuK29HE9uObg0c0gWZFIVuzMAb9CKdRgsCO3SkgfjNQyvfYy+37G65DMzG7DpcXtg0r3KqGvIzE7ZTjVtkxlqHnV5xqKMezz5CvtZHjQUSA1q4BitupsGSoM/pdwAAS8YVnxAK2wHakA3YpnsqRKZz3NKzVGexebiJPPLcAdNNPyZ/TSyfqgbLCQXwoHCWbo0HcHt+03B5b/Ke4Ah9nGbfUuC2Gi8GR37L0b0bTWgRd2gTSIkMx5EoefdoI2SLdIvkDaFh6Twg6gxTgswkiE8RaUD/5SFbEsahWjR99oWeJZNLZ01oU133uNK8Lri+NmR3IfJZPojBPK
    ACCESS_SECRET_KEY: AgAmneTQ7uL7BOpwb4OFjEiP1xCx0OJ8KOkl/0COEL/xLJ1AMEcuGAE8Vh3ZcKEOyhQLGpMBCTm0M2R+wDH/X3n5Cf13mmiGxLLDJAUtxvNeHfAlkij+DikNzCqjj+deEwvpLbZGZp9ROqlhZCp6OdN3+gVanO9w5+YD1XTrkLKtNuDEkM5uqJMQX9LXrRuXOdhq5COQ5qEFu/pvjWX4jku0R5r7Vtyrz8dAWjJG9GJXWHxpuwxQikoEJDoWuiJT5WXZ0A20ovW8UsCsPTOLT9FLuNU8UGV/zoCLXOzBtcbnhxseTCo6tYgM40PlIyacNHv+P9QwJRlKeR7UF7h+7wuLFxYbwlK9vIuyEGsfUdge2ZUNUj5HI5hjROqqSy8NI4Ulz6uO6CXDdf5pLEY+yRUkzL65ZSPOJ9TR6zQcD9vlGlH/9w93uF7Ca50wMfL16taE9Dqmh2+4ER8Brcr1d+SgKgqSgnHUILLdidkf9xHDSqDG/CQoogmGhXyP6VvF1dSGu1bSlz32/5fCW+I3adygsIvfTllo8Ya0e0D7ovLuqA54pXaYVgnJHKW7gH6E9sKXJCZ3YvxLYaxL0ZvR+t1nQcrmU4Au55H9/BFfUxbXmMLkPXsDrBhODHQdIXNNsbE1AhuW5Jp7dD40LkLSozXybqHPijugi7UdBQVin2hgYlwTFaw8ns88GrCVdnQ5PpWhLPei1FsNuVyofuEdCCj9E7ihPnPSWlTDg+61D4gA
  template:
    metadata:
      name: backblaze-creds
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: synapse
spec:
  encryptedData:
    password: AgDOK6YR3vX1ZrjClUzxU5B4hmk7FBaRjm8JCePY0E5qCh3Iv7dB8Wv1woLKeEps/pK1mAOgPzv6LRIIILkxqwx9YaztfbEKcyAOFV4hgjMs/Z3GBxxzDpyNSf1BABca6mHCl69m6xAYTANvp3oX4uymeUqTWJZ5tC5OoVSlXLl1yuFPIXQ6OVLw8SPfz4kLOQscYYhQ7a4+DQlkuw/Xf/GTW9HvFkTBFlfaSkkZZtI5h5lcInwy/RJA8o0GFoDro5ltzKJenlA9LLPeLteV1kIaQBauOIkbf2fgv6MwzSb/e67LeJluK2SAoilUpsnl9DAI9m2ALNca4aeBQicL5CejUUZL5g5vNyNrr6M/Nm3+e1grrmriaa0nHaGDI2ZESTZBYsRKw1DPhzIV/J5EljRekeuYLumkRiXi3uEPhJGt5M7w9Eas1AsKqH/yEr8KyP8dbkP2OJdZ9wYBz803JTefxHoig88NnFUvRvB8dJH2qqjma+D0rSmoDEBsiw8Qge8CnLhU2jXIOuXkbFAAW8NUEMuYIv1wkDv5mXAN58uHovFRw/MiJ1zyAzKAKFZv1mGerkEw3UIcPLqyYc2zuTUy8GLgISjmwMpCi6UsqVwviu/XxyOeR8+fPPTOyINliQ9/EFxDSrKxUPyGO+2wfEDfAYhP2MKgkNOSuSwm5dEWn73TT9mbekR35G4QuG+weo9JC0qHMyNsWWXX0gA=
  template:
    metadata:
      name: redis-password
      namespace: synapse
    type: Opaque
