---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: matrix-synapse-signingkey
  namespace: synapse
spec:
  encryptedData:
    signing.key: AgBoCbpOGFVSxlCIYQAfDtqsICdLLYpu+BjJhJlhIHjF4wN8AOlAEl91/cXodUBerFynAx42GgHnmRX1tDjQmjjl+S3x4ADOvpaoVwBt50xyohcTZ/Zz3BxHaJ2ViGC0gvsyNDsJKU/iq5ApjXlJt5WK6+mz9GLR6sTirLO/rdIkyq0J4MZyiK3TVSoS/jBVGHXLiMgWUX2P49NHfqJ/xykSBCVreFo67BUaFC+GAbqhW8MfcekZeLeBNdx4+AVN+fTpNOwFHIPmxDSp1EShlhAvbc0RC5a8+Jo7gsxaZkvzZTx6UlOoNUVvvxFUnkTvzvl9s/fDz0nDcisi93hh/4tbFsz6Fh3I3KbXDDKPRHCOcB7dnviaezr37ki+BKFodX5zPYY8BbO9pyN3Q8kIcIZTgNRKxsGaEAyfQHJ6wG2kQ7J+kEd0AX1N1rozFVxgTTlUb+1kM3zEMmoYSWh8MqjbY6jmgYPDyzqpjIh+6WYBaQe3DtJqGN0/USqwOdhaipliech43huGvNOkUDLtwVTtTHikHspMYycCy7MW45i/aYAVH0YTjcWt8C/vBCs89DoZmxtvtW3W1meZv1TTDPpLhTa7EVaoQbOpgCVU5ErUGy9SD/1EKSGkGbfnGvso8E5mfT9y9AKZP6klphWMevzAEKRPNqxgTX4B4UVYSURX67rQLXtwNurzkFcdq8NDfTcOlBdbcjqxTKy/0/AO4ZotgFg5vqLd0XnWkiTeXnXsPPRXPAE5lFyAugqg+NdIl01tUVjiXcZyBKXtdA==
    signing.old.key: AgAOMIxZ860gzpEqYNFo3ucnj3pasegkvO34TpWE5/wfNXGrUFEE/RZvQw317LBhwLfHCqkYzD4goT3HyCPm2W/3aYzhy13AAGR74AdtFZSmfecPsJ/zU92yooPFsR3BZA4S6ng6PW0mwO2y5gKWaOZ42kJyuyL3IaZmki5pwdLKAR+CeXYM2gM1yZrt5XNk7WC/qUdxXRLOU+MGp4TCBYDvBfKd5LT8Bz+qlLtU3syJgC5phJiRH6fQa5sbEbTD9JjrsVzprC0nW+DgOLFpuI0KKAbjTNREFp4G7NaNUogHlC6/T8BRrYQEUBTOyrxkTBXVPHv7EFcyCdM/ScKBhxpc1GM8x/ccc4A2mrKPpLCo2v6W4FHA/TsB0WDEWldI35LTxPUe47Rb/XGxdwUR7yQ7pmKBAZXxk5Xba/iDnRYd/tioC+pWXx1qkRbjrsxaqz15wWyXM7S/uRZ7nVE2o8t4PFYDmfbDaa/P/jaZnLkT9xYRH8mfdHQl7GH82hVf59/IOeEy3brkGRXcSyr5jv5KVppG6M2Ylck588YgcUGdM+n3ew3e9LQlR3O8lLyV804NePjCvqsowJhUx3JCdos1xsVr9tAQAFU0MXztpCRMspRoK555OXa8+VMGt35uldCIy576yPK7LkZX1E9IHVFTyle7it5/6UX1xguW329Awubb5Dp7da2V5gWbcFFmeuhlqqzFN9R4pM84elIDjB/v+dtg84sKVFaZXSppRyjL4SnnvDKdP/4AkyGd9AXyCx6LJDc/DPV0MbgKIQ==
  template:
    metadata:
      name: matrix-synapse-signingkey
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-synapse
  namespace: synapse
spec:
  encryptedData:
    password: AgAoVRjVOWsQs4WOME1ctcP8Cxc3IHah1wqshF0guQP7qHLYH+bvgYPMz8arrSZXT+hyNtABJP9lgrsqruX2Xoyc3hoDClZogZttdD+aaS9T3uhmydELEnRvBbKooSr68cbQK0XLiqFdl162X+8n6l/iF60lX/ALrPshqDDey94UrFOSVw809BW1gVoM6W8gY1OLHpwOlz5JslNZV94PxY1kkXlK7i6miEkYHkg3AXfq+rQopKxNMGFwSG6O9Ci5vxCmek9KKlKJpo+I2Ej8iEAJK0jAeAhzZY9Wgpva0QncCes9Og1lphFZhIbV93RNEDINm1GmIqToi+4Ea1VE8Z1XATjekrRQyGYMnC69E4NtorqpHM7DajauF/z084pu6FdtA8wE6v7207wz3cO59z/zga/Uab0PJK3o4yt1uMgeIZwDmB0W8zl0oeNsvQW3EcKQn5MbLJTd+Lm6S1hiF+3h0Wl/RX7GKuteERes3pJ9kJWGtHHSKdaM4elJXC25OkgLmIf7oFmCx37sUpkQPPuCk2+9PKW8AulGMnjlboqS19wIwxPT4pftE9jzZl1Fpoer4Tk0nQGCFICySkf4XKjq1pQUP5v2B4VsMaLxRn8EjnHwoIcmU3Izo9NchySRqDpvu5TRNCFITCBWmbsgLdIh2vTQ14/AuKvLA6ayLAthX6ijW/CmSkZA6p06qaPhtkz8hCRLAvIstFhw1zI=
  template:
    metadata:
      name: postgres-synapse
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-synapse
  namespace: synapse
spec:
  encryptedData:
    password: AgAhM4qpsyxAjm1iC93d9zc+MPqO6OHjUG3EL3D2a5KAejwYn8DiDbXMCJe+UUA2VQZzqvmyjCBJhIP3qTldxPFcSrRf73Tq7z933ooxdWMnhYwHToYIDpJ+ooj/5dpgVcIJeElv6ARTtErRMSYdOjrF3SqlnEE3fUsJkzbZrHZCi/jGmO/n1tGbKYaSx3/vE7EMwdi9d/HmD3csr3bTUsojv/fP6w/G2dpZqxA6RpRi+WsKdeo6Hrw4fPVL3U1euQbtU/BDEZllFQpzZDOaJYhTPVHkV4ExS2cQBmEaHY1VSc5eYyeukaw+pYigvHruzAzYFUwr+M+FMzpLBA80BkILFw7jASEn7O/+GpkUa5/+AEipaCbca9BnLgGgsXf6nYIPJQ+3bVB6Oon63sYaL41EqEa2X56y9btM5epFIunNlA3yiP59T7aWDDEizZWJd40itIXDx4h0X0lVeK7INQ8cLFJo5e5qG2aJbfXp8Tz2qn/nTqHvBdBUi+Pi0k0iPnl7eMu4X6qJb2gdVcIaU0rRoyiFWad1joRCCeiQ9/XIO/yC9LNKACcUUYAprB6CS/WyZ5Us9utU5hJ+Zg4hmePHX+XfuOziMdMZ9Evto7Z+eDozRl+jAfggguN+37PcsD0nB5m1Sf/BKvqapyo3y7Ry4MPDwkQpn04HwIULRnWOHoaEyP1f1pTEb7NWn63TKBJSKsy5tcdAk5bZd9M8EdtVRev6Ng==
    username: AgC2B8cTjCtM47avPaJ335SS42T0Thu8xFaJIxoiE1+AFK2KK534HwEptCuZgtJEnjkvEBws4rgU6AqKnJbwKNvnU0Ii/xRE2cWJLBX+GPJQH+4/8cnRT5GfnKoSrLTTeqnQPUjD1UtO/lvd7RjXFQnm/cdecSTSEtkUHGkpOIDxZjoeZtjQyxkFrgQdPmlePLiNHfijUXjDgK+H4buXsO444Sa/kMy1clLs3kHMifzh5h2HsbRE7hSlhfZFhPX+pTFly7h2vLIDWad0V0JjS7TOYb9QDkQlerRLg8X6J/4wFGcn+u7CpFzbj5b1xu2Ayi4EJbznu7/Z57tw2cd/DNjLvMJo3K3VRPefdJSZa4+d62OVHMXmw84T1I4V2pUP4+/qnsvb0hONFxPXeivpmr3n4e7hYkr+Gh1IQ1VcEVqxYIihZWp3ue7KApCUui+G0Sf0qE5yMFqicdr+f1j4QGXR3TOCNk9asjwzlR63GVR7laBqLnxC0r32+SwLSvJbPgaXXvT+fym+wz81JZbszQn63wh1Nkt8MTYqZHyaV0CylkJ+9UAET0465KRaeY4FyiWgwK+n0m0XKt9FO5sD8GIWz/nacSFfvllP3zPuwCeTJl6YoQIBl4nIRAwv4RyaU6ii+7x93qxwzklovXVnmiK4cVefXNLB+FWC7S8RxPEigX5Hz2kMZ1exdQpXEJmnW+qD+17NvyhS
  template:
    metadata:
      name: synapse-postgres-user-synapse
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mas
  namespace: synapse
spec:
  encryptedData:
    password: AgCyvdVXZO/VBCKG4uGyW47Fv06m/jFy9ati5w4H4cWqhdskk8tC8pD7bmmP4h7NwR3gw0WIbILk37Z40ylGWD1Je5Iv+1JDXN2xdDB6m2us0Ti+YFvULPDZeC2rCQ56zOEbMx5/PCgeFTo4hmHWShzAayn5O3WBtbuTCHbO9Sm3WDcTdoMUEG6JKDFQBmLhVkV5jehU4wCS/LSpKQ8YPlHzb3Rf9bLQONpZO1QZ69y9KkV3wmpOu1tnwCe1H05ckCS6RKS51e+S1VRH9uhfVQXDVdxzY0O8YyNwlxW126fnX2w9OTnEIkWPkVCgSlA7BEu5ujMkUYSM0yIBQIy/juv9bGvt0xHYp7F7EP4F/pcpjJ8rrRQKk+DvKFr58dUy6/gigym43WpS12DGerg+a8CWKzOnzc3jrT9BgtbavE9+zLlIF9RTBiB71kTrJkNv65BSv6HfFP5wX+Sibfwzsiu0thju6vaKasV/9WMFGqQS5fVu/pyKTss0snTTkBJ6XxJIu27F6zaEyXfeJf2PIbT/FA4UUVwW/mwccYSTE0rvMxLsCoHpTGnm057KW2cyNTkrGlJvD55o8IMWBnMqggeYHv7EfgIsbQqnjjS7mKYlHk03rSVNu2byF9a+eee2bxluZjiEsIXaXLhCI+uzv+DIO788YJbww/tfhT7+m4lOF0JEZBor7TJVH20M/RCxOgwrqHez/53i1aTQ4oHlT5uYFe8ynw==
    username: AgCqT+UEVQ639HJJ5v/uwcXBecFnLJvFEREzYhwJerFvWRuND3wY3UA/HDNaR1OkPJlwkC9fyiZurIcd8NDgAhHg++ak4iVl+ii0X4MgOTOZ8HLCB8j4b24Ut+INdnI3dFCbA7TWIzL8gdTir7bc7yHkQXyYrjdxl4EsFqrFL33QsACrxKxKBjwG0vgdweUBKPsRcFCTHp2qB0CSPMVvC03BHmYbfg3aHULluFkmehvpET6rfHpcrXj3KdNWMymBN9NYd9h//qwUw5mykkf2VjYcP8Lb6+kFctjLyPPvCZX71QZmUy7PIjDmkrLpkGN+d7RC0sAIfDW5znZtHvw7gS/13E6sz1YIZ62xuSUVPFBKeRwTRwNGtwIhGQv8D0iCsATM0CC7UdXVFP1iCXcvjwd+S/DIfUTmJKxdonV994z+f75c2xhSbS+Ap7whdgVhj3/ngjUkfG/ZBaM/fgwzR0fetEeyLCV1NjiuYAtrnQxcD9qarumKKWPvvwMCjoNSJAIAVBT+dRv+UDnjcWwTpLHtEhd9oCY8iuDJl5ts0oWBw4Q0dpBjGiQ8oBsKCBbVY6Bairax2DTbUiZEd3GVk60o/mRzcUadDSlZF9AE7QXHSxxnULuZpJiP/ZOpUdbHYDoa7qPgxkdqRoPJRtlMvC86yKK2A2xraZ9QSU+nU36L3Yk+nwcwHt82QqNRt2jc3HNpm/o=
  template:
    metadata:
      name: synapse-postgres-user-mas
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-gmessages
  namespace: synapse
spec:
  encryptedData:
    password: AgAQ0Oq7eGsY4Wj0WB9Y7WNu7ABzLtctzGmz3c5T1uRKtdOfKTiZmeYvYSJNsZggbJw4mdL0U78ARtWlZrpAIXl2GMiElLCVnqwH405cwN59SzMxgQvfP2UYir/xZjTDSjbMxuMoJk3uRyEKPStfEH4uZhIvEATWbxqHtQQRSaXu9hfX1ic0u/2zu+b6eD/FbCn92BTlq/x0KKIW7Cdh0SbCX8IOcM/78xNEGgmj2Yk5J9KGlVMyVQxWNfD9jIhehFYF6Gr7kQjrAJemTDMGsALW6wupYEmOKK6SL9rvf8AmujBecdw6lBwvGfL/s91sIdnKyF44bu//XFplI6mxCNSyEZ/rnayT+Pao/JgfPz/WrxAPDfFvGAGOUXdSyNkMtHxJQuhId0N4NmVjRVQwV0Zd02F1TTw09DrSbBx5+t7DzU0qzTWFnYNQnCofyXNdZ7Yg7BRphU3j1rBT/ZVbM2ystNSgwYTJEGACu3s/7KQS+hakXdmBz+BDXbiDt5q60SO86CfbLRmmEpkD0F98/ip5/6yZcYxG5RIJ/9N//FenMqauF+j+Rzbo5NeJvA+S1ni4L0a9ijxihtIpUraXiF/EujX88xRyxcztseRmrvVGeYJPVW3Jl5LlYuLIGnv480QTsv4prUHinnd578bRvY94tAU7CdRGE7V2TuhYQgAKQ8Y1c3IHpxdCyV0O20din9H+tp2ihusQw+EQNQg2V444pLnxXE6XYV0=
    username: AgBZPsJEGn+sU30v57wLcVGQ2joIVps6lRrloZ564oohjwPNqvdGLwUJSVpp19VQCpezZ1RYl5BILujnmGHSJ5SNangu+i63GIs6G2DoxtIfVocoLICDAyAYAHhbOpDD3ft9U3GLy2alOwls61peRSPHjxwykX/978O1MptFJLc5QNems2HF1WP3SFx/Gq6jSMi9QjUg5crDIcjwvQMYbAVFnQkHJeD6ktacl8A8TyKTY6mPM40hqhGR+VtCkCP3JEdLB6h+A4qrJBBjZPzczCGlPXTS8riUDXWdkm4I58OdBDHyCaG8mK+qTUfgF6a5OCjM/9hrLIyr2gc0EJS1xFv1PCv7NOKjf8cSSkzC2GHKbA4bV+TRVf7lJt2ie1vw4oDYWwrgxxshK3xUsIYvn496lG6AkWJ/UYAO82sUMKYkXNvpfYjsXPk8WL1KT2d+Bk/48QcArr2rWJVuX1fKa7vBogrwpBVPOawfuyIBNFyszANtm6/2l2NJF9jD8hcNRoq6KmdSrL/GYRHFFSyapk7DLBsagGIiXA6h4Q5sNYjeGjEkDOv7NPLPLdObEcIjg1xl88F0q2gPwsVMKS7+J2wFXKCQfxhVejhio0x5UBDGwxUy7uQBH7wC37BAtMa1tyYZ57mOZHNV0VTVdP3KOrA4uPdF/kcA2tSTd6w2yYnUo8ik972BJPU4dFGsEvMt6VsL/zRgBAJcI/L22cY7Retl2A==
  template:
    metadata:
      name: synapse-postgres-user-mautrix-gmessages
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-signal
  namespace: synapse
spec:
  encryptedData:
    password: AgC0qOagcyBEXWFlDn+udqMz89d043EAjwxUnJQ9O3xUsnD9fZJtcQWAG3x4Se/4neefbCNsr4qkIh9rS1zH4lAZB/ez/DEL4k6Yo61XG/8VoifjLBfglwT1umFnTkvC78IemfBZcldQYQfKirJ7RIsB+gyLNJHrwBaikUJP1xbXRtCGXxqyNd6La2ajd6udD8ehciFP2SlQl5Fl4qMRyFCQWCcU3s9ORLNObguwfCU5sn75SPEzcihx9JMlIs2CihS58AtR2flzrHaxItjq/tALUaPoHgjgllJhAla1vQwRgrhSwunGlMI+B6Nq0pG7bKJIuwrYkZF1F6LGfa/Ibd8uMk4R6POTuXXTnv3EBc2UcM5kCxM1fLdE8W2TVcGAE2ZtA/f0N8OlAA1X2c4ZIPpTi+9s1d2Pt2dA0HnuUCZieVxsM/uKgtClR+aFdXmj2Ol4AjjQtIee/0mNes5X3wp62uIPUSKE06gr53Gtldf6dMGNXnQRdJep10FFc46hBQ89+5fqkbJ78WAegJl1fc3xsFDxhyP28/He53UYf2e7nhBywRGwfkcDVcck3XvJ/NgIlO7EU6rvGLGz0OA/88o3LfgfgBWUaLcqkiyXJcPiaKMCofb6aBvz2zO2ukf0L1MKilMPv86K2ILB4dzDYE2BCXnoKIpXr1zzpjzwgouLa7cvAa18v4ME2TOyHgS2qJwA+yL8ugO6FdTPASmZdfVpCM3RxydrHjw=
    username: AgADenucICHC9tWcENpg9IyDuqWNPyb5hHASuNb2FRF2UcoXrROQhgsrJUukjwKklK/KIbyF8unqVcNpH1pjg5moNSzvKuv7ibQmKlEzIboWSH6VIV36XXTAvOnBeaGVugE5yldtmW213eJ1/nNoPtDXEwf1HT/PQkUag/HWp4AsWfyYrXaq9Eb5hB2P06uHF0r0IfxHGduNzV0EwVVV6UcOOFJAwh7vlfaunX56/oo6USATNi17/Yz/XhR55Y+cVKUiGIQrRuLmwOQtlmRtqRMoYX3P3XvvWZUOOp6/TBTJMP562sZuqHOoWnssH8S/+fkabrEtChm8h7YyLdLtzH5PC1zOLwbyDqNjOgIUEitRJkVtR1Jp+JjJ0WSoasYmYrQTEkwg77WXCZenrQP9nGasbI6nUqD5i6gpMa6VM1zv2cnID6g8VuOAHOLw2e2AOLHEH/41kR07YudIgUFIBYF/gDDbPFvEA8Dqk/8wDlMembaB74J2BfG6jmPrsuYpwD5aJJgfhYfOOUMjFu0d2ON5uQCFG0nNDrLlZ1GteKFdy7BPaGPTm13XTdh2xv9KJ01C1GEh/qIof7LHN5Yhg2LrcxisZ2YzhxHnywTWDgLVfXwIOtdNTaNgEYqpZgWJ4kUq8AzOGEeZ3bihF79YHdwWaVDSs3Ne4lecB7Nb3IW6tYLnqMFgFCCxyrP0R3hGP6Hp39wfK9BqBYHNSgz7PQ==
  template:
    metadata:
      name: synapse-postgres-user-mautrix-signal
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-discord
  namespace: synapse
spec:
  encryptedData:
    password: AgCmQBBebQDkRq5/lFk5sFvvFEV44U243PkaW4Q1tn84et9SgX6WmmGlu+uXBzcll85iS22kJfKmd8KSpn3cK1nKHxvn6dcAS9MeHZoYcMl+QgkktF6rSkTUlbKO85KLYs4PcGi+Ptn7yAgJtv+2TfweYYyhVh7ZuoQmTsQ5KDrfzWctN8Wjl1GLUBcqwwsTrtIqjyrgA+l8VNChjPlBRIp3xtM8XkjmBnNc1ool4ykPEyLrqAg1tYU4qY/OiDDjEmqy3Bh3QI11M4wn3X/oT09s4wnifDT89pigPzb3o9w6o2oHew9zUwi6sazN6YlgalTfZXDJp5YUAcBix2jpVJJuZey3ljkU6bCbQPBC3boGJEsfpA0nWA49uEBzPT1EjxQIYQVhNbO8gcIZZ77Gy7H/3mxXdPFpNFUiSH8L7L40GMNM30B9DBP7LcCu+z2rY8tJuzSgegt1GDSKiVu5bPWHG52XFYoD93c9blKpwk+33ZppmXGcqPrP27x5YlkA3EDqxaAIzcEDMTe3aK7Vk/r2PEHbTz0hUii8V+hzop0pPgWuU1Pcuy8KCLCZDKFr041eEwO/SLajFGchepjBI51VZ6gebVpePcILtasRGeTaBnGmZvwrv5YSOg0qmw7El4q8OGmEuIMRcZqTLk/5qsdrSTtesJDlUjzNNAP5mdXQdErTpEZBJ555XW5gDAo5SBmYyxwW7Z9lAoOERHE=
    username: AgBBM/Lye+yv69HmZ6Q49xad/IQTZsur7kIJkHriaOxxbdymKD6Z+dBy80spq8xybQhdYXlKtJ/PJibtamJWM8pfy4RtKLLtOKOiTxczyH/36sIvct6Zf2XdN3vDnuRUwn3+hCdjTbVGu3lZRqE8nSE0cDczFansDOLRLFKZX6evyRVG8ZCOd7diYF+urTmnql4ZvMAUG05uX13J+ro4k0tDWUjAgGpTANwv67H+EjNrDg4D7yY7wKUDFCbPXIF8joLNb+qpg2Z8xsNn6KU6/xjHJ8bZXOYb2qXEVLeJ75LcZq07FuHC9h33i0FIlYeGnlYo9dtPwkM3+CDNwQSSOVUuhJma4x5peA5GogJar+HrziBjkHcXYd/cWCDGbtGCgm5xePBsmMaJpay/Rp7v3+sc1j24r8epbFOO7tIQ/C7ojOpE9Ou7sz29Xa7AZFrfvxQQQo+TgOe0hBYyPH+x7KEEDVb/EhyPXfI/44/7C1ifsOt76CYQAYzjTwNepCLdtgLzyWo9f/jB9QBtICSKm7pQ5lCivgSLu5p9I8ICJvdXNKPTedL3YJnZgUxDDINoN13PZTLDblhaLhx+E891nkZrLzyI2R2V8qwikcRIfa8R+UNbuSZICJqpPQhaTeCDoSPUJPMVipGR2CggQSQouTSMgqrTokBUNNLmpCEdt07QDOLXkvVPo9+uJobWrvixTYHZPDYvNRF1BWN8BildYDE=
  template:
    metadata:
      name: synapse-postgres-user-mautrix-discord
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-telegram
  namespace: synapse
spec:
  encryptedData:
    password: AgAZwgErYfjsk4P/JaDcmNTrDDfHFeMs6jITHM727mOaf7tkgm0/G9KwUWqtS3crvC4tigb6JO8nsUBORTm4LYyk9lDYoBBhsTbqxF3pBQk9KzdKa8JfXBxfutuJPCDPYQlg2l8/HEFqIWL8kT9lOvX4lDfxxRYFxUYNj+Sot0db8JAafVYecHiOOScqj4I8Lahwg8QNoT7JMrl7ErPhXDljLs4ktY1awmex6hcDlpXluNsZ3c+UtECTaN2n06AVN2MgM6bdaqkzrjPRID3+mIAEoSzIr1RV9EBkASj43iZV7Vis08eDxetwmIQWPQBM7k2ehOwp/Q2bJ5z3bu6hgzfHxEJUybVOZXKSOOcpZESJd+V2xsHQdAjOFSO1D+awM0f5gxKieoew04rVVwe0GDq9r9g2DwTfN8NBT1Sf3Hpwz5IPKm6NhDkFoMJSYsonA9ZkWfIkcBiNjQxIN48bJzSbWtsoE61SSd1+YuzKyXATH6Ux9ra3ZPu6glIPHw80jLxK/wsH1uDzh201Kt/tlbBVye6fJ8bkiFUiHekCFnHqKIYoTxppDFX2s6A8u4DQ2sLqT/z4UbY2ww5zb8O2S7pcHcT9u/yBDzXmhnk7+pR46D4+P4oDCfrVCesxKghS/Mt0rWU4qXytFLiNcxb0OJe6yXjBcKjkisv6qrebdkb1pYb1t0MxKgjoPUMdV5EIIVaw71robl5+QdNdthw=
    username: AgB/6bHq2UTkrJWGFZ472Q7VzzEoqmStVlH1KR+DeQtIVGVza/u22nwxPRBPLJPXwi7hHeYdBYe/1eEg0PHOr2L+QVllmGG/DiloqnCscMXb+d6+T4gA8zU2y9YwkwqbznVq2LKDHPEkYzxyy8IwZmSOFd5atURrgy4AikXJqutHay/69sxKp2SgfDGrdD3GVL9M7hE5F4fFPfS5lxDgrNV0rF+VmvZ1WGIIndEj432sc2vkzBmifogK6ImHTo79obQRV2Z7QKckV7srVHxe3ubzSixzk7+1rFHVNQq/RE1BonZPjFldsuA8Nhe/5yhprnvWtHVXZLSuu6s+UkPI+KpxrvAguOj3ku07c+yYah9U8gRzhQ2DqGERqfB+i6ZeQ0RmTZ42T3YH6ZihCEHKoWG6uM2oiBwZ7dSCYn0UjaiaoyLPro379blw8zPGpnr6zgZ8rIHqm4XrUN6R+MeaHr+HcfVchstsxDHsjFqFKUZ3kYJmShEd3KLjcagfjd/X4wCD7pq8hfu/zGBn4HTM4Hkd7gOMWncQc8GhrzZ1qfFXu8jIhH8CBMIIJmpgtpnLz/H2qQCHIR8MkwGzN0kbmkxSiNol72Hgm2WuTXZkgROzV6QYzcB9xd0nhPTNvPdUC4ZHS8S9ICk83bocDikbiPwPHie++N/IhN0ZR1w8ODr1ghT732ODGUGzeDF39SR+JpeBSj8PqtKnctKqRcmuRC3/
  template:
    metadata:
      name: synapse-postgres-user-mautrix-telegram
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: synapse
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAU7SM0r503S0n011u4oiQIh6j0dDPucx9q0c6/ENb0mpxTdIhg/hYqnCBVhuZw7qQMNrhykOnCvsVx6zaSqMd7S56uXe7tVEBInJ8FL+Dv6vWQZq1kbSgySj8q2WLBdz2nAimxFOT3pSWsIuNgu/7W/4u2EzP/rTo6v32fWr22c5Nm6HvmTTuM102SXKzGOonsvvbYbOlrrNWHGc1DAg2QG5s/L/LUSok2Dn19zbKdxTWicRlkkNRJXd95yS+vXMqV8RIiSNJhYV1x6JPoVyqig8CYSE1pZA6cpUHxQBdHAytyCaAAEVYE1DWEzjZOKiaSh8NCamAghFZZLWCDDD8Y83LOtPAC/OFFLr4vF40rdovLeqCXfu010yzvIc7eOeV0rWYpnYolA836S4LfN9KBUSjdeeT7zNXCMRf71UITqa3/QakIBmr80kOql1rXi7BY1naZgZc2Gubv0EHZ8IuXE0K+qKyu48YoRKaGvnKGsPhKD/pGwAkPfMf8/H1AmWPLhZFUzyUoZIBSKv0U3NhQH3058yKqp9R+6uCOThA5QXwsfuNWi4lmVfVOgTb/UjUSfwolQro++qPxRSgAAGJ3j5RlLUw/sTXiMWTf15Dcr/WcwIIy7DrNVtZm0D9cZwb7agYJESTR5EGC/UbcH/lLrAmXW5Mj/HBtnSqiRoJ87ypuvzYABhmKta7pAijofcVppvrS67E36y2Claxz/KR7f8Vetm0+Nu1r
    ACCESS_SECRET_KEY: AgDBIIUARNMXzhU+8WAEPSPUQg2jRGUTGqNgmsNwnq2yNSVRjHkyf/Rw0Xz2lj8wjgZRmoKBdsO0GvKmkiy39M2Y+Pt9XRBrUKBmUy87Qa2pJPyzY78oOlNdVU1Tn8kOZke7X1Goi8ZkPxpPjLtBv8S6vBdUBMDFpbTMe/GLazClzKbGQS1ezl5S6Woc9ykKOx623rrbv1Ru0/5nCw9RYL+W2FojnRE0TZ18TNBU/NlG+LTHufX+KQdbfLE+hb+i2wmAKdTpGjynHZr+eVvLsGaJokvDNJm5vJPUEqtfHsP1gpybFqeH5OeFLeAGPOdyKGR/tiu7T3r5RroglJrShqAPy3CyUrv5TyXq3kCLUB2z5QzgEAlaV1DeFqaB02UTwUDVHFsQYmGfgt7j2mSB0iBXPVo4L0eoOLHliMRRgXqPg4hUVpTGKlEUDJDhAQ+Zp1k1s0JecTDMhR42fBTqi3LUeBAPBNRaSE/vuAzXX+VfnuF71/DzCznyeCTiW1G636xCXj0HQc5rbsk8ZefaXKf1Nv6bgDU5XxMO+RI13sKPcqwcI7jBPRxzIYAp9WiKEig21Bb/zjGme8Jjn8wPa7+2eqIDOIghjqbWeGAfEylc/+S0XD6VLv9Bd74Vl/i9avWDc8Fg1dPLJmtkosfoYO5RXXAOoZvVfAqhuvU8JL4Uj2iHGNL1Gb7L2ZUwmtzxx9jdno/gejYsZb67IqN3o4mF7x2YCuaFG2H8ygvW9nEK
  template:
    metadata:
      name: backblaze-creds
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: synapse
spec:
  encryptedData:
    password: AgBYvxLKJYkA9O/Bg/uB8WWg0MHq2mithK/DFyyNO1/q2DHUITx7buWV2uE1rXGLUzOI/52wF9ZKVrMZPTe63BQB0WsvM4ibMZUaO9AYuvW655Cf7WdW1iNnaKdI7K0iSCl1Qi8E/lv7spJ/Z17b+jk8J5/2b4NYlGrGu4MMwJ679KgVCqgVyfpJldyNdkgJVd6e01kLQ2ivWDmlRqX7e8O5jqH09/gBiUFjRGcOfXI2ttM3hL9u9+q6f5i/oE+8E8AxCX/uV/rRQ9/tFWR2Wr0lq/Pppmpf0OqLJ2/eV0mU0pwEhVWCb6Jjfx49ZPToB4pZ/QdfwwRF9aNsL64tdagYY6SM0gRT+cw18OF35EyGapzWZvIUZwByh9FG/qjnr/cjFSbIy0k/5wVgDJ6er58FiWgOfbEwBW1yiRw3mGskllBq/u/FUe3DqREo3USCKLl32VfA3ol+Y3JJgru4789Yv58MXsaf+d1khyhMq4QF7beU7gtw49tEh9rkF05u14omBpQXsOVEDGNn+VWltX0KZbJpHpu8xHow3S3Vb2aopr/WIh9wKIH3FkAsbm2/519EYjW8PeWasAfTcJVvqubqFiA+2f3ZeKIdHasesGAW/Z3Z/kLcphKcajixEqnv9nZ0I2xJFAU6UcBDswOwQ/XNltzuSjKBJeITWvO/Md143vlBoxng1U29GzVHCLk4Y7o4oXV07ehm9blngwA=
  template:
    metadata:
      name: redis-password
      namespace: synapse
    type: Opaque
