---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: matrix-synapse-signingkey
  namespace: synapse
spec:
  encryptedData:
    signing.key: AgCiAtpyI0KQIQO3MzIIeRulxQhNHGdCYje06zD/bd9xEGwyYcqWMxhDYG3UZspbUnyInxPMHkzzD1LhjgOWJ14w67LNGD1D8Ye7ghQBL7QF98YSTrfmo4KVokeO4oyz32bm2djevsjilUOf5tLGmmDJTxEy9xj36Vkw75y1ar8rnyLhhDilgwuvmh3Q4RhQxnqnfk/1OYyjClLHLzadq7emtu5vanW/HlLLlkgCZPjwGbzkBSG38cYIZcG0NKh2v6kCf/iYTiqKAnvvrWj6teAnW0mSgyG4gkCI5RBGVrMVz8gJl/QkzZbxdZezQMfCJKBHm4qAjOe/ikk4qPlFJvhNuuMwiOgAryKyJq03wUInlVlVCNBYNACXXUoKpYw7aPp4kGQ45noc0muSQAtlJMYdhFlQ5hYw2ksLKjCrtT8nD215rxUeU+V6YRRjbvRIgr+n+GE1dz+57gy/piidU8gWAPVBEKKguTJcLpwFzo+VWV1xnSyS7fYBRqcSJsCzOj2Hf0/M/JNVDe0MBEjciOehe4DyiyBZ/1hu2CwENhdqRpnCi2x8xL9BIhS4d96E1JLGY3n8EyE14ZeC+DDym1N11uAHYYXJouoS78W64seEG+/a1xsLEkd01EYy02T5iS2EqSneTYEl4ybFgtffCRjvQS+L86iO5CsF4rNFx6AqmKab1+P8rhDIFXC5VFIXaIAfoYiv5twvh0QfBCRK0xScfHmMBSHIngtTyLltTBsd70gesEakjoccm/sq/5wC/9u/szTZ3rqhlBAGZA==
    signing.old.key: AgBTNf9LgJJqB4PftFkHy2jPvwnrYjcdN1yT35DxrzHEwpRfP2aHjBMoGwcQRzHmjtYvNtxTZf+cG8LgGxLLXN5zIv7+tay06kFKKvLOxpd1QQ10lc0IHjTkgoAVQv3Avor5H2CJ4qLf6woM91eRHiEzwYAW8MShIT2jn7KPcd4uKQNwuWOuC7DlnH9/SY993MHxX+XSxS9qbkKdinQTL2f4LS9ARxPX46dfwEZ7nzP0IOXcCbpi8NDEa7pr7XQJFq4YxuHJHzLR74+uPy9ENxton4FlOFxKw30lDOKLL/YSe+UiKnj1haX3PcItEMqSJr84LwQFHKdcbsVJeai+Ea6rUSc2OsF7ZpisV12dPEUPDrHnhjj2RdQ6jfC6JLylfvEiYtzCQNsQEfkGm0ZEQX9COjTzE//GrIL09YpM8PjwbQCGKYcO9b55eXrn8D7LlPTRr1cR+0RD52j3de+9qFUM7G55zoQDUTS26YvPAJdhLV+vXx6sZbNDG8nUQBjR1Z6kdr1w0UMhlgJAds39vZ+ltNFYjJa/oYN2/3uKvRQn+uX68QIxMDhsLaK2HaYxGcVDW7L0lQprJviWd8uiYJ/ngmvr4PTyrAguUP7QTulh7H9D4aSRyENmo7NFc4vYcPKWmDjC3SohyAuQtaeb6laQfDtg1JPnJqLLWLImwsEZRNh3/q2S9ML4iPu+RdhTr+pi3Qxzc85VQCN9WaOQ9fT7ASrbn6VeYT2JZv13zTlfNDXmAo8KbexIJjlPZKHJl5ZTv+37MC2ao69Etw==
  template:
    metadata:
      name: matrix-synapse-signingkey
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-synapse
  namespace: synapse
spec:
  encryptedData:
    password: AgBhaAf0GvPP6Q8EeKQzJPkiI8Hdr8K59Z5Mxp88D/3Ty8Da/v8TBiPXI0FvQscvWFazieIs/aLgN7kWuCJXEPZ6ElCSXonkSJyL9Q90vwXZ6kk+zBBGj+ZlvHWV5cOwOzr+deme/N3ZyTEOhZzJBkRQwI6olnyHfni2YieAzP4hPhHWwsKvBL/hIYQhoO9BB8dj2AmIfQ7JvDamWvAiVom7JTuZnPsD/NkVC6xXnv6pKxUxwI70oP/uAQ/tdsUYdxrT7IP4Ety4brrvs8OqJaPcK0FjLxdQU5V206MPblguiPV8jro+E5luT1Bm2aNUXW67hEa3Sqi94VplzqTA5yo2mmHEbTlPiaeOgBeZQvGmJYbh8Eh9Kka1NwfkGB9400bwhxwQ1zfj60ARQ38RD0NVGRdNNA9tKO48jrEz1qQKt6PRQoyaWmzhzL2/BZUvKcr6NZi7DR8nA2S9dNyphBf7eHHYAq5qi5MpLnoLG9SZydTNZfMBfS7mfkRoJQ4oE7KLCyEbMdItVVU0BjDaSO7fCD12Cb9z8q4AzrnTyGrprFf4Md5x8MiJKryqCdj3UoOS5apPbtAByJBmaiBqq6IPNxi0ijp3Acwvtze3uFCMZsKRujCQUFSRIIhrbeN/JHOv95DsbP3J7yqvF9FgrQBvcepw06Zo0PH8M2OOHQm2J+ASnVT07AguPe+YPnK342B8KRvJXp7J43IyKHo=
  template:
    metadata:
      name: postgres-synapse
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-synapse
  namespace: synapse
spec:
  encryptedData:
    password: AgCbqOqEKOrVNvYunyw2hMP3p5sROp7YF7ckw8JUedS5wxEBLCZ/nCthxo6SnbKViblGV3rjJu4G6+oGZYBea3PEKzeqWzQNri8/9s3kSozWG+fGvNy4GP0F7shh9ffubmY9dAWjojBQwG0iun9grHda4A6mXxgwPxPVVTBYMTyJ4bnTIQpN+jmc806KsFnHmA0BJWmN28+X/5OuwiRwuXksAGDuCp83CyzmIGSPjsoNy82yCKKddLP1LuA+D9TwYUy4ZDDJJ/TXsRz7mxtS+RN1iVjIpj6nC45Bmd8TAol/XBbTokW6laZp0oPAp9iGb3j/vnLeeq4Lh8yJ0Dk0qJOG6z5EIIOJ84PVMelRAoQ+yAO1zJkD9oJ/+bPEG+WgPpLEpzwzwKKKL161zup8DIHnFmQnuksTxXU5YLeB9fWmDO7+G3HuU8V6DvFE1Gtl5qc5v31eNX6/Wij0thdL5dfy4+toFgeNKbPjzDLceRpm+/nYCjKyPswn8+/OJAQNg6Mvuo0oky0zja1C823slCT6vlYb6mg7TP0BPDguHJOzspf7mdlD+brR96WUxuPZTWQiYldiX7uUZUKqMqHDuqL6z9ZMJ1HKLgiovGigyLzD7uE5K3m85Z1fFL440FPjKS2v+cKOXm1ABx5CAnQCzE1YLBA1AVMx4BcJJq0WjBQxCVSlecVEcpN7/J8KCqDkq70y6EtCBZq1c+itdFIyn79aH6i4wQ==
    username: AgCuPqhUp/BzzPAg4ln6Yz3ym/b+meyA0C5QOiB4LrgXi4o9V4jfxc+qDUKG9sl+BqK0tcYk8hnDxba02BSmcBFawEr3YTeJpV0zXMbelsGPmD01f/VOXc5i+gC3BGKAVzDS/m5ppAuSZYIFeLKmBddKkm3rCQIsPHe9/19jK5CZR9TkJ9Ywhk7aiamSjNRr4hyyqiRoA0lJPyKPDpXA8bfWLLXBmcTso3pG30NRLnWb7m7JHCwMfNiRfJeyMXqYEXUpCph1VagxARErCR1QnffnHwByYW9FYWmaU1EmUHZUZDdWPSfzjs0QPGkHwJinBf684oKUdTDkfvCWkqMsl8dQbAWRpQWQAypXd74fJaeKMxbtTzrJqcmG2VGT6y0v1lbwr76tuVsMtEKziPRhUZ6/pEWvGDmtdrVnu9Va65Az7nS4b8hdqPUNmHqka4uT67iqBUd1sfW54aWx2p+KCnb8UoaLQunRT/F7U5MJ2ogUGRyY6tr1AsNWNolxfovh5vAOYHHs7z7Xq+fnBoQPHpjxax0Dfyb+Ero2SunRrJuOLhWprhOi5NtsuXWW9ruefhohivr62riJSIkCknGdW+zWX3i+Mrh8YrueaOVY3hlukVha6FMMrCOd7omqbkMUPHME+qg2nY6IeGz0Wq0XISYgrdXJOTa2Fqwwaqfd1Gek8itT/s9TW0PVaExsbJhBrtgAf2HMsOSi
  template:
    metadata:
      name: synapse-postgres-user-synapse
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mas
  namespace: synapse
spec:
  encryptedData:
    password: AgBQm9hWUKzvYUHKup5wmtDE10WTOg9f0a1aa4eJWjQcnfkeCgzu9yZQ8hNMRA6fY742UL57MQ0tvvASzY/vhJbbxI0iv3GVx45yv3oGf5g3GnyZLuj8xpyB1Y1iSQ2ViJjyxdW8Opel8d+GuEy30FjBmydBvhkapqH5iI5QMzekCcox186258gZyo70AxvBZEDCJ7T5rrWs3mvWKgHna6+H9PltPmZZ0wnzfe8mo/smljR0NuE3aB8SpdW+XAqadek30GmO9VaOA3zJ2e6Jg90/dEICTtr8ntXj/Aa/FGKNFKP2ZScCQoIIQXiEBuyjlgbBwC0kLUISa430nocta2xCYcVrpr8OSNd0QVYsShiumt13SSekie1VqoQdlfern4gYLuamE72tg1haBV85KarNDVtu7vQxrz79in87u+qCoOmRyLPh+shRsmcL6pjvWgOtFmxwhueYjcxa8pqz21MT/ldtERFOsIEf+X7aNI4bz7khP74Be6AaBheSgVKXcsrjmakgCOYqbxf0HgfGYzopdKg8llvwMpa6a+/hlQxq0pq9l536ZoNtTBqkPN+GmxuU95AuOULfFCG2A/434oE8z1x67WrKybOt8natQPWvBAGof7EGHkQaeHWuF48aZiApNPMB+AMkk8Q1xnhnScqZwjiCiljwn3yrKUXncUMXmfmcxIV18nU7uIJMzb1Azg9Q5zgtKMby83E3yhdEIouk46VHRw==
    username: AgCZuq7mHNRfUl5vSUUr6veaSfPqwof8LeQhBtEzgTRRt7s3PhZ27oTRVN/1HqZzI5M0vqu3PmakHIdsLo3WnjCFIZsCRRXu/R7YDMqo5mroDCnf2FMb/F3Vbq+GxxAAxR0lMAC35Q3yikFE+3qthyqIZt/wjswYG+iEgFRv205aELEeht9y+49A5UYvQvrTFSIbe8uAFb7zZmFfGwcejpZQO3kFthOmQlsMoqucnt5z/PCx+fugH2xxUjUmlbEXh4GMLLY3IJIlf7e9Ev3dInW+iLYqH63ueYuKGFAJn20M+KuhoZ5UAP40VY/DmEKeqmpWvtgy3QMA8hRY//bGojTaBlDNTozhJzYpDu4SZsxBDKBeucPBjcPZFBUhDlmmlFQgMvWO22Ejdwc+nWrLiy3b0diV7Xt+RR6owFl3r9Ntv255U9aOwXlmBaJdOtfrYdOKCQSGpP+Pj3GLe5iLrkT4N7G77qIxqlsxgtJVY8O9QuIHnvaugNk+yGPFHbXJ/6BEYSpUQp0i4CcMuL0yiCU1A80BS3yV6zId6KZFRFSxo+uI0iz+VyuHv9xeFDIH7lRR1UpNx1GaDDtOUZO4mFkiJOVqniZtF0HNIeUTYWIrM+o9mOv5Ka8mzAiIwquTR8zUp9e1/bUIeylrHRdHcL/24l/JSFYyl6nyvaw9EYdq9qLKGRxVyDFV04JrXtRb9x7y5R8=
  template:
    metadata:
      name: synapse-postgres-user-mas
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-gmessages
  namespace: synapse
spec:
  encryptedData:
    password: AgCFzFYaeL7xm/Bk83wyl6wt1sFj2rJeiqbwhLLkG2xMyJyL5Zw1pNPpYGmu8Jd/tsZd4K4pbs5rrSAWsMQOilushI6/56NHi91Spb8GRqDXHFoVfXdze06gB7db9OcngWNEDGeQ+Bw8nLLDfQ64t6jei9MZboVG2qJx1UHIKUEmDgnFO5KLmYeLE1Y0hrGSaKSpZmY8N9Izyi9v6Wn0l8hdoJxXmnxjW11O8SelnXCb7YjyWpbX8zpdVShoG62tn64eBCRuWpRu5lWzOnyfc4Jm0bsk3RXpIi2sjTat5T1AkDm1IumC2ctn8KCuZyVF/+hXV5P4Pg3AC375viu8hfGp6cPsOe3Q6nTRHPUE+KvFVdD2i3/SmJfzCV+OHQxP8hRYmr3YnfqMfsLwB2L6KirThwNAw/Q615q9TFutWAxSEnCj3z26AeJ5rIuFhuV+SHwFjPs5XrXIPaqqpvhaSrFhz4cdnvN0HVOj77Zj7/VVfiXnS9BVqM1tN/2dO3Ct57tHQYecN34Ehu0+unQZVuHWw1BZOOfGH4q2jqKa5xWWFd9+2i983M7TCqnPYGK75DHsm+GtUMoPntZAoH686/9FcJK3xw0/h+Ip0Y2Zu/JhAiwGHuQUD+F4xhLWzX6BE+fGByyEGyO8xU4mXi+QLNThVu/5UcbHhZyl3oL8T4tfYVplkA9Gd4oqIPy4t3eCg191qFFJI3oPmJ1LQwWfSaRVbOYpAcoJJFc=
    username: AgCk19ZoO8hTuUIiIHhBLYDZjwmy0iGEmq9eZuNEYEW0pQeK0MSJ0iLAhs/GIqezWLVnN7I273saXt8Iuxgru98beOwCIeWxqYW+01j5am3Vt1E3SXZD1bl0YJX4BGkKVkEEJNoERyW3+Eqq4Hm5DSUPl9+wu4xDLUCbTIhq9JA2rDutdIIiYLCoIbryMjIhxso7ITj6UmxfTdFuXZ1bhZJ0HxSyhgvY52pQ2MZkBZzdi9Bx1uijXDx37mldEJ5k4zaQUwZI7rbiFq19EvUNuKtkpRoiPTQt1in1xrnAonBGu4sDTpt7rD/AHyhqi9get8tpu3NM2ZTUXwz65ELZn4YSmw2McasjUw8WSjFv/Wp6GRvdNcEG3Giifhyas/8o1qaQjZuTrRJpp7RCX/IEY+DprK7QGjoMRAta7RyvIQNaXJGYxhESoFMasqg5+1SsHHA1AIY7XFVK4xeWWKJxIDnJkwdYTEjSCv/D4bNwPMLIydFcUWY5K37AV5zjtauui2bYB/h1oDi2POgD0M3feKTFIiCr3xRGgxBpbJBtfT/VctbUKGmXNVL3q5ZgCP7z0aeTE5Fw3U9zxUW1odl4TFBVOMZdTaf+qGXRai/o/lxQUENfWhFXr4ueeXFGujVMLXKwuH+9T4BH0v2u4QCN9Vez7hHHbyFVLoALoKOfYRyFlu17Z/q628tgpIbNEkVbgeSKEVSWmQCI0JHaMhWlUZXnbQ==
  template:
    metadata:
      name: synapse-postgres-user-mautrix-gmessages
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-signal
  namespace: synapse
spec:
  encryptedData:
    password: AgCmgsDJeATEtC+w6QaRY+8Mj0Xx0YcL1GzE5oCRFfkhdgw5aYTYg+SQs6QoTHgehIfgLa9r6/sOBKWpNF+2p2vd5JmJ3TOCYYypcKa9Vy3EIFoSlqHXaLlG350USiigOF0j2uQg4e7Km80JJh19VGAWqjqGMKm6k8nlodKB+YT9MLBojW7PBbqltd/zQ+IbAchpsBGP5wF/SkJSP2KZ0GOBRQRee9jRXGReoRWw3FSzTVl1wRYKHf6ast+7vec4p/BuMoN+CNXx2tL1+QAd/a6L01KDNg7e91lsXH8ZKZNOf8hZAt2eLwfIXTotrMAh3PCQcqO/ubaiNbO5Nx/uugsKkClQg9GYoF8ngWx10wVSTp5toAVYd205JZjPpN41D+C94xXWgOz7g8JDZUBwHj3VTHuw/SOYCc0ljfjT5friEaSZNQ21bWxxBhlPd3K7SYi7sDRvM6svoDtDiL7J/0OJhIOCuCCqt2Xn3IDoh9qOyz7J0Mu5oB+Ot1DfDRFBtTKgAutf0gzdAsLajD8PvtWObUtJpJ09zeMjuMdz/Xnh9a3NpSCtO81WEspbh+c2/gngAHJ+dTtwQ6i0zTM70tSGJ0P7oHNPw3XL8Wu3sV/74t0DyGj/RDP6WLDNZnPPZYovYGma19Wtk+qbUNDd58sHd+9aO8yP0iBdn//Mn2uKimrOMEOu44N6Uw3lUQBmRK+yJs6lf5PTWUle0eLKjYNJh55XgTgFPyI=
    username: AgBL2FKZ4Mot1DzTsyV4J6NxBF6wBsafn3d5sYwsKlai76Boo6e5xOfuip/Ptmk2P599RV4Z/CQxx7AXOp3APWjVls4XesAALL6rtB5sDT+ppWE1HOECjHNLpoce0KvFE3lnbnBmAXhjudS20jPWSp4yDIbhrtRuwdG0rdLq9Mwrojb+7DrwRdT2mmpxQbN68moA/6xUhuiu7Vdnyppeq1X5nwbAbUmi2HvDEYQeu6XjVL5brpM131N7Emvha+dE4dITE37dcK0QYE7UEsKaifKBZBSUuMYdZbBQ1XGs+x6pIpAUoARAVokBZXADU1O2yyg19osfPpQMJauc4T7wyxkWkiSG7yJKFNCJZmwYCL985Ig86ommHBmYwGwhSCNtZGutVqlK8mSteH9FRv7sX9w7I2stUltPYY3xKZEe91cLOXZi7cIBf4c16lWTB7N5JA8fGEklPcjIMFHxwALBcS6wlNWKp2XSXhtsz85wLbfhnTaRddtvZPfHhQeOPiAZuW6pFsmXk2ZKhvo2Sh8G8VLwmz9uE21xyruM8y9TmzScStBl/hlJ2XXbUWiqxcsVU9I5kVZrdGFfFIdJGY4VczoSaIq1OC0BBdr5m7i33SW3BxZh1Wqw4OcTscUaCA1gVrSzyuaiXzWS8rwMpF9g2+JoC3j4LX+ieF+aLhARKcEuymkH04m90SkRn1kWG65KcfZWF3wtIWoZanPxw9Zzqw==
  template:
    metadata:
      name: synapse-postgres-user-mautrix-signal
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-discord
  namespace: synapse
spec:
  encryptedData:
    password: AgBy1AyUmPFpIDlJ6rgokcCpFZgT/V73huHJs9L7iqV0vlISRzgdhf2XixvSZwGiDTsM0wD29TGMtmf3pV/Sou8GNs2nthvU0zkg+AE2OICW8u3hrltloSeOiyiU/707nt4YMtY6oIVotRPmZm4gzXLlRVvJlo1aa922Qfbqdm1XCi3WoAI9N7ch+9nnokshzMTeHzn3OUn4ftZJndqDsFhr9Wy3A2J0QLty9SK3UD4x//3FCXI6VvyJw7zPyj1cFmY7TPYawtCC2I3ro1fp/y7FsDRi4JUr9lqUqLmITegseSC5FFfxMNkDC09SsDxRSyIJxrIVUTm9j8augh1jSLdW9Mk3gYXp4Ey4xxCbx2hPuyrltKEC154pOpYy3MVkxi64rGkHL2ZadPoLHX9ydso19G4TBwtKI+R7hj3v7GI8wiUNdGAl7FmEDDAKFn4qFme32MCuj47m6igW+DI51s8DJnXSQZSXN+YBUnh2jH2vXaeiB9KMa5rIbgc/NdKlBwtHSIWCog0HrF06n70TInvdwoeuImvojh3dAmj59ZggAlMrCitaH1N0e8sC6wwFZFic47SuANeaaA7e4d1oEruCuSyMBHVCxc2g/0zlKgts0tNCIwcoTIBv0+kFaRK4FGjv85B8AhDOScXE/LAIWaOB170gucBqyzVlSIt8tR1VFV4d6bKuRX4xSuVnCm31nMCc7Ujijb/BpWXeP2k=
    username: AgA45K6ZdxL/EZW23Sjg7A9EILYx6NJ+M9ypeBSznhVudag5FnFQuEzOxytwsyoJZdrcwClahy0bmBDRQfEaPom9wEppE/OuNmhvKD44ILs++Wv/WOVa1+CMzat59OJuXWXTGn4eKLNognG1FmzT+Q1/EPrC13HZaFeXWGWP9LoSVEYUa8QSxcLQFgqlZJNMGI58QxMAyCio5zGaMW8yE2V5GV7YuXe4hQEwjSL5S6ylSGj/EX8Ebnt3apiKxtn17p7klF987/wblHb2e1GHr+EvUV4PHRLrULcoHf19Rk1VvyBsBZ+XJ3NDzKK3TKotn+Y2PZKurnPqU3Rbo2lInEwnBzOpql162u/JihrftYdZ4QuTXPof0E4Z+XuiRWW/IzDD0sxCb/or9hjSHNgcYgCCSmg2ZRxGc8c8sjeJG5gYeAMizcNnlDvaBaczjn9BUacmKO4t70JKPh73sitxJLyPbfAA32Qh0sWIEiYTHKwNlM+XwvKGUCl84tZ7xKu8YwxaiOs1oL+zDe251M4XptXYfK+9OCaJ02yWf4wSVi/LzaX+sKsfnnrr7cjyynh4QTei4+ELsXDFadWrakGZq8pJNgHdr0zz9mcy9Uf5/fFWx6+8SxVhEiWcO4dK+NO0P8Lt3HEMMxSUAAenNHW81H9McMLQ6r+zQ81WnZo3oSYmqPSo05Z5Z/S/nSA03nJfGI+l6yekZ3z3XGgfTOXiw6k=
  template:
    metadata:
      name: synapse-postgres-user-mautrix-discord
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-telegram
  namespace: synapse
spec:
  encryptedData:
    password: AgBT6n7tJfH7/gpY1eD4z1A062sfE9OG9TneRm4QvCQs+jCZ5miH1O3bLpuAYuk7pdE03WKkHo/HowG05WgKxZ7FvkmBhGx23CSbCyiXZfXun/ICVf1vcRVtXPVZVf6QkGMmovjIz2jBy2e0EcJucB2Xce2lFhB4EGyla+oAyqY9Niqlqmti4TJalyvz81DzambE5ZYiyIYssRjH140Pzxbs+dqm3GONVFKxuJRImxqsFRCxUeQjvIfsNd/rVGs2EVjyRNe+8G9NtepilnYJZRhpXd9OVfqP35OSZsECc8Rw2AH43B02jUFYfvk1OLdb6cVf3X01PtiJ/a3aTUhFGJzqdCjTzzLFvjLevERtCtXLcXy7qrA5GoeKKssVyCu9jCIfQoRU2iLAIriX3dc03Fsy8YWpiORHEU2zvYz0qEwIjCvI7qmyyGxLCfmbMTX5MBL/zX+SUbnoHZab8IkvLc4/2Fe4uFDNWkoZRNXWHkQ7Yx4a4HJWajfk7ZJyS7lfWax4QWLtNNQInI410Pwpv7EnWL1bLZ8CImOdizLlH5pVbXxPlvG+2JTN7oRiXcAmAqWJrgQDLqCHhVufevB71Bk+eYqK+P5ALGqnvbzXl+kUnE/+c4Q3qtL9zer0WP4fbmkIe6hUFG1DWZlYcUFEX3mPS4vBhkxGHESZvjWikmyo3jKRxKCdriLmJ63kAQtr9//PjokKbaChidqcOc4=
    username: AgCa0aMoJvomjciHk9zq6XuBTp8xd1EN9Bp0PFncbW6cf2TYZU0/MmKZIkBj6fLLnU4uKJCS00qAKnO6we5Ws9Ipo+OdpigthX5q0jXccfscBSNORnmwwZZFIH+aROmqw3h7UzNDoSZnpHE4cuZ9TpPfODpF/xiEwSZxUMNpoolRU3wBC3Jj2SmhWMjD5dx0fUwo9m/HzEXn+EQc/EX64RYhEnH3VLXT3MiEUTKMaRfuCWGfsmJizPx5PTxB+sBhF4AXRHbGb/YSryQdquWDpqC3Z/f86UuDIEkjAdnX9SdgyegY0J/ex8kSnvCNd+ZBnMoDjtwEMyAznlWSu3MXbHKimqhb3GsWcrbUktzYEqbipCaNGyJSTa4Le+Lde+I5sW6Tgog0sQSSDPdeRQ7IegJK5Vm5ubbltuGQ6qxo9eueA/ihvbSVi5K4Pe7MWEA4XPtDs/YN8iIRQvr1u++kIuqEQLTHOSyde9AUOLy260lkMkmpgUNRsKCPSYQJ0vpzW3ex2hxd67i76w8bGLroHOLyn1HIIiGFJmlX/xcUtBV1quXUD0ZJgjQ3pbKv56tynu+RKXvwH6PPzOWY6tb5UFd7GVqH7C8qcej8P7vKm34/uM0ypXYE6WHyYqAsKDhwYjBGqyqB2aTTGyThQg5UlDDBbB0WJntq5ZnSx+T6ixHhwJQmsg5GInJa49sTazFVFlKdvgBvoFHt3FPoWsbYdnwX
  template:
    metadata:
      name: synapse-postgres-user-mautrix-telegram
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: synapse
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBLrmRxUsjszT22dD7lVtbRMizZvPtK6lGh3L2R6Xrb8aeO1OflyRvIYgOuCu+W/7LQx9Yfz6sUO4R4JKOYORsxEbKWqQPnWhl2UfddknTf6OJ4/LtQ2vN9x8VAE49hK3w5jPyMRr73nMHoT5uXPr600Bo1gU3+yZmxVrHA9I/rFuHZkq+mz/97hxPC+XSkMSko8o27UXFeXNts3wyiERO00MSEKTOzmzGW5mXBeZ6VntBDqx/E646FrltwNqlYUInTA/up8xbRvfQplz2z+RIlgO/ORiLF83tpPwRu2eScc0BIbVRaudOAiuKQ+YHOclFIqmGitqh606Ws61NKufexSFncWeMQLM5TcpOYp7b+gsmDGZXI13AVTRb+S5CQNKNQKlnNXC95wvs1sJ3ExNb4WbLr+izPF09VWZHDrRtIDd7TGRoHD3tunyu4bydkfqkQmCC2BbtN6paKJ82iQqSj0jCk5z34NKi4orOkzH1XIW3WywaIUU2JNFGA+HTyD0qQIPJnfm80A5sYyk1XK+vxj3Q9WnjqRnxDEfGdsgOK5onsEJBDG3JBGFrk5PWAGk2Ws/yuopySsRVuS33P0hV0qpxhYLCVOwBWE+bYhI68FYT/vkF/BOI6AVd/ldNy7pabwev4wFBa1jdoym9UNEfuZS+i1a9O8IkwxO1P2/vBYaQaVp5N7SBiylGQMAzN/kQk/6ItxUC4QoNriuUBWRiwa7QVSyV+zBvK
    ACCESS_SECRET_KEY: AgA5zU2sfJyKNwm5SCCJnt5I6T0cPvEposi+RthkVBE/CkNMsm+va6DtChnz4uMHad2kL0w3m2BEtKj3k7C4QZuOl0S6XVOFFGPeCoHGHEISmYNgr6ienJ82XdRiApaa/fz55E/QpUVFAIudSRCwIydiMenN1Upzx35Sg90VoyFAl44vRXI/xCCuCVmZMNsBikyeNYTkn0Z/WWIWFjvDeGcyM/6TMIOTIHCe8YKFjxWkg/sgSXJK2fOroqBr/MOjOGL3TuzRzyST7GdQD8gYLx3ZWTwM3f/v6jXKHffXd5N/u923xEP46qDrJ+YbHRyC7CmBZcw3Q3FOJ9Talts8bFRELfuGeprZvsjeSIEXOX8SFTqFMlivBGPsZ/eeP+es4jAKaTwmjHBxC5M83l7qsVirEEwZPokJ34+1p4gU3XY3V9OKknKBTk2mBGwVWPD4ad1TKsJUS2OL3uNOKaSOL+/lcTN5W2R4Je2qTJqrSYmRqFUn939xUbqN9JJTx/fjm+ULNpBF8St6ZGElQ0s1QjOpqMx6DvroVi9W1Iidhg2PQdINl4iyLGK9w1zctfqHgFgrFG3cDOTRkRLwaDeO7t8QG1Pzv77xqeL7Q5SBXO2BFc+LVU4GyWEwHezhZuf5RScTs8Yd6PUXUN1DY6tJoHd4sBrlU0znUHzogv5JEUMvfw6qoxQ6HMmmxAiL75OjhNTGI7lJcw8Hq3pb/F5TptiPFGZOnqzuyOHy8UxBvZ+o
  template:
    metadata:
      name: backblaze-creds
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: synapse
spec:
  encryptedData:
    password: AgA8xy87ytpusuaiNQC5ujPeJZyXDKZvL3VoB0vRFiy7yT5M6QS65TbnHtqH2USItcY9wnKF2zjjqqCyWsIzLo9nCNvARFSF9xrKQvlZArwozKLPvitZMBc/kq1Cnx5T7IOWCOReOf4ZuhptrgTnylhIRx5iblVjddLmhwJ1lRV3RKnNwHvuL4+7r3mSU5fDL2veV5DoKR7z8uE1M+ZmXUuxZGo4OJhELsb9fxsrMyg2Hu4lW1KCz0E1CGnDoSHCk1AA3LqI5vcP6uh3vt/Osi0sngpW45gmKUGuA9cMU4oVQEbDN117I58krcS+2c7CZo9oDfyzr0OloeRpr9ACs7kZHWZf1W+s7ondCYE/lY82u9MqPSwK5qv3vuX4sDxkTJGFk2uQAtahgn7bcH9vMSBXtos4uauFTL5HIpOgqgaM2FUg1W0qbE/nVerYkLST/LFdiciyaRLJzhERNHofgOgK2F7uiDiinK00qMmskApO9Q6ieXW0FCuXmjRnpXVI8z1azYekSBcOZ8KpygsBbvg7QdD2FQ69X+9MyLK5JQR5Y744xWtj6H5FKRFFaMESpDrWP7bIkeV4O2Be+N9CKG44Yt/xDM5Su2YEFuYo5HXbZ1Mn5kQHU+rUax5vHJlNim6omlRGIkUQGLgFq3suS5itG1ZGMetZp9LunpBq0SE+hzh7GQFKkUqs/ermn93+w+yQEllfZATeG0sPP2o=
  template:
    metadata:
      name: redis-password
      namespace: synapse
    type: Opaque
