---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: matrix-synapse-signingkey
  namespace: synapse
spec:
  encryptedData:
    signing.key: AgCGY/QFf6kr/V7W1Ysz8WSmz8SDPIeZRWx2aVb8T2r5/vYysrQUIuon76J67jgf56SjFpzuC3Yh4bn4GM1K2xXouHSEt7exT1YN8CJLpw0q7pGmSu2BW0R+K8NrMn41pl1CVKkTBBu/h/bhJn6jsfE+FT996Yi8IipHNFGXp1oYWarPrcYO6cnDCfgG3vCWh3VdPyvb5tXZ+sB5WiJdmYdm7C8l3zR81iLn9hdudx/sa0ASyvsM+iPQXSbEb1Aff4BIDixjafyCK0xW9jDe+sspwdlE8w1RD7Oh9ctfnycqarScUcs/+rCTObsf8dh0RRInM/Lz3LMfsxBDGOlT7CvSkql+JIyRW+ECB0NPQDvXoUqFZFvCBSZHYpLDo4nP+vn/hgGuoeMp0KLfpqckodGcxGM9zACc2eKi2+BfTQQcW4QMBbxsxpcwj93tBCZmwx8P2VVakLiRJ2uCW/qY8U6txLsIj7HyjeEPt/xMNmNBKW+Cj1V+qfWL/JkvWAUACq1FZQiksnJcdh53QnuF0KAF277YyBkYYKAfS7CFIGkOLSFPsHcUmaBipzFRWG7Y5mR5q+HQeAnuB/Y6c43kN8F/x1FGBKgoUyYR2LcQ3cZxoNcTV019DCHU/SLrQAbJmVS1tJt7J4Pj3xySpuiSZUQcoEFPegiSZncBpMY7nzknSUPNKcqDfzWC7hR3EB2XaaKDUonHHttqqJvOPJbjWsg7moYvDZi6Ju50Gi60G254/28X4kP2jMqQNa9s/m4MVPTfSUFUh547apZcXg==
    signing.old.key: AgDEciV1bpkXFJbzHIQtxn7n4OwfgwO1FJgkIf+SW1T93OGJs9lyuyoPiSUNd6z1jgRDWa69bczIWOsAzzKYpo8qzWN+7rW77mCuBkbNlvVjf5jJHSOTxZM71EzlNubPbXI/+cyGyKm8lgSnD15ujUmME75bWS+5fcf2sbP82728DYweqJ+z37HLRY/LXG8DZrkgOOOkJym/oG7Ud4RKJuvH9j3dADGvPX4Br3NxFV3HE4Cb6OpaCPUpHWm61JgbBQg+h5rU7BAvcdbodORFIoMh6U1osoLZcJoMDDUWlIdCnua0oD+F87w6IiPCmFyeoxnISVAOs0twfuvyZUEOWS0RGZCeJrrJVidwQbEg7FBdRhrtZkClKWyj/izEyYEmXSj1LkpfCBTEn8012uaZday4QpwUr5jo2KsLJ/pd8YgIAHZeJQYcfVvd0oYuguXBMT71oxEqHmWjaNBPZuGpgCo9483m3SWjmhSfAPZFXSs+sWqadZPju1yKgAyq8IvFnl8QPV3BG+wZa8KCwHye/o8rC9hcqSIRx/2bsG2wmfr3e7MC06BsdyyFXoV1WiRTa5o1nJAeMmQCkZvooJKOr9ypxUvCFnvHDd+GUDcGY4OJLaSN7Ocgpai0BJ36Lqj89ULXJB2MEsNlD2cp76Czuu6VJA8MBSGWISwT7GnbSTqw7IFxsEgynwvICOBzntSImNk/HrI4vjK7Py1AYpqixShgs+3Abg8Mi4DTjFTZX4safR0g9ylaQR/1YfME3IHiwK+A5xiH+ZOnqemzMg==
  template:
    metadata:
      name: matrix-synapse-signingkey
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-synapse
  namespace: synapse
spec:
  encryptedData:
    password: AgDC9/yYYNibVc07QyGC/HLLDfBA989WbRKXiQ60jxgcZ+c3T2fQty9H3kM9mpWlqSFZYTFVWpT/QN6n+cpc3+OvKcLtWigH9MFz7kE2p5R2yCJDpp9goWrRYf78dyPAXgjeRD5NaUM5FxwXkEHgdOC2z6uN45KbZiF9gXZy/Hb3orwCqYjxFhlB8Yb1RcdeUjfUrKUu2tb2Y0ouwxn9N0VMKGSf5sNuDuEsQH64wkkyUTabjOiRl/LYhX+fDGoW4OEUJdW2fwI8K1j4FPY0XzjyHqvdOf6OfnptzpxAYW7PAI8BZoIiHQeRsgIHVDppM0gocA8WHouR/98lYaSoOGjFtnQFgeZa4JkxHTaFbj8wBNypEUoL3R6Q9w6OtPweU/TzTQefhgz4c4nca6lGKuRwaxwUgvflKZXK5fU9ZNUxUsPTd/eFxL5cN+FzCuwbtOsi8n04Roo39F46V3nUCu5XUwvxSgDOdC2VDYfK014jf18GbuRhG3yCX4GJnCtEwldQCovUSUEEPW7SuAjoXNeHWnUc3Qz99vG+C/OCyWdddSx68eel03vFq3nN4SsJwej1ShxKTIQQdLO3qvDrmfUUg2/c0Hb8HXDrZkwaQHQ0EZKx/5FG0RS1dIXXS9TyidhjASTMVowLwggkVMtuuDH3FVjXq0EzvtklbN7x1xHwmrq1Sp39bc3zi5rj46ZUynOxb1qK6eji7LOLaz8=
  template:
    metadata:
      name: postgres-synapse
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-synapse
  namespace: synapse
spec:
  encryptedData:
    password: AgCb+2tn/h0/Odz648k1PdjetzKFZXclA/6AJsblvChAarxlFpDPD3cJnsGOv656GxVAbGn6hkp8tNqJuJDzJ8gHdPFr1dm/cNizMawnCGaeattMxnq9i3tl3YVFXPe8QppEqb7sj8GD/jl0sfwRpsm5jumBtYDGzCwi9KmyyLxzW628/NH4mpHFILIIfFHakOYS5Eh6PdLGoPEL/d1xldt0ilMQEZZ0jCk/CTOC4bF5/mL9jo4gz/nPdykAD05IGQzJq4PnK4R4iNWZzt3Of2MdSggL54SFcQ7eWdjWQE8cXdLXP9hUrCYJYskXhHz/cslW5TJVEynza9YdvlJiRy4vhZJwzlYcPdDP5Ho0y1O/MBzSDtGIkccGQdl21UXhOxMR+31kvd8KRmkJ8x9OW2G13NEBI8cRGNDQzzCJolVM5edrQi07RICLvkKAiQMyCl5fk4qCvRvZ6rN+mCAvJK/+IwzgJRTCCoJmivpdl/oiSxumHUV4Z0HiQA258FfFdPvkFK72SJEY5OCv+EaIzKROXTZQjpauG2krdhzUbf5Ode8pkC7cFd70ouYjpfc6CEPJGUB9wTCgY2bYc5exSVjr73hAN0Bw5wSCtarJo9XuqAKUX/nWDKuZzwIxsC4LOKjcQoFcuVIXvhQJspYLV66WLrmcQwkGGocjASmseoP3qa1IXRJ7ig7FEhaEru55ctzb7pthocEQsGdFYwjtzQraDJIcQg==
    username: AgBNOZ3ja1iiJgSdJ2gMBwnDXFUFL2mg/eLej6PTo++jZvvpJLPfDsaG33UZklsN7Zs1RJIb+2IkCf7RT8PnDzAo+huFBg4r3IY+pIIhJHwznnnstRAx5vq0vyhFxzmUKne8lhFPpTrVaVk/k2VixBGZ9z+YKFdZMU9YTRu+Cy0GZlpo7ZNx+BMZyf6tEswenxnjHTAJ5lTRy075CcpFOz6NzNzhLSCZeokWVv4JvcTtw2WEassm7Iyt8V4zMYz2fKmmn0VhUhSOcxd0yYDInQ9hqeYJsxtcQ1ibl6+aMZRkuMeAwaWrrG5Xayrx/5UB2F2vzkuD2zpxGkpF5RViy/doUexwbXszwHo1ulfL5ccLYc+QzRjp6lHg5OJJ4kQs1hAF8vGiVc8Y7NDM3cdFFiEF209PlVKzFlZHghiK8seTAQaXLSuNDQ7PalAYg4GfVIGLvZ05YsTna2I9B5arLd2l97/lCOKMmRZOsjxs+q1GOKhkQuENoSrM++rZCnV/8a+xlnCWWLwRvG6VKiK1vPvVRLITeDK9rXp8zWffr0AHJx0/Av1XFLGKvC2YK1fWvRiI7uRjkY9e/ybgbvrflS+ExjwLbRYDxiOHwj/HTspqK7lPRDsvfBrMc36kD+E+YoU9wzOxwY3o+fkq/PSb+cCFPs2yoi4jAtKbvSUJ7cpWZVUc6bfRw3sK6cdV6xc0Wq+nYPAWfcJD
  template:
    metadata:
      name: synapse-postgres-user-synapse
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mas
  namespace: synapse
spec:
  encryptedData:
    password: AgBaPTIlmKSJDITEjcwysmjtcKl6C6i/hB1q3XzVHNxDvi88V/0lUpy25Q1Ic0gLXheoO/2bU7SYqobYMjNs7mkfHdYU+knfKxxC55iwu5zzyJ4Gb1KbifQfkB6Hsa1M4ldjX9qB/s7UbIGq1hIkBBn9WQrpSzDGrZSyhlQnDzWhrQov9xubA6Duhy/XMDYW0gaXEfpXw1lQWEwXkgoTMiPtnIpuJMGAX1Huem4wri9K9OzhiLHGcLfvJ8/eTRyc/Svw2TF1NHwhmM1JJDHz1dX5DGrVeDGFWhmrcQ76Iel7D1pm3idMRIdqTDhFdil21sC/wNaP24anD5aAmHiiG/IRp4zZdgaTpebPKSfpEcVhnPIzBxzfOokCza6Wbhq4fsPrnJ4SaVVA+9P0WdHI/2qXFiQhTi4gpUhWOObPjP0VzTGYEQ3f6gq4E6JfJH6eipN96TDqfhcbwmry4kzkQ6+CoI/IUKE+5ms5Mdn3TitE70vXqOpF3lulc/gQp4fURItoQh3iW3hWRDAQfiqAEZBmwedYaumd5U0Xo6kF9VsY3/kDltZT3UEt9mFaN7kvVaFb7rnGsmmwypntxpaJiZLcVmxAN2/pwEY2ZCcPdoXqgNmohXgjoKCwJDoiZqKJRzFiLENrzqTJRaiHUiWdmm+h/SA2jHaHIz43j7hnbWeLcX9jYOL7Esj5CCKYZ3OUW5Ta0Dorpz7XK8PBsexd5OkVcRY0Iw==
    username: AgC9rkmyO1Snpv1X7mYSStU2epReVd2Ydmdp9+EpIE5ThKUpc+Q0bXdDOgzbAAasnjz4yJ342Fkgy3gsH/toIflbHJWa5SnmDt9LI8gevrubqguel06czV0uwObATJ9hof+MwWqGUJRhiAIyGpNJZDCY01FcH/WhUwufuByM4OYahTJmFgtKpFRzqosFUZo4eqPB7PHW0lzWw8TIywt+xmILPwNLsI6GV0XfN2KYk3UwTj9gc4F1vImwOHtb7dBIgwiufzoODtULk9EaewDlmRVFFKCjEvy4cGeB0dAACuSKGUNirKnkjGcSLnjaxk40vQn5DJGu3tnmCO5uH2mkVeMoYYENh5F6V/d95mSLouVhbGwWR89UKU7oaRU+dA5+fbUniS0FBKVyxHrc5E2hq3WRhvSDL7/FYTwjznxlgPzOGIVOJAP1u5DP86ThRZ+isdz4bB6UxEDN6D2gEV/MZFAY3XMNaXUPPH8XimYiz+7yrZ/CUfHzG/Jrj0EIz9Nw3H/IcGKjv1oF1ITxRovGQKSG6WK3HBs+iQnYDUMmyVfxpkIQ2EYoAPHaK4uV5Miwh41Kih9dMJPXzWnwsWxckt49sg2i29ORJPgWEdyXpJCKjJjHoJVFg5pNXYJmO0OvIQozSiw/Az2EfYeWk+k6uEpAPXSyVqr+RVffxXU9loTqqy5AK80AA81Q0eiuCvynJIy5nHw=
  template:
    metadata:
      name: synapse-postgres-user-mas
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-gmessages
  namespace: synapse
spec:
  encryptedData:
    password: AgA/fA5cPyWdynUTIsx5jxxk3HPwwzYXbQn95X+zqmgTg0931juQBr7R2kIRYw/vbjch9Is7xeNHy6MelsHbrFPOZMjdqGRrDqvEA9MhbxYH1KY+ug7P1CWZG7j3NsU0e08jIz/aR/acDoOX2tOm+HLRxZncIg3YGvYbf4HeehnPO3MoL5FLOnrBAFpQF/O7cfszwwXnZUr9vLtLSITJoWiNM+nwoa3oxgM5a7Ek54qrkVv6XdUAZXYVOahr6T94EI61QMG9SLBO/iY1nLhvzb1Xc7DoZQK8akBGkv3SE2Mq4Ezu6kcriGkWT5EjES220DgJmL6DiCaIa9VSF4WYG8dSqfkMIDjcbWo7rtp3yYhqOafyCKrqFgjlz/wq104Hr/zsvCm2MD4FBe3WQUMzm6fEgKiCs05JU4qQ4oIUwZXITALAaL6JSFqaHw7PTzzFFsKvzc9r5OjhdPz+QSM5s34DYxRTDAbgupk/SpGtJE2gETB4hwu7eObybCwzk96Z8vNT12G0QUbcK/zZKXMPmVlgXC8Koj52qqp+2VsxijP38/zWOaUTwaXix9oEx6aUcD4UxAj01zi9nC4QhJtkAw5cSDAAgu25k9hvpcuCVdMFt8qQC66voktEIdS/poYdMEXmWbuFgFR0UW9N7KWAn/fg0nJqQRYmjWgI28j38P9FwhhI9jB8hZS69RyD26DEb3u9xrusSjwuxdqof/6QRuLIu7AbblppNGE=
    username: AgBlQU3dVouB43oM+CIpK1W4sBRjItU11RdqXMtHT27+I+/Aw7VzjJzLV7Z06jhfRLuBulLtUG2s81RVobnJJi19U3eT8UN6PeFPiY2wRfzdmP3wt8ygYuhcDvsSUUQH9Yguxo2021H3lIMJY0Hq4G1S5voI6x1XP69stWOM/kN779dhYV59wjvr2ujQamjJu8y5MxhCZFhE8F1EJd5FK6EV0CgfMD54CCu+hTagbTeLdEc3jSRzeHNWyEbr1gCxe4P+aKQxVU+WDt1rVAIGogxBNdjfh31+zCph3/SpocASTPfHVh4OFoxmU8GB5wGOHeQsxnOQWG0XWKPRC2n/GW4iv/1k9rpHhEPkdhy2xmxJ2CaoywSTWgvwGU7pAOu4SpE+ynBn2sSvLKmqpcMcs0N0qQ5pQ1yLC8rMo5QWErX0GUlggMk4HrRrojaWlMQ2nGhvIyJKAp5PxNOBHKaBNJt0gIgkmsYJ86xf9syA5QHQ+9Zr0zZ2E2ZYKh5CgC9KVotkq7dvSLPb10Ouj7JY0qOo9PIlLV/xkREvFHg263FNryEzK5z2JLZCJm/4huO8Hy8c/h7OK1BOuCC6KoSwF8lvtVwZyq4cwAqQomCX7rw1N5uQJZlKycnku/TZg6zxRsb5Mqt59rg+snL4y23zF/iNIyUsuUo2VF/odTr0yWnk87tD8Eyr4N7z3FUNJsueUUrzQTc948ZkkvlHCIz9LsWXRw==
  template:
    metadata:
      name: synapse-postgres-user-mautrix-gmessages
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-signal
  namespace: synapse
spec:
  encryptedData:
    password: AgAoxN4WavGgEzbZvGXtHpNseh855N9myv7B8H0xwvnot0OQ+Faz+UacI5JB/d4NTl+nWF8L1DTrBfR8lEpcoB/9dvvwKWzfoEyufrFMF9lJdH1jmtSuvDVUMJw+x8KrHArMdGCAO9z7VXToHQxxXaafupo8YtYmw4UwNYSVMWJ2njOUe/b/8piJeoUj908Gp6v+KNQ0QSPiJh+Euf7SHQBH6R42vqK3CN3gwsQn80jhPT8pj1Rh3VoY3KnXkrrOJXDpynTfBBCwNJja9ZZPuvYZAnU97fJUH19LwlaEXIfYZwxfS85GWs+dex9Dzc5wVxwc74VGRKMFUKjEGrdRsipa9DTTV962FnSuGbZczpxmiojM7LMYKzDVvGd22h+DoBFD4XgmFt0omr2+91po2ZzmvRVtnjo94VWErbgPLi6FMBInidjVUw2ea7t+kK11GJw7GaBz/aDsloz3lZf+brnge4RBScvpSHxS3biiJoMlcbH7LU1vk0R6sfh1GTzMHvyRtp8jP/kaL4rjNgB3dC6Dd92QwFUf7t0MQi5UPHCUStOTQNLDJBkHQ8+ansQNFYxUmfmwESMimiR8ZkRNEjAKPximbDrbqLX9oaLaEIHfmHDIre/oH2AfxueA6IRtSSfSX4jI5zG1Bg8R6PmY03POFovRMjLXA1fyVxNlxbNiBoGRhTfqSJvbdojk/kwDVkBjPTLEQ5uA1AdAAySN4ZHb0wC/T5GE7X8=
    username: AgDGD42sROkw8FEqvfFHIarUhd0VLo1fUdJL63pZP3IazQuWPu0WzDVXA6n411qoArKkC/YpA/xcxLU+3+22TjmshuOD0W2mmJxCY84M1IhVFZ+aJ+Zt2ggKH7a0416sZ93SM8sTsCLayiNdZUN2SPpONN9lEE6q43z+8Y0GhpnvBrmWUV2haZuduMNdPZK0jDYGTX03nQtuMWM3Yr8VJuch85e1wzW/BMyZrCkJAIHioUFfWL7Db1fyx103z0Psiq1gWWgYO0h3Pj1EQHB56N9yCf4bW0w/O80545a0j502JjcXrQFjseYBxCe0r2aZRj6FuvctpCx/kEeX8qkFUUbiFqcqHPS1HhFWlShXgY723K+ZbQ0icS0nnWUHiiO3Jkmruo49osWAXqao8h1OUTWAnoy2B1jQc/PZlOY5pVm2rtm78hg/uHcarjP34EsIQcQSAkiYq0e5TT//BBpatEL3mVw0b7AX0TTIi+awhWR7r4xRw4cIz0P+BW6mVD42vqhJKP7pmVAShyfiTkd+z7of9czAN89hnAf5jzvk//MIW/kPpdbgYBlgy9/TVw+D8nMdCsdlrKsnwvllUZVOSFuWqEqgjaCrMq2Eory2pto2juXPd2rF1WxmOGJriiQVTpg0LNb/m+4rUL+ziSmjxDF0X9pS2uHjcJyNG9N5Lzf2qaL7CvRVJYLrEPPfQIiajb4qI+i3xWJCxr/n3u7wHg==
  template:
    metadata:
      name: synapse-postgres-user-mautrix-signal
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-discord
  namespace: synapse
spec:
  encryptedData:
    password: AgAqIzntpuES5w0HVr7uvhlX615JpXIruWW98Utxb9zSBnbbWvXIQIeA2eV+YZ/pyGQFbDStOS1OU0J2NypjqyeILJKt/aT7/QH6F+iBeXUVQ/J5sahF3aXXcrMSbrV/2mrNizXKfOWFIJXhDh/S65guREM5Km9S5T5LmN7MWUrMiXzJJCbiRtxbmguguquXvMFRjq7utS8UHPdjVRYe+VsdwlAtmgmv9sThNVfK4LA1kUQA9oebi0+xnxhWiHgWlKuKkIGGj0yNXY1XfuMj5nXTWrDiWUrsA2rv68TDQykpG8Ci43fLRFnPPaQT031/NLEqQZDrB+tn6x97jNN0Oq7sY/eNejEu897SJCpo/fzg8onSEiB7pqO4JTBjeFSXJiYUIQ4EcuG6HC4WVPCunpt8uhzFR+F+xvi3+1DKJ0MaS0nseZH1kPwPqmOgKJ2K2HXxWWvsHMzyVqzesUbmWgrbPzHE98O3dWJhaRr0w8Q/vjLbu7W52KZwNbF7VA/VHviQRgNkivnzof6SxdJZT+t8I1k2PdMM+JD4I5vYTOr+qxNQWDBkeK8J7xVsotf7f7d5yy/mKlwUj+ZhEu/RVoHz6ZOG/4vyJeQsiJgQACmGjE7cseiaYfrfVT9tsOk0emEuv0w0GR4IIwFd3aZ2GgRHFpRTzPcyOR3lG5FFcSifeVf641ICISzGau0wHgoT2NDV+g2V/rMKWacMj2Q=
    username: AgCt9PTLnzGulUNuT1Xp1dqgbYjBu40JO/Az6QzewG/UT0cd8CdBEbDiUU15s3ZTjwEZNtWfPgneZjfk+BpVGiu188iQ6IJi9v8CWH6HNaTThga9IWsRCvDbQOChL51jgRY+3T3AxUC9jDtAHsI8jQqEJaYE1YI+wVvbwPSXeBA6t28E9iN5NBgADGEOcATcb+ae0aPaU2IeTTbRKIPJLwwsMzMu9lawFD0FG0248r+pRt0HGP1TPQXhkzmbyO9UUAuBIH+OWe/LJ9eD8BW8tAUdvfzTAINDxHcnTfF2jyVJyxZAQ4ydAUKNCREDU7rueo+ahcxeb+mHD2Uqke6YNV+gTUEH29fupJapuHRjxpjWR9AxNQhXSwOoqoL4EIM/SybTyr0J66tZPvBp9x0QG6YK7Hgm3GreowZ2mvJqiabRg8LczFGLYA0eysSUNiPW3t7II6XedwLsOKDtsHCQ4HfSyhAKaWhwigpDmT+uh7MVky7htlFGbnJkyRDrIrvwSKcWyhRDuxa/Wa4PJvrJpqwsJ85BcuDoM4/ejZYKWHx24jGzxH1+hy99HaSyM7LCHszaD4dCLOsz5ycipOpm3WAUY+LH3rPZHvjbO2HnwZ4Uw3oIGeCks5A8f3v6IKr/RKwts8xHoDI9KF/w1w/8Tkqp3i1+5RVItjr2F6PCPF1WXO2TVYcARNkwmQMKIEqL/PN9zWBeslT4z/RpQAJ2TeE=
  template:
    metadata:
      name: synapse-postgres-user-mautrix-discord
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-telegram
  namespace: synapse
spec:
  encryptedData:
    password: AgCPSVXwYUMbOG4OBsei8SBe+OC5zDM3DO7mZyoQCUGGd4HG5kOREWJHuuSWe6/6P61FggsQ6UyDxYm3q2SBhI9dZIXdWe5bJ3xddgxt7TuPDc0RYtD9qJwPv1Es6Wv44cxnwdr5HpRKm7emx3oF9XFQFXj8cvIbYg6HfBZWm1K/ZuaWMPU8WZzVMOckxA9NM9iwVgTgAvQ2dqovXTU8oJOwrwpLHZ1qt3dHGCGaXkgXxsbYZlaaf5R25k2VywyVClPS9vbXEtFlLfw8E7kqai15VTkyLmaciTmCIkrvinpD4P1sFQVyH8tUCXwmEJBcU7+sUOlyjHprE3xpI3+7/Re0Nh8AnHMMy6uoBfWYkJ2pJw7ceD5qQedAPNr0WfKYI9JT3kweAx4CxmMCTuAZrrTphLBC0SOtc44gyLejb8rt3/KIrrwB2KrcRTZkIPaEvqCxnUd7PEj+6o9E9Kr4DV9joUUfyNxm0kcBCz789j/HYJLVmDStxYD1ac8RxwBeLPsk9cNFy/a9VkZ4F2KzWO5YSWv4VO1vgHyzXmw1x2O5oDEmzM/ExZOhtjVYRlZdbMXNWTI74xxMht5QBG475CKsxnagqw8+Fk6AyFmVfY1xqurQ9hl73jVgeJWO7hP9axDqIOYfUJnhHo+CTHK88fV79VavJHWzJ470+w2KXlZQhxphrM5nhN1Xla27O0VmowUP+oWEOfMUld5QXmU=
    username: AgCidwl/N13MItLjzrzt7QQlF385UeKY6S1z4eBTVuKgxozeVgdxhGcxgJI8rZGJYoaMUPA6Ba2a6HFmBYYvKXolbYliIY5E0afH6LLCVm3S1KVCyAz9rKD1ltoF0vC4E3CNY+1YKlgH8m6QMzolnVcHHBBPpZno0/Cu+CF4p9RY4mSWc1TS6UYbWi3yQSsps9e8+uQZPiqC5SyROZbYmidYHSF5cyJJ1va8+AoYFMg7FfBJ5JfMIMOK0Cf9LshsCTYhptUvCFqSr0fu15MefUr6gDGuJuA7OEAMcjh8oLQAXxEvXY9yZ3vQBclZp9DU+N6jSaGpar/CvXh07GKtMpwUbLuXpWMlI/xxfHG9iKaqb5SwgEXo9BWwBQxgKLvoxq3xuKnLIrTWylKe9UH9bgwunEE8PEiVFomW/eChANM2XfrCiWeaIG+zUHKtkSxzXQQEh1rPQfdZgPQBFg2wVJFCa/oSUusssCKXR0bFEzugc/aj0dpBzpM+XOXCvlFi37OWPLsQFP/TWciR28yeEwDEZ/ojtECCayJsJFsL+NAAd3AiJWzVKWdTeI0KqDPJvaC/VaCoHdTCgqvxeLND4qmE9/rwV/mH6wKb3A0rNEw5Fiu8WhlTYJ4oC+qS3G+jUeEtzf45lvkplGXoOEPwtejo9GnSiyzSTqb/3Ewik6ChBQ2OmhsKJhhDoNfeDI0gIkPg1oR+Ad10Hd3K388VuAeA
  template:
    metadata:
      name: synapse-postgres-user-mautrix-telegram
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: synapse
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCSyCXrfRa7+EDyQ2CkTxbioXLSxQbc2O2TLdwWiCqj/HApzbpGadiFUmhbMt3aaUtYNBIxAVTwTDB7SZXn3TfKhJ+x0SP24uz6Kt4w9WhVBAJhTgJ40mCpjx5X5xEljXBJWusE5hpJR03JabzyWENZ5yZmarZeRBQ8WJ4jeRBcfIVlGn2sQE3QxhJHkXhzyT7w4a68aBK0ATcLjXIkqX3fZ+5z+3cGrgi9uXpOU4bQEvRD2/PJ3nSP0WXaQBWpyL95rpZRMGn527SW84YI+SIhGu1ETmf3Y2mYHKihI/YB9SWCVXJznxFBcWVa4FBy/DAYIcYF/RojPdLfres3Q4wp3wsjF31xkFWc/0bE0nVuF8gKuM1svUZeAxHF+on9yVHWDBvXuJGhx+X2sWVP1XuCOznGvZOlkmdM9V6ZwuMKpF7rhAyIujkhHahQg1z9Inx0Y4P+cv7wi8xg31IoTy6a79r+grc47GoSGTa5VZVFltV7rtlJY5IadgVdZSSqbY1FcA7Q8izRuF3EKlr7dUHidIUxiktEddkPs+VQBXbhDLZ5dzqRmxnxa/kL4h6B3pkrI2PTmASrPYco3V5VhmD8Lrgzjfcn59oyspVrAbX5TRMltiXwiCRxYAFUYUlMOigYu0Ac2bJJxeNV1SRV/86gVgda7P6t+g4VZHNbpAS5z0xYUEye0Dnbhy2pkAoQBwsnBtcDlPUOSMNzTKdPCXzCE4hvtEt4a1AE
    ACCESS_SECRET_KEY: AgDBimag+4URZ06Af4mQYcP/wpIyKxfIVOZf69ILOtGcdBdiUc4dulWvC9nraAYk4wsunJZzrY+V7rqSufKw+R/qExIWP5D9RivshDTdJcSCL6LXSzDfNWJiC8nwDVCT4afNRtAgS9PXpVZ3y7KdcpEgN5xVmNHAJXjGJ5RhnM6xljo7JQfJQnOyoUMbihV7Uvlx/JURxV4nlpXLP14MUUB7uxXCEL3/PNmxbDcoDOURy/momnLOmwZNnk6Qb/OxhvlJnAQ3OnJHfsfxYF2BVLvk3AqOkhdyo/zuDE7RbYXONdrk1R+VVEPzP8STdvLBVWBVuqUjUTgibATRJtD5DxcyUzlZ+PK6oCDzf8XI8Mb3P3sYXJoVDEO4Qs3mWmjPUXH/nnE8Zi2v6WN0jc8K8tYn0u75pmf9ropUnMZYxJrmlpaKJVx9np1ut7L+05mYWCrRkQPdNeBzHiLfDMil93D9M5hmCBJKL4hdwPcrHJSA5RUbtGSMfCxOyIjV2+PxkNZIFs2TUk7FlVBG3qu/Jq/METr9E99R/rkoCpJNR6s8K17lgGFCceaId/ZxgvDpmq2x5ew45FIN2bIUgIq2z/W186otPOI32lyLoi3sn5sjLrf49K2TI03odJQeqtWiKAr2VmrEGlVSTWjQy+XM1lKRlBGxUa5RQS5i3lZLSRwjnS12lmFm7FnzTUKIEkYD94kdjSwrzG3u4q4BjdPcNGcnCttQW5kwUG9z7q5Mw+8A
  template:
    metadata:
      name: backblaze-creds
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: synapse
spec:
  encryptedData:
    password: AgAP65t4k6GqfQmpPWpSSqe5SL5ww31RQW8eEQ9VLIXPXNyJ5UfMQ4dsM9cVeen6I8guxsgkblXAadPA9CqJz6Wk0R4ZBwiaZkFigBUzVbfdlDPzUXo6mQk8teSANVce1VJ98GZHuoE2SyZiSbOBQ86dHrZ1cU8us1GrIoaNFO1GndS/MqnPkAPjAe2Wef0BdHSfXy9DyX6iUSTEJ9qfoOULQM3ixS2+t+1H4rpxpEeKLLx/iIVh0MeSS/G5qS9rs1WO86tPtap5BbkzNSnUPWcPSkp4pMS4ZLinvpOfbfjSt2HIYnfqBnszHfTMwoGzmOd7Xi+Bgi8v2bmAzxDepbcOGNxEOcae+OcTB3xtWND4TPXoYPjlvPLvyt7dq4HRcfUHUSzcwgudwRR7qbDxk1DIvtcWIIdAJ0VMVklFjRZdH/3jWQAcb0QeZxuXHG/7nGEaFld2KyhOTBgix5McbBxSmLq6i/vvX3FCee03x/QGizr7cDDYi+0WL+NvHDyxVWWn9r9vE9F61glyaijld9GBJjy0QjIyxhorcJeRRl1bOfewefz1oRXpK7D7FlKo7K/JlzL9ww0y2SYddtQ3VGDVcJTz9nDS4nZ+Ga0aAxARExbmYAOPrRF28SLr3NjuDnKrcqohsOkeRAoo+4NGbaulfHZcjVkx448Ksv1f3Ss//MmjFrcxU7yCE54Rgx7BE3fbFYzZ++T9X32vM/U=
  template:
    metadata:
      name: redis-password
      namespace: synapse
    type: Opaque
