---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: matrix-synapse-signingkey
  namespace: synapse
spec:
  encryptedData:
    signing.key: AgAz8MTV+NwTAifzs7UvCw+LuAWNnc+IDt/3P+VJMJtNOIkrey/5WqO41+VqJUUBbgC2a5fWzkow/ZRXvKx0hMVtAYbZ4gnZmXNbHcfYxkWO7OZDX/b+bsv/rFyCP7j3JvlHv7PCgnKn0k+YF1OxpLR7OBvByky8U/TwuQ/ZJgy4CD6mPc0zKdVC0VRBzZ2YjHroU4lrubTGtOrwmwp7z0V8NcPsDSfoXJP7fr5YbFMyes1LoE9Tit1mTnDOvmK+EY3I7hUcCXj2J5GuZycrImn8DmcwSWj78dio1aEpET8rSE0zzhMgjJNDPZqlznO+7vf2ChGDA9aABM06RO6T0ZpBY449JM7crs5IfrhmvLXbSPW6niLMSuGwkIJhqFfUimMVW8BbGgJM37sxEakFxGgsWl4uLHSpdL5sT+95ixUdbL0To7IXuzZRVdP6iTFcrR+p6JMcfih1NifgAQghwfrD2Rv2h0nlzH1CSTMDhdcmwH/ZtsZumZb1hrRqIlnojEhkyqjW9te5lXhNkquRf6R0FwY+rqneJMhb0eMsykC8DzX9PCcgo4gbTQ/cJtsJUGHLt9rB0aCGhdrqxjFg3b8cspFCwswGVaKjQ9g9CKfh9kX5yues0T5+rUF+16BJoQPjEeh8XpMc56v2ZubP5RIOQ4Fb5jgf0yrpKA2F8j2VTl/0NsavkuctdfVQYitbJSd+I8XkWGrddK3bWgBxXSDTSU9mFpOS1p+pm6rR0L61zwPjtwV68Q1i+pM7R8qC6rIfU/mGZ6ojak2aXA==
    signing.old.key: AgAPTVCGv55q+sdw0YsaXjv1U91k8FloUtpEpicH5CeTWIPOLRTRhbCufczjQtHr49N6PPTS1YWoZOEySBzBCXmtPY722BwW5F99k01ij19xfdvQmtep1LoFClOs0C7lxzrutRgTd8nF5mcq78uWFYXFjICnZRJglda2QSQYnx0iK8NZU8gePBdoSysAJB6STTBgR7aXV98CDFVdPP0oUI0fmumgJiqZS2ddWHdMF49D5ctncOcDGltxJ9rpYFQaogamVSGQhDSPULocPRCMWu2/AMIZtTROFvNhK3rKgWqXsi4KEeN/NWzhWhKlLMqN8ttH9Neli7Z+oZWx8YSeC6FqmiJTuqIwZ8H7+zhBoXgArlRy6AeFtuvqKDFUu/CS1pTh+WGgP3DvMvs5yzwS3J7DUwrQKt7GjzIgkjmtYSZWOSTePEy52peo+yNvh2qoY0MLAm6uO2CJz7L8X4eK1Z0VmpOhNPQECrdl8gvc3mKb9s7x99LdTq1xM/FcvLCqtdlb3LZKSM900WhAZhqUmenu4IS78bxqVVTGyWWPocr8SO2uzJiI34FTJz9pyUZTFqlo2Lk6SglQLkAi82tQjlTVgGGb9yxLwgMqXkAS/otrRkjq2hi+t9+7cm/lWUo6L2+Ff/M7ZXWsUHcU9SjgNWwEqZPXYZDFVA0U4F6u2L12I6bch/vFTkmC2BDq6xnisi6UFkBPXor8OWIPRfHdOkWmFn/7bMkOJAw2+H2AqIgj5H8+7CA04jw89NGsV+upQcLwq98Ox6CvbyJ6wg==
  template:
    metadata:
      name: matrix-synapse-signingkey
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-synapse
  namespace: synapse
spec:
  encryptedData:
    password: AgAEiRYhvVdWZKot1K9ljw8lNX/lOMDAKWyMA7Cr5CRFMIKb/CEPOjc3JoB6tTJtEtgUIRjvER5grn6RSXCez0vOx7ji5yE203HO8Xw6vnM4GjWNkFKfKDDAZfw0NUIXgwPqZDQAwe0+JbIjoHRVoKGdEyqA4UAxfIZ4qkE9huMOa4/kAVFCXK9oqNvbfXDHYcRUOY+IDFXdTx4zpHEdlm27Qd+75t4Iayt5RQzXslBlhvVhFJFVtGXIkq7Yii6MMRC7vPgR2bO7fFSLpkEzZD6wGbXnmxuJnn5feQmbgLRUedNxoKG4u6HDYgIwXoqYKIF/OT5NpIrEp4pEFJSUUpwSgdXqLEz3UnnieqWdgmSGhx9LKqkdx28snCbJ6/mZvdf23etDnpHCfyj6A9pucKC87+HLzEvbD1xnP3HrLMkie7AoVV130ECR8DsQQk78krnlr5bZynnuARV6chWgzbIhvqzHWarkWK5Q6ARo6fa1oswNs3eJZiGDkZhr6swY+uPGz90ZCnF468wKZEYsqujF2JvPLBt14ROzgIimUK49CykuWY1KJRH+kjbFbe6Ltx3oE1lPhzcc9qh29r6zBSUoU8F/ebo5JgyILdbYgbSq24c1kKY5G7ie6n2gr9yxJ4wd+wmRl0SHguEyDn7SE9mrXyeGqLjP1VvT+RP2A8tkVWwz6+g4TGvh8eLYPxXE85e1jMCvajD3wEqm4q8=
  template:
    metadata:
      name: postgres-synapse
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-synapse
  namespace: synapse
spec:
  encryptedData:
    password: AgBJfrmOGLAw/bfoRW/9bt2EkiZ64qzk5kQiJ2oOkqT2VM+HbOMGXOgF0nnIvcgTtnl06u8L5JhJGLaCrbD9RMnMqoNeJKBqpmAZyVv4nsteNiSPg63fvjCqQhdoi+Xjv0A23OkKs9oik1Yj6HKsQdlXSBI6thBs8iz4TaMRNFjEJdHZjC4oNBTTAXci5V7Gmy+O1UTDcRfgkKEEL2O2uRBXYy3Hizd6QmwuAmPqmpdJlrZqfzDXtPzQtBdIhNmOtEpIQ12A2aL1a8hNsciSJAkJR4bAetihdr00Dm5OJDfm0LpXuTQ+Ju1b8Yi2hMUyJEbuMd21Q7dJd/cB2pll+v/r0S2xZ0/I2UCbWI1KGnSv1voAnH9cN7+2mRRdonkpUwpy7ni1jRQznb6DZneHBIhlwxsRH7uZTW2Bzctn2TNI+AHStEW6TxE0/3gfDCavF0Zj7yXVECBr4+lNaLQFgeXa4Ze90H/JLr6DqDJ2AlruTuQKZP60rRuyiw/QNgUIqAX+V6aTeHIaMMCWe7A4mgJRtUFOjqRosPSfcawng5UfBAf4VOzGN7nsBfXBgkb1Mx6gzFTHz4L8gfuNVjeSx5xRVC+P69O4dbmLZwMBF1U2HLus5ksR4M9FoyrKDDzu54rJUdR/F3C9D8O/jOdCkzrjD4K1k8ZQsAJWuDu/dALaqYkDgkdlbiZgBRHuZ7G8gJj0oDUFgcJ5TMVOUS3WicFvB2Mz/A==
    username: AgCfju8xqz155VgROlhWw+ZY/MIy/5ZcdbOrrCzH0wvYdl2HLw3hlxeDGgFUYVDSCyrQOXHLu79ZQ+X6IwFJ3JcDs8LGXkdjTSaqQg8k4f5eK8tYx2Kug79pYu+jif3mBCAcChnRyRtjGIvp/Ne0BcNo2wHK0wqJR1Bud1TUZMrGY7uneDN12G5nW4lB0EUG2fUcr3FWJLjJakjdKFN/F42AjK+F+jnrVUFmoJ25kCh9Ae8eOvZllpLQnb7AL209DLZceoPsMxajXEo5sIxWYWqhubl7D6eU73srkTjbhp6gPlbcExKGaezzg3yB67bTEiN0H/OeZgA1PnZKDC9x0EbsbEYFYpTYvid7t4wY5o7ij6bYeDA5GI1OruC9d8ghLHwpb0w40Rl8LKm8SUCKd4qwBy/cBfjqlsilPeA95+N1dIYYs20TlWKvnJuzlv86UrjuC9afWE6M/w/mlePFSy23OlTIvxTGZ3okGwhqpuS6j++VxEx0ZFoGN8QnauECFxkJvSDKHCkTLB2G2NHEIVWekWDZD8IYjEfoDIT94ojAgcrkw/+fSewKmWGSVxlIQo6e6/E8FSzrG4o9/Le/CweGFlZ3e95rH6n0+DfMp1tpzA+ENh5FnMX6sV0glnPgjGFjjtCtyoXiNS4oVvtYU6n/ni1Rxf/DcdxgdUVk2n0U9SxGF7/dL+M14y9h5e/XCghN91hBsFTz
  template:
    metadata:
      name: synapse-postgres-user-synapse
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mas
  namespace: synapse
spec:
  encryptedData:
    password: AgAsfik9QDi1ISeLRwAzITEmPBN4j2RBcOUaoefdZ913b3SrYfWyZo2nuwfpXpLgEGnuI2fdr6b/N39/ZwozucGwIU8lg4Qu2t3xP1cNYveBgvlQPcwgJDZ1iFZir5KFRszDPppVjpuGRvQTL85Di9SbUaBZwHUf4Pa5DoFak7G6I+QC0fbToPf4myP4hWrIQfrtmVkmMfbF2+SvwmMBxzb2rpHiIHx8LgqYVmJ916kkAuo+G2qZOyNff6walHSo0Zo7d6QEUkSaekzpGJYakv9ru5Bv+JCr4RFPmat/QvBh6lm2aGClplYv0RTEr7b0gEci2GqUZW+gJJjYk112AQE07lrjyjDdloDkDZZw2YJnsP/F7ZkMWclY2hdef1XxCxYeslrZbGaV8ydSuTaDEIYjjzemekhvdvgg8L84jdYB0oma0Mx9bE02XQUE7VXCNEcpla9Wl4ssaO8pDoaTXDXvWhKQ4SDS2stTy9K657Wnpz09KbeoawJeWO3Q0w8eSlxMTeG+/2XlVb7zdrqdan4Bnzq3KG39rfuwAMOV04Zn2byMuoyugIcEZIYzaB9Hv8m700RgfeMs5C2zBnffqyx8eoirHmihZjZbRypRQRps3t6d/bnZdWp6/pYnoshuEiWQyfkYuoGbFhBGHFsUCzf+yd+Rv9WiX0XMkdyqH0xmHmS9e/c1aRzLU3XnlijTvaWnxIL+skTaUPx488UfWsoW4eqblA==
    username: AgAJT2JRpbymwi6ZuFC3kE3yxUCgBbMTc+rOT8ZxIMsdYGhUI6NCKph+kIxSACeMcG6levUALFDuOJLNIqNOlRbBEZmEMYXvxyOru/7I5oUxZ3GHDqJnrq1FRdq3IbNniUvc2iTKiqEs3wJRDBszDf00wFVnFLI47w7TTftWzYAcTW4zFFM9GmM4u2hFHdpT5gqLkseBa4735TwmS1YaYKGCA4hOAmfyxBASXqSQUBgHfJ5DcZ9moJQkxozP6gHisVqFUOafgBvf20vAHRs8Q8On46llvs1Rsl2p3zFZ3sJzHHFJts0+5pNH4SwvivYQDHySWfLTsEGx3TBF0y5d3ArGoxwhDn7yJWZSKeNeZNBQyj/vBUKTaR77lI1UqSevlip2xnabVlYlQ+AreAswGwVSeb2BRmjZv7RBPH2qooFkFr2dY+rSlNmE4+gIVoB2PzRVw0fYeJaz+mm0tb+QgGwd+QHw474fGYz5L4j80DgA2vURswp4jxhPoMGzwI2hKsenjfqGeuExSsBjUmrKbPsx1FZy67Q6DdXeQmLxWrWrKc3IQOj0EyR/dAwulTOTS/kwoHZr/qvQDhaMzB98VOKXpdX0hcborT1dcMfYtBDeG1NyD6yH39auKZ3VVTPiYcs1UANTMeE6hTEgVHbelsOktWLhNfU90ynrNCI1DEP6WXCH2KUbGKvvhOyOh1LqHSpAhRM=
  template:
    metadata:
      name: synapse-postgres-user-mas
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-gmessages
  namespace: synapse
spec:
  encryptedData:
    password: AgARYGVCc+JaY7LOq8UrAisShZkQKqC8LzMv0zX/3mISbVD7lRD1tyB320hpl56qZzf7WLoXT/lAZUO3yAQ+FF7AsvRwJL9C+K5C+bx1r4uUSzIUZHQIT/Ji0T9yp0Nr+eGVd2thudBhuzTkOfr71GVgQ9iOoWmPHj6RxRQ9NQMmVJfPs7YYIxP1xy2T7PlJhxF60RfcUaBQYpITgYX0tPrzOTHmH4k9yR7ykwyHyfneASTq4yi9G30GboNqhMMQ28Ff9pMgEM8MFkz738rn6cj6SM88qvQj0/SUmFGeG3b3epuZuK43e40jJl7YPPh+aYQvmFF0iCtPRbeKqWoqZ89QzV7c0hhqXPIR1d7KDXC331mUtSsluMyanqH4Blp6MmRkBNAyc19eTaLZSH4+NQn8ox4gYwFMoCoi63tBzS5ckEoUx1XcIR16HE88p96ILjIA0jDGHYwI+bGmNSgUsHm9xE9EryNA6HWcLiH7Nt+HnjcwZHP+H3zBMe14K5KkbcLdmwWuevtNX6Doj5qdtJNm5UBUHTwj1x47wlWlXRtt2N/TXmdSOZj38l3s46WJKS9GZ7xCiHAOlZ52OwUjFioPxwY+LbbZF32T6BrKEgN4EjSq6FxKZ+JdnUYA0Yq6mV0gm1nj6Yx4W+/2tZJDX8SxhbmqlnIZzmMQVb9CQqnfl/pyllPkXonoNWB3EY2mfQFrWVXTA7IljDrPSDFOCy9u0EansJmRABA=
    username: AgCgMUzgUHGkBwPENqiNLtv4VBOTonxvSMRCZpTp8EK/I/1p2/NS1KapPSTOTJ+NDmHPXl4Q4jdenBMAcW4xrhM3+TdZFEX0kyqpytxW8b/MB1Y5WPnFIqLTS0ZdYRcsKeMnWwpY5xoVrC9AqA7NG86GI9kJrDObZJkTJg9mX+k2fao/MKSpoMFrq26EQU4VKU8cVAUUBM8vw3LHRI3ppc8EVwYb1cb0Fjf+S/Rl7pJvhaZjshNgCqQ7l1x7ct1mlN/STXbUuP46RH03i3JqOTdjeFEif8m5UDDItlQjqkMuehWc+MWqUnIXr6unj3R5+rqUkKnXrKx/oi08rNeoxo7guASIfNm6gOPbtl1ISlbajl2CsL3ZBIQGOI3HfkerjB+wIEiOV6M19BTmyIMN9hfxXD0P6lbHAu/B7MMdVrAPiadroY1+zB45Z4bSUfdBx47fOYDtQeN1cCpvZGfjU7wx800Dc1IuzXkBmFJr5ayuHd4j3r/dgD174HMlHAt23F5uzZT08klls2yKwwLIIDt056zVKwzjGEM+y7zdEUC8iIX6CsqX1FJ/ILzIBzfAEjJPIo1OUrfsSBB/h9AESCXCiKztjFLlpMddJ6y+i73bm6/VqQymJ97rxR06cy9ZcvJHBw7adS6LxC5KciEX0tJfKFIBu4mZV3ss5HVO955vBENQ33EbdYp0r7xtwcLa7kGIaFKVH9GZxtFonYhiSc/EDw==
  template:
    metadata:
      name: synapse-postgres-user-mautrix-gmessages
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-signal
  namespace: synapse
spec:
  encryptedData:
    password: AgCyIMArug1pv8hs1ERRR3MREiqLEXIgz/+fYCsuWfsxTbtdqq0PawJS4SvWTBj9jzbb13m4QF+QT6Rz51lXdQHhtUORP/Kn3QCFjTYQJtsa5OqkWRAKuFYWQWCpbmYu/+0JD+BiHkUk0jJnC0N9Gx3gm26p+UkoklR4upkzczkTsTGqxnNdgnC1Q+zp5KKBbA5Zsgr8i23TSnIInhw0sa4jsXqJXiQc7ZITFcKx9DV6Qggs70I8ZxPZNuPRlTK5MhUqURkQMYnZgbLR42hIbgbvcbzACd1x053gOV+UxGPqkfP7+xFb9PHiBQkArAOwjkG+psu7/b/DSPd/WcqBkjYjkAqGj7HvxFxm07VemqTs4Mgo9u9AtWA4ucCDD9a7lChjylu7qZ6qw7916CxSEmixDXZExKrFnwlZScVZALykA00Cvmj9FtLEZ7m2mIw5XpAxqeEM4Dzk/GLj1Sy8OOClENoVRVcNhzMKwMtZzJopuv57ChuqKDB8mmRhC87nJ4/rnndHwtNm8sz5SJ5RDYMBwisGVszLIMr44seSZW32FIEwuX8ySxS6fO313wopuUscetoC3c+fDfLZmoZTC7yxUoDpFenAS7yVPPg4xYbBXBi/VVSsfokOr4Tz0fRzspvZ458sAmJ8W1HXK3vjsLb7kIJ+nFUuc+S1pwMeKdB6WZSqZ0znhbYrLBl06j17FDXdKfcmzD+wX/C9mEhROemKv+9+AG0H1Lg=
    username: AgC6oEgj5VxTG7j+ged53LcZbZ/bG7w4SelS/j5WAJ84oBcAVY2E/SdrWy1/UUZCHyDPxrJFESgeJLpZrMMWZE2cvbYUS+j4R/jqC797HKq88MSEEOndqx8P5NzGOszZ6tJJKN63H0/7S6Flf46aSy2hLgpl5EC7f4qzh53HayrH6P6PNtYYxGlz0i3wummSOXz7OcWCNG1nlKxwrBXQ3+fr7ZUGdhzpl/UMz4/F3Zw0XmRt8vDNIev9MhE0D9O50yB1s34rV1giautdygG/DL2T8eCjDI34xGQ+I4VuxLFQnOrjPxOjiNmPRhWPFDYhzVDD7D3USxdrdrwFWLFRoOVoS5w9uRjIMbn5fG3N+OAPHr5m+Sje/lXaK5GzEBg34/V4arcakaGAGh04sACPDjSOOKrnRocUpe4UMk+AN9uHxfeZy+BPWHVw8dREcfpcI8oG3cNidWl3UB9f/oU8UbcZ3do3k7UZhX+/xWZ10LAzjE6Socr2UR+hiI6l+x4DZ9rU6Ojh93m7Kcd7nW24mnCaQmaokaMILcm5KQeo3pivl5J7Pto91UMqwLgLWxhMVihHUiAB3HJjVw00cLOIMVX1cAmrOnjIdEve72CfhO/pz+8ezwcRFZ9utJjRrJpp65iG8Vk+j16D+NcDKyWT6oB+SRasCCO0I4gaGQt1VYmZtBe0doVC5Oeed0EOiUR3EYlnydWm0H1rFkCnwDbkfw==
  template:
    metadata:
      name: synapse-postgres-user-mautrix-signal
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-discord
  namespace: synapse
spec:
  encryptedData:
    password: AgAdz/x5aveOd5NN89XKhp5jZ646mHv8ogJXHP9XxW4BLvmUDy2pZ5uI+dm2+pxVKI0k83uGWT1vxyk5XocNJ0ooIM8beZdm3VidxzlDQy32epkLSWlC5i8gxyB9M5Cel8Cpa6/aKn3OcT+woJ5mnBsSLU6T8ydvCWGrwi3o1QclJUdH9GsFozlkN/ipGtFlBNkTxgv1dSyzO6bmU2FUkl3ya8XBe4QszYs53XcOTf5ZE368HFOrkdGEbEx73Tzt8QG713C5sbswY1fghh+T6U6gd3/eD6QZB1czRabeoZZlGy/sIqZZjzJy0UKh1NE34so9jAZPiPe2opm+UfUREBPABgEB74YwfM5pFHXArY3PKaYG+LWQyfNZ4ZaF1sAFZjiJSH4HaFw654LqHs0y1Xg+81tf68iSCCZCoYPcHfK5HLFpgfhICEYEaQy5MWLFnrXL186E1i0SOVwVm6fqikN9AMFsTL2yC0T6AYySRT1PzvGcyWy5n33m8/cESB3LFB37Bl0yASSDvmMXNdFVc12OxOYf8ElZWZ/gPa0S3C2r32Dbd6aNzURLHCjcBhFrLnFDFY5EYOsXNvVLDrxlwG5POCDgrya+k1ZsQgfwv5MkeHdSMBgpYi4kXlYK3C/KE7/0vU0Aob1rLKRQD8gaeAEIodTDQ9P8bqTmYUGp6tuAa4965RoahFCodMT4iaNxB7KQDgbP9D/Ope61QB8=
    username: AgA9kc8iIhtPw3pgKpwkl28pG8Z5l5YGlcjcXvMu0dlvwMOJHaz63K9QWKsMb4orMtnGu7IEqCT7Ch85KmbN3j7kUQUbS7Z7l+HtukngXQUvjCGo2qcyzR7+FZwRRYNZLVCv8jMDaLnXK11KcasXQ+P5UuF3Uuk0ueRnWyM0dJsb+h8i/nCGPtsZo4NGTc4TZXeXmKV8I6ryDOgktjS5SlvIxIH/mNk/sF1vicsPI+J69u0/1JKJ6moRxKHLliYP+s8cqEqIm2TxxDT7MYTkcPD7Hb0fl1A8gGCiCzw5kM9dPEnt2EJTgtmikCGfBXutzuVApKdzv6/Xts7OJF1yuTDQ/olhEYxCEl9j3qdidxXn5TBgAERmPZd3JXMaxeGeGhc3oWYxYUesztez/Lk9kAeaeJmKyVA3JJU8GKyVVHd853lKHiweMwQMuu0kwKdevOEGxtjsc/he3PSXuBL5Do2+PqTrgh7cdMbCkE3rZY92OstJjSy44J7Kxs2/G/GxXIupOE7CSCjEj5ZgArwzUV0kd/cNfF6jfk0HsKneagpoDz3dV5PzlNSh6/hDIwKGOQV3WgGxQz3uV4Hupvy06uUt6AkFCbTEgu85vs6ZOmdRGNpjwwU54lYj2q5hLLcNfd2GrRnb6uPqVJV2bE9OnsYwHJUv9so+Pxg0hK30neM7p0t+uMiaxX0waHO5Py4gKZuKEVY0wh6dmQ3BZSTkFwk=
  template:
    metadata:
      name: synapse-postgres-user-mautrix-discord
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-telegram
  namespace: synapse
spec:
  encryptedData:
    password: AgDHfkKkZ6t5tMfzxtII3BLF3ak4CDF9DiMw+O06MMEwmUWv7pQKF9yZ631uPzYx7iyX2NEhRw04EdHXI8bGG2kIxAcKcm7o1Nt8z+WWtIXacHOf+tim0YyDBvvs5HCbGKqC++xg40a/tTjsPnVVf0hA5ClAJhkqdN5cZVsDtmzAsrwf+Ny78BzWTWk9w35ztQ8JHemZsgElUXr+XoptQndCKoT2hspnDDrA1lgIA3K8P+aCeqa1PSYWvvAzA5Ai3XiVfCoue2DbC556198p1vYPzdkxlbOF2ul0/RwhrZZKjZOtqJbbKUZUTKGsXx1Cy2qmcTKhXhrPXPqAn+He1RndmoheVDLbA/3zRUS0y0jr60I9KdTQmJINS7f/1VB42J8sB1Ub0j7y3QZtE4VoKCgl8Jji75zc3aHHSs9E/uiR+lxb1k1+mwK8cCEVuoD+b7SKblgyBG+wY+YJhL3jRz290xpgLqKxHf8BMgZ54pN9KGsT+mwvAyK3SSk3LYSwbyQEJCg8+71uda0Zj9d2lqnyK6N/LkufNCpUDgZ+Vy4uM0I7LWwsm63KUZR60egS1oWKnu0dtNn3rQH2TElQ2VCWa1rl6Yqnrd7NCJ0TR3/vEpaaH8Cfd9OymCeYFo6UhZx/+z9Op0qeA8gQ/xJq7eYgBlilaA9YOEe/dCisYNTLYyuA/MoaXCo4KelnTUoHWCKgxFhNfZZekSOXNbI=
    username: AgBOM73cR1+Hkw477D4WL2GUmRrIrlxRdmwPnhbA+1BKRsJoSEqTQdAgGUHoA8Vry7rmmBRUtTujx37yndnY+n0gFIG4OU6PKKpNhvAa4EKq0DDoZAZwiNp0JbJGWmpz1Gwrzhs1zs/v2OZfHedRWsFaaJChsCNFGaW5muRgy2WgIFJh2iKkDwBtUM9WG2TpzmPNY0E9mtbeH7yDdKnhwScWFOd/7+s3B4GeylrntzYVcV2U/ashpZ2plQYD1SHs1RT15xZynEPzm7ohCtfoBxm+ditMPPh7uaqhwQ1UdD7KKpEQiXtvfcemneQL4fj50B52fKHsGm9OVSDTCCBQi69Fvc4SXTEVu4bvpYy+vj4f0iJupFATxu0XOkblZwZbypzoDdEElZsp8Eajg5QpbIkv2J/qY55JOI8MZfMEaitRyoH7z2KzwvlFCYr76Rav6XwsWHEGocCT8Kqm+mw4fYx8F1GPDS12sxQZ9EQ5P67kpIpXdJyl9LxANRLAzMmCH6UA3EAsWiZ8RvIdi6tTIg3cWNvLvaSh62iZUABgvkDZ/E1VnHryDQhEaIE5CJ0gmTOdgKDxkhE4YuCr4gvKgKi7On+ATUpXGvLXdTwsxiK1v1zD64l5nL7XK+AljyFXUA6s28DX8FPjpYkaJdj/sl7NqHPj2W5e1dFF3iwjefyFEhOaD5vRWpRrmBtLd/D2kHSc5Z5q+9KH4I+Can8eeXQ8
  template:
    metadata:
      name: synapse-postgres-user-mautrix-telegram
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: synapse
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCM/HPHp91eevVK1CFldf2h+WOCIeCAVPBZ3yAPGjsXDPsUUq9m4x9PCgTlPf08s2p87NliYiVvHf+wvHIkKxwZGdHVASS7mxLcSmITc33HbGYBWRAUXBu+W3uboYUHsQqXG/X2a3hb/qNUjfYzjoRNDy0ASInSm/nXZVraCo07tjmDzT56QBpSSbkoiodt8vB8YUzAioJeWd/O6VRleUKfToslhas9BCjF4SsgnB2xThM920NbxMvTaypnrjpnC8F8P7l9W+qD7pNlmpJbc+1cMqyMdsfAVbaENF0jH1Mwr0WOwRpoYJavJUTTwqzLfgf1fpuBY6gTFpSu6O9YUypCMaLU2/GmroqT0hsv224H/vzVPl/sXrkM/p8M6gW7ESkqEeNzyaEaxrY+mhI1bb+wXS80brInAN2GSH14VPpBj1t9hfy4fKlfWSHPBd10vxPFr58BpPkjBcsO3YHiFyX6wvNKMQ5FyiA7laELzVRLsLrqkLR4Hae1GKg/G1SOIhVEt2liTEfU7bzqT8F2UuyRbjnJZFdxdCB7jMe8yI2Vzbrkky8sWcl9J+8nsIBNVbR0I1afNfgIoVrm/sv9E4UJAdzqFt9kJz4MZY0szRVEueonKfO0JJY+lKmnY7iFRkenV62G75SclBg7ZZ7j1w93AMSxh1+Zqsj54KTWrK3hguKjVmSXaywJ7YcivXwdzGGV2KB5hqM5G7kPxBpKLbTgeoK2Eo/6LEJm
    ACCESS_SECRET_KEY: AgDEYURI1RKymm2FpzWBzVds4BAQXUSPVspkKAGUpffL0S0kcpsgOYrs6go4PU3esi++CptSoX922l/LlC40FRRQt/1OR/C8Z3NixwtisuD2DZFj57Z7l2uwocugoqQhLTAIFRqiHpeCRR7kyCbSBKRc50UgXwJSBxf80zlAuBWlmY0uJMaKephlIcW1QxVqYRsszpfqR3sUQCY/MuBrlIcExq2WxsxkYbpi4XFGZHDA8eL/D2Ksgldzft3dIz1ve57V+0dsTeD1rYKevJ4sYRWRnF4zO814aSyaTAlu6wIDuSPnY3vGzJFBf09wGyg0E2NHUOSjzsEUf5HaBnhdL0wyn18C7trAA7e0qo6lOpFh29hRyhd2fINFLslhgVBPVuvWCC+gyGc/8Equ0wTdjjTLxaCidFoVkJeUM47/+beI2oGcLI7AWAmHXxaOyEYlUkZRcnCkhDeeecwrnAOaiQn4wRzzkvO7twa77LRrePGIdkWnywXN23xbZkZtz/iDDKDgVxc1h96yrs1mpZTbM76o7jUpepgCT8gbYMRqAuaeSruWrl7TzQcxsmhYVpj8nkh0vvZ1nUnFfX6iMOVQ+0zXbFu1chaGfIVoiMeJHBpWe6pUME3Q5/axnxaQu5km9XPUGwYGOw65thdeLFxG9i5F9o1veVxL68+b+hX+U5DeYxJrmfX7yVbgGcZ9Qjwnpr8tubsHESfB/VI9WBXHNGImvUz0yxYpo5sWzkBsjsx5
  template:
    metadata:
      name: backblaze-creds
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: synapse
spec:
  encryptedData:
    password: AgB+1nkwA1M42ifclJJet7AaFQE7648VDUQqJM2ZEh1JWKzCUYghRkaWLY3RieV3wvVfKLbdsRB2KDEWHtjs/ntnYtFKzj0qQYZrRiX9AynyyDajTK/uD6RodL0Wi5mIqn3UZt6Q6m0dS2cVUtFxLL4UohN4jNImrIFC+G6eiexygvveTSuOpz2uTD0Du6Z2vPhzVVuQ49ya0jO6GeHq4cXjqbcL3XyOOD+70RfyRxQd+oDwhrTIZnoAvMG9355I/pbuXWUhtTZPuaD8L+ZNzqAl2L1cw1p1hUaO//4QHp/M6Qm+wj/9GYD9CpAnIJhI1XeoZjiP0EMC1eVDIfqN3XypeELG+SgYUdo1yKO4/5o/VEiT46TtNp1GVsaKolAHcDTnaNdny7kykb13zy1g4Itc5DU+wQ4Rena7SBHTie5OVhodSujYAoQc5GmIFnqUhz7bXNXvZ9ORTBS6OkPA0X5/Rctf18sBscebrQZ3Bsza4OeZ6OSqtiCREi+iBpzifCY0gekPAK3k0N0AUbcVUGb/ubTgKd0PMvrSqSLrL5mqaJQSaBsgPEKad0HI1zK7+vdKdPNKpZIZ8pqVej+pnar5GOZAdYSLseeN++PvIJy/99/gdWTpvfPnNpOQqab4tzNf7s7W67dX9FhuRNfv+b/6OI/04le5OGAViuFEaMqp5DoLGru9R7fiUzuBQYgliQMXeSRLyAKvgc7QF9A=
  template:
    metadata:
      name: redis-password
      namespace: synapse
    type: Opaque
