---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: matrix-synapse-signingkey
  namespace: synapse
spec:
  encryptedData:
    signing.key: AgALtbURek/92R/RSaWDEwFDC0gigez+2yUbjFaXbZx0wtK4TIg3xMmclggESkj5fijomdxQFRat3y/DIBTyTL0MYXwf8G+4h6o5E8dQay35OwXAp/hql8cCUQyopgYgZ+kl4AD1RJ1eVWsi3HXdvAuEGTn/CB1Qzl3lOcJlQ7vsOiwRLU2jfWfGC+fKXeiPLmmyBGT4F3o+2m7T39CA87NV28EClwxovJITjFqpZnfKm8acvtgBsBl3a5oLvaNOqgon6bAckmT5C8ayAJdlMI1mzMxjimQpACD9pUWoQ4QXATjOjxic88Zc6a39p6ZGqq5gplULWqOCNoL9tuORywDiXbeBcwzJE2C/k53Ea34ZrWNtYX40VD2sx53elLRvH57Mu9dA64yFqQ+MbFbVjQOSZeb7/NlCAlBPSSc/Cxf9FnHdkt+Z1YdbMoNwkAHcVcv5R6gB7qe8887Thc5OXyYK5qa8Kqza5LvmLF/boEKZRtlmeC11rQYFOZL8Bv3u+O+K/g7gTE56OWPmqk0f26bSJeAwtOmgywPbbCmWNhTyTAkmyJnaz3G6nc6vrTZG/QPq4tLq1lUGXYBTuqQo9pHeGqdxCJk8yv6AIoxv6+jLkOdtuzLA7n8hDp4QNJbPQoBSZ8MV8uf2Uhr8tNGpcRQhMF18NJrqan0lALZj61sxSWs+7+sEh6UQYZWMOkVBBXaHXnbnkWS7uzfyI+gWGxzKPYTLezEgjNZCZclgeuiYBT+3yzhvn2btxu2UdSpUqsDsWIr8+M7oGDZoQQ==
    signing.old.key: AgBFTwPlGNYr7XfXbZUIx4gBx59m6of+qw7FL6Y7vSozHDL4R7+x4YXgfxKlAVGxT2ZfKoLtDkEQK5BkUFFnNKLyI99RGMT4mpY8lNjX6BIGkvcngAEnYeTinUmf7KkbBXQEJP1dSvdh6Iz7Wt7zEo++T6VB5bEwpFPMV7+DcTmaWh6nPQ2zBfwl8hi63aP9stIm+4wJ3cJ/Jx0hS4c7wXzSnAGWfL0sXEiRgTBItJi1p4iZlQ9J51ebySE7bmxo8UM83+PQxMvFdRC2GmdwHyYf23Qjtdd2N4FrShMFYzCZulgWEMI9u+EWzEKg9YZ2dusA/5DgK8cfoYJgnlayev2Dz4XW8/iJc/W/JDIXbFloXmFOBM20nIuK38B+InDfIzKXZ/8Kczkk4Xr4AF2yavU6blbfs5BrIXu5u/UqKdyv/xYGitXuLtL+ZDrFcOeOwlw0jDIS7dCenJkLtgUb65giICjCtHZUuPrfClj/YDIaq0sk95OyFaoqHUlzXwc4HLSCdjASV3g/3JTqn4iTjxNMFILhw1AEWS6p3g/yESKL0e0WS3yEGwQGpzdsV2Z98eP6rLt3SubhfU1zxzeqboPccVtJiMc29PLc4UUmDeAPgz+aMVosY30J11EVcd9zHWIpKzCPJ8Z/jXLXaYbpv61AqUwKEtx8Ny/x/CxfkqJiDH0C6jZbssLtvwLTpPlU1hgPhJxb/PrYTk1J3Wccxd8Xlaiw6y4jlp1qNaeg/msLoCb6PGjeDD/bbxkbUMUFnokINgYYn5mC/l6l0g==
  template:
    metadata:
      name: matrix-synapse-signingkey
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-synapse
  namespace: synapse
spec:
  encryptedData:
    password: AgBQXr9PXLi18ICG3n34KGndnTt4Kt53yXEz2aDpzNMc0kpHXT8D+/8ETEm5hzLeKzTJGhVbMsgQm4s7luYAJk+DKGA6SuxXxU+msn/DOGytIntxs+hrUMVU1b3PP6IwJ7CO9/YFZ6tFgz7X5KlrAePjNWPFU0dHrDJ7l1+AB6QepNTZGFQ4tpWdLx84rU71ifRLA4xhXAFW0Rt7EOq9cvW2GiYS8VDd+GIzCPZK8S2YlTTZqdNgs79FKznRyuYwzWvhC36FpITvI5Z62QfMVobeZkwmsSoFzBJZbzl8bPNWOKfAypWJF8f1yf2eQBxbtFuwEZ0OwDobVXg6a5Pt4XMq3c5ixjDgwsFZSHl/W3QpYKVL1CZQqCtAJn4TUxNZLPk/yIOSSdAM1UB0tr4fYorpxFqQb1tNdykATHHbHnUHMAXfaU5CS7Y2mNZDKdvecn3xLAxMQ0hfWHgjyQeeAKW7OR0CLt6aJtP1e79hQlsE1O8F65fUhPUhH3CLECrasLk6OXImwnW+bn3ry9ZzKoyO254+8VOsQC4rwfTuAAIchehsiVjVsC+j765nYmepSVgeTObKvDMsP8BKXls97qnae3DE+YUW3kQLBcOOM9I8wovfYeCFaMmIGekKLFDcs2GypQ57l+k1z2H6c3DVgZlkGpyVPONHFGx/qQVog+6Y1arjqGh2ugNUB701Nhc7Ir9r8+C9OXDzUri3lFs=
  template:
    metadata:
      name: postgres-synapse
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-synapse
  namespace: synapse
spec:
  encryptedData:
    password: AgDBNEFhUSVgSX8Epej3oxqP3oXe4CYB8A939xOvwijvtgw77u/yDBE52jG/BnYiVcofXV63kH6WGYjezitaz6iTQW6MbZnB9byJ9c2jTE4e4eru/tOwJ62Ocs7otdVRef7jrmsjF5JGt6T2bHBsERnVcnQvOcFN4l2w1VFlLkY+eHD284fyAT4d0aMsEuVpoOTV4di7dEPLjH+7TAIx8qFuIKWuwC1m9hCiuEedC6Yusj5QYSSNM7kx3RPJsliKwP0Jd5HnNp/D/F3fsgPlktF9PbV3+W/fm2ln1tIu6/3FuvE/oFoVhMSo8rPMuf10GafQ+FeDPe4+wu7ODK91gl+UH5vD5B1BSc6Pnv+cBajQ9jo7g0zxLTkg031PW8LVWvz00YqzRYcJadON0Kd0/Tbms800Q/veDhfWoNcpJjuoDJZxiL1Z5QAYOo2v9cKIccEwlm/tW2fV4kUS8QvRSpQKDLQ5rh0zUI2kkWXxH8F3Q6xtxovIf8mTWNV69qzxJhdQFWy02TtHIlZh/9inosBA9dVwa773KUO5sA9TO1dHZA0xnQemAEsOxedKFa7+IKAAh92lnm2CJDyymJy6R8Tyr8VfBiqBLAnO35TS5vF0JTsaS1Xm+YMfNoSYjKrJafYGiWnHhp2Vy9Xv3wYPViqfrra4B5mmW6IcG4/4ZWTXd39WazbP4fZZL5OO0mE11nbGn3BfbL70WsaVjmVTNws5p1L75A==
    username: AgBssK6DkvUxuHRe/OMLHqpALYsMzUIXnPv2eVuOl2BJykM+Sdwm9/zhJNfncjk7sgpMvKnqrBFiLxqaUbmMfRXPf878zs73jU+tLdJ6fEqWYfDW76LaymNdj7X4xEwKhFn7MV/UsuVkAy5kIhjYhzUcApgXx0DQcsfY87VqFS16FmjJ1TfRpw5mqzuoMQATxZ88GjViJOnk7TvElFK8YePHxG/k0kraoc1LoL09cHI3xwpXz1XvbEvqjMuXZKqn6PMYCjTh+8+XK9ZTzeWJjjYwwDtc0D6z90pOILvxJ79Gp8pWl3tD7eH4bm3q+cNIOHx2iM/PBfw/njP88H5wKUPBB/Uf+4KVedXJ68pv7VY8Ki8GzrmUkzpL/LyROA7otVkl/ZyaW/pTscoon2ZJ2wFAqm4V+b7mEgIsk2f/e6sNDhb4JCY4r1KSZhde7jaWP/n11fL4mwwCd+uboGdi7nOoo9eGNEM1J0wY/Zbu2vGiKd7RDKXPybho16atjBOmzy08Iy1hYC3udmJ84mGoQAFEDnN2YYeIT9lYiWDmGh72bCGnbZre2xeNqVwZqjYxF88Zs4x7o+lHAucNVxajBtLl0OqfS9vMrQxhGx33yhaYADXkfY6kjsaZhd2vvOIuCAXKz3znpYiwn1MWqS7H426NStGy9+RJEj3f2aAuhyqrj1vd922T4Qsxdgm2oTVJtq9Qx6PIJHQ8
  template:
    metadata:
      name: synapse-postgres-user-synapse
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mas
  namespace: synapse
spec:
  encryptedData:
    password: AgCIZHjyAGTsex0Os08QT/nmnghejCyIq2pCkXi3r9k7kT5mRufw+4AojaMIRBSbrUyt5E9uiUD0WVgEgsqfGs2VNnWaAVoxxY8lp+HtEQQQ60WCkMqq3DkGku7KKmGmkBmtsN9FL/w7gvpYQEXU/7PSHH+xnJBpP2mLAUQ1dRKPpMAFpYFYPpWu/jE6jl4eS7KgCTs/WNBjn79qpvaYRqNjCUrRRoPRU9CnO1Rsxa+H2B6UTG8Yxwky0YhE2dYQoNHKq3NVCkPnd8Ou+SKbPT/LU3tcVXN86P30ppaq2X+/vgRdWIHPeLx00g1IDWeK3MCG2+hLOMBiLyAHS2xebqu4Q6C4HWXnL4g4kh/3mCaQN0pZm2XxFEq33hsmIS83OaroeHthB44Yhm+mZzZbs/WbyExjWLe+HXBrvdDOQyO5/5wTj4Wx6/YqHc5nhdI/48G1+sx2aNcx+9tdb1prge1lNwPbaOpSx2Jh2XPsXi1e2hPMFi6s25yGON1tY6LTghpdxSgbXhhv+tkBstWa0XltKJKtq224/SkLH11NvRlozhBgT38cQt+aQ0sR3CN8ymwy77sZ592mfu72dAwWRq2hs0CTU2CMt9V+1WPkFSVH0rfFgsl1d4KvB9Er69pxFXajIZpByLKDeMs7ZvPbX+yMXgyfQGRK1IpFujh166YmUxX40sX5cUtqE5Hx1FmZ07xGEcPH2RePaIs/2puHZDvnqQjbDA==
    username: AgCEKLmRrdSt05aN+Er+mp7JqqE5vOasDski0IlL53qO9mXSbtHA2607/YgOTzNSMz3jaOG1tk8ZuSLjkLw8fH8YGyuI4JyXr6rbbzDV9VcOncIjgLYVtJO8f0Y5tZlk25Vjd/qzCUGWw8wIugdCawOLu9wYW7pEP2FCTp50eCHj0wQeu555sTBiSDPl8KOLT4oo8n2Fz2PyDyHFKpQcPO2gbjwJqJy2+EOINb6Nnz6tmYBvR1JRiauu65k3YM/yb2oIRHinhcp+3In0EKMYXzrDgtvpXkupi+SExNtlaZEZHYSs0eNVvYm0QThOQ2Lu3epiJeLmJpiYvV84y6eoqraoQi32IbhezovkIf7H9Rv4LASVs8xtfs/Xlo9u69uBejpj5MOwrPfGTIzmlnP3D5K+5LdlT/GOAg9ftJp8hu2efhE5uKGBtZ6thAl3ZySgVkKR2mm60DUxFAkCsrMyv0vcqfAjZ0V72qBHXNHmqHaGYVPDrqrUpgQEO9kdmqOikkjQ1RQXDAkR6FREW8zcjvt2D/Frr7AnGWxbtpHKcTMdyM59OIrp964hNoyKd11rb3FXt+Mku1X/dEixVvceQTYZbZfrppGnCd6cItlKeso0I7eGwEeGgoSC2w08sZcMItBH9yZRUrDE5eWWgVxy1QhREPDqluHugkokPIfZPfiKn3nM2aF94ZBGpYL0l/YGZ9d+wGE=
  template:
    metadata:
      name: synapse-postgres-user-mas
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-gmessages
  namespace: synapse
spec:
  encryptedData:
    password: AgBKsaACa4n0XQSrOhdnoMZ7aS8oLSrMGLDosOvHKcVyDJCshJgabdMod1Pi70BBZJT6WBx5fMsnUBPrek3Flf9YaKcS4kdkvbeDh5GB+DN0TnlUoMMUsOlD+Gq047RUjlIxXFCUW5pKWwfzKGQSBE0+ZTYNF8zjWM86WDNqHWiL2XTfJHgPodmR2NE67kwXOJ8GXXRGX4pBhPqfxx6Zp48g+qJP9UTdSlhNU0yisrEhwJieVaGTBNh06VDbjhIxscgYGx43dRpKRvIcofMo8+12TCynBOLpoeFtlSIV+NruPuIJw9smi3XhytRusshA/E/mfE4Smhp4uGJBCzzK4Lz7T07NZwwh4ERQmAfb4wjRR0IY9xJRH8i6d9yuotQoUvnnqK8RbcWmOv7rF4fG464ARD5UtVEEtGnYDyoWxw4y9DL/y+G4p+WsmL7KodU/9UOkDUQ/nts/hGIRvk5WP7rAbuGF7dOORNdcZnyXWhrzdFaWKzpDkEoc5q8CnYauPG1EpLd1Hu6TZfnk/L1Cs20b35RTNYRJoFVd3icGFgDOnZWSpyqtSJqX8QfDPytnzaWs3lcACRlG7VEIp/CBWUg2RLQQkwS6tYYV/yc6Cp0ElVALsyckeikn6mZ3bXs+qashLDWDqM1FcdA/o+21kQvbAfVqVbmT3GN7UqJOJ9LzSDrdC/c//kCeGW7oLc6zqSBmBV+jO8V71bHmhqMJzcRbAht9pqrlKmM=
    username: AgCH0ROlU0e2xX4n4u4EbuLNkZoX3S95019MyrKt+XJjxVhwyz1MFpzlj4EnmjIRv0WVxQnMVDdUQsBlKZlHvsxM8cQBlXS79SK8YGZ9Q+OPRFKuzsPXqzI50DzRngW4sH53n1zF0ij3Do/O8p3fWw0JF8Pw63aIHgV4u6U95ZcNgpEG1qHvbwZFqKxOmy7mkHc0+0rtN0aY2OTlDuzZSw7m5WogCMq6huoE6g7ubKb11YCLrkUswe5Vb2c+C/7AAhbkB3arqCYlzuEb3ui18fCRLBLE+98uxJuKhORULeTKtOnkXTvAWfWU8UhVRurx0fyW2ODJV6X+dA+LgvtUs31isTRmlaqQyPcoDLdWvIHz5XC9dr8DN01xhxP/+uz5vzjTSYORAe3cYFF/eSNPhgya+m8FxL2h8z+/CcQA939lz0mnCF1vQrxXoQTVPwemim39XOOnk+djoleFGgvEdNqKPzFk2DOn/9KTK7g5ORs718Z7mpcNyWnYKJTLjSvYp5ptGFcM+6D+TceezFGXqkfcvxAOnu8yKrPLf3sRKBKiGhnKeH0ifXGpo+ZuCdHLhJ9OsJ8ZdqH9WeJSKlk+ebh3a+m1n8j7R9/b0utEsgNtrmgD4r8ahJfy39QJ5U7+kZ4tLgrMDYo3L8OeakZDZl9zU1hNT1O7j4nYwlLweGjAtt0J6txWptSXued/6H/bIiZYa5KQKYOFSc6ZAbWF//88kw==
  template:
    metadata:
      name: synapse-postgres-user-mautrix-gmessages
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-signal
  namespace: synapse
spec:
  encryptedData:
    password: AgC7M7FShxvC9a6JsJhiEDtic6pHnuaMhetnGJSbK19R7/HRE4Ha7xnZQCtchxX5lAUYYIwakvIHw+LoW4QKnC6psN5tp+8I81ITBxSqEQRk5aAKv0qUI+bOJBviRP2zGsMXvlSHzv8MGC4vLH+rkVOEcn5QDFvjdEWZ2xNSJrvyM++8Uhnj73z1wRz0FqVs9XnoyUwG7zlofh23QlbR2s26o/C8KXw2BtGE++7nPWqnoXPtvhyEFp6BkctDeExbcHWQiXx1pQFJbXK9d47JrLFTXPerTme6D8R0kb1wPCVJQASDQROybF4lhSdLFpmjoLw4EwquErkRVVnLyL2WXqPDh3nFtrcnOpUEwGRFCfQxf/c16P9yFSWbn5EPYAkOgTADmARxoAzHeJG4hYxf8s0Iv1HN+unEsScs+X9TD9QDeG0YvNqi0Ch35IZ+7qof7d4GToll5exXE/EjmdI4oZngu+kCSo/CQcMaQM+zEZ+1Sv7EYGOfYOUFan6xQZhdmdA78u1IPXCWhsRIAk048Hgx/V+D+Hht7/d7wfZNFHRsqDsgTreXgB7EkENwSIFpVlhR5V+P0IqCuEanfxNNbhM+aL7KfXxEFvP0rn6jSqoz6rXnd/ipbCHGUOCjJQEHc5Ob5NVFDSI1FNKY05MyH3yor3vPOb6BPtZNBz2Yi6M+r81LMcNxn/UomJFqsKsOHrcz8yCTrgUDOELwLHnXXoD8byN7U6HUTnM=
    username: AgCnyiT3iCsgKDWK5nOpeQ+85lyd+2Sht636kwvnUqL9gaL8r5OjSZCXjKH8iUvGcqvLraXCxetOuoloiTkilZyCvKqYZnHMFfD3vjdRvp1E94dkH/kXimjezBYHPqSRNKtT928U6OmoSkUG8/GMyNfAFP+KtSx1jN7F6q8te2a5qC3Uv+HN5yb/PGhyt5xUyL436pPlVlTK3I9TJ+4iGQZR20sOIwzQMg8YowtDDS9qR/jwtPI5Xb30lgOgMLcBM8HD+GorIlxIPMAcORM6+ntRvsWe6Y/ArbshWooiyheTEmFo6FZBWcOdh/DQpyOPBRCG6t+saEs1QAglMpfmLT876T5F2oywJtI4b1gHjhuZPJkK3c/FaAxQt5nYgvcQXCoNprxVP02Y4i0dAwz2jkajfb9I5VULLB9qen2H+TKmqa1GTUtAKpHE6qAk0RdCN4ZzBAaXgeDE7sImvEqBtdyatNnm/MlRh8fJ89JZWSWyQnN6yBNsnxQOjuQKaPgrKRxbovkZcXzMWsM0rc+w/ocuetD3ogFN1pH8KznOblzE2CmxEDXvbRCu71h+I9zMA479gHtq30nY91vqx2Tv4hxuzctP7jmYZj5r5Jz46xEhv1AC++6vtt1b2jwhu/kpYhf4i3ENbZ4+BGHzF/7/j84KU4XDg1H8iCM8iSkb18pRzzMIj2HJXCEetGCG+SvsYjTjJ14WGm44ZBlgINOs7Q==
  template:
    metadata:
      name: synapse-postgres-user-mautrix-signal
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-user-mautrix-discord
  namespace: synapse
spec:
  encryptedData:
    password: AgCqqfmN4017fYGwCCXYemwHgCzqk3GsVu88Eh6kh8xSgeN1ztC8xNMzUNMPnLSITroZvUQC/weoh4Z+0XzlYS3mPOrD59l3ESkKfUF71Ssx6wI6LCmhSRpio8+IHnOGCaBBKXV8K/LzUelUziUIxpWdHIUJWFmrUaukR0vxvbbkwiMUk6HuuQAPdCREkG+CWdiyY21tGNfiYtf9XtrzJPr+lYF7TK85tcYa6iODYqQYubNRUNVZxnYxRVv00SmGuvwO5+s5PZv7rz0i5p5eQBEP/7emOsiwck/UueW0x1Y5Al53BUR8PDHdRz9u0UVUAPoznRxQlvlIi03VAIrXRGPwEWp7/1hoIksPetCLKiryQ50v3hjRKIKNvn2kY39iCDCe5CEu1VfLHRpEY1TgjRphnP+K4qNggWTcXKRlQS6HWqzaffh0lyd4JfwqT+qmWLUYg5x3vaNFjxfzx9WO5UxX/OQ1uNjDILc1CRnl9W/SvUuacQ4Z9MFZSzXe0YZLiN80FsjVfa3km+Me7GGa7hO9Iy/znXGlqo2r/tz+wllE/YPJg4nYf7rxCZ1gWzHMDIIC0o1SJAdc7nEyzCGQwg7y5PuPcCCIYRpyRkZG374BQRgo+tPEFQ13aEyB396pFmKhpIv5br7Faqu9yDVVX7mhb1HNGorTB9rvMINSuu7z/0yQgiiwRmjCyMJqCS8FrjqTm6eYQ/J8RbmZ0ms=
    username: AgB9Lw9KaL5RJMJ1gCPRQm7ZID9vOZxqd+pCrmDOcEQhvZPFAfuxkAld+dYSdm2wVKE6qAmXT+lymoNg9oQsN+ywvSDbEx59XbsCZVI8qtdH5AbAG6twWkQ+Np4DTE0abQuRfToc2JoNK8qgxiTJsprEgRVgSUsqivaNefUmpWlOuVuG8UUv4nPMDvcK/TKdfDW9z04IihRpcXhzPIHauZZiuibbeWmrCg6byEWLqFlMjnXzkQHDISjJrXd8JVzhl+Nqfupkj3R8T/tY1hBdOxu+a/i4Pd7BdeDWHLAgFyLzXmeKdiZDI3SqGl5md9MK6gvfyJuXa1oQ6CDSmSyvDQf1VW0setNzxB76N70+hMgY+sNyVYSMJsbFLL0ZiFIgTT3v7/3JaDpvrR7XaTiEOV1zdkaFcL9OtlZwH8uJ4cxLWxasGeOXyABi4Z0ISg2d/lvPGlDQGe745RDXWRJR8snpOvNbww3DoD7j6u8UlxHN6FY1jvBOafQJ6paDz4P2vRQRJLVGD/g4vCHAjndM54861m8ZBTz3nj4pUgTRUFxpr5jRMQaDHI8fVt/RZTys5aX7LW8dgOFTkIa6p1E1calG56TOqn7/METux/X1DSuaFH2W3fYfyFKlB61DCzc9vis49dGfyxYdHG1nS+a7dxmSVH+nyDYoBOvJj9EvBnJWzKvpJYgi//hS9i6w87wAYXGOg6m6khN5CJawEpg/mTk=
  template:
    metadata:
      name: synapse-postgres-user-mautrix-discord
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: synapse
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBkIbK/XxSbj2Erh9d0VJNzlA8q4GgZyk5iHj4hBF8XE6Ri0p0VWlUI3YmrBB+CnJF2aUvSGZOECpAMo7EyrrDMgA/lHPYWhqwFH/pPVZbKAugArp0TxiA1TvHrcnTxOkhlxDgCfR+3iNUyR7BnwTzqeMajVi7FGiw9cuFfNhFU71N56agXxa4JmnpLa9f+0Qpvw65DBJbfyWYBYolLMP85D1qORNvDU4KS1yRcybQZ5HjHVMBuRYqXNnIhBvi3uGoQADy7wyok2K7o55XfciNRWZS2GGelnbFmhN1HsiJfCfXXQ7AZJmPMPSQD5ImRQ4NZHpfEWmzpTemPRHJR/gJJ2XdQvmY7ZVpyy6xNcz4QIUgJee2aPrHf1GbfIqfoDuIf80+zCUDizBs2b5qd3aAl55SWQGhkVFtA7iEOrcGsUGUxHsGvDNCX1OlQoOwFTI3Gw5U4cJu4WoCCxzei8kGc07G1IjCCKYQc+ZFYWqU0WJZPS/wW2tlVgxrazgFh10pRTWhP2apBBx8ZrTWtKdp8B+Nz5f8ZZFb6Lb1shw0VX8VaNQhxiv7+Yj9M7ETO2o0xhEWNu/kEYva3Y0cws8QCZ69Yl1KDH2587aDM/ra3Rt2KiUAu0gL46Dz9WrhEBs5cHjWydDgsAwFAYPaRkdnxTbPup/sY1hytMqr8NL/z4RmmqxybqW5b3sAsEuUb1SsTRmKJFqfC2fbrdk2eujvFbSOwQOVPR1L9
    ACCESS_SECRET_KEY: AgB8SD9iCUg8V82lX7gPaIkeKXQUQ020RYyQblsE7qXXb1Fd9Gj4lQ2q6eI2dxdcj3ApvZiE0ynndtQOZ7KSCyXTRz6UIZ27MfLJYn6bbveEK2Fo3RWc+SZVny2obajzbJ1U/Y+viu+1CotYhCNSb9KKFGLMtPTLx5htFneR6FLfC55MbRSO7qAeDAMtfE6A1Nw/P+Q1fTxqiuqi/ObyZfVtmY4VMdRp+pKK9qbzBg4HMH7twzAdJgmueM+/8twDWAN/LZGnOB/fgDaiy/gQki3zQKzvm1Jj+WnvjUbXj1EAprqeyCLCPT4ceIeWGFMsH/7/kVzbNHT7rgmui1CUuDB1pio51BJiensPevmrHqXKuLD2KGgjMKW16F1D3whI98ejM5Mfn0Vhhtqdu7QX1+KuwORJPV5pkegnf08Pbtjk0CbDGwM0bPkoOC4l56vCu2w1S3DElBOfXINvhsnRwP83TqXvh2y67BGmfqP7V718jYym1A8JncaCvQfPAlY3RqLmKD1BYFLvTWG4gsYkoxGmoUj5WZB011zqVoQGZmzKatlSrbVuuPF/9hO9h0P+J6JSlRY73EpubldbIoJV/BM/GIfd4dHDX3pWhXzTbP2lxYbstU+9zjEzoezUiDUzdy/bvwzlhnpoRSyGcWy+mbNl8Jxzt4gYx+2PCdpDGzip+aFNFSoowlkeJ0OrVzJfn+t4OG8eFNx6szfE6HqQP62NeW7p1EStHQUY26Wec0Zn
  template:
    metadata:
      name: backblaze-creds
      namespace: synapse
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: synapse
spec:
  encryptedData:
    password: AgCWv8drkR4Qbxekl3pWW/fSTtnpFZvYKW6LRx5+j78FsCEV23cQ+c3n+ft5gwfbDmxEhe2UH4Kafw/v9N4gRcfyGJj5lTzUXxyvU8WkIIEbdzc/ThKIMqY4wwj2m+FMJZsT1RCejzGP0cVibC2Z2+WQoo7+MU9ZgbwpoYTV69DcUvw5vnj+3Xy1Bmi24WEG0ReiitZsbnepRDLIirVvrnw4xImP9V82/RIuBZoj3Ujn5P0Z8uCkTQYAmBaVIStjnNBtcTzYJY3yOXZR2hMtPAQmSNA4FpwN5Kquc9nXZl5pZzAmIVWcWaZONPrpOlVMBUburkuGTo54FuUUOCWjR9ADWN/DqabjlfNnyY4WckV75Ez09ZUXmBnb5TtQjM011Vd+Q1CaP9wUnVLENqxnYxKSsfV3AA+2gmH7GbPg1Wibt4rS5LaLFm4UNEmLyjIRAWXmShmoX2LAKtOltzeWzlfuboMUyx977JPthKMeqMOnBSRPSW9RaNCSOr6GRNIz+d8u5DyO9wGyhgCVCrqQwu1MYPOHg9Ld/D2QX7plPzXQpyacKCQVMxT4os8h4Z/SsnFP5DSjKwhP6lszqVqSYEbggYbeAcHGXqCu9JIvyZj73hNEGNq6e/OHUsEse4yz/uh0jdDTlVxteiC+Xqqh+cTAf4CRhqd4FIzID3BH2s0o5dfBJzQdSyQ4u8pxyuynU3TZ9HO4yJ/7Ad9a75Q=
  template:
    metadata:
      name: redis-password
      namespace: synapse
    type: Opaque
