---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloud-provider-credentials
  namespace: velero
spec:
  encryptedData:
    credentials: AgAonnWaQk3eAEEOqY43ToC/3JIf5evNCcvpjhBKORTw5iXU2CX8ErMJgB4iXncH4b+NJUPAAW2Gd4pq+1cXgu2AmFuhntvlj3OaKztVKlyLqJWzDzBeKhdMRh0rIHejO4KO2TnkNIlXKazUVHw39E75d/P2H9sRnLQZ0jFNlH2BrIQ+OTv9RiKKxB6mDk8ZHpOkqa1fEwy2Ef1YuWqsWCcYKRwSEu6WeBrXYBnKYDj1zKKuoQDwhoe8T58l5WUHtRSfcg+zfdTaNBhE5hoOyvYKgzhiBs12ei12819U08lGRXXQfv13N2a+QEGNVIr4SPAnhH67th2I+f8/LL4+x8Och8Vu+0t5qNbscfWEMZAsDxrG6co7g4D5go84x8+wqYbmtD7PT5QB+WSnKKHU0aUzlGmd5jBtMk7dmNjDT0DiR4mkiudlkuTDwAnfHnkwZ6nqxm1+F5AFjpu0Qnxkt3pG/JFfbGztTJPzIIIok30ubINVfPlGit4GXZs6eZ7rQ0QBCb2tT35FHYqHBLHMbGgCp3jUJlvXMzxkifI+LnBedAyzTas6Jh89O09OuUDCrxwUZejGXk9Nes5e1tIReh+W078GVSqmluR62Sd+ndMJFRRCDCAjiFrOoMqnTPyFbNqClKluQ2HZlVqltyHyp1Y1Dhy8GhN75dDQXnZ0xp6gdbxgg3NZCJvBQXpxacAIfNAd5vEBji7dEJ4GMADqWOEg1TyeiYwTi2LKSeG12L0Gk8/WbSBvmCHCDB+SK/xfk82u8/GKxy3TEBuMXsNTJaopRKziOfZPB5MWDrBSk7Q5vDeuk0EGidQI9q1UcNN1j5bDLj4hR87DxJS/OydZ0R82
  template:
    metadata:
      name: cloud-provider-credentials
      namespace: velero
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-repo-credentials
  namespace: velero
spec:
  encryptedData:
    repository-password: AgCyS7dnrO96j3+0QL4YiNuCoqaj9XYkpGZkEsQgdmzC5wZ0bUXUt42Ru0sDo5UDAMm/+WFPFOneBSssBW6PgmovJGWt1TTgkXi7Y05dTwv1WocY8BkrgcV1HsDaScqzEu/kEpHhL/vY6I4Ya8eWDp5tQ80Vb/kguhcOV9SK9TLuCHA7Ty3qxk174eGZjx3oYHx8wgjX9lH18Warfr/LuhrdmFWKgMfvU/SqPvE3CHl9/LlD5SmF7ijTXImqqeS6B/BvO/+SDPbiuYRqlyfjGuHWxyztWnxREHKnO3DhWbRBu/ir+rR93akoWVbzSM9ujiR8nzfiDh1YYNrcXn4WcgA7Ee0vnFf3U0dO9KYXR66j7RIcbqg5G5i8uT1myw3O6q2SnEcqafEiK+KduBYcxrKla04eHlQ7triHxEY/5idUrFbwikvdayuDXWQKza+XVZ4hAkvUHQ84Bm03ygXAA+9y5yUcjdV9mzXwb238WQuMzm4JailOA2N+YyKKo3/iZD21HuazJg4SBzd/RRLWFO0mWCR/BConV8tnSeHzkPc6QzSpNIZ1XyjHRTVUs18J/ceYPhBihHwbMSt/GWd7Shmf/J8VIlagL4QGc+j54ZtLfn+RiRnJOnJ73QEmjbOsVKSoEovosNsWNVKgcvmgz2Hao/Im3wzbxeLpi7Fy8ycCZy6ALzecR/ifEwQPUIAFiH9pEeer+A0M1iCy25DgxrgGQrOaYpI=
  template:
    metadata:
      name: velero-repo-credentials
      namespace: velero
    type: Opaque
