---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloud-provider-credentials
  namespace: velero
spec:
  encryptedData:
    credentials: AgBvDmneAjtE1D8iaIdHKLCG0d4YztviEjIIVBn7DoswnB1qcHWR50C19fNu8HDSnZiAmO5aK0IMXqCS5GXDemIXJQElUDaZSAqmMW/uY/Oll+tSQ8KeGDfgFloBdNorC8PRhe1B69d0lci7k4050TMCs8k6t827Pt5rksy+4ps48Zc27ZkX7VXIBIT4otf8Rz/Fq8m5Zy4OSD/fckJCaJefRuPMveokixZuNT8cMP0TIl2SXjKrFlTLVsAEyJI9jxKxaP3EKEnOvsw95/c6oQUJd+jwisWkcAVXCCRUdqHbIMd9JFrD4dfP+zGhvus6jGXcihKJkdZ3gPTWVV0U1POsllb2SpWqhQvYqX6k3nq88wYGc6LBUf0qndpEyW9DDf7E/1p64xdWt9Fi4HouuJXyNwcBExVF4w91Nbd23r4D5ZlSVAX75FWpdM6eL+FbaH8N6OjU6bbLamenRb8/3gvm0ikNGI3CGGbBh4CjRLmVRbGrCMJz61bZBxJZsbg8aZ/om1TDxt2E7rNtJhaYETGtUBwFvyXs7NS4hrzhnaJKuSgLJ4wD4u2NuVSa20u/XmHu9qxDRl9zCdAN+wpVrLMkJdrzmtbkAk3NT4+kGjnCyC2JOQR1htmvo6u2VVcab6Txz1ahfdkOH08Vhc8mldEwmOnCUK6u5K4Dzp/8F27c4fHPaxLMXf+HMQIW3Mh5H3IAT/rh7ULOTQm67uz23mFrMCCy+A5eYuPoidCaMsm4zaGm1Nh5SVGLUFD/Musf2AA3oB7jB6BzWO6avtOilmvuyOVq4k8L5MHETq4Xo+m/HIyjih9jWf+uyUSmHOJPdUTKqZNP4o1nrq6ztZcEyA68
  template:
    metadata:
      name: cloud-provider-credentials
      namespace: velero
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-repo-credentials
  namespace: velero
spec:
  encryptedData:
    repository-password: AgANRLwl/mj2RZPjWHGlC3ud/aHaOmyWr03/8CUjgXb2sH14Wcci0/D3pvgwyHbXCtcy4PFe7AH3cvAyGqvRe883TKcowkR1+mOXI3erxUd9oEnepDzkA8AlQWcAJcyobyuYiMrmcNHTazHNLTg/jO7YuvpJnl0aFgSl8OaRBPnd/OOD/4zcbuYiEneIMinmhZ6ppG3UeeLeNRRZdQPTPQjaGe7XxOTG2ff0FzOfsD9o1B1kF+giQn2VUQ+PH8Cba+bdiAQSt0M0Y0wxr8Xd87e6hu1vVS60Q76gG/TVuCDeamj13l+X725u58uMUduITzlVY6Gw1nZNRvSoRXSIHkWNwXlmyrF1VWZ8gYzg1NwfllZjKBSoy4L85gwC+vYxEIncwZhIHIOWicy4rvO2wqjTjs+xwZqkUUeGWduw1RU8Dh0JtVh1whwA2YDkt49QSy4qiSqETOm4JBjNMX4e5FfhZGYggyJN6GuHu3n4vpv0cq6dfp+HjRCgENGuaBfUUMGhBRh2yJ3wI2bqDqZHO6Ou1XXoRXtiMLCEvLj8rb4y7mvJcFSeVRqLPUxP3t3H3w1harDNoiKOqcE08gD8d/hX2l9nnL6ut2ZI1QCJLjfb8rZ8fa5t+fdGfDurXqXZKQeG/a5iaNQAvbyJlwCZihP3pInbTfYZJBuiqYySjWkFkqqjgbybMw0zZgP+P5kq9sVmRLI1DdTtHfMF18RUCwBGhjXZ++k=
  template:
    metadata:
      name: velero-repo-credentials
      namespace: velero
    type: Opaque
