---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloud-provider-credentials
  namespace: velero
spec:
  encryptedData:
    credentials: AgCe1SK6X3krFK/55wNsTmesf0JpZeJbleHeowSI64N5RBtO0q18pui1I3FHTGLFVlni+4cB0ewHwq3uEqkn3HHYdl4l5K3wW8E/TYk6JQjguiSKKFtxW9exRdgslltvWeeMAQZR+ZW7LNkxhq4khKC6jGyY2EdjNLqRBJoTebKf3/2V+iVWY4qCz/ikDPMp1CBbxKmMfQrSr2Tm9gNc11heytSbv/DbeLcYyZznoqU00rCgk6EF8MtMYxVl4VqyctDxUt/+X5/MQP2JqXXw6wT9ceWS3DiM8lZTsTJT28lnV8QEMMeSQFU5aVHWLu44yXbMhEuIioyMW3hg9nOpaoNklRso5THMjGtVpMaEtB6xQ6zLO39cJYQmpcSTvtU5L8mBkpOZ8TvWWZQpXbKl+5HI/8dr5Cl6Hv09r8WiAOh2TwR68+a60aQ5VqgNNtbkCDFzh3rypRrdi6xhAgJEnzKxCr4fI30yi3jonz9+Zm6N3V1UCxeGyNJ3mecvP5UBPZkc54+88wG0/rS2wCmNtrjhPosxdQON6z2z7nEgQ5UDnrbbSqOKXHwq90Q7Yj6HmBrMAqON1rJQv9lX7Cx5i2AKGFXyUt8p1IZKUJ3AITNflnmBLwBmHkv2k1Un1Hjh6RqHY+niVuNqH9poIp+ffdqYS8bGs28T4KAGRwwvoYL/T+tB/s+LXXg9tF5q685GfZzSaGgH6OTGm2r2LkT/7edjLUfRirn9y/0w+rXbTJF7b/2eI+x9FaYH1xenxBbM5z7edh3SsPLd70OKljrsSgVMLnl7Gq1b0QnyDN4/mcP4CFhPvsF/CQhKFztsdbJV3rFuPS3YWMTxJIUMvdU4Apt1
  template:
    metadata:
      name: cloud-provider-credentials
      namespace: velero
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-repo-credentials
  namespace: velero
spec:
  encryptedData:
    repository-password: AgA58j73T0yvNg94yuUNqed83U/UQ3E3ZfYrF+RWlwVZUWFZf3wBNh+zJ17YofR3eaD7XWAfAPW9GM3PcU98xN2l3y7yYJDRDC5KnCsTGyLGvqqwEjATIfBj0BSF8tGIoSgkii1mA9tz4JI9DtS9Crv3Xz/vHGASML3tNCKKaJH2Qr/m1vRFTaSoYKfui4/f5PJ/cowN864QCXbjWR+kOfIKyBUw93JyUr0Dj9NlIEYaKzRMIxfKWYC4azOMezz4dLEsiutEAMpQ9CWKlK8qqNqYRzEM6QDB7EljDN75nfmCftBy4HKZ6J4Xf/FIuJ1elgvmBumc+hYxHYdWMjznPSk4A2ZfDubE2UowWxE9n5HwSl56GKK7EzrYx2DfSRgvjOEstIE3SlSBp9ok/sIO0hbxiyrd/QU5h4iPXBDrIcVqwnpi1w3BCh1+LGWJH64LoLgBLQlK8IkNexROx0tLOMdwbwnXGl5RE6QTnPWvp/ed+HYYqOPIyy2AVfVC8CEZ8PP4QzL+YfTe28ZC9/Ic2c/0f8khIZinqNvkQB4vggYRzRJEEqqI/DaH2eyAyaB4qwyBm6LPgNB+YuiVKauFnkhMhy2dZBY+bzGtQfMtzCSmRJKcl94q+kz9pECYb1fNEmbfwRbJSIv3sRVFf3RyeeF+xxWvcAQmCsA4FPXwLhc+HJkcz8ETK86pxAjdqeT0m46lkP6W+/HZ2nxQItfUk509NfqmqgI=
  template:
    metadata:
      name: velero-repo-credentials
      namespace: velero
    type: Opaque
