---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloud-provider-credentials
  namespace: velero
spec:
  encryptedData:
    credentials: AgAt/6z/5aIofX45zk5jaGeU3EqzxoallsG+6Kztn2PjySTTwr9rST99p82bdzopMx6wWdfyMAOnMtSD/ytdsiN3tnW+eu8XmIL2W4njonqZ2sOPJuYrBLKtGz/j5vkEGYH6Xl1tVERCEWmkx6eQ9LdK8dt1T7JxeEESxQEPV/ahSuTeNKTmmm7pgc3sL+wn/veB/Xn+Tdmjlq4VCLgfQUtNsMGOnzLUa26r3Qut5w2274p5JiQuC/5HPIIo1tNZyiEOn1WZhR7/MRWi0kgDJuhq/AUcqFM53RvdrZDImoPKXBYkcrRGRKRCLIrgow9MJmdl3vij+yCa2Wf70SnZMUfYr7nj1XRrUnLCgxjVJGYpAWKrd2+GWYROC77e08qPAOcfa0QC5nTauAjnX+7w8MkzWCluX/gZ81o39X96Wd4nIWjNAJ3GRnO6J3Dl164asdwJm7+TwqwiTOFWX/JVTIeJ9lIbH1uXWGhCUZjnMGlNt+2A3UCFewBu1JKIwqJK8a9pdD5rLzO0ranAHnoJky2WBKWw8eC3fgSG/F5bIYOVVIWlZSs+w4JaAyPTv5PWeNgDKn+PHXCUueQ6NAD5ebKEdWf09HxVh9+hQM0M2MmVT8SIh0NlF67eOkg8Q12VeG0d8+6e+uD6J90y69f31PHpWxvSqGEVmDszI7kHnRFO6OZiwhVHDW3T3UlYjVXRKp7B6wNdchUSFJd0D6QziawNBWOjTiEHgC4HDud0kFYVh54k1O6lRze6kifj1fxJlzXJZd4xqWM/ShknZzxpRjTKSUNS+1++oKe2so227C4SeXoxH3ofj9DITPZnak5drmyyVFZXfnAgD8XbETSIsj8P
  template:
    metadata:
      name: cloud-provider-credentials
      namespace: velero
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-repo-credentials
  namespace: velero
spec:
  encryptedData:
    repository-password: AgBfRGZbp8rlbVXx6QnQHMXclknMbVo5oh8QV/dkoUrJDJn/wvthC6G01j4Q+Sm+ouyEFjc1e7MOaTKx/8PgFEDhKz6b5vCDyDsKHxvEA8AAbGGcoLq6CLAiJWw5LtB3A/VnOOydV4RuCVYJZDSnJz17NjvS/wzDbPFL+DiYhafVx8H46+2UT+t/ihBh+b9NANfKuEh31sCUhW66mZ/DjkKz01SrqihbY+v+WbqXfDYIg70vNN1ZSmzjbCVfSNITKBKxTk4I02MQkP59tFIdRJ0pw8GpBclYd3Qverltl3WKnmcTC8mxyidSBVSLclqsqGpzc+IKrYYjB8/lBAd8xkxVnf30JJnjBJb8VwUVLPGbJSXTx1D9EFn0IARYS9z6FEI0RpkWdlq99TwVFNOFEVB3nEdkcoUyAQE/BMBDj/4YRL2NpzormGPwFWcIalC0c7j7guHAYAml/7AvE9b7S0wXiYsodp01+SJyK00mZhaa7F2vEOYarU2j3VdoSaYcOrxu0TtQ29rXG3a6Q/E2I3MYiKDf/JwnmbN6t14ssKPzw9xSi6DCPv4WTAj1dbjtRP4Buh1K3aw0k0rNFY0C4fzW3zqVHnXTQmKAmTTowUAQMyIs6fofnAVEbtaNKb0BfjnKmUFa/cxggKkG4ZqX865GupQ+W1LsZrhOBJuNveG3ZOEHCsV/VuJBs+gJ1Mm0RtJy6z2Gm3HkQrf0LDQT76/TrKUtkLw=
  template:
    metadata:
      name: velero-repo-credentials
      namespace: velero
    type: Opaque
