---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloud-provider-credentials
  namespace: velero
spec:
  encryptedData:
    credentials: AgCcV1l0Qh1bIcis9+2TLS2zUUMcb7q9maKbYygLbZpefA+iP9GxU10kxDn3/QGQfmB3Hu9w3IZbDko0yiYmvsqLXeelLEUmY96H5BYNT+Gmc1fkHVWt9hG72zZ0KSHUmVDt6IakJXTMRR8ceN8m0gzfWYJ5deS6sfh4xOfohEOuhdpwYbg3g0GEbEEB34WwPd6KFaxq9ZMbXGjobnGT+67ukTVF3CM33TWodFKvFRUWdkDG57g179IY3um7GNaPRea8L5hj7mjfgRjRFPbR7BrL/lwbMp4m2Rkta6WO5zFH3JkpV4YsQl2ByrJHanOMlewDAxkD5hG0wVfNhubvMGZZIk5Dtr3ibXr5LY0bWJ42yIrE1++WNvCQDunrHKKVE3raI5D6zHxppEn+pA/qbe6GJGCmdP2582WpoSwFIbSjHUW3EvSGWO6YU9M8qAr1KSsa8op/nRcRKZUaTe2fWf0PSR8K3rBKAAQJ7381I6LJ98Swv9Ucf+9TxeGU5b0TJEPS83GDcdqoYbG8Zjn6gm7ZJfJ2imcQH8nWOuFC4XeBPMkCjK3WH6taAzUW2kzF/OIoC419E/TpCek/C9Ms/cMIUxS3Nwt31elLrWXkve/VXZ9N4ptG8Cx6csJgo8h/Oa/rJUsR88+nh94CKssDDB1q7ps4VRoqrMaRAwJXCnru17cVf3wzcg7RtpvPim5KlTKRRjZZlOYQ1c87nu6MSzL5t/qbIKLlyUYqYJOm4Y6uZ453R1yRlynyJqc7N9QHaQqxMNxyjE2qjnKNlV52LqevVrCZEY5ilrd+hJW/oZksKcKdKW5YkPpBQMUwA/pEcJA2RK/OsbyKKeoZbuWbivei
  template:
    metadata:
      name: cloud-provider-credentials
      namespace: velero
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-repo-credentials
  namespace: velero
spec:
  encryptedData:
    repository-password: AgBI2vxmuJkOrOqHgKT0AwApxpkPtLDSMYkgxPg7CFzXHITl8v1f+fwA1B8q7WcDrmdwFnKJ3S1uSsn4PAbZlkAiu6++upHGpKs2HmQeH57xVDqTcLZuDf7MmNKCX7ulUC9MhJabipfROX8RJKDedsdRxBYJZ9wO1GGVYDt3kz4RfTkKNVjDz2HE4FhHahrvM7utLr7m1pgksSy+69Dx+AIwIZUjc5A3zd7YcuZiVkxY59lxU+yn+xPlfi05fbydlkS4eZWD0BbdZff/6rV9LtVdBxP1rxt53en9EyljYyF8sip2lVpn1XJIhDvdx6niGSr/33NpZfAcFd0nu2w09XwHfcoXeQeBbRiQNJbQnD3Bo1HYadOFDs6OCO3ARdVT6KGf4ljSQL49AVI05WUiSo31CsVmraT3b5ej3rpO0M3TOEJIMqnjt3m2Grn8dXtxmOvl6d7iEXMEILCNsMHVRK6K4Vrn/ljRES+cf7UnYUwV5fp7KzVui5jESIFYayP2k2ap3iekrA79M0zfnsRM1ARhyiUUYnzItCuy5LOTnExzH5o9GxLh2uPTVQ2XtGTfIw8r6LuMI3ZLmGC4ZmjxVt68X3X0wLkr9Bme3gbQYf6WywdaglsOLF31M76eMxGhbVIGCz+9iBOjW4RKusLFLDvfMV/wMGaIlGhJiJ+EBs1LRKZiTk0bamwfpfG++rMUuKnMJw4FG26Xd5fcuXGjmtNQZiZJG+E=
  template:
    metadata:
      name: velero-repo-credentials
      namespace: velero
    type: Opaque
