---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloud-provider-credentials
  namespace: velero
spec:
  encryptedData:
    credentials: AgBGoBPKX7VCfB5Hu9W2maOFB9K/zuD1OxPRCecwrlvzomhjQMUA2mV5WZL+yXqRBpslc7kFzr9v6vwpFWS2u6DfXN8aZf50ieY1IQ7LkIcvG+FiX7YvvEpZGVaxxSIU6TrZ23V7HS7XxiQII+3xg+dIymuP7ei4QBGDANhFfjMMN/dq88CktCC439+V25+Yb1QdTPt555OLAtiAU9quyDUGgfyLlSK8dmWsliVRlA5/Y88JIwWZjUNArrPg42PWTpvNL8AaqKfjUjswGFRiznTdaMbIDq662QXbPx1VmhJcFFO6q6qPJ2RdAepXKHaSjtCohWrgazonCzZkW2fYRBVa1m7zgKPNuc5lSgOsO6h5hTpk0SX2p4mw/Pf9UApSsuz9TZ7uL+ZwzSmAoS1eG7BnsiiQRQ4r+knK97KhNCo177+yXgNz76Ug+lOTX8S+FfOy3Zr6X2aHnGiwe9aWyLJjeuastAmZcqKk9uWk/8wipGsvkxVNjlHW1888M3r0jzsDEgXwSJpkD5T4ahddjs0Ya23z97bCSBHwkaJdugr4vR0WAmUgSzygw/08xPxHnn9P5KJ99pR1Go1SOff/WUUHqI2LhkELbwSb+YhtaJ7riDOM0hiWjSGRqSXtG002FAIvLKnS+F7tTikGPABruxj1YaE2UToIqzAt28uoa2eOZ2fDXdhKTOfIB9TgeWM6l9aALS5tApuxez7KgWRPngy1aUPuMC4zeI7IsCMN2JL2XlJxyYoHC57xCfAq6kQnjx1r1szJSUGrVx/S5ZFdgh0RAF0O+YguewqTd/TJ8kuQbkwGiZuqchZTwAY6yDReQjdqVcns/9vqCEwK2wgBU+6+
  template:
    metadata:
      name: cloud-provider-credentials
      namespace: velero
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-repo-credentials
  namespace: velero
spec:
  encryptedData:
    repository-password: AgBvvEHcdH3gZ29diwZxCaXWVtdEMybM6NuHyr8soPCwOEWhZkyqQiAoGb4xROtbMp9NCSpmIhXibpq3RiEa+oOupI5VLyO4PpAlFYrATcZ5YJSqeHwtWhENKUZjTS1tQGbIh6AiRbgg6vSlXl9aQ1FUB7+uYAfEm8NVTonYIp5W4c01FQNawjZqiZKaFhq8HyMuencOdJpCvsTwyQ1y28guvMnCNf5GeGIt0Z9Sjki9S2UzCt0ZoUbFgEeL6KS8NaDVK3GI50N+dS8mbykkCDXteBUDUGe2XTLjgWjXymrTXkyDK0WcV1sQg6U5bY7REi8ePXa5GSbUv3vvLjRKZDxfSQAevqF4l3XrDZWBOWRT/tOwoi+ycY3KoDpoqSVVLLWNqxmk4GrY7XhvITDndyld4jdIQQd6t/ALKtd2tanH9Vlb3y8NFi/LTcmGylAsSc/jKBnMKozRH3D75RUOLcUhkb0VK/eIUwKiHg9WtQar0Py0L7SKfTEQGf7NEead4yPqZhDkCHZIcmKDohJ6mnaw7hCSpRLx+Tp9pkgiUflC7U6zP0lbGOGwllEnafFDaVOTmTsg+qWeoBYk399NSmUJHFGfRDd6muKoP7w0nAsozDCO8OhSn9Ecj5W2FipOmGIcmLaItgKgYT/cne0IESlWZY4AjvaMt/Wq2f5MHGtkp1yjB7pEgc6VeDAM+sQl8tP5N2SyUncKB89wbwBQVKOFyfofsBQ=
  template:
    metadata:
      name: velero-repo-credentials
      namespace: velero
    type: Opaque
