---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloud-provider-credentials
  namespace: velero
spec:
  encryptedData:
    credentials: AgDHO+gUFpggcEYiRyt7sMTFI18S2Qu7FDttXrF/wETdAp5T4HbQp3yfCs1qjnFonedY9nQLZZnlkkuN1slrVi3YJ13EDUhtOw4GPZx8sjO+hPgrwQxCkbywTPbe0umlIwbBAIx/IoF8Z5DCs/hUJVXYxFywOCTfUbwnjby4eAmlIy3PlzPM15/pUF/TduOf7Jpf0jvfR/WdduNMUB72omGTBwy2+pOaH6b1sJO82ErANek6bNbnAsWZuzygFIzvAmnVE+uTDzwkSR7vHP2ieUxNKNLlCttky4tN1eOGp5UWKbZAvf80ypvo+TcaQbZo2Zgg+KlFkvwUC0kHVngPhCvPG60Cldnc3y/lMSw6lRGYuvo2PSbvSiYbtbClzqZB45Zt/I+5KCzNtBDdNYOQJZb1VP6n2Q+heilA9oQruoSs0LewQAaWs4aUBAQ9QmgiJxl1LbDJeornu7KRNAib0rtxy09jRj9IZ1Vs9kh4hqgbXAjiSnKjO1RV//ovXjYd5UHHCOml9mFUXpz3cgoeYaB1PEPrN39iVbAPin0l6dVWL2Wre3+wNaq2QRwEl2a9cybZXJWgkJaA6dMhEAJGCwjzFtkfQriRhhGJOT5NOU9FVNDA7YuUKYKnBkV0a6iNEwEaIiHTTtj32ttKyx0GkqihKgB/jOnpNC8O+suZiHqDIiTAVNH8DorUaRJItnOhw/8Q2uNusOqiED6G9fDwrIwAUgdKdKZvhdiW+aNdM6vH/8B7RYDvA5S7eWtpLvP6WiXhgAYcGt3TRieIizQZT4W1/p/pIVu7IAVnVmbIJVsh9taBDcAkLoeOlBL6+BWdaxPB8yF7EU462tjxmyUGFuj8
  template:
    metadata:
      name: cloud-provider-credentials
      namespace: velero
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-repo-credentials
  namespace: velero
spec:
  encryptedData:
    repository-password: AgB8d+hoaugakWq07xEcOC3ID0Lg5wYyQMf14xXTY5HAyPDOd+T3/4jxye3F/eNwQpPYHAnxS15SWCJrl6QjGrEgRpZ7dCwDmgRbzs8Kq5nWXrjO7pxIFMVNnbnIJoJ1qaV+D9uRYm6O5uBoPt2tMCgph8YoIDi8YRK+CWOaePi1XzEIBk/JqsM3mpHREMZvFn3jvC0L5/ds1YyhvIYp3WWSJjoq7yOsff8R3iuaf36KScKpK3bWZ2m9jAU5T4trLyWkQRe8SjbfkU+cdPONt7E2jyjuEMxr1gHZvtgC1aHd8lJO7bKRkiGZ/YZkzAUaEL4LC2wne0O2dTx5usKu1vKOL/fbB/FvbZkjK9x6FYpTk9K2HCGCnQKazkD4oFgT5uyaf24gh/UEiApbG5icqgX3bc56djLeODmTgQe+NRA9XVN0P3OcD5CsBdNaPgBgqoR031TyXABpCIG7FHlGh2Yas0EzebTd0NsIu/BFL4bAgpXOeFMgqVCLzBe7/ymxZSGhB0TY4PJRM8YCtGR69zOkdCSndj3lriVFKGGQBFoXpsTtpdcEB/dp/UJG2IidnDnVcX2k85I3M7Z3DrE3N9ULqwcDsrD647xdRjNeCavQFtB+C78C5pcVE5Cgdy4T2y7a8Qao96zKCJ6aJWDZYhClFU4vCLBI9rECa3jAhGgSwP8sLnfBFgdjhtqPJ3GrkGHJipqAGa3I+PNgSytGhVVKspgrjXY=
  template:
    metadata:
      name: velero-repo-credentials
      namespace: velero
    type: Opaque
