---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-values
  namespace: authentik
spec:
  encryptedData:
    values.yaml: AgAp4JuNhFBvOIr+txcMC+JYhGQ73HHGsl+3YBzBeytzJMUSpEsxVvENdkdOjfcfiMkA2jrhK5AsonOy+a0zN8ovspOaGfOFDCsDwtCuk314+w1ShIm/er2WTVPXBU5LLZx3jFjFENgsVHksQqODNNOJimTnV374ZCY8Dv8/hvfE7G85uBlECAmRjaoBz5G78PLk0oCQNF5swSiSx/y8QXh8OGIvZM5wyT0sybt+22Cd8WwbLqOPHIL9O9YNdMetcxHXo5qi40EjC4BhvBac7Ow2V66+HQoLWfIIamgbD1ZKCHNSROJj/9FKlJ8dQlPzDdpz5IKx4EGksNzgoZkd7BSQ55+iNurJpbHAsFPGytwuCY6kahiB17jIdIio2cVG0RlS396WyHAD08QmUQZkPsggVLX4D6t6p254YLxJyo8DMzgi9HtUJYXQNa9+pswnCuAPQhXnsvFNWA0NJ9Uo7VJc9QSdxyNk9guwNaqqZdas3Pnaqw+cipHtDL3Bzs3VHVDXVQ2TNW7xoSZk6gqfKG6fr64OIgB3jpKrcPur+D0iY/ULrTIzgxLDxCYZPBb2+HqN9dnrAESEsXcAx78NGLlHGx57gYgC3oXKny+48STkA8ko2l/KtRYAFk6iVFt+oBGPy/mfSWbU6Kzm+OJ3y2T5/uJVmGyvl5VMHRuGI3UDtOT8PNeI+VNDn6fI7crFXYM/UUu5+otx0nP/4bqGfM1ZvvAFTmJ17Xe/4O7TndeunBYV+3d7RSpRCw0EbbqiZcZ8VFYqok7xvUHluv+nh5ecZbbXhoYv2UFkyDULoBzNZHPLkeDxXarOYSifptHDY4Guac2WjRwPnB31wewY3zMqqxMT0ELjplyzx3Y9IQb5kz7UYm23og4b5kwqDjyUuXI2WSAyNfloRC2kPMt6Ti2wg6YPjdoRzIcFFU0LjiUl5wDWp6d9fUqTng==
  template:
    metadata:
      name: authentik-values
      namespace: authentik
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgres-user-authentik
  namespace: authentik
spec:
  encryptedData:
    password: AgBs6CL/vNp4yl9FNBjc3WL4NaP7afVNbEd+iEXf1Ngkt1AHC3kuVMMNK6d5N49e3FMmJF3Shmc8bykua5shM2GZeV+ChzXT9MDJlCvmw15ikppwunfqGSyaDXPSgoe15hIg6omi3C5WGULy+2OrpiSgPZsCtTrvafOoqRPV2DkmfgB8QFVQUU3iL35wlAFPvLJlFWTmJYUthzg7FFnCx9BLVW68SOlcdUHj9+0+XZY7LCGw8Okb6HWk3fF0jOryT9w2PeUmEfnjxnppTJ+uBg+MnatbWOHqVuwKjcnG1p+L0MEJ6rGKIEmBv5X/tFz8S9ZpM1bQLUXb17VPV5XXTjcHfgnM9RfjpO1I3x8QAbuaqRTNKwUKTvLeGx0lMqre/y2elCf8xxqlS6W455J157rENyoSKykpNUngKtqkyTM/e2bOXhUzfSd1YgdaxeHqgqiLV2uHTJwX5fS0UebIvqhtFlxG+YV1W442oQxofz5kHfxY7WyNDrz11mhAY+7geFGSAbr9yIQvxgzn8Ih4sMGLDaRkAyT2weYxc2jT4UqpLSKw0u+tk1bk+2EnPDRg+DDMJLnmgavFGdchshgU9F7yhUuAhoSBWsqup6DMUwnEF33mnRXY5L52D+IkEX5627fSQZdQM+3XEXdhFvW+7BP+fHkP8iOpkNiM+jJnVwi0mCE4pwUTxnZgyCe1dzfIonhhXf2u3c1U0GjT98FCgQs1ajp6zA==
    username: AgC5dIsEAfuwGDWMIae7uTq2yTd4cc7fdi0AzH53AtmzF8tFomr4Vs/Suuu12km3bMnsMn4OF3s9knMFflg3H6o0lWWUfdeDCpijIMxWYHGXmaJpZyvZfOLYSkNVeHvzkUmyiHMHE2XNLjmPaa6di/ZW7ixu6hjm9d0ZtiPZVSefTFruycI/yuC12lmoM9r2nKJWJJxrK9wY/E/j+FtIQ1UuThjrSwAstZhkV0I4qa7vvzBqr6Hni93jbzdiFpHbvEWyTkQjP97KyxRMzMY8lUmhWQKcWAQVb95Ol0yJnZuCHU5DO0WNEhOfkZlTsrgUL4CBzuppjHomUMP3Kqe2syBkV1qCYzgQ1k7ai+yDhJepKa0k+5A8o6dq4Rs2Xpj8Vn9VeE1WcI2QgnJpJkKd2HfXKNwcuYn/Bb1YXLnEo3mjezb2AlyRkxuYzH7y1jbxaosP/cwkUAmP2XZGUUwa92GILTx5JONQDDjYwpXQZQw/f5c+mNQnm5QAdToCxoqX1TLQgix7VHMfo5cH+Bw9bvA9e7DAc21uYYorn9TdkHgHL/7n46EcHRalOATtqvLsieSA4YDOGQoLSinYSLHNIX2ZdzXS+KNVaR771aDEpnVJxeuF8tT79Paa0Lj66IjveaGw3h6kL5ifvzjthvh1Lch4TRotOJTz37DRz1ZvbciBOu9kEOOwWziAlyQBZ5ZiYON66B+KxuQ5pVc=
  template:
    metadata:
      name: authentik-postgres-user-authentik
      namespace: authentik
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: authentik
spec:
  encryptedData:
    ACCESS_KEY_ID: AgB1o0ptLVE1FjNrM4fJgi8q+i9rRpcE67b1d6de0PAerihy7tAzzDqfawqINBESLIfj5HYMSO4KBAJ6RAET4OOzBsngo2TBCVbrPDiAsuSgnK9QE5ra0EWJs8qNwsPGlwwJ4xwdCnIw8pLavuEMmqzhyE2bLbkvaVx5lJw3LlFAVqly+o4NvPPBiooqmwPAxJTiuQIff58XkhdHAeN2i9x2BpF6rJ7OqgRf1VATl0kzhD5bvw/jf+K582vq3xD9B1juLixRXEzfv+Bnf2qtVAQxmEWE7x/7EFz4Gi6FR0ETG6FQP5f7BV7wBdb4Ycds9TrJraUEXIIB9ijA/hNkwos4HOmTM+u1uQnlR5gTiXPjSHiVZU5yCuKxrbkK2a+vn6w8zKrc3OcxoeGfWWJUuNT3PDjtDLilIzXnmO46aRFZdmVuRWwtbC0FV2eooTaCsXv/pqzg1qRGdQZgR/NT6wXLUwz3/RsiMkpQ2g644rrYd76OUvdAETB8jJwOXVgZi4Cmd1xBbg7jLz5rzGoAD63dUQcd12UbWO3xOvTvObZzXtmp7H6RtvfeWIpXvDZFwsm719pduwRa6ggASwe4ZYUdMrtt+RkqB3oSEt2Iftjrfub2xC/bKvJxsn1N372Ic+3BbE31mlWTdMb7ur5UTP/L//2BYoCu5hN3oJHE6QQeCDTN8uUU6S8cno2MbDvw949avLbWZv2MFpWIMD0+B7JOtEZxKpbn6fOh
    ACCESS_SECRET_KEY: AgChPodArTOA7W98J/ZuYxhg8NufQ2iv7fljOammV+EDnvnEnMLN39gIMv5ZSzNRjD5PLPpWz64hb43hMiKs/WgP2tTf5YXKaVQpkrhoqExQx9efebISkBQQdZsixQ5s3CE3BMDCjXwpmqjLa+DaKUw4swRbGTCfewK7mkuAG9Tz9W8MV3rr//szStK7f7Phhxwtp5n6fNjo4BTcC1W0O3PL6gsIDBWF4O4p7Brs9ghR+IrpMr5PSWEI/SF61fPs+fXwbL2P/8f4Qqx9kzMp+lPbTcK+iPKOOI6pr6cxg4Wbev8MZL472dFU9kGMqox6uTcxtI2WBet2ZduhbpoQypQiFPwxOiTqKEgsOVmXR2h3r+DXnN+vbjtvw5wFUSVOOUcpijdGHYpY70gIBO+pV4LQgqWKRCwMgNXTato9yfSv4TB95evNamMB9PCMi0ZGw9/JTZjj2gSHGITDJHXKSaZvIPZn1v0RhYfZgfe/kveoL0q+4QlJQtJX2MZTnDxSXUPWd3vhji/c2nQjaV7iuLtgjhfZwu+07GW1HRGj2RUO9YqYyExrSkGPrMx5BRkHCBzlinCX7+hMzrldB53qIAbSk18ZH3rGBGq9wQ6HDEVUX10JKPZA6tHmIBj6JgS7mo4Qf4pCs6VBSl343gl2Hp1o26aqKCGKAcjR/x3ZQerbvFJyESdZmvsK/wFZVB+9KQRkji4WtadkzkMqoxTG6P1ZbEIYG0Yq8OMbHg2bfX+4
  template:
    metadata:
      name: backblaze-creds
      namespace: authentik
    type: Opaque
