---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-values
  namespace: authentik
spec:
  encryptedData:
    values.yaml: AgB+3BTYQSw/Gv0szMavv8B04rPM2ywnW836ZmNubsMdnA27V1bTHmfGg0EBlSvIa7XoeaDs9+H4BI89CIAyE0ON/3KHLyW5bH0INvcQk3N89sQg5FeEXqAo3P4wyb4bSueHici2suJmX4cz/tS1obwDO5BwT4tHNSJCf8y8lh9QAO9Y9MRhxUO1m05b0tUv0ZisrAg8Y0lxVIaZbbMX5EOuSMRNbq7L4zq1t9YzD/+Bj7G/VZ1aY2YEmibpZL39eFNpe1femP4J3JVwHrTm+ma56lbsqzJrT1aNA7bechrcdDtG3wLqemsaGwfLZQWcZcnMAWfAKAfZWNtN5PYTV8up87dbbdQ6lNNcq0LTEhARbi2kLrMU5fV4W06lTlLy2tbHZjgHHDiWq0r3M2EBCO0H8QBGY8w/BVMDt5jiggVd21yvGAqDcT7lw6YS2O4z8WXvfOvTcEllhDDvXW2FYhUdozlv5RZvKqfxaABxRoZXxtAi/NLhWuaBhdTYmn8TRLPZ3eDMq9Eje5jO/GcXV4zuuAeMn7wPqitO/BYkwGKbmK2Sm9dYvXrlWldvQbhTNFS6uzpi/2dxEd2Ww/0m93vGFrg5IJ42+YUkUtX6b2GNZKIDfljLxdvyyQ8SK6kpZNwJ0vNuZlvXjxDDaRsIns9+po0FrfdqO54OFrV/Mp0j3kp13Xkga7uHX2VqwJe4qcODoYRSg583lixPfXs0CKZuSR9KGggVxInKfDJc//Mkj/p+084boy0PSKwTt4o7HwjuTaduRAc7YGfhHD3fHSr1AS07XUKPGjK7rtCPP2lm7v5fdXKlJ6vbrffjFl9aBHuSc+o5+St3pC7SSxrOvwtenvjQ5TVHDVH9EiXI3D+D9jXSw+thg+UOgYCoumS+br4YjL6bVi09fWy/wKJiqbcpNi0UE9nDe0gJWw6uOFnr9EOqVkC4jbsIUQ==
  template:
    metadata:
      name: authentik-values
      namespace: authentik
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgres-user-authentik
  namespace: authentik
spec:
  encryptedData:
    password: AgCzubHbt5VgkkljeRsETtu1fa4RRgIlXc6SvLdCq9eM93pME6rbJACyQ61rX+Xi+BM4XdFqKohx1J1x95c3kupy+oDrR9OEoeXKO9+ogM4aZnd0kRVMDujIHR3J7ZsB5bKMPU9RDO6nIxaAayyeRhBKxAj823lIBpS9eogpyDcvDLBumsiHL2N2IQlAQQ7bc4g8EBCCUOOnTyUP+PjS0ylY4/e4lB55/qBrXvngnS0vEBUz8frrV0nU9RwPmczt2tlHpCnufh48tOf2mYTy6NP8PjSlvdKt7aJI1xilo569VI4OKwQIX5b0586qKjuRFAeckBTeLuCOBAVYA76uDcIJRNpLaZzAHLUJNZy445qI7Gjxh5+vmmdlCFg226XoeEHTxgSTsawO7EUcF+P+UjKJ1qW3vdTxGsxZmM/9XbxdkW/l996YX5G+KUW/CpSobGYamcrOF6AABhy3vjiG35W1SuJl9UGgN+j8qjDS0NhMpfpacH/pKYwwJw+2UShPev5Yt+9/65ZY6H/jsa1PGdjryHE+7RPY8T3za7KL0K7f4Q9wBgEMVwvcaR6qK4csEZ//itUw4p8LCClJNHcD60FAlYrKjJ99VNXJmkigYvqLNHBl31bkiK5F0ih6eRECnrWTSoqBv74FrOop8i46UVgDCBebMmtt/K9bAZZODe2Ls2C62q9dz8bgfcG6LN15TRxVGCtBSyvOPl3a92VvMVeC9tWXGQ==
    username: AgB2xpOnUj9iClNmV68oYCpbbg7D57sgs7TqvZf4TV/z+HDyds2hMHDeWRLzGSiUvJC3HBePxqNVQuE46V4LKSiJVGcB4PlFAsKualFaOV29Qz4M9epKfdOXxZhm7zOdJ8rqbIS24Vy/3UN9A+tPcfiqtd7+Fga2oMPYeSi8FIKlPZBPQx+pJ4FAjTVFqcAri06pF0wGIGNYblVt9iBeUlgy2eFNR/YSelt/jXuxTEdOARIi0EpRt1Jlr2y5hoKZnMcE7Lbisi6yjAb2qneh/aMpVfJEeqw986u6l6Uj7JBCZUjtZj3x7/2MwGPTsfzG7IPeyElCfieU/LX7vuWbBPwZcj67IPfUS2o4SRrKSdxkCZYhNqQF1TnG2Let6gv2VPoVUVfoTbzJ/p4fkiRDeo2HrN7gCu5MtA9C2bPjbWHXmdtCjdPfy6HjY6LelQp6Sd3twB7cSaeC2/mUFgVfmZY9m2PKlK5Ae0GUtvl8be7x2VwZVEkGKc8tuI19mjU3k68CmoxtMmvHAjlh+YF7xjVLoPen30Q1nsVSKJbucyP9yNH+boiYYyVNVCmQyWqtTvUY+JeywCwqUTh6FKoLCcaJ6yQ5XHZAQx2qViSlfbGADo9dym+g4CouXEk8GzVduR9IJcThL0lDHKMy4oEASXgrsFgUs5yuK9j7aW2Jo5My4BozyoIXSNpMjTqxLfVo8qfjaW3YWIKREsQ=
  template:
    metadata:
      name: authentik-postgres-user-authentik
      namespace: authentik
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: authentik
spec:
  encryptedData:
    ACCESS_KEY_ID: AgARIiWok/m3tIOf0AgbG8JeDtMHH8yOLfHntEPJISXQisR2BtYdcloqTPfCphkgUziDOqvOQ579LTnAtQTf5YKqmaZ9JkeZW/luBO9XCI9vWnQ9YeJ8IuQdw7yQLbTveuLn1mNhLqpFVgNRyKW3EL/rbc7VlfiCaGl9i6CGO2EcUUdWvDXQo9rlqTDWnnB+u6VJozazzsMGgYHykd2Mm8B6K1OuoYqfq7E65D37IA8ekJrsC9g/iU7/yPA3mtEMsp1DIp8iVEN8R/3yCFrn9MYUpdtw5nN6k6f9TZDFhJyD0d19UBQQ/i+ytEmrDjw10NIzuARUr2Ne//+3UN28KzY0cERUBQAYXEzLgU/lOJXLH8JNx88kTKs9lF+9voiR5Tj4/cvNot+Ezu0u7ZrSbYfXk/UKswzGKxXOLWbdozxOIJwkJIfHORuj3GhdIGvOwKV6Y6kgl7C8xPkw7YymJj3KOqoH2Lyw6888ZlWQF5xxVJ7+MX8S25P5uU+UcQxweAc+Tgoyv0mO2izp1EW5FI9YQruAr3AUUFYX1CxYGrRDj7tXrugfRYP8sQukVpO1EtfuTwxcBTqyMNkf9na18iITq8l5/Yxf5Q/zPnGKL2fJ/VW0V9vvxx25n/6StV7Ng1giPkTI/1/ph8qtnodIcPsA7cuoAjF3ziK+P37vpZgrUnIOYedVO1Uqj2nDmRMzkr0NmRHVX73ZSBxQU7jfTBMRnOzMrATZggGB
    ACCESS_SECRET_KEY: AgCkVbb3lJJatYVCnsCk/awWi8xeI0Lzh+7uclhnpZxEjnZ6ZeCUfCmQGORPVyEYXZ2HXk+toQCKCwxxFnikjgd+OKZ2PvbMj7dKbERZcyAQz+TSbjB72X5bcb2sjjjDcPO0huocKBFfX4DEslz6NUjndEUqjapuI7EI3VyrgDfgi+nEoYxM34pjT9Ydya7z4V0DrXWUl3bWfF8xZ6x9fc3zTgXusRLszAI4NsrwJXulbxOlmH1ow7fvpLnK+32xuPPW/7n+Zv5E8GFCux2zYwyAa0EbSUu3SSDZBqcUuQ+n1SDBFXfeoyoKin8gWxYGGFjoYO4BLeczp+sQiRbyqzNK46P+nUBQKlcfk9izapsRNVMLQ2BZ//BeDAHDcjtbcPv2R6dFEVq/0UbPbSHslMs+ThOGK8wdzjRfO9YdPIjFkaRr0W1cQrzD2DNprl6R6+jUNZI45gUXmzIo+xr5QHFLfxxFCOqWOBjTwzgXAJBhr7mWsZ+gUd0G1HNdMpFgLcoIOHLXSU1kKQVN/XwvLQPXKt3Ye287cFrVK8NYVgtdLMGVysGvUYiN8E12YbPcseRgwom6DBRrB374FkRv4T9rORMxOhaR2A9pZnVQBlRTgwNdauz42eXpYbcPpDlI3VcNRvV9ZNMFzMJkRZQMOffuggKoS8Ftz7xwxh0fwzqWqmV9fsukABzLA/x9Qc6rwgzIrvFccttzJ1cAJ8u7hs3v9M6ChHHX486SNHCke2Yy
  template:
    metadata:
      name: backblaze-creds
      namespace: authentik
    type: Opaque
