---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-values
  namespace: authentik
spec:
  encryptedData:
    values.yaml: AgBNdZ35TUDIKOiLJXrRPuWNLzNFdoyufqZEMv4pTWAXHGlgyOED5ySXyzBtc/mVUESaK5+V73O7zZlrBpBjf8xiV8H1OhldeCw70vT/5qBaoC6no7g7xdP0iwo902lXzbv4LeUZZ2loczpyUEoF0NfRKkOQCA2hVneQmj1F0Vh+8hYLHc+PRQ8/AIQwtKDGStVGG2r2NpEdxLcQYf9X+a8FLn8UGPzWABhQd4vjH62ZoR/LARXytVBTRSAQO40fPQ2E49esBq+tHRIopMCjOtqawiPHunjwaIA+qTn3wgJmdSoUwxp+TLy1HtXq7/94K61XotQR26N4AAooWX8tGFxVU3OTmrE4uttBVK3aQs5OXUCYyUMSH/EnxHIOwtNlj6Lbq5G1zRPGBWXa2KIHNgglvz4Ldbqhhta4Dc4eXxc9OnEKEBg7KDGDbnqkO4cX9gconHVSRHxyIZbxDPsUZYEw5W7z7mvzY1QUohv1ccIWprtvBzRq5o2Mwv/H8dn0+wB5pNtmq3lrZ2V5HsdyfbZ/U7LQpsILakKnbIxIQ4+nfRLh1Qq67Ub8cjLTHKEpFzbZVjfVdOJpSKG5AvWCqJdIJf/mMewNoihc+WeiXtV4OGJzE4DWkjdSUKfsNSW1UuPg+xykypy+Klxja5hvCpmaLedl65qsAvPwVVD1DJT3zeJWxdwZ3QwMTtZS7HWA/l8kQK9R19fldsurmfItAr87TGoZqAWMSWJVlysrtJEimLNOp/yFSfgr4LQQVcJXYqhUxXCa1VcA4efdlNwxod+9xrn7dnZ7J/KjfAxIbe7Aam0T7Ps7vPwPkJGdhW/y8VFAmmG0CeMsPKhv9Qsdu6GMNr1W2DP/zbP4hJ3m5ZcctvskbngdvEIBWwPczkxMNBVZwTDkgSfIorONPvQwp95RGZInq/bCIPSB28yy7esgPOphqF1xTtB4vg==
  template:
    metadata:
      name: authentik-values
      namespace: authentik
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgres-user-authentik
  namespace: authentik
spec:
  encryptedData:
    password: AgBUESnNJJllqy7Fr8R9G0VKmTLlihiTA3IwO2fC6nZTE+690rqjijeOKHCRtJq0jVbNx/PdRnxI4zJKFzELW8LER92R1egHJoc1ykuW+sfiBgv3vzR7yw7gSKCURjvzqh7yPcik7nAWdJMtOpfxchaC3ScrOaMdVva53jYWTs3B7MW9VKdb0Jh4qkJy+tKCh2bXR6cwiK73PXI6O0LYLpbPopie8wZICvEv3bVuLymkPJ8mh0qe4VBRm0bJcVjrGBDQ64HWRsOESSnODkN5ObS+YrjcNIGXR95jrXZv+eu7+z1VrjQzxpDbbj/NZuZYrH/G1wdoBJoXyBZH1zJSwyMxii788949qlHzyMTARv+yQMEFY7ucEVXgPVX9gEPGIBS3MwAJeNrFp0R8noQ/03pgc8qQFDlorINF9GTNsadOKOrClR4nixBIsmCpsLqkz8S2XGpW7bUr5rTrJiejviUwmk9B38u8ZsVMgewcV32HgffseoCwZAqg6JtQBGrQqcuP88pfgz+6UKSvumaqdygAo12+8k9WyU8YH657lMZJLBQhyeyiLAcUxKzIJN005Lhe7g3fK5TD/OIzkDZQJdSS76itCalm7MzidBY00D7mLECa6gF+4SF6mNZTS7NEeKUx9Qq4sbxrYRgqSsDX5HAE+V2YMk7reqmE3x2YQEYRYoiBamj31xQAVWXIXwH+bxkM5agCrKTE/ey8apxwODu64sqxWg==
    username: AgATBdDCEL7X4d/SxlsvBorFv56mpBDmKO3TNuduEZ/XDtTK5jrzRfe0kN7KLH3AMTDO3FwWLOJ6VbeQnvrDgNyNzivNQO7+DHQujNSpUJbHSEtVPMgAHRS8cUfqnhIF0FFWigab75kIMzwCCSi/9ZqsM1+EhR4aBDOKbSmdH8bjeKEwubeMNQvxSyEmhlORJnRFyUBoT/fuQ3M1+/ycjr83jYk0fz9Vcok/Z37tnk7AhJWFKkkt37xb10ACEFAvDOA274MsHllmZ5dN9a55IHX0VmRHTyQtBWKh91EJPzj7aToO1+rix7eCtjP6e6vrPC0xV23qwohSFLAhbXMvEOsVZuZ+dAXxEGSg/JXBVEi2A739abkw6cor2U7QjLii7USJjV9eG+2Nlr4kRVjuTRWYSk5hkzcoo1ZmPGlRPmyfgpgPR/iIg15bw6MEUqqay9ACZ6rvbWwT10SG6vshCj5vH5I1aNyILl75wziNf+TwAFuSuG5RZZhFv8WpJmU5FP8p3LgLBgsJC2KOD3QF0pmoxYAtisVylcie9W4l36Z46aCYM6nOo+zM6bkbl/qT7958Hia8yDfSGZ0eaNwer7u5c53f1s3UDG/9qX916yUT2+gUkEoq3SJTzHwuGtTTZfh2mrKZ+8iWQkQbeWSB7g9jfyglc77vmb0w4reXhKpH4nbdj6CifL0tMEuQhFFpy19yumJTvrRJC08=
  template:
    metadata:
      name: authentik-postgres-user-authentik
      namespace: authentik
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: authentik
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBR3dHtiY5BfCtY0QxDQhwF2+w3F7JOJXN1qlxKlq8AGFNZFmM1mG8Bo2aGLbonhqbN/KpgGaunnlySmE6Fsxex+pq2O4VhztjGO041vEw6efyR4+TL7T47wBJsJzRpVimVqhJzA4RMmrItDpnesX4MI6SvxYjXrloKvuWFBEh4ZvHhJDGTIlb0o2DuMHU/Jp33JquFWGLavWbw2HVQ/y65tFyAjFB5hCQBETxaukl/+xYPALy5T362bRB0xV3YaENoUMSXW3Dc093qEof1s7yXnuX8OGk+R/qM2fAdQAO4FAy5LvixVExk/ZFfcroeLrxK8MatP44tAW+JUez6r93iNB5k9MZQ7N+yYUj7KKG4u0R7wr82ktgn3HM0ckhJ9BlaaIMNmGv2z4/b00GeetTpTFK313nEzFvXMfkxJz3p9i2m8yeiRxQOrJU1rSyH095RXtyU5CdJap0qwR2IwOF2JEmqx3cAan+0tbeHO5SMA08ucCssHOrFURhpKCWkHTsM16xsTjlV4bsm6AyF7nPWJ0YO3/zh1a4Rk5JgC6DjipxgG82naINJZdCX2y/dIBA3zNKwV4TYguRxZNws+vqhLZFJis3euc5El8FhTk08ys/xvrhJWNb7Uft1gYYEDQxMrHuGWhMU/pAOQliHysjc8YHUHpyyA7QCRGZjrlNBgBTvXTfxwgFcjGi0bss24cIHmbAlJ31QpPes5ybXcPr85VaWf9uIPain
    ACCESS_SECRET_KEY: AgCZzW+yhpl3/l8SYoBjn6l+7QMHYmEPi8d5+QbNkQcRMidREDQkyAikO52T0FWT9+og6vX9dSD9/72BZY88l0UfUyMZ1+Msz/Tym9NLuom3bQvMDSOoDiTAbh4m5IuFXA4OsdgAi0CJwI2x0ZkMNjLlBan+d2ZWsdpMmidgkxM3kAquj61cZgHpJ2uFppuwEmQHOqbkNFW3tFtDqPAf0pkHi3PwK0mhWkVDWDoEKZNdVoCyerceSdEFdgDm1q5mVrFFD/mbQudR4xFnPEo5oBaxDMRBpXfmowiV5BaqbgyMCCm5SHyKpoPBiOcPRg5zJMn73NJuM0XjHWHcJRdRpB4s+KhOlQUHy/jHVY7hHS4QcF3jD3qhmGadEfgDac5CNQcW/tv0QxGDF2vKgIVp05qlJoU3M/yrIdQjJ5XGLpyruO985sehDicL+HGSR35J0WcdwCiEzDg7PHwIcrYIImFG90IFRoUBoM5ycRr5aW5M/J4lCEhlSy7zfFlkpQgqP2RIgMtYyTCf+Cz3dhkmZlslRIQHLxLeG/eTRyCi5raBBBBh1lIDkZvHBcNulEujsL7M1dqyJQdEq0ZXsU5X5Nifkylk5t9EchHO5yPByVCbjF/id6WUrD7emiB5TH6jlKNzPVy8HtmO1Ds98KiOdXe2RcqYoE4zj98445wYXn1dOogvioQHlKvRcaLR6pxIxVN33oy1piRkL/aAvOkqxqneFUanocQ++QMgjYOoy8cX
  template:
    metadata:
      name: backblaze-creds
      namespace: authentik
    type: Opaque
