---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-values
  namespace: authentik
spec:
  encryptedData:
    values.yaml: AgCJhHXDQOg96SiQxauE3mLn1enAiiuIG02jl5ztQ/mjaOdqEAxjA+tKFRfgKqtflHNXznV6DKNk4MiFX9H80IIPJFTVve6lzaDQs5RcSPFcSPu2Elm5CXRdFCKXfJH2ADxyz6hF1Xe21e0Bzh7vMjzSnQjQgJncl2HZHUyyBTrxXbqLi4aI4YIrXs74iiy6tJNZOnT/xYX0wYY01EOU78aa9RJLDd+mqnsz7KaRzGiIRyGczjionB0PJIH8VeYVmCQxsRP8v2n+ZVrfgi4EKHoSUtJCfXBeABnr0nx6M8cdI7qjRIEkuk/KGVaxC7IAU7Cyb7+y6HObU/IEcPwBhr4kXe1V9Ra7v3dljJFxEI7auARiFAdmRJmvGJQc/nc1V25/Ewfxdu0vA72958jLw8G8eR7LQsWdLhzIp+zIHHZrkj2oHDBm6QruGHhle+Z5iOwXLXp3wIIzrE+hu215X8d7DgH8cyrYmywQ5S+VOFLR1pTLLs4AkZzYqGxhdpNHTnRY4BB7qu34VoY8GOhFo6wGt4R/kKpozx8ch/kwsCuAhFxw7HZEqQ4BihH1KGx/+CbjKMdPuz/Jpo9/rXB9ZfbCvUACIIoc5RJF/sVptxcAZPld4BA2PkWrnv9TXPsVeqfQdpB0QpHtGc0nyXHUBfRCJIkSYbdXoevF5Etu2ryE0eViwdPwEUXepf/JWicmMn14BIuDQYQsWZelhFpFlujf5pyAGV9uwNtT3i5goh5W6fD6XQhABW3J7QSflRlsdlX1eH3jQCfNIsRPpJ1aN6raZMVyG3+IAqbHtnfwX6Aczr3NjZy/8dWg7K+V7BSoZPtlDYdNKlJWE6ftmkINln7f/1TSIHNbJU4T7TN1stCNwuG7J3QcgbCo43HBMq2Wwp/Nu0r3zE5TcC+fpw88diIZj6aoI/AQpIYHdRjr8HJzpjIYnWv590JGlQ==
  template:
    metadata:
      name: authentik-values
      namespace: authentik
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgres-user-authentik
  namespace: authentik
spec:
  encryptedData:
    password: AgAQinpolB0FT7bdLtkzvPvae1wjHoZYH+sRWpIpufZgE2qyvDXNuycK1P4lcgX2AyniiIxUsnyiVblfS1jPzIeix7ChNtqHCaOo2aQkaC9ReeaHESnS6hnkq9kCNrX3v5Qs+toNAyPMPqqXXyo4u7oAp3sMBPc15TgL2iNt0ZL9Dc/MSM6uEhMM8rFLl51Z96QJhN44staFs/9hVSPmgqXzzePe8+OMUgGywbxd4UvHfUdeBKCwNqoqIuCzgEMb7X5xu70bUOdozvvCUA8u90mxFU0sZ+e1sV7YJr0mtuLNkaeDoKt1KoChlM7RqSGw/38xZut52Hqs20juPbdFx1IKZIfDreMhp4jOaBqNstWsX3c6ajdaT/zXJ+In0vD9ObOjYYcaykjOLwLmvdNV6rqdw+xPAxoODBm3UUgN7ccrR+7C41niw+qKxgKobAKkeepEX1FBs/RvWe31P+6/IKdMOzzot2RidiEbMybG+yZlHu5j2PYqUrbW+A6k4NND3mAZ9Px+uptC7AnnFTATP4iA67w9P567oomM9hMPE6q6+yT5M195vTukcqSMnBiRgXfs8nnWtAhvpiyHNrnLEMH6uDPRuV2iuhZl3X3Zwj7+3DdxE/W3zhpZyXVZqSYBLotsDahjyRW4f+tbr0+jbjdfJNXxAljQMEIQCRi3Bzk4eqaph7xHLIlwr/+VJ3n5ZtpRJW2KQXZGt1AwZHglcH9HZ5vxcg==
    username: AgBbOd1g1hYYnPPoFSjoJPPMa11d2PcLDfrM6XYF918mo2WLF7RDL3Ts3ucng2W2Kn4QdGiQ33B+jlMGOmIw/0vKjJIAoDXmgEN8/d12W0O6aLpasyku3nfkWEAUiHdzI4IpfvJ8gNCVfwCvCJPTEZ2frhkbgmZTgdrsq4iwPsd/+Ex9tPGKB+kI/fHZ2mA3nbcpLXeS7Z/tMgp16WWJJ2ySVXwBgnPn0Kz0Jqjhk0T7qLP6acievZHeGMm+OpEbh4sWoplNeih1vilcqLX9TMbes9xf3A9B+2MbhIvtqsrwLkx3I4DYmBuJPdmhJZeQlZLnlwUQsNhex1T5oOLrk6MaDB8C8h9zeLh8yMQWIkR97M8eHVMib4YKiHp7X5A7acAhpc4sa0QhfGB6vuSyDHiQ4xGiswGsJa0MDgEiFuRBlpqkIVkgk0taMjI2s1lN58aTHwj3BYrAE7NnnTmEVPsnAdZhwCyt0jYTqmkptpC/FRb4/HXAUfvMjJU30JHvD20qR5Fi/wAgJRrz8jTR1h6I1SHiflHgUgrgThomR6cta2WO1ShCCtoeQVVqghylcNe+09QdmdaI35yMaw0AoQE1qJr+zi3fmKq92hSrIb5hKKUyuKqoi+XaRyfAH+hK8JwlZpfDwShuZ3Le4Tm+kxkJOAxSw1x6nTozdMc/HJ0R+GeNxD9+7mJDES/iiZG01tULvKMOzoCEjCQ=
  template:
    metadata:
      name: authentik-postgres-user-authentik
      namespace: authentik
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: authentik
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCEPCcvSvzzRZjSCmuj9hfpIayDlyn+2PAVLr7SbI/5UDWfk9JAiUgQ4fGMggUcGCPPMUBbczRy7ZQaWXww7uM/eYiKzRdNI8VHLk3rQ7R2DScG+KNs5Cp1dMmmTvaqMvSnxQHPOOgEhMAJ8EtUPAuYqWGRS3yMLZlR/RCAVzKFGDdlmhDP4w5o6qBK3Rh0AM2uI4C24rCQ95owjGtDxP93CJbF4UqNjA0ZHrglndz4jyz/tKyzELYqafPzmEkK4WhaFaWaz6XpY2Zym1CEQq0NzxCQtYih0HLMcnIlizLQEIN5Ez99/YRE2368azj852u80Ho1qcesuyCwAZtLJcK3xBQgvVHUpeXGUe2JzRji+9cYbE6SvdNV4tArrvS9FcC/lhTRfRUDAbzL8IK5Nd6Ad2ICP/CZVdHLOaHLlxQ90m/E4fsKluUYD+28wIwBHU3Hw2cHxARjqR4xgm6IttLIm4bB/8gBWkDECjo6xrniy37U8LSUT69jUh7YjhOaObYaqkKUitE1SQjwZPajq9eelSf4eQwNnBGaTlkZSGT77YLHuBCEXs9SNEgq4Q4l5Hnh34iiiCnFiZkKpp1Xxh8fZ+tIwaqjrNByPMjuzAsot9VzugvFosbanvI4I0iWn6GDmqe+TqlMgnQ7qcuUltLt4PTcmuEnrCOPIaAlCWgokptJ6w3nOJXPnzqjZHMvB5QG/zksk5+FfiZHCpVNr4uf2LEo1n1mGPmK
    ACCESS_SECRET_KEY: AgASfA/OcBdHuMrkSrFQAlAm9cIfc1awPIocYFOVEk26i3DOa7s/iG6SiYaFAnyhfw/L8LrN4hM9iX83kn2p+n53+NFxPViP/c/e9r5dLQyoflji4JnvBRVQ2hTHXSeGtouXhU0yflvW84u0tQPrTH07wqNT2IATFPpHK72pW+No7JEmybDi6zoSuAGzJj/3/MC3Jc2jfZEPeAEnnGGrlFPay3nVqD5ugKUMVd+SjiGX+6uYb3NDQTIcwG+qpVmjZsbEUxI4uHn7QoyYBT0CUwKB1bx4Mqa+KfLq49m+Ac5lMCvHji1SwcbapT45t+uPXQXd2SgLHxoyEclZ9rwS9eeKKgmvC1Hws4IE88/fXyfy+IYgsDZsC10EyBd/B39ARqMkurU/WWydb7um2IPbluU9NwQ5ycvBf+Dol55yLEadIS1N906o9FGxKH4rdTyHZMIUJjC8YImEBgyVdLyoaEhY89XnmoyI2Pr6uEW35CxSYRecfOXy2BnUS/IBrkwY6ijc8fkEvvUqST3OU52qsVCyIv0gyJJ/U1vUpDcP0E3ssrx4i08j99+aGcs3MbdL+W6o9uetxfbln4Jaonu08785wT7mgsUIP2pWKmLRvB5ag1oXBT3uV2viDCImjKPs3J/tTLyT++08O9J4bfh2JvLLN9sJO+39IiWa8HV/brh4oXrkLFIcGNb5L/ViDpEE0NrFG1XjUZEsBnfI+BjGI+d5YKbjNqCzDhJpu13B9kBy
  template:
    metadata:
      name: backblaze-creds
      namespace: authentik
    type: Opaque
