---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-values
  namespace: authentik
spec:
  encryptedData:
    values.yaml: AgC/dbeEvPllq6EFADVWxUfclKIjpxk4n0FmyHYp7WHEwus0AgISSaDvWBYR3yIry77hR32BZ2JJrDPIztI/uwLLsNfY5SIus5w56NaM2o8nHxwanxGIz+lnb/2X57HNn5bp9QOr+gtA38RlBWzGlqcWb3Yr4Ar8fkhrvlxdO/1/xTxP0n+tWCa1NQ7IReJynGN6b3wgr26cCwfvLwZ+yMZAPCTRpbphTu5CjO/FlOLAbKmvuT4RVDlrWZEY4eDScNX7Uz1uU8nR4uHBjJLEzeD9s0aO9Bi0MU0oYpYKktCKzugdgqEnlHYHr1USoLwaayrP0RpPGIgl+Ro0gsKC34BYHs5IKtUQZxEI+9tY6o3n0Ii8+iCW8sKcIks8g+GaWUnRAPuDHwWKStw1BUCzKZaWGGk8Ay1OugsZVQ9efjrUOm/VrXAtRjyK+A9y5JWQk1syiWBBte3yw4ejR7/+hCxOJknaORFE2si6955Gd1of5es4DbnVVnYMlOczRUiSQ7WaALfk2NKeB8K1H5//kZ9y/YEpJW2vAfar2ennQgE6sX8oHhP9IBUgUaMdjClrangsq4VYuYfTYZO2pSD+xO4VNgCdS5Vm5TPeyjdOONwJW1ANM3RvMq9zFe+RFZd+xdnc4IKWm7Ki2JqSuFSnpqSugbmx6MQOnpA0om8oTbp2pi2YRtQ3fZkLbj8kEC1AtuAw8xImtYHOmT8FAA4gMAeRR4lyVb/4u++Wd8XHKN2X2zlsA4I+1oz92540LF1WT/UrAHWFuuTEHv/fzjkQXaiUPHUk/oMMx9P2f18/6pFZnLRsd6lJqND/N2TEPwixvRTNjkoU/ho+lB/m2wrIm6P5eVsPr+JJTc15tAl63s9lszkwmp7JRW52W546+6rFxnijvNfHVYpVDiqKib4k05TqnNMUcjmw3UwPUneb+kYEGym8ZD9JRQpIIA==
  template:
    metadata:
      name: authentik-values
      namespace: authentik
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgres-user-authentik
  namespace: authentik
spec:
  encryptedData:
    password: AgA+1cYi7uLkjAdr88O8tSiCEYtSLgCFpt2O57gxFCLQteQEODHM7fYJXQ7cqPJ3vUbpOcw2EPrsAbltAhgxWM8r+G3JsqsOPXB9WbTrabfHqqmOEncm5Xe7FiKMRdGr6JxarPQ5y51bFnczz7X5T/kP1os1mDn+BhT9qqTttWtpjo8LS6GrLBn7CcX0nam1JCkCTxqKrMTw0SWfaGkq+rj7gCMg+mzMcqje+J0TrW+OMbpwsyEzrY2sKOa3NhrFXKqeA9VPevF9IAjs4n3R2C9bgmrO7UrDehGBsbhjbPKQQ871PhLtehB4ZbqPkfh9Yq+SMKlAA5uItf6k5pM5hhvrCZGFkAE8wccRl2o8SpEQaW3IgTe1qfQZRjwUoPtnf1DlAixTx7EHpFhSuQIl1pjtU6+OhDYu7rNvT/0CEdfby9SxE9yqXH7LkBBlnK5f7pllm8MHH6lRCEVGSchvY0iv+NT5u4kiKt4eTywqel9G7GAOgHIx95Yp0NglV0RAz1FQsObY7AZBm2Vrp/je6/+wNfr/M1qoqoKN/Ib/waY+Z/q+j1ei7RFjwfpIFfebAPZ+NgMe3Fse6MV1ORwR6b/IZAl/8h1BZ+Y8KXCZv7+migeKyiWyJlBV0oWLBTaSFx8z02N+l+PN+zY8JXMayg32D3afVYJzY/gA41+P4h95FNKnCHHZ4YW/Mvhc1F59gUWEM7zcAyiSTFJxZLwPn3VNk0fiQA==
    username: AgA5+Stkk9ryhX2TL8/muF2DikQ3Oasa5/FIDLiQ0u3ezoUuCT/gsM9Hjttl5FslgdKuPVDmCbphgWESHfpW6AkExRlpzvBEQcbsZNa+rm4ur9FGHBzqvN0K/J4Ba143iAYl+/bJY5WxKTVQWYaVpEscLgng2dABr5otCpXQONfXVI7Z6v5IULlyl3BxniNQSxr2sKpb/VNeEfCEi+/eE1/O/ArbYSUDvbPiMMoR1n576H70KttUDSQ3JhXoom6PbXTjkKvCGGni2RjXQSdxVbhvn4/audbyG53+q7lcQ/jvAvwBE8nVaP1WYrKrqHmGhNVyLqzXnT+fZ8mIdPxysNTF+x0rziWosocD3EcymqMJfuXmJqwNpl1cvDLsi8wvRe2PZSjIoQJ/o8pxubyf7po2r4Osu0x/G+dBLxFP7aHeTW7WykM5GEjKnskCHtoYkJbPxyNWi/mFAX0fe7npZOLQhYfnZr98abAoHL1zq6EN2b72M+CUD/wQvrg7woBTWCWkyB2i9MnuQnPCadW4qATcPiOtpIqGIGtOwEXCnk/isjPrEr33iBNX9+pD7D767UyS3HSTLhudfenCckMEIZSec1EWnHaKPw+9n4mjPpR0V50r7bRZzJWslzcJn++TnOWCEk8jHgoVbJBYXWf1FiT6oFlGQT6xxRAKlSAd08dErlHT073cFHnTa+tcnRdz3/xSBFMFU3Y/MQc=
  template:
    metadata:
      name: authentik-postgres-user-authentik
      namespace: authentik
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: authentik
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCQBzFxV4c9YHJOlVcBsYmBPvoynP1HP30ft4q1suys+H8+tytLvt+4OMUkkRlu6LG7Gr6/zbLpyDWPHcReJolfot26x4WA8dN0FuN85g9xqdfJSa/NZNmAwDNeRJ+vqokOKPpne6spYxparLShTQH3PS6hxryttMyalP9NCjJIqf1rBmpZs9dHGiZMbswt3H4qdq12FTIn9An3tmXy/jOgWCWBKOg5VXaGOuljx9QSdVy9o974MuG+EgeIXpVtgPmh7eZ/OFrkQCjmIcM+SAEMbGemgDXIAiFn+Bwk9VkWG5JXuACsHrKCYnrrPB/RXC64kyOE14UeDNBMwrDcxTpZQr5PwZfKkYJKzRjI/xGZbYphMVwJJgjzmRG43QN0uIEqatxPylpNPXCXf/31i1VPhcBZ9YEx5FyM5KTecn7znEMZHYMm/FhUeP8q49jsRF2aCgVRE+PnOeiWnWyq8l4Z6vOmSbvMSi2OiND1joj64AiBiA5sWaX7Unm7DjhrYKKbTTilApir3mEdm7aid/+hpAonaCNj7JmBup06zCA/sq+9wek3Nxzkr0MHh75ThA7yy+07ATxBLhEBxQKOyRF40ydDpbIvOB1VbSagMzCt7UFLpgJCbMEzVOlPGlOn9LRJNAsqZQ6GiXK5FX0v4o3Uu39KJdvXxnj3AhOexHRVyrWJaQ39gO7V3JE+J8Y/C5WwMtA2xfatJTq+5y8fQmZHgvCwRWHoEZWa
    ACCESS_SECRET_KEY: AgAT+EOl6HU/KoasInz1W0S8Ul5Gno0dOfRQAmfr5YiuSJGDpWUkB05tk2+GFHjn8OYt+HZ6S2DMu8aPkYACvVolCMOC/cAhHg7zv4GyifaMMDI8oTev6RD3AB/qEnIAywCxy79uC/cctiOPF7mXiOPN0OeaKNj1eqR1QnIDkDYtSgZAI80T0bLK9TvnBjUNYhohcJb5mjU/4bX+4qPnb1kukBnixcBhy8V9XVGqKa+aLG/3YBT32KLZWglikqiT2hkzmCDRanEjrXyvXnFb7KVHBjlCkSA69vlGA4QuMdz7CKgm8px9dRR11z3FWawopCy45hyoeb4ZbOVhn6VmPShAbUTPM6NJBVBNDrDILEdOclWgBvgyTB1A5mZX94NVPcGKpnZeCQTswZ9h8mmwumhG4cXCY6qAD/NIJnf5Oojm2Lae+ZnAj5vt55tkXtEOkrueey2t69ZsDwxE9D/pcpBbI6BbxMJ2PK2bC8nSZGcnOmdsUl/l4z/L2Wb4fmHaYBoOyvr5PWwtahVvo8Gb/kBKXx4EE9XtOmnMKpzjeIRhHL12aumV0krF7eJOp0r6H9gVcHIDQFmPh5lGMthN9Fd348qEqaTZ2okQSMXv61YV3qtJiyqGH3qH+/fPb/U5C0q1pnQ2HcYj1es9EbxPG7Ce89op9YfHac6xeQvnDn8bUQEfet2kpksw55lKZ1OtEuezpK9vHsC8E9lGESKHDFohHB+gIJIvAZ8v3wIkN8eI
  template:
    metadata:
      name: backblaze-creds
      namespace: authentik
    type: Opaque
