---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-values
  namespace: authentik
spec:
  encryptedData:
    values.yaml: AgCvPnxZVZlnJ0hWIaNbwSsIuEzf8leMZlg6QdhsD5oSKdv4F0Zy7KoocM4aTd8Y5zsmWs/CqMbbPBNIm6NeMOn3TXd7nPKahQ0CyP1sIEHPe6uq2HVZtjbewz0oUowlzhT9W0Gi1/ObLp9CKah0zsqDmcHEeo0FXOfhjjloPjMYEigZXPzLifY4eArmEEuBDs+rZoB5uT+wZQ6E6OSEUJshWjm2O5E224XAS3Q5hqhirxl4KN5lBvMZqZmtQW/zCPQNc0hHfZHpwvEXRfjf1vn9eDjj9xW4VxfZ15kKd6Q7vjEALvn51UNyqYG22+PnbCi62ZBCdx9JQ/fWxlyNN49zrqxdiOBUDHBR7mwUbhC9qA2qYRfD7Mn3yqeKU4uw/TgbW9bspNJFvtcHPm9pJ5ePAbBONierWP9UiZEFBLoFBONmZQQqntqTdjBkOGresqZ1+Y38jR4aBhMYY8cDoBmxzdVmeDwj+MHMLLkIOI2WZf37uhuXCvCthU9aDQfIca+odda+RzMw4mXkFwLHKc/hNz5fI44tvBcnCPHlq+kUWn2Zs8Mf19HAXSeA30Rw+IjMnaah6jZfi4FxOHc6NqJASdXxsqZQpx8dydzsV6zIA9wrtlv5Rm/rUHjq0w5KfUR5fYdr1G8S5EywuYUvxC6v3/qSEEu3okBw27C17xvnJ4q0jt6lf7tjM7fDzsrulMtXv3OUH2MfExv64uQek+NDHAivYvaSC9+Kio+8MI9ZixjOoqNWvWmdG2Noa5hxN1iSxh7YJ785yDacCTdX9gmGpKEQUdkhlCTV5HkHa6fBNyV0p0SGc1fwCTm0fLArvF6IkwMCL2M4p22oR6msZnqgW4jSEYkso3QJJI6zmJ2uG357h8LWRoKIHP1asWWKE5okvmy9YXB1C9nyJnnSEVnryZTDmPKiQTZCkCA1VpwdUoY4HeTGkg9o1w==
  template:
    metadata:
      name: authentik-values
      namespace: authentik
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgres-user-authentik
  namespace: authentik
spec:
  encryptedData:
    password: AgBE2zaBWZZJ858y2/dNVymdY+euVQPD9iNOuyjuIaur/k+noBwuBQ9/rRzr1kgufzRy1rkhIuGAUZedhopupMgMr0KNWJCHgNqYFu2iuUjW6dX//RMNvAe3a3T6TBJSchatuWM+o3gYSeMKfL+wbq6tZoA74sUA5t8TnNKPaJYZ3o+mYfvELZ3bAP+OIdR+K2ivmQtbAf9nAHfHHhVawhZZ6JmdpUOgG4sh0kW2JYkPrIvivOhDufzOmao96Rei7wm6uUtAbB8xZxVQL+7d0e3vX/E3fWL8tGFZi4LivRdXB9Lj5NkKiInAg+AQ9qe1OnDucJoiVlK47VeAi4Jpf3623aBHLvxeyCM2GOVoiHztyz7XWLQ70HxapRFskAe2J1ubFUpBtWP+1Dn8zUeOro0QN2uMuUnVBNDu8CnkqYCT2cg/iWAtp4XCmPh0ZnE+mGG6Bj5U8oEOCz4zjnhgjqy68OwLdw1JkCYtjcfyICFsE4BrvQlIrfwYf+XGUZCQ+nten44TciBQyELf/wFb90bPDpzum8Z/ljufE7u4qkrNNIILwXmUzu/WxAk6egyKxAunxgYp68quKcIxci+LnaPIjB7ySLOqBOB0Hg85ltZk/LDDsxBSTlace8qjZQIVqwfsp6CIDtShqAT3PfQ6EXa/HK8BhC1Jpsk48mz59t4vkjrW3hpOk3EUVsnNWLkzeOP5ISZNXE+U9YfSsYWzdeNdRhMx4Q==
    username: AgA9Fh8MpAczS3Nwx0NRr42X/JrI21+5J9UuJfMtVcPHi9M5mcZ8JwvIcU8T+M0UanovXELr1NoC3Eh7/civUi5lvpcPq80EFh0iI9KDYNiDD3HXTziGIvwKvEbBtEpxvi4CxXOjQ03bzVeP+0cHQwPm80CpO+ozOjdY0DlX8m6oZLYB6gAQP3FAqxBqy3MFno3YYH0Td4gRGnKgFh+P//H58d9ycTv7BVdxWzlluChGHk+MPl9ANNU1PVZB22G+G2p38cuFSurd9nCjDU54mnfCHMHyyurFxyUT00De7K8Sy6YexcUBtyBxjPcwwcN+LVtRKdGtrY+neiJM9NxUnP2aN68NB4o/OKCpwvLes2iRiH/ymqNsR6FYigaJU1tCS/Q/VYx7k2dtsAFyPHokkynOizimgRQg1e7TW7cDihFV48uIjalADkuRBbTtUVmg2EuhPUcgUgtwFu+i6j5Pl/DpsiD+XYAtSbJ25Vylu8vMcnrxNNnTuDFxv+fujnSnFwww9LVuf6QnARCL8lroHy0kiOzA6ERXwYAcvh5vKdee2VKM+pg3iHLDUxl05OtNvZ+SSBXl6pyg0jYfYbMPYn0nfEU83Ug5IZF11qoTzHSeIkfBsPAqo5/UWi9Ni095pj9GiIDdKNHhWAuNbqSuhHwQpXT3VRHgo6i3Lg1vM71W8Ruz6V3cJ3xh4FHzOZuDlSBHXkOtM+l20HE=
  template:
    metadata:
      name: authentik-postgres-user-authentik
      namespace: authentik
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: authentik
spec:
  encryptedData:
    ACCESS_KEY_ID: AgClgalSvmMjse5GBTl7iPpfmmZv5nZ2kxvNPJ7mz03ieIsCeyo7A2NslwkB/d/qqB1BxFh+dXehjtrVpaxsYsX1yabTNtn0Rly0LrEsU/CkgPCw3MacOsc9P9ecYKX3O8U2YOZpzxQQ1/E4msG2raY6E/p+3UcIXZYA9S/iBEWMqDJYCOs6btsv/UzoOvqAPqT6DOBLpEX9K5a6j0Dl6iRyp5PhCXgZtsqy5+zaH7u+eKCG/SDSzc2AlBw00aO0I1JJklwCTNq5p1RXm6p964mfD9DRaEqXdrjwAiToWn7k8+bfU02l2xwE2QfeZWVZhX52AEPej/p1P7VBgbah00vq6g15w1PLLZdg4gCXRURVvF/k8sqyKN0t0cmMb3Ei0qbhlpZehy213p8TJCZcMmbwcVgR4EJL3/p59ZSqTXYcYv2oN0DbjK7Ht+eOa7ELF4CdB2yY2EeYd44Fu3VlajMoEUwnBoeX+r9aNQLtC2xBnOpiGUIYGVN4Air12/N74rfqVWPrAZksE32M69loHcyE+MRwGCJSPgaV3jOEUHYjF02ejsPK0+Fwq6pso1VQMn8ym2tSjS/TXeV3WwV56/MyqopL8CGG/bjkr8iQuCSiKiYV5hGjqrWm8DH8H1B6OMTNz19oYvhK8NEoNswrcU7sZCT/mVjyc1sJ3s4aDfuV8rHwDZUqNcY+ufLPg9A9sKSk5U6cYyPO5aJpTHSy/sYynPPtVvsQ1OFk
    ACCESS_SECRET_KEY: AgDJHGIKTgMdm8hJg1NwQQitaUGhWkJizEBez1SAU7qigzz2AB/ZvLV8k8GaakR+JehkgydkcNyX8ArxLTAyE/L5Q9GD7QkAg+YDlL4kwSc++4Axt45ntf7TGJBZE3JdpU6BTDhI2iEonIxv+i/EqvyPsw62BiSZ842GjVa/J2ys05rqb9ko5B2+tHpUmycZ3mOmO1mGDE71P7DaEWwNNZgfVmCXVEd37Ze1sN629s4zJsbx//4sRkubIhDKrcb1L6B7lz/9VNFJvy0GxEtYw8wDCx1dftcfZkhFixDRnk8SwLWSKlo5W4Mc2J8U2TmZx/34K25EQl/5n3ECCLklooew11RIMtgG+2WI7gV95WYjj40f7VFPercwq8cNVjxFhsd6Ycsrct+NzxVy00P3ABs/8JPTrwIL/CdwKmEHQqWRH2ZUQ5cXh/1FLrxnE5dY34MgGBwSIrAYfmIcEhELcJPrtjFlAoKIbmqRnH0Xs4meHRXSAypSEX+8oxDfiXV1w3gZ/zj+GeEFjePJ6p9ZHEKN53NbNXtmH3tFXINpLa26IuqOMmQggkBchKUhgZS/dqzRjbiybDHSXranFN/wsMOP+MjxrHTscN6zXpmuKEMDp9asYAZhHcF1vzGPQBz3AcLMx6irRG+/NcMbQjPgNaa3G3OwD+tU//FTK2if7Vrr9BaSGoBMhhcgjOg8WOpDWfQGYXxgd630UYg43PXE9RcATKXJMUgn2qHxMY6bQREK
  template:
    metadata:
      name: backblaze-creds
      namespace: authentik
    type: Opaque
