---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-values
  namespace: authentik
spec:
  encryptedData:
    values.yaml: AgC1h4bKCqK6rQDBxoFl7sDFNk/RTMIidjAK89PDafuzGgw1OF1LFvIBVWkevQtOIbTMtEFVQGQMGR2skOiSXjv3VX1mUSAwtI17I5SEobjmBKAH95h0gsH3NuqLP5xdaSnIgRoCJf3v7ydZhrPmqF4mlFM5JqHP6UiO8FKnWMgDFoAhMCzztOMVqmNxoBn8aZKWEMnaLcKRTZsYUjVdWePUyaZS9DaXVT2dKCO6p08DF9G6eilatumqhhPPUquDpjhYnIN65LsRR/HDn+BBzdNXXnMKHUhlVTEMrOsKxN9DGPn95GEJXm6SXHTYKHj6IHK7RiUKblDVbBcaRD1G2DriH7blBpKS6mJ50+n9wFCMKfQsYT8i8DkLfudgfY8L/cS66Z1nekzJjXRr7H0wgh8y5yvR5Sdi71TzgjrL3o4f/TBm9L7+10sKN52us61XLgzMgHV5zVN+FV9k+x1YPFWrDMzP+rwAaLSfq/n7ZR60aZ1ZWiSLLRbQc7zpG2u57N+gQ2HhDzLUEPxhOSoHv5FLHz6tVQk6v8tlUKsrFh3xOyN1WEOHSY9odCkZrkZgMnoix3BW3PvqO8spgGMjpSvV/KHfd9jXFVLttClMPiJ2BXqrK17/FTe9QD3lvC3vOrzenNN9YG2WDpQjJz7NaQIr2vWVlN1lsAGP0GCMP4K5szcpZAtkvIjG2IgWJl/E59XffzEmr+B89AGCgZUDVLDueMt8XrzNWl6jclkx0WmJEuIstCcXoNHbpoSph7Wh5A7SMMR9kvHFQ7ingdJiWbGzx+os72aQ2fGTwERgoE40hW0IXe7oMy1D90fLviBAfBzkrK2KqglRC6h4FRlbOq7l9ULeihB1DpHfRlKLQalTKIgFU3uwqUjfSzjHKyfAmWgnHj1xa3ImssUtIgH+2++d9fkoss71UuB7bhw9v7B3kUEhOo2pXtf2FQ==
  template:
    metadata:
      name: authentik-values
      namespace: authentik
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgres-user-authentik
  namespace: authentik
spec:
  encryptedData:
    password: AgA+idFnkDex5i4u0RiUcHCYuq7kSdhn3t5rFA9m8T8zGsULFLhwGpEMoyX2NXbKlFxhQXXf1MGcctKwpWi+hWk3QlSSaokYSHOUCrPfR2fapVTlCI9iL2Rbwl5rxCWHEof5krmh0iqKdAcvynUHUoxZO4lA90Zw7aRrTKZn1dzeMBcFxo7/17PUo8lT21RgMLUOW00Jfi+HM+iHyglf3QFpJdy1qjfVzy1LkJLiqJCs0u7QCktZctS234wq/buJs3CrZlIHPoylqOCiwdamMR0GbLoaGDoZdjmqqK8eb7Pzx5C6KuL745Q/Y2lC0eB+p1ni4OMAL/qWZ3bkVsmawaSriHU4NwbMuJ5A/QeND9Q8Phl9Uml+P9h+Uj0VRA0KnAewVvjXj0gixUHQwvoPO3gED8H4uijn87RCdxf3RiZod8BN8B1jkoH2BijmjuNLz7+0IOif39qZZ+pPu7mwvSMBkq9JbZcYE7PpfgboJshVCq1+HJczYi6olc8ZDHYkWpAP5tfeOCMZhOqx79vTrD8sREiAT9bBmCAu4C1JxQ00krGGSQrxkHlbBVUrssyA9Sy9m+VqGMUp2UpbeDN+/jGYTYnhPy3xDBnvB5BJmlO0T99fZlvowXYhEcip0k34bk085+l39x7YayrTTfpFEDmlMzoR23FL0GfpO9WTNkdIachPCjlHqB2sZSGbhhVZCy+K9ekxv/NP5mTeSyCOcMtHUoEqKw==
    username: AgCeRyHklisDleaMs/U5S7ZFmd73nwCyacZcurZAOj8ZYsBEARs/ToLkpfRotW+WvrCkPhOuWZi1xUoqEiG3Vzg8L1mju1v5Fv6No4qUQ69SCHs6sA74uENW2SAkL1isu7+Dm9mdAlBtXMl3bKPTOS4GzNWA8FK5+iVQ1Ibi9uQdY7gvXlnxv0b+O02pPMwPH7o5SZbQqgMRhyaxptBVWVpG6XQXLRva1DJVcLn8026/iRPUJeIee0pwAcyYkKs6MpJ5yZjgLlgylAc9bdSfHoJYh0GrujoXScCGPsG632y93369b8SLiNo/shSzj8uvJKNVxBAuyahmlWA+nBbtdiGjGQsd0g83pQjJEpNFbHYkMDH0Gc10riev1/8kpDeLA3HCN6kB/H+zHOGuOsi+NT3vq8EnKzCqJEGapw+v1AdBrzkgVPIqLLAYZRm4mys8+yadNxb9f+6pVSR8P5CgOCrzhR/kVQHptWwmXryi1zd7DcKG7Nnl7FPJb2qP3YIe575PcLWEp3HvvK2WL/m2t5sVs4Ux3A8qdOMrz7bN6zdnUrJ3qdXzUz+mjIxiHyfu8n0ktFBz0GryPO6DgO1Ryhyik/mcmStKayHPXTdickQuHlyFwbJjb0TrRE90HTkKX/wnQ/YDPqd6al11WOme4NwJvcWjS81q8toU4beke75ZSidVyTC8trk7tEPJI9P0ejoJz6ptvg9bs7Q=
  template:
    metadata:
      name: authentik-postgres-user-authentik
      namespace: authentik
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: authentik
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAT0pZQS/GUjW6aa7vhAEYUYybK+9tApm0EWrmef6ddLO/urHxRXcNnbMYLWKEmptiPW5Gcx7y62kCDyE3yTI5rXu+QFT6wRtsHZTWvJPyXPkPmk8UTyTd7s14oMxOdJdLNinrJh0kfDwEo+Cbbu7dmlUvcZLYq3v2PU7Gzs0esxQDHJAv3XzgZhUmOdVT25HYNf3ab53/tp0PavsdRU79oQV/m34lhCRW65aKC9k3vMrhsZDGU/QMVk9yh7gl0EnIQZAnW2TaTB5N01f4cvoiE6OPIhxdcG8Muy0oo1Hrc+MCEfIekk4tCEATqQ9SJnx8BmVeMc5Ko6qMkeSjD1XRvDXTalT0zM9AL10jrx4wKWcezQhXsVoZu1HsAAakXA1hWh3td9hlgldzDBO00y9zHsCUdvnzV9EQ803G6Kz0O6BCR8h92exFoI6Yw6B1j/IHU67lVZuX5KAr+6Dux9+pznW8sfyLiov+fl8Esh0UrzGOmGEufvSvRDsUlU7Jc4xO/+8m53HLs++Rwagqk+1xwonbD0Bk6WAA78nernTo7cTQpxIxAD+sv2aspJSyrd9QMqtpLMwADInW/z45Zwys705BJ1+CP0txr8aCSexcbBQuHz4gw+uyn5iQ9+0Jyji1wZRaNWrlTBYsPkzxbM5YKrMOXH3bewn/MLJNbbBl/WzOBwBgUG7PVfnnYg7OdE/+flCiqoeQiRjcUwa559VJcmM/ck4dLqdUt
    ACCESS_SECRET_KEY: AgBjJIg0Jv6QEkSbDmzqtzaacjrzB4V/PsQ83suiBQqA0tX2epJcuWlgA7gIc686Xz9dt90gNx8neXoa0aVrzWgiFzKO5gMVl3C6Zfw86sRkETkbu3diI9xaWLg/tCyWfjHuwRKhRUty6c3szxbYfNe69QWpjIVJIGEiMuyKlmajMJIn96brk87oX7VgKME7jpAan2wSqf73OvUW1ZVzBMMSKBKSqenTTTC9nXNPIDuUdQb/8/TCIUVMjZKFztL8sVR7UCZjRAOOqpIHiMw7H6LGqkHFb+IC+KcOsgmWFA/55AULEzCmSPHXCLZdKSal3hEAAaxRMQ33c/Ce2rjw/GqvGuf3PI6bEBKY0cw9CehM9dQUFNKUT43ueupC2k62/U1wzLNmfF4XJvHGiZ4reFrDdDz8r2b2Kd+O07ehehYLlhR/T2Y8OjFjzuWYNPeGramVGkqeedSMywFf7xEJKxFW67BSwaFGsdbmJuHhahfhzCAPRBXaffcTs0Rw6JFscN5EGBPFxljdNzV0MVo+1616ilm0+wA6nMdylBc00OU2ZAq0nTAqtHZ+L1p4iaGf2+g5lVakmdGh8lK856KxnKlsJ5kM+nIFz68X8VA7MG7fhctYAb3/wfHohLZBfU83Tsw+V2jSBY2FvinR2GrBnR2dFTHJS++ZW//FrkuAPMgHz/r/GnfqmD1+MS0Kr9EkNSV7R3TOI4rJhfDtcf9lyQBKAd5CR/8/fwKmntnY8/uH
  template:
    metadata:
      name: backblaze-creds
      namespace: authentik
    type: Opaque
