apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
resources:
  - helm.yaml
  - images.yaml
  - namespace.yaml
  - redirect.yaml
  - updateautomation.yaml
  - sealedsecret.yaml
