---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-postgres-user-nextcloud
  namespace: nextcloud
spec:
  encryptedData:
    password: AgBEaHrQhWo4hmyLIPUv+76xpgMs2aQ4ox9G9EYdIVTrWzWtK0XYgLaTphbF45H0uDIzEi5YOXG92tB0TSIBQgYgnLeUHTqopchP/3iRtfTOXQ2I7t2oyZ3mdtwVYmF1CFGVmRy+bVc16C1gGscWmPgbaPPOUBmgzJcs7sIIpeNI6q9AhjEd+r3RYRgfxWPutHCmEuCYiubobCU1deYHCmYDWXL/bi9RBRZhABATD7f1/Xdg5wVbAShgI47h5cRQ7lwPJgfjXTg9/7aglCtaaQZV4m1ZhA/G4Ro+qCBTuytDYDo6XtCqEDyOctCrVhpzV2RquE4Yd3VmSMJ580BHcO4rYoOeA3lZEUFu0IhJUAoFSJSdiARlPSapTF5UU8TAlz/20NVoV+l2eYIH60oj2ArKErjwa5Vt54Nl6gsAQWAiKMrfjm9YJ/QdhaeDfs1LP5tzO/KSHUQEEpx5eEivyYo9pOJE2uTiyB9npaaw5uYwLi6/wMs/94lG8ryS7Nq/8kropq03Umwl2pc3lJAr+4Vl/oFDuH4msHXZgUKnaRdDwI/vxnt/+wsFYMa28S2o1WAcGwoUUudRtH8Lqrf1S9DEjG1Z054x+n6pBTh1IDhv5LMKbiuOlVHfMscgZN3W0C0ya15K6VZP1oB1TOXI4VPiRBZgY1S+cddA9k6PknIodSbpoASt2uLgDy/et9YjKKUX/CwVmhp3CHsynGgtnnuzxr5wAg==
    username: AgAhyO63vlTlATRcDhkM0US5nHHVym4qqV02ZRROzC8sixhDEyga7eZRjJaArbkkx58nHiOAXqo4NAcKFA6TSbMCj09YQVaciT4uWG4Akx4aAJRRWwomCXNyo5Q4l/aGRq1BWvtCeX2WVFQfHI67gJw0LVxLsd45ls0Pg+4U3RoIElCNuTjbJQJpEUGrllaPof9cYYhcqm2EW+L20R0oe+7Li1brP497lbnoDBJH4Xkv8pgkcW0Sn6pAwiOFmLGd2I7VjZq2TgOJcOVj0DhOaiM7GfZFH59sL4oMYfWALa3QgtY+x4baLLH9NnP3BnkH0rNPNDM7xYdvvMoXmTmyKuDxERF82ZUhbr4I4y0RxQtMv43aYdtHS87Xo4BORVmLo9OOe+Rn/EYvdOG9al/zoPAi7CuN3cxzatdrPq9KMHImjGoATnzMoVqdd1opgswbECddS05logjBKDG5f1guaOxe3VUhPdQ5lqDU1zvcYQjsslj8OWJq7JMeYqQ4BPFVxreFWocufZCnSxT0poVbjdGUSR9rGM4m4D3sseuXQEn+NoYRuMDZ6MmRpNiM4QYK37XgAnDCAWs2VPp+oKVCBBwIJlB/TJTkDHWWd6mqO9fWJgfA5GfD3Soy/5dmMIOOrIoRK4PmysGuelSG5J7NY+V4/0wejvFe1nTxTS3z7Yvj2ewXkSyowk2v6msPFuM62A8/lFfNpIrjQ/Y=
  template:
    metadata:
      name: nextcloud-postgres-user-nextcloud
      namespace: nextcloud
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: nextcloud
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBXM4JYM/v+4585jbYuOXRP+GwNNrvpXN/27MIGPvFfkJQE7huWFnTDrZdf+tLpuuXoB5tbottnDgwX680AlzL0/lWJssSPxVopUeJT0BlsdSh7v30EnwNWqj29w0oEASCiN8n0Ac4I3PQD4PE5nQVOirssKlEtob14VWj17iofu0xZXJo5uNuQXzblZedUvYsKrZUTwD+txcD9kAmT+R3V+d9uG2tsiDCXL0Ed4FmFa30/WrlJeYQohPdRd7XINq5Q9kR8mYn+7WUhT4jTrNh+wxgO0as8HrS5EYnNPbiotZ/+EDWRgOt87NiCbZiEDb1kYul6Lej8dgltyuIU8uEHHMyXulVbDtjNPoCbalMbu0hpUgKuSdlfCxFsQnr73JVad+W3QdKgAXWXB46R7VIbjz/2aU0BKl/EfYdii9OK7+4ZousDhWWarENZGdi0RbGlRaMckZVp6Y7tshjTV2G+y0AMyhfGuXM+MAXruRcChiJuZKOR4qP+avH4FcToXXBV1gW5v2DbctMasCuOKxXt0DDof5WcSC5CNB56a0PK5r2nc0ITaIVy841wGkHs4B1T96hsq+3X/PGEFHg+IH07MSON0Wu1KILjyy2itCd3gmbbwaBVliJ0UbsATFivnX0X3Xvp7Fyx3pExZomEZmOS+TAZoBCuouiNls1x1t4twSduQne771+VVSjYUMZ4qk4X9YlMq76ywMwJesOiW4WiSYfWpwKzefDY
    ACCESS_SECRET_KEY: AgBRyZrs1Crm40vdSb5jkm7q20VlQ/osDoXLbq7o3ppFmJ+wrWBDFE3CbgDZ5uShaGoZyh/FDWmxlx09gFU+Cs+GaYRp7HUhxuASXBzX3Mp10jSmN/zdOABYwh9ZkysE6kitrCpUayS01H3Lwc2/DMdQ0nvhSNw5rehFLPIxU1VMCnVoQOW1mbswsSsecLRvv4qKnBgsxsyOYK8Pi8Iw1s+QApllmN3PVWu0D1RuxIr+SaSWpv7v3kEiWE0OFi/W1QzTmZ4HjZiK82MgX1FFf6Tto6SFMMfqvVjTFk8mmihhOKc4k2/NfCrQjBYbf9DbFHONbuq3Ak52v4/D28TkBrEB7LVZxS+K6joVJa1lLDJ68LJ0GNYZBKRHglEZH9Po1RHn0DOuUaOz2G5chbGuNU/g22qQJ4OfEIHQUceWJMmRk0VIWTOP20RjRGVW5p1Zqcn30Vv+4lrspnTwRh2HY4f7GArUtcfZZDmx5W2t//RtkC3ts51okxXgNk5HfUWBrihcfvth03SE5IgZaeNHUDTctxzKcmANY1XUTYbuYrWiSp7ZlThBR1QnKMIxBI162Q9F59VXJdmLxne3NPpBX73VZFUMRJC8xW5zCGpxtlHa+4mMKTiDbVaCUltHIIkb7atV4AmQjA32ZLadRVp6M7PUzNuJRGhWSfIB3tRTWw7ewP8P9aNVzev8iXao05YXWMKNOmZT/XI5o5vxR7PTI5PwkQHGUX27CbvvsN/6PdCe
  template:
    metadata:
      name: backblaze-creds
      namespace: nextcloud
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgo-s3-creds
  namespace: nextcloud
spec:
  encryptedData:
    s3.conf: AgBZ6CyVNGQ9AQmVxBovoy2fEeA0kedRL0iZJYYfY9KDXpmRCsVLxz5FrjOMh8DKDNEpW2COi5NDQG0SkpeUxHlnSyW+haXyBmlEOuhlFuYjkndsNHcS11lyX7nbOYsZxIOvyujkmGN6uqliLjMrOyQUBrrLCzOVSVx6Sz/G0eNtSe/LgvfnblZLoGEQo5W7BTYKWuXmpuoTbcWvnfhvlD++j4Q1CzApoGtBOpw8sUWpfuJO36wUo5ddMJr0/FmWl+W4U6RYCEugasdcv1zsKnC76L/9eptlrYIYUvBBDvZI1EKPCHvkWyKqL827PVT9kOfcyWR8CMJmvbOZuV1ZyZNZXOaWzghdsd2Y9qP0kKsueuxZpT/e2hYTHDocjua7Ifm5jFQladbkXw7O7cvNAe45t6KXPdNMkVewqzEWCzyAxUaCweICN2wrWu01c2/Yy3b5cCbpFLbrNdgmpVoTYnxkyhANyfFRR5yfg5XX2Wlrb6O+AWEWjPPT3I47VviY5wWB627rfYAvCefZ54DM8WDCK+j2ynsM46ckQV6OrnjFP+B1cEmtOOUlkLvWZbuWlPn2lBgPr7ff8lRtM15bwTY7Aa/AAowTjHh/0adioQEnm4ByR/NlcwwkgvAvz1vv7v3C9XsoC8SQveL5OzdoMR5RdlusBhrS4ttUoQgrytzRu232FQzo7p9HGZtlY6lS0Pite6twMKpk4MwqcmENIwcbMLfUv4OECbHyUL7v85f0tIJ1cAU1lUqtrP7HnSu7KCUC6f8sCADfx4imInG09A1wFoQ2PeXB58VSslL5OBETuWT4seiKzJhHsgxDFoZh03MJPiM=
  template:
    metadata:
      name: pgo-s3-creds
      namespace: nextcloud
    type: Opaque
