---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-postgres-user-nextcloud
  namespace: nextcloud
spec:
  encryptedData:
    password: AgAhd+cQxGcvKOxJ5JyjXR4egufRHiwcS3M3eZViJhQPnk/kbPltAa0McTEXMIQYBtk0czKiw04rp5gH0QS4W20IRf7NPQmJB3JHrmu1Rf5rPWpZGhBXqDfRAu8GsHXHtZkSSDRMEJnUXaUbiFNX6hAxqHZThwxqME9NQ4kh2orAR2uoitv0BDlIMDprxnuy2GkrTCEpLDyTM1jKf/styNHEYwTkfvKYSV5k5oiYuG9RPQtW+sz1VOOQgzTsWAKAp4tvnegkiedLPY42tEh1L1CBTKNTKkNwZn1lrHcRZPauNREqzzq10qVFKmoWFnAS/COQTCksrG27q/vydFjpDIjj2ZOUjxN1YYIz7GVsOQhO16m4BP6SlFdxiFDJ/JmSka1k5Ogu8cB6s3L4ClIU32avts7z55aAd7R18mmsQrcvMEtluwGmePyRB8wjqNmc35L7gpZhKYj6HWer7ufPuNFhBp5czSvPID1BRu4GEaRVvT6sDNjs9lT4B2zg0YaAkSOdH3/x3v5u5YJTHNpLzMZda1ZJdtwRSfRhuXrhNEDYHTvVurLyRB0FAVt1g8aX+spyJ9Oe99yqDyzCL4YUMlBcUb7UP2MBDBeTc3/O7mCLDyWjcrjdt6U977UG438EJEIiEqZPOgqKphZOEGqPD9jzYsOOj28yaDtGKsk7kJ36SNcKG1geUlA3kzh6dZSMX2ury/CoF0/lPUVKQTzYOOt5yYRXuA==
    username: AgBeLO3OD50G8Vkxpot/iev2BbKtv7a67/HeM8iB5YG6X20qxoPh/cRNpsyPvQ9rIhgLEBBIceD5U0NLsVy4kAAHupjroJBjFHHlP0u4R8QRzOEFCE5kKFpPhd9Al9Ci1Mn/wz4xbqiZSM42u2AjBoBpXIKvDjIj7woJj/GYj6LbvNASUCfCZbjmdhqy5OZWEqzTPlvQZ0rNNv3UG0rDBhOb6Lu6AhYuY3kwm/FRBdD9GiVEoqWnM9fniH1wp+AWXad/Bx9kj+vpIDYTuHS1uGeiU3PQNo2huXY0waX/5jUUKoDshU2E/SarUqb/RkXOMIztALdgTD3R7ue2qc4FH9nxjy2mZdS7Ksj2PbVbRBGxpFacemYdULMsdv561YOe4dEXrWM3Ql7pLiPIXfjTPIhh3V55aVIPTqoFlNNp5/KBJV91PTXn2mTVhxU1lTiIJb0v4Y/xnzmQ6uqRxVxDxbq4qTJinrEp7osTJBewDPtNVGdvglJST6ra+SGVMeiCcPvuW+ZYI2tyd4sFr2z15CYEhypQZ/jZq4sfqg5e+r/gJFlGdQdAS8mZ/sunsolLwiAxHw6T6y49n6JvKHke/hiDzBCfqoeWNAlWciIcrVMLnwkCVEvCDBXXNr2iUze/f9RCovD6Oo1pFO8+ZKoUHZ6CYfrwriM3C5IC+P7cQ9kQy7UoWmSQJxs+uj7WJoQ+X3GJjt6e5h7wYgg=
  template:
    metadata:
      name: nextcloud-postgres-user-nextcloud
      namespace: nextcloud
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: nextcloud
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBpsUNa/XP5liqvCsjW5xNwZ4WGaAJWULo5bdb8Sym+GeUA4hpWj/2thaNDmL+r4+x2ZfDSfR7iHmrC+U1pi/wmyBFWiu6fLnpNUQmXMTyrGXt4xj0RX9DcwC4iMqrQLumcQCqidQKWrf7ylAoWSWDayrle5cqfqpboaO0SEnaNN1aGq9BhGomYmgChxqr8hDALxMaa0MFnD86CdqgFLdI0DQMZNmLqPETLzVURigZ2lyRjt0G2WKjd921x3Ey5jTdciv3sVYq12Ncm/kCb6F1nb4jtsRLsYemoujmEVxt8TMRb7I2H8EYBo/Rn18lKEd7XQRyYmkm3S69/FvUXtEjYXyQx5W3sSxpblV0HiSacVnEb1Bf/Y7WWLZ5wgsdpfWilECKl06UqLYE5z41fDVVydWMen2Y/oWXQqlnoN6/Vx+imaz/rczjdDVcO7UNfj506ShOHZRnq3VSsXgl2e0AcrOiSuL7lmZlqT4MndUdqaHZUR10sfQ9M+KPEA0LlJKjW18pyAPZlbLw2JTCUPqYqQXalU3PnV8tbjHrD5etr1Y+pXAtaRsO38JccfY+p4ycvEj94J2uPHYG4kwRZbRUgUnH2WRjk/TF4cSUhJGBYhoBadIW4h0IZqS6lBzOWzQC3RXg5PXf5aQjXZl9S5U6gvtP+gjYwIQe8koLXjc0d/8TTz99uPFPGixUg/mzhNmPuiPCHxa8Hq2Z8AxpipjwlE/GAjA1J9LVT
    ACCESS_SECRET_KEY: AgDMDtyPJ1S7P/qL3wPf6BhsllR/LOOsli+eEV0WjD4jl10nniRzxNmwXTqeI/pSOKSo7GuvIFIOSGQBaHI7X6Ui3DE/KEnTsh5My+emQAKSQa90BlG83FVSuRBzI3pwyYHJZBXaGHjnpoPX4QpakP0ktEUTvBgI7KsdNojExGFgC6tSI4Xo7vyb2dc2MKBkANHA/L6w50mD7dovsRwIpidCrOUTySD7z2GObR+yskDw2NgiaQOrbrDRspzV8Xgdur+3p+v5WFkLC2DIJN0MpCB9H87mS4j4vI7mbqAnCsNvEsBvojy1l8W2ym8QD1Bw6SyPuh6M6c0RJeNUatM+UGfreZqEZcKXYeLk2Jh6wyJXSLqQLD9Br5x3HE09d2OLFhiDAGjK48dW9BIMosYwkhIyVNbEWibQQtUSu32TcUDEFTuAYufHXrVJG3aj2r13rfl3hTlBhcP3p0HRAnlV5e2UbBOo/z6QhfEGadS1EAEWuFnjC6I+cCjJHQIUQ1UGe1Cm42xdex4jUv8kwOsPCVnbO+lXTO+1tjpoRVNg+Xbn4uVf+c54p6OcWvcWoWynA4jfdcD/q/EiMBHuxzH/8nxQRb9k+yQN48ZvZVlWTSRMl0pazMsCJNX/j2obeWymyQRCwkut3khtJ3bac+Y2KQ0jjsrvnFaKak9p+M4VU/9RBF8W1u6qn2duIAAz3R84VnbLROMblOdaTOwRnHRDZEgwe4awgh6Is6fki5AIQncc
  template:
    metadata:
      name: backblaze-creds
      namespace: nextcloud
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgo-s3-creds
  namespace: nextcloud
spec:
  encryptedData:
    s3.conf: AgBN423loDCBItF9A9/ndMUwZCzGef1k5pKTaPNoMkEFQ+lCPmIcOljsxHdjbPT2QJAmz1FN9dsiYhB3hcqh8XSron+G3iJY9HciLZv/94RwqKC7I8Tc2w+J0Q25F2HGgD3YgiEhN69SqEDS/q9duz8G6lOqnovore8PxXpYYySW6HHOxwHPEnKFvENNxIFPP2FXNo/YDvBEEgQNc5kX/6zFZYmJ/apk9nJqDiz5uLAXlsls6J8NYaFVFlFIsfSOBGKZ9uoJQUZ8w1EuAabfuGOUPys5QZHEaQXL3jPgQfgZ4/9Vmf8GTH8Exuld5E23gQRb7kpfslmDfnFF9eUdS2mrzXJ+UMV3dSA/nodGyLiJpxLTF+KF/YJUqVtCuQbPIotSE+1rmbbYTeQ4XalOtlikQ/T1+Nj5NjDS2B19LH8sSct71FQIjrfCGyLl5vPr6/oEUcBUf3i/563e/Vy4ZrzcgIH/cqKSd1R/TnlnjYXJ0GEOlyfk0v6IGP21WHw8PrR8zHmAqiLDy9XPbhrHi1/YrmUdgz+bHGd9yhD4vXQyMsKkIfzkWmgXnpbRQCQOkLM/nnwtSaO5aFgZ7FTZBAzMxWSETCpZIrkgvF4s+fcjLhq0UR2T9/3jyEug+brqXmr1F+1CD6+h5tQrVgCwcfLpN+qSds1B7wUwFpuRsxtV6vTCs6rURXw+kBPK0dPa4eyeAogK8S5xc2GfT7hZxjh+Q6Iov6a3kFhQPcw2kC2aeKL0f4E6mdSDo560OU50sSD7ZkbYfD7kCBSXCeRW1BjzeYsvZEryK0m/MaZAv36ygZAthx3SzNf+caB6xJ4G9enx4x8=
  template:
    metadata:
      name: pgo-s3-creds
      namespace: nextcloud
    type: Opaque
