---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-postgres-user-nextcloud
  namespace: nextcloud
spec:
  encryptedData:
    password: AgCTL/x8/NlBOOC1o+z3SnIE1nKIq/6YK9+SQqh225HdcvQcKdrdiISzAeL5uqc0BK039EZt7eqCEU0igeY76nXIlEhy/wldpQB3usL6jfCdh5VQHCEvJzIKUgTrdwfbMD/P8cZMjAsEA1twfEvfG+6eobdVRggssaQezTH+IQJrmkWI/R46sylz44KnueLwIZ4tPyeQdrRA3oY2Rw1hJWdVAKfCXsirZpDhwjSXysTzGXHQGiPIzYojkHKPWAC70kQ5XnAsCLEmtwN1sSnfEdFNIFPNjnc4NrvoZJ3fKCA5uHMrh86YSySYlIj8r0YEorbcqEmym3kBsd6UQXiKu/Xeip8AEl35JcmI9iYRp6Pd9O8fXfeRFh5Og807M/BzKWxZNhtvjsHZ0gqwGwW7o/NgAHChpAbkrw6I4py1lvb/QQYoje18iT8jbW5U9eoPiffxovL7t1l+bLrNypZONVHlLUEzqnFr/Uqv40TboWGnyLihB9MoskiLCRdnBT1oFH0sa+rGRWTXCkjIl1gDt3NSYDVwY0rI6VtlW4D0djVpyBv3Nd5YDR4kOycXVLpIdZ9I3ofZ2ZORo7myKRYMeCNP0T7hxcVFLq+FHoo9DfTl0JoRq19ZtMhjEVy5bXEicYojQWb5BTQEvGNb18/NTG6+QIg7uv4GZ44f5Ak37ax3jExhI88NVL9Q8gaas4aMST4jdAGOLaG7b7TAONvYqGb8US8WzA==
    username: AgAR8HUOh1zWaWQ/tA8fNueeA6RSMF0MVe6O7oQdSNo9qDwX8o0V/AnTXCDqHYfNSxP2vPmh/FgCVsWtUlj/5ZOKUxC6Gb44upRJNZCTDMwd/ylv52k33HRdHKkAEwzVuDtOfjw8CYJvRoNZcaH7T1YwSh6dS85YHCCfGZL6ocpPwfnstzSFDYJ55hY8s2ASTMEdfF8Y6oxF/5j5V4Z/FARoE3UmgCfE8JcuSxyr6ZmdZIzssRH2JIdaQ29yKosPk9nE8t+G0SlSOQ/JTYqgqbCYhxVSxh6moUwYbDpMRUKLa7kc4ia8wzrZTiiRPlkbCMIsVEW3yBQRLwUiQeMaoXpSBuIlBYUlvSWfELp0Idgy5ngND93YjGXbhczTNZhTp7dySNYFs7TjLRj6uBDN1gV4mbTZ00tGBzJNtf+CG5I0NE5NJgcV3eovbdp6BiumYulx0qowKcFRxqjum8eKlHd1VASU69ltbz+fWy1B/WBcmfoZc5MCw/A45RROlIVhsNvwsFBjqYPuQoHPI2Cv3ZrYqDPJZisBDTWReJ8xA33+Umyc9rrpVjD4LMt2efYd9k85C/CRt8vcHwygUzPrynmP+WbMLi3jq3+HVKqr0z95LAzY66OAAxqxZmx4RuR2vLCmvPiQQl35VqatJgFxkAiwqe2APty6EAYmDOOmC3kAYziiQ7yXf3IKAWuXPr/TwFn1eiw+GR2lNys=
  template:
    metadata:
      name: nextcloud-postgres-user-nextcloud
      namespace: nextcloud
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: nextcloud
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCPDX5ukGKGn0cwMWDzE/3Not4Ul/gnlF7+ivTyPkoNzW+FFVEswBBt1vRH6KEiABC2YA84TWQmZRwG2pWVaGl7RmjA3etOjksao8CYCAN872DYZK7BjNM6QWQM3CiLP4bg3VnDl08QdqKGm9u04DToOrBI3q2GRrqRrBu5lZZaZ9rwFqk4+/Uj0vJkSj1CtaFvk64NIZZGyclpLLfUpyBzYAiEj/f5jXJetbBQfKHXwVswYvv0JHk2HTqPGDu/3TORMqP8hXwLmMJ9kqE28YeNSayDyR9UMVhWJh1nhrrOTfZtVqU5j86yswjkM3Ovd7hQ1NNwLN/OAoeAFhO1nl4VNvZ/MPosObgdDw8cJks0MYq0sNa1kAZ8tU3MClu3VP+kR+iIUrHCfVJxKbWptPNWH5Y49ptY7Fh0a+HfC6UHrnABNCpSzZQUqnBuoe/cqcvLOLiDxYEb3YecQKjiFQwg+YR9dgd09eo4dfMCuy7bj1KJm+vlrZR3ROcE3PKBF/OZuCN2bj5ef1xCw1FBIdvob3ibS+sfunMWIyUArC0ig0cqwODNOhNXeZLp5RJaTA1aA4hmgVBjg7zwcZq1R+/DlSVBmhlLQ9NZNYmQnk5ag4GQl9XXAVcuQLvo9pJJ05nSNLLHntW5cRIZmV2Ou48rR7cLZgLhw5b0Dkg2kV+zz1sj5v+5Q/aMJMCvMulbSLvchxp8sA2P+yV7ONAGtHdHB5R98PX04tVy
    ACCESS_SECRET_KEY: AgBX3jhpKue+PTL7Xb40gpzqYl6UkG1SUti9zoAQH8U3T6OsAk6qcmMsUeH4RMUiqaWqX5D2Ysn0B2Qfoej0f76fy4VwsG5pi/Bs01gkL15Oba3OBCJuaMPAAEszVeVezAYxcFZhnvn5pUzg0DimcZPvImxAS0e8DPerIPfb3ya4V2p2SCmBdI4SE5Le7t4TY79NqsBwj2sdmFmSwu31j9XyCa5JhpZ1C4ZYipcha3dgiAkW3kJUhUAGjl+zN1DRJXofErQq6kxUp/PtfQNWimR7jeEWZW2stR2Hw5J2O8OkLdDsaNQ06JdA+AVCI+c7rsJHR5Jv9MszRb4wyvSWD0HqNIXgoOERbKa9vnPwPhq4g4BWKSVLcj0vLrmtNbJsJc5ykegj+u2S1RjcLnbidl+eWXGAqBbdJnPJXdsBDRomDWhDjPJYIqkIsblhRYE8vJGTITNpmDmNZjSKO7Gi5hdPThnInwC8XDi2Tn4wAS4BS6B14v2eKNA74Q6FPR4rFOQCTV08RyQxv8zyO0BYDelnUWVXAgdhQzi6oDuH0ga4SW2WAqKp6dBA+Nh5JoWDZqsaGe9Hj/slLw9yQhfIMRPFhBlOrzz9HEiUNdm5D+ZarFufEofaMRZSICgvLIigUbt3FsoVQ8TZf1Mglhwa5iyF7u1L9vLpjg0RpdbI4t97CHeXr7q2u0p7l16PIiaT5zC83sMdnmWWyhI65DGNzSxSdFVLdmpOOmrbT3GkBFYC
  template:
    metadata:
      name: backblaze-creds
      namespace: nextcloud
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgo-s3-creds
  namespace: nextcloud
spec:
  encryptedData:
    s3.conf: AgALiCD97Zzz2HwR4gTkEW0iPFyyX9LjVvGAZ0BEhTifpAycTl4NIveEwPyQOSQmMMD/+hYjsn9sJnGL8TWdKHbSOE1QdobWnI9jBPgh+oHwOishPlGTvy49Bg+8YR4bQy2tKnNyouWNo4wNY450RFYxWeST9O1myf8ObYQmulTEV0O+ArGgDpxEXKT5k1PWml7WuSTRPBUbotI9eO1E49ur+EY/8yuNtNJq00jpSW+hBY9UbTj153A5WDjRfFRWnCuzBJ0UgVYgwTMDkw9QTsiz8AYiU8dCrE+2vIDDdjk5huN0H981UP7T/OQhKMwqF6acnqN+QCg0DW6+khNs8c+kzaoD7l4CMR5ar/aAI7clvk2OLjU9VgYQ8qNhgVN70WSHqa/JHhzeU0TwXMQKkGi0bXpc1EtBsSF+WjlHQ8M805e5g499Ru4hyzIhmi7WUMcT4voxK1HOFO7gf9aQ/i+6nstKxzMYXZqX4Cf9uuixRAgRGaQm33/IZGewvIA7ikh5EAwpRHUbz1NP2XXH3dAc1frHKYxaucSpEiXQI4GGdrdI4+chMMxCGlEiiFeysaaWTz0B/GbHHW4sq52Bz4Og+v0VAbfMETX29JSbxto+gg/T8CDB0DPpOPtQXyV9960Ww9okabi5lyY0Q28ZMhoR7UkN3mtzHxWginVGvFFSgoBa8/SShUHtnAybjRVX1cWPwjoc/tZybRoQJkRpvCjqEgy2VrdYqp7+xTR8XgxSlKdWxIK7HD2uNQEgUSbSR10D6a5ahgGrWed4Mq1Q5t5mwcWbTn4vRTxZEb4f9hwMGrSg0S2+3DYitQ/gU9W3/eaLF2s=
  template:
    metadata:
      name: pgo-s3-creds
      namespace: nextcloud
    type: Opaque
