---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-postgres-user-nextcloud
  namespace: nextcloud
spec:
  encryptedData:
    password: AgCalSykUQPAqPxti0qOwhkgMs3PY/+hXK6BChWWfbYlf9cCl8PHIS1PVu4T/ifrb53HVI9ChnZ2bg1N4z4bI8rEJMlHbmPlmtVumQK0q1CELcpGbmqUFn7FsgImy16hBMVUIO/wtlI2rYuWtMMj7MNaHoLG3FsykV7y+sb/PG4tzC2T8vISBvLFp5zAoiOXwzsCVISb12Ofctht8HyAuMd+vwHIvSSPLQoPNKMFLDbalg66Tg1NfsPSJuPzsspdW7l79TqL1Lpa615IylO3IZMyDFsOth4Hv/4nmbSZUytxD5suFofeWcztchJ3Ko1j3T9HmmUufLuRS6BWDW6T1LDTtrL92wjuouqe47vavKXRHzb/jn4TwgLVnQclUYxiX0sNZbdCUY2LXTKJXovZwTeWsmAjY/QGAt2FyzztUEyiJYUFY/iO5gd/YQ2aoO9qW1s8tMkK2gw9sEvsp17JvtGT9hT/VeB8lSBHjsCG10eiP8+wCE4zYAedqC3T1cxAKw+CHZ2UThGEtNh2cW2Rbqc7NY5jZ/Uxg67VK3tfdjNjW+tyydTGYG7fl4+1D/vVPKi+TuHimRnqJyppwb7FNxv7KBEn7NuoHAPN9LU+irdSYkH4pEbslewsSym3AEZo/Y+nMEGK+axHA4r04E6CWBO0S5l96UuTT3V8kdFaqwFtEezlu0T3KzoSYlPOvmshAfJVc50UE/Djo8WGwaWZzu4cVyp8Gg==
    username: AgAuUtNKRXtnI4tG+pVE0HiH3uNHQYb4HPkmYtt0veop1guKYOuvkP9OG0TbFUXpVYg2njr1x9i1dfv/Xa3GqGXSJwDVHaToVIa3wMGwk6kgnc+O3udsLhEIdHKDlz+BGTl2tBfR/yL3QslbpU2Y2MBwL+F/fGXctrTcGqSS3Gl/ovmNJQhECRhVBFvOtk0pF4kHU4H3FrWVH1qeRXf0qhGsshoQfUICf3i60bn/ROhhQbZJ6N+1OlNtV2syfojObDibyGymjCpG3Rm5NyyG9ybrNC6DrrTaM35XMStGO9BWBJLNd0tBhLibUGJGApsYKEImtEV7NCH8ED6OKRpGMFKxx59OIzmauju1Yg2vFWsqGb7fP6a2qjhqvxK8bNznnUYVSWM58QxXpP8iP3LSa25HgWCC+l+eQScxCzXPz0/cj55B0rdbhJdEJZDX7c49Fh2pDaAJbe85xWExxM6VWORxuHNxydrGLBLZUm5ie3AvudOuMNOKR8vRDmzxZLp7ER7Af/pJ4m09JG36Wv416QOFyrHMlC2aWww9h4t5Ffvkpwi0EzAQ5J4Dvt1izNve0aW9cSC1nBm3TT3+N48gQguwPRHeb9+WB1qd/ZFKkHwy6Wz88Lu5Tk8tF39nrWgKeIu7ICwj5QDkLJJTDCUh2E/nVDchInbfbnTZg7/WkT6BxUxXXUGjGFmMKD+lTXTN43buyyThPnoyC+Q=
  template:
    metadata:
      name: nextcloud-postgres-user-nextcloud
      namespace: nextcloud
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: nextcloud
spec:
  encryptedData:
    ACCESS_KEY_ID: AgDMlIGez6Fpzh77lQmsxSWMz3vpE7XW6Sl3uWfivSf+ZxFyNDbcukajcI41HLIScsZPdxwkBwmit+0r4rQagDumMjm3f8M1eOzPsb7B8hifki9oXHq1gEPlZVqQNaXHkVOhh72gMYKXRuWR1tU4UJbv2NGizoBbTEdug/NsBbcgVxoiMFUl8fjJE17qvcyK6NZAK6NQn/WJkxa6sV+cjtGN+PKBrL9W6y2L01iN2ziq8oOCukjht6vV8ypeJJylwsdzuQqAkBiw1ZT9MJpulKXeqm8Sv84fxZDU8vME3q/dzPMpHgWIWbcdlFxVTD+gPMpDRK/eSKXIalp28NRGhEeNSp8RX1qM+sdJM2BZqvlX3Kam2YQYY0789c3x7uuTfzz1iobYzPVlYUc2PGNVGctz8ZNGREvUE6sODyBmlrNI8WaQ3Fa2ICEN/cymyJlcZtzub3GQsY4Jprq30cFmMv0UlH6noezEjA6iPM69mxgH52fxu6TBpHPUe+39KOHnF8LOwcN+TDxCeTP1K6WzI3DusNRyomUr2kaBABPAx1rK13IL7/LNgUo8B8s7oDuDIcrwKJOAHypgWoTT7AbqDqcSobwSW9uWVJw59j+dajbp3QFkngxNUpGMHeI6nvsuTN3LriMf3igPQaa0ufKgNEUkH9K0PfTtwJtBVbR3ZfTGO/ycgcPlnqQOzk6ccr6dCNZJhYF7XJpbQWceILX4lIx6xSw7YI4uQ0gJ
    ACCESS_SECRET_KEY: AgDIwFUQToUdXvp7Dh9PIeZgMwfqABLmjyWCpeZljrEXCs3BT5uhrqF/U9Oil/m5CGJzgnwHxUSDB0E/+zO/Pq9XIiQ8MqjcckKNXJohwnp4PX9DET4NnRt3bX75aBR+89/pxbw+Ayn4eIZDnWExa1p2ELx5gxkjQ7CoAgMBFkLJR/cn5oaqhSmjC/1mowQcFs3kUlqaCXw2/vN9Cwn6xo0lcwANw4GVSNXCLqUrjVoKoNFLPEZokPV0bLLLSmPL0/64pM7GZ8J5V3v8u6IJjSGW+79WRj9quaxMNUKRQTgE1r61cRrWN9C2Lb5rn0VftDtvOPjH5ByUcLZfEapOfHwIuMgWH82Z+gdOS40Z+EaWczIgTjqz5uJo2s3PJFShC53ERPw6x7yCAd305RdDdcC4io/FjpH5eD0yVqyTIpSMLSa1yn55orD6IRXd+EPZ2oaXI4HBKyzohfxJca5nUO3YXMbVyfsv/1llf72DEL0y+7h+4phtaHE3lSCu2SnnqYl4W1KXxT/Fq9bQ1zsQpOGF44JjWNZWyyONVTB2j+XPIX2ADn19hSJUVzsjofMgm0MqGNsPWGAYP+UNkxJfrmD3rkSZ//0OZMl2xl/vuRHJz66FthTLxO5TEz+xHlIye4wnwLuyvwHzVw1D4FFR+tSUX24hopjVReAEAnGjKMwCfYTPLtDUrMTC2kKMdpoL98YwpudoiV6jHRzXNRLnEG6eVz+KP+GAiZ5kh7g/uKEV
  template:
    metadata:
      name: backblaze-creds
      namespace: nextcloud
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgo-s3-creds
  namespace: nextcloud
spec:
  encryptedData:
    s3.conf: AgAgIeDPYsTfqlUoi1QHSF9/1hTIWzJB+LpGrQ1kLG2bq8uHW9hxfoMXrG4lCHSM7babfXKWMeogdsSS0HoxdcpCriG3lWip9ERJZ++/65BJbgQLqzz82w4Gqe7FRHDt5S6KibMU8CASAe6qHBKI/o1joqq9VB/FR4PgqYhzGFXES9/hcIiHFVRfNpXO0ROlIX2ACnonwxQa+MnxRDm60SHsiaUx28NEwnfy97UGlhwv0ZKz/Zi9v1mEXrbFoyVu8n7Wp/bX1pmbdll4JtbX0zVwgt4JoPd8122mhLg+sZYwrvMbtxonCWitnluboUfzhWXipkpC6jizAB43jo3nlJ17oB60PFuMjCqtjt2o7L2gPplCRqMrsasvyL4kH3fFjQarYGnx8ynC6yZLBPLuW0aBWwUqweH+m6LD3cEvtLymvMoYTzOlFuyAN1V7DMc4HAg2ky/TQ6dShjP5218RBlL5oosPjsKeFzqayZfpE4gNWC4Wtw1wdQVNnBFYs8jfQ/3YnawfNSSNSXWQ0IU9jCuIEVO+EOj5V0Bix1HWC/uHZOAqQg0hYeXJykruoXzkKylJiHCDwpMvqgldQLVqUhiFCAxPWS/bR+2/JL2+8M3vByNHSz7pLdINUKwPRHwod59oB68ciEUSEH1GEPAdkpM16oNbatEhQTrFH1necOL3eHEC/XGwxOwDNpmNuU2tE9L3didtqZDsDkXg17Fw7tpkAtFcU2Lj3KLLjdyldSyUA4gnYiR8ie8V0PbqPW7+Etd3kTvtkRFLk32cgwt5RYDXpLHc/Bff5wRynY6u+h9UQECm1baaR/ZoH01K6AfcRIPRUws=
  template:
    metadata:
      name: pgo-s3-creds
      namespace: nextcloud
    type: Opaque
