---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-postgres-user-nextcloud
  namespace: nextcloud
spec:
  encryptedData:
    password: AgAhjolFKJNEfU4boIgihLAE6E2feCgPwxVZpB1chDIv8sWUbJ3KW7Ma0d6CwDKrhxy9XOCC0dGSIgY/34+Z+xEBdowaxehJCJrpVgs8Mrwq4/ZQKub15LvqelzX1Q4N+HqnRvsC4kpLp3KLsfhTO6ZR52CPgi7/o3FlPoZRgpXR5i9NE9sGT9JhidmC1lLsn8SZ8YXemZoxaInyo8fXJHp6kddD534WCkabmpvtFMQkKrv5zF5SyRsM/82NGiPOEkw3lHsmyhLpVLPI9XGFwgQcx94NhLvmVnJXgJm0b0BKhM60P0YoX/VBrCymiaHd3O5a+V1LDbHDhueH1n/m5Xixcz4ounn15B4U9JVRS9ASkOEygVa82REWigu3WynUps9GPeSy6DpaX4xe4iqWkF0h0DFeCRjQ7nYZVEjV7wmvvE9HIdDUSy1pUWpcMJDkJFPPQXmDVf2uN/vzoiJtsZW5LL27R9d7r58xzfaRPWGDc8OSnIQCa9JyXl8CSm+OWIW7w5WM7REyQG7yT58GoT0VrmURrx80FPtPF1d2iNW99Y6vhTPYg1nQyAp2zKqygbd2NNrlzAzBJ3id8/JdDGyawohFmutn7s0d5BTe9VJHQao/RI7F1ykGobhPOXc/h+7enhl119u4Yimw9oaqlJuDL5RSyhWCABmDCV68wAufMfjEj2Np6oHy6MuVM0vLigGf66+1sgRvsvc31Qq79OBDV1RTlg==
    username: AgBI4eobn2PNh2dBQC8lEch3NZ1Ac3l6ar+/sMCnnjQP4rOykl7kzrlu3Mvr0bU6shP8jyAxAFeHryruGQKQOZ+SAbEA5W21ZPtOCP2noWuLIDmiXy7ZWrI9kbjGssCX8u/fxKcibLvtlvM9r1v2aPLUH6ne67urtYPtnlPxP9jm09FTwCHlbYhvfVWE0bBsoFH3KW91RVV7uI9QFRS+rx7GE8B/PWuH9AlA7UTZ3w9BDnEg6z4KgzkLHIdVDwmBFkanIT/Yb4/qrawNAwJrIHcTiYcmfJjOm4IH2Row5i3wI2fssILWG4obzQO8EDYv63VP0LDWTqP0OdLnZCZLLzokuFjUZodmV6vBuRj1aAY+oUY9wF2upCUkEcxhHpeBNvpIATOjfmqjxHsobFSC6r+NVgSsuXQFAl6mM/0qTgx8anEh87TY9eIEE5zTpOntx3JRPbOzz/L/nj4GQK9nz4H9HBWp91q9TpCDWvYghCkxUzpwLToDYt/4YTDj1rZV5a5ala2pqHuh8zT0wK9SRPMf8rQWFHw6aND0GaA/8lP8rUl4cmh6iGomv68Dwj3oTnCSIJsm6Ov+1RQM5Aeaq72ndjwAlhim7Onfp106tAJ1loawPzgI124dslHpBhgMIms1niw8TZQam7Ajx6LEa5ioAQIKrJxgLsvOdK+XWaP9Br5htM4AcXJB1jdNxJBWYZvqxu3mrXl5POo=
  template:
    metadata:
      name: nextcloud-postgres-user-nextcloud
      namespace: nextcloud
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: nextcloud
spec:
  encryptedData:
    ACCESS_KEY_ID: AgA0xjf9JROf3DmdYZBifuv+pWbmWS58LS0z0MrSPm7FR0M8W9UdWd8o0+mrPGZPlMVKvc6sxlIfwBXNdcqeVniUgJ3DpSg1mieT24ZxyAzVy5SqX+FVDeV21tA5+l8A4hvTZrYQwZQsQxxkYLvSYj4SIWDuU2n4G3ksGtGbr2IrAG8qtBgLbfv2Ajp4hZDa21egC7ayMUOt4R5MSxAxc8t2lF7htOLfvDm2yUNCODedYENp/2fNm4sj9MOJkcOFj4Ot05k9TmYND/zVG5mKVrKXFLrkTb/eu7o1qpP01b3b3BRA8AUB4wxDuRCBEu9OofDXGGQDnOIoPi6+5G6UyOhTmFBcg0p0B8zotQ4EK1YPZEgapGwJKVGpvtTzHZI3VPjvWgrdZo5q7MrW8qVCt0+EGfPqReZxQ7Yw5RPd0Bx/+NRa8xBb6zXrTeD8K5kR4Dt9MUQJ6sWJmX0/NAy5Bs1REYOn7c5TTmkniea9SdRELOWEW3cA2vMrDBttUxLJUC0TBqQkd7lSjYNJAYDRSoXD7flKp3S3V6JYA5zK5ymSRkjx9zG7bhSUlKoyza75y3uGytvNuFQMIouSsMaRE4L9y5RTCcZGVNDRQu6YuPm5Xrq2iXfg1YYYD1YVhOnn0xvg5IMNgOdW8toRH29YIyfHhoSX3maGtM4HotJzgwdA8IXGKyRaHG3rUkWVRcRsu05TImaQDDI39jh/doNZwL2sN4Aw2/G+37p+
    ACCESS_SECRET_KEY: AgClpuESVc2cjRlyytfOKdZAYa8VWlhVxqOX5e/MDmir2JktBgP4COhd22QtFpgdY+MQN5UwstEu4cngtmaW9iGpJ1YT2fK8/vzKQyDBuYD241hvoYhy5OisJjvaOORlp5T50fI7fB1Zd8ulThViWdqPzG/pkWsHxEVu0iX6+ZpPisaumGkx5H+eA9VO8kUwi7N+mRAH491kN7Az7QXP1N+OtVrOMFcTXPzhT53ProgGHI9ok0y+Z5FNMeQpPqs1IlkV0kbtHJ8f39xoNYrk3zPNS47QlS5VE/JZdy+zBj5zp9xHfo3X+jW7vzQN7tuHXSSfxRHd+G8PjAlb+261xTFsznLH9ENXqzPwjXd1j26BrIBv1+GQcUQM8zLQjlbINj3sOye9EJSO4bfQQOTbijUKfPSAMygRMcwgdZUsD6aQpkZR/UZkTUjCU/EvubEtLCsMTPtkC3Y9i6ekICPqBodAeipYMfgf+OXIWKyIYw91TlcSBTC3hub3CU5JG6oQoUdxWFxOLu1+elEq6ruIJuO8Kse/bFPieURksH/Q1coDpBIONYjbLh4czQ/HWTlZG1RdRi1Pkywqw+1tkJuNph1IMMzcwnTLm6QI7S6V+WsbIhvwLAOGaa8w7AqO775m2Ktm/0lTSO54XQoQGweHF8czk4NuL6yRWuQTf9nkijrm/9gH5/5p9fUtSKmZcZxIDBgQL4/Fkf1M6iqVXkElyed0EdB78+9H1La1pgmvx+uu
  template:
    metadata:
      name: backblaze-creds
      namespace: nextcloud
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgo-s3-creds
  namespace: nextcloud
spec:
  encryptedData:
    s3.conf: AgAT/E6jvPerY2sNn4YPH86XFldnvXNnQZG2ldRIIVPmy+BtUdJQXf8wLcWZEHuEW1KfA0yAyw0agoCLiDqRtF004HtnZ3SboB6yotnd0geTWKp4t3vYGHJ9RE1jt/p0sVCZpdF14cmK7oF/cm3tg9IkyGjV64mCNJuN4xe3gfFSes8FiDazCt0Zj+EJR767LIC+JC62dYlhHDI3M+gW/89Fb5+lBlylYGr3yPSzO/tgNU5/28NZQePSPe2EZlxOxnFuKLhJb/jG4GAeMVXqCmVtzV5sTHNB6eUtHrklOz5Ziwop2aLq0qOlCNt25gRO71LgwpqWyzvhs/8NuozcICKbJTTDmuJQzLU7uu6z/Ht38QbAtAoNYp+7xu2fGj5/+vpzWF/CWPSNn+VjHFqjrOv4X3T2cpYKZRmMBz0uh2s1KaWq+fn1lIW4SJQXXTO/JO5zokeJpD2GwJNdbwheaL2wXEf7TZIykBOkuc09y/8QkHRiYJXnCQD7RysNA9Vwz8UIu3BNLuDYwHs7WcN69+lm3z5eek8Ul+qHoL7Jqw6snRqz31OPgwV19NKEGwTU21Qp41axpO+DQc+riuxVT4ZtO5R3Uo9i4DQ58eUz6WNwWJVeZIRncQAYrSexeRPfpEVdFFPtxzJAWk1jKVIWWLZZnP6LQM+vexsCqKbWQCGroKHjhIZz0jNnJQRXQMBSpw/EkMeatWyGT/GgJvYyrpXEQr9/sERDvvNnPfS9rQB1rTC8eoDUzBnye0yGx1RzlTA7lr8LZihpQLFiep7I8xowAiecN8TLqeklqCp3hswINCSS4ibfEztVLt70CXXrYSx7nLM=
  template:
    metadata:
      name: pgo-s3-creds
      namespace: nextcloud
    type: Opaque
