---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-postgres-user-nextcloud
  namespace: nextcloud
spec:
  encryptedData:
    password: AgBEBgxzCOO5fQsFWXjeSrGgD6QmgY7SMzk8Fzv4xcLVT/kcbNjVVcQEJL2HxY0BQdHlZvVnitawVcT1GCs7ZAj/64r0weCneMLevcSXdPz3Wyrx3yoZaEbr+XuBG8oBL0LR/bnZ5L/Zd8OwpSRpZHAO761u72RqOTvM2uz7uabQ0y04GqSygDvXW0FBidr5bsimAkRHiBIOrduATMSUnYH61HXWl0H89354sKSy4NxiW4/dfgli4WEXf+1a94m8d4DqY64s6m25bgYlI/xLBNbXC9H7yJ+a9GmQ58pidvmzeGSmyb1RsThzKP7SZvJMCsmpH8jBGOPyWZnBM/XBOr9Q3NCMT3D9cqLn6Tfs2MSfsMRpnzwWN5RRl9Z/LsegdgY/SzSzFVVAxcVmFinEOUGILLc/AN0v7PnWfeSyw5IvSIwAbvsoGyBagCmZGNITrSY1DQeaaM0f0BwlBDtsTZhofgzx2jdng4jp6t5Po/oxfi+9XRDZEbDYlJVajOR9MnlZyp/FHyeA1eXy7wVBQeItLigpf7yjyb5RcTSxq2jjDh4euCW4ax/ci74ZzsbAr1rS7wApwVInq7EjeWAQojc0DNep1RVL7g0I6m8PMWlOoKCa15129eDNNJtPn07YDtQgZRYYVfwYUVfA/0EdBks+NbRPNf5IjP9RJu+mdftBHzh6eaVuKFv/pq/7aaknj/2cJ9Gd3bCNwlFFA+Xb3aSGgKpAjQ==
    username: AgCw/7nFrErUVZeQoIw2+bVT+JCELSeohsM7ziw4Lw8VU8jtdbhXfWc0YOGYcbQMcmeeug4iHp5O/VusQLW5LQERf8bG2pEPK38tDU/MhD/F3ZFaGEOgcUf/oJncGgeLhpsYO3pAEf2Is/wUjK1K5/HTQYPFAbhl0lpqQ7pk8pD3/KtQVZRqL6/5iC873Y8TEvHbhQ6tPTJqBwgfUcK/h2tUmx818MNzuuhE7nKd/FjxTvldeaCYQXEyMoo+4/l6nZrcBD/snG6jLkuetWqtPTlTGvVJjWNlwI3cysQV+E+M0pT/gke8CIbfzshNESBaoDQQGWYSuW4urif/tM3dPcUFSPwAMg5Z9xygCNn5rDrF05FxiChBVZl4l83bWeO0XBwPNKyFvglX2/SSdNDWDqEiLmEfqlOSLdlIvZwNPprOOPpa2ZxbFOWp0lRTZsniEX3aZC4el4se84mQRgqmlujsFjVJ+rDa5zSVXbh4kn0XIVzD1/A8tSFCZ7eUeHus6tfRj/nS5QGyFBi12rzIVWcv32VrG01gIjsuR4XSh8jiKEAA3FsXHvufIR7SX0NbtmtLJbTpgJhq3oJ9r8CPnRAZNmGagGBGkRHHduOb3IQjda4O87s03TTe+DvFgIL2ufzAWzqHrLH9QPyH4sPQF9Zzg2c0URXHl9Z41eu2r1n4hz1MabeyJGAxHJYaX+3dz82Z3ppi/IG1Ig0=
  template:
    metadata:
      name: nextcloud-postgres-user-nextcloud
      namespace: nextcloud
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: nextcloud
spec:
  encryptedData:
    ACCESS_KEY_ID: AgDI7FBlvG0eLGlSx5lF57ABl7qcTCbXXjAu/sVX7urhD6Ous+WdhkRDsI8L5Wasy4BEhmRWDidNZj3dPXpXG2g/uvE+kqZiNjmPQnxXMtnrTd8kAatItwnptaXUsJmX5zuNbjj4rnvNNt4673B/YeLT4eGaEEb5PBcZymHViW43+FtVylMpozqduwiWwkFHFwPvfWkPkD1UbtkWF/kysknI3D8/rtz9mTbyMcqp9yeHXPQpQ1x654eJhFPHbjHwYg0BHu+vg2710pa1HWHwxaCkUS868ZBMHUXC5wC9JP/OPnKM2Q0xNyr4Rv1impCTXwJhC18LV7bvnmeKdlxIEbXtCZXjrhl0T7XTgjF1dpco4UtYv8NW92QeX1VQLGcZHo/oiBGv72dH9+jFzYHGtm8nglD1p2ThsC4zSfMuO6SBqARNeKHGIdvg4pkTgCb3zF27crOmz2W+alnQBq2AOQm3b9BMHscvakqYAfEj/UrFecEWNnLkHa2pRSjFCQUqzKY0+74YK8sFGtkllzWvCHTdl3q3Tz87nfLUQkzepRCc6v4s+zSOcSCEtvLKVvCeuW5/kToUbI3lQkjidodLlS3WfRtrbLwOYBVGb+JvdfiyQEyn8eD7j1IXvyb7ce63AKPvI+m52GdWbj5ja4hZWaiv1G0IruDn/J2goJMnzwgACTvLw2KAwcZiEaMTKnu0plyI7qu7wxJKamAEQ+ATQM9HO/fxPdAObkKf
    ACCESS_SECRET_KEY: AgBrd1wWcDLOrZvWBDaYLIjOUlo8J+u3InYV+pEQ5gyrs8DiQCD/Q1Wtez7taeSjBHCmn+56AJ2mBbBmFVgQgHTwSQMBkCri5nIMgTqYRmn9+ZiR7PPDabyR9WVtGa3GbhrJjeoG5GW7YbGemoQkgIWzai+U0EKPNVn+A6Bx4GxVTTOK7iCuifEBX2E6W+0BbYsvgrctIEGKWDKWHaeUATP2d4bpQQEnTHbyssaaH0MVI1+BA66YgS8f0090Ei7TdyZ3Ehr0fab3tQysky0ng62zZZQ+XxJvVZXKMm4655Q2d4hcxeT/N03PInkvHmqh2+kWjPgKb19YQEVXDr5rzzZmUrV5L5SKLKBwsV9txUT5zm0XOMDnZHQe8Nmsl+jWUPmxEVnH87xoqSSrJvmSo9VMSFUuhko6WKt9Xo893PT/jSz8yoqQ7v8oszfUmCbLWJux5X1rXke3Qxt6xEkLePSiGdnvj+Db0iiCEF65rhTYANifiqQLKWlivlL9czkOm8C2zwgonsZEQXsPNVKjH/zSAgl+AWAFjycfQRBTZBhFp+3reaw94FMaXnd5VxAWO44vo3xIPcRtWllImWuQqhGlOxXjodbpDcZcffVyYrX47RD19naFedY+miF+kFvGm4DH/6yrVoiu/Et+9w4ox3L4UZc5AKuIH4VMEZ1F6tRrps5VksmcvnZ8eUrZm3U1k8QSOQIAQfx272CE+cFWwIY/HfUM8gCWOE2LKug/czfg
  template:
    metadata:
      name: backblaze-creds
      namespace: nextcloud
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgo-s3-creds
  namespace: nextcloud
spec:
  encryptedData:
    s3.conf: AgAmYdQSRIy48MBp3kOroQGcvi0SVQLswKgBu1Jypc4NNaBTnJt+glHk7KiLChzlbkCdY7fkQ55hFkvSv6EFXIUeemOTQjx9zju1UVq/MaSm6/yNLqb54yqyr0k5lGJ3bSHflxtytn3bjOksDWp4fdWBAAtuY5LDCAMA07EQaZw6miedSW6FsKTHHbZDSFZVXBIbjX4U02Ky3sr2xUKT/elNKGAoY95YpKoUPt6ZZ2E0ktYh+wGRLrweo0Gv1n4H8BZfRPZ/+McniO278CJffmQjHjWIOYL12dcX6miI4kt87s9+RmoKsrT2MYXcP+0+QhK4oSz/6i76Xk28cf+MZA00Q+Ra6IqEXsDB8binf09tCYDuzdWsPfTNChII7fv2YzW4nlXjXYkmTDDDdWJZ4zEGm5+B8TYTxxRZpWCxpzKYm9sRpwDMp24yaDZNy8QXsCcW9NbSUY02byqka4wRuFoXKivzSGhnTrRZPvKwIN1KcDSu/eQzZyG8bdSVE7Zvps14lqGntp7whivU5Qae9xlqkBeBwqrTQGkG1N85PXIX8LBuGp4+J48Pq4TtBmP664cFta57BrdR0+eRfloLLrJuPOr/bRBqfSV+sp1AU1NGttvaN7ypleYsL8tJn7AfzInf5zjtD2od/rurnv9oSIfSjOJsG6cNcWsfHI+2mlMiu3fUVO2JcGhawqambupoyTMOD4KFKzH8y15BNGezb+DaPAzmFf5n8wDGKolsDcI1DQGMvg0TwpRQ3xHHnGTMJWVchUBgpi6m+ipfTYcmnyzqEgwyAfijtKkCYU4Agz7VuWsOOg0kEu6egQRSvRBn1OOpujA=
  template:
    metadata:
      name: pgo-s3-creds
      namespace: nextcloud
    type: Opaque
