---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-postgres-user-nextcloud
  namespace: nextcloud
spec:
  encryptedData:
    password: AgBBQUj4hxnFVjuGS8GAj1aCQC3NuRTLID9G0f6lP7AoeMVT3MIYkcELLQaFQpZFR6dvCGGVUA9N4pHkNIlGYueodVGc/Vo3HVntYtCr11JwSxm+Ca/Zqpvxfaht4jSOsQ5HttnrtRBtWNE+Wblbmc0ILDWJLvz3q5tvkZuqs1KrZGHD63G3cRXFbGifyI8zYmJCl/MJX2017YAongVzqLFujvjCuLelP19/PBT9ooLL7PvyojYZNtJtQoWJQ5vN3EuaBKsTnPYVYyAM+l6HvMfIjPMrB9NtsA+ZWiMLR3tjXm8iYrMq+GLX7Iza43DgS+R/bhgx7nKlZX6i3qNZTzadY/CuVblPIbvEHnLrb1UT/W8RcLwZh0s1q9kzNuczhZRbc7Id8VSW4MFupwk34c4zVp8e9zwOyUCcfIZZLF4/7+MSDv2lYxW7inyiOzQiaFNDLhtVSeFB+1e56YBoN6G8k9umoc53v4c+aTz9ek5j6F05KNxo22bXw5nhtnavLT8XkENtQMK+xtRp3s0+VnRZLAO6QDrfCc8jBjQhR13IZU+11jig/6IZ5NY61S3mBuiq24L42h8tWjU+zAmS9VszM6NjSmbP2l1ATpDoTYLGmVyoAq93ud+1tirbVTMq+e8P/V3DqSzAf9vxvBAA5TrgYUMsWmVDgjTQV3+07aSmO/TdKBDA5mk7TepbdtKQlm5TMUcBlhalf+nrXGuciaQ/XCwdaQ==
    username: AgCWmtMJbHqaWoDieevpbTLOUdShj42PwglWAK/U2D7oum96U/MO9eY28x10uA5ha5vAIVbM6azDtE8/BQvJcOHKV4T4PGHrcKO9MnJoWKmoG1Jckvng4hWkkCaSdaAPQITyaDCSWS3tmKtdV6PqBIBYysr6sHQOoUf9OrLGrHQup04ihhxO1nqrOX5HhaUSS/kqCwI0j0+EaJ8eKhRa8BSsn0a+blwh9aa94KwKKeHA5/J6Tuz4oS92PZYbWNZZZ7GqBxU5b/pygK7LmrUuconqYzHjC7bxVZBKP3nBV8HBXmM75dEEuVGshs9KGuGE/NITNM4Z3hh7RPY0XQ+cThDPOZCf3g7sxI7wiEXbXY58WYRIN6oiKmkheadXC3qkpYGpcYp9egggkGyEZXxZMPEQAOgsG2MX1SkQr0mAJpNexO7oOu3JCcc1LLZUhjPhuASQZtNRj4z+Arl76c4XjtMLxKWi3iVS/IdPJaklw1Mco3eD0E09rLHRLMGrqiv0ZlzfZIouGFgGg21ff4tJDtsNSqVuUj5hLHQUdZOIrx7RkEfqVNSXdUAXsoTHU6i5xhO8MAsyVlpRUL8P6nTnpwN3rZuFAGC3ZgH4+UmooMtsS3aioa6SN/EjpyMuWMZJoToMl9ppM/hE/lZxhRic+2Pm8+pQQO3CKi6E88DBrkKT6jFBr+Vh5ACaKnsBOR53OakTIKh7R1U+OXI=
  template:
    metadata:
      name: nextcloud-postgres-user-nextcloud
      namespace: nextcloud
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: nextcloud
spec:
  encryptedData:
    ACCESS_KEY_ID: AgADpatoZRdxpfj4KPw3ZwVHwHuz8PZNZc4VEkefubLdkQzKqbUpvTXEit9LPee8EL+aJeUUVsWuS1yZCjsz4y738uDQQk2z2qqiHLqLWBLJY/3CkQc+EyLCQ3gUf4gTGl3gBs89Orje9uDRTY5VjYePLhQFLSf+O/3YUfWaMyGqJx8HxklmTayK8AMCaGly/1xj9xg0UeKDUeAteNzTaGeI+vPX1pkGxR/ywjnDCgXnQetZvR5opA9U2ZJ99LN6o6s7kw5swDh2C+/3QF0ZN7TlgavXquBVNzxhtFW0is87DJEZ9mkOedH280zeKdk5N/LGCYB7FCABvZ0mZFXR3iUmDU6fNS/BISYmyfVKtK3E28EFDpuTeMUpgP+D/IQchqJ85Abc0rKecfDcru6gKhFgEd9ceIM5O3Xbcy2rP0HUcq5vEOVgu2QQafr56VtXT5BIRquWtnVsNiavwe7j5jsXSzP3orxgPVuahud/4Nl7Nqyw8c6rYOfsxAwnWyjdkfFvgMgU67sgvsyFyEhLvDvPz+9zxGcekH0Zi4esKMTUVkPcrR7q4mLp6e5Iics1+2TfasdenZVi0PzbpI22H7diPyEmAIrK3OKNpPtzpVP4vx3iTCRd8VhQ844Jj8D+WRCyciwn0rE1kVrAAHVaNc+EcwvpLgTnlxkYGOLhOdv2goIjNFmXH5fMSMkE6a4Ga0iecfpBcosszoUugSIXx6fSnN+6esrfhdVO
    ACCESS_SECRET_KEY: AgB4d748cbBE6+OgmO6ZpvcIdlzRM+WlZYqvg/3OUZlmRqKuD23KRbxx0RUcdsXJfZTfLsnkqfUDi2O+zAJqatwJ5kaGi9rQOBgNZDEPAUHzUDAabKnmqqbLocCzWpZqa5VMnFCE3QtToX7TtAqYrMQekmCeoKp+w3LhAzmWoWHEie7EU0OG9VdioiMnDK0vC1r5prbsTupKzgQymtkwzmU3qcZmhOomhn+JDoAnJRtD+fRZlTUdLG3EqfE6TQ+tvP1yBl/ezzy0GeEniZ+AL/4OOfAeY8NUMJIdtrxVMkpiBA8PuW9gg6cgDmXMh0sGisaD+TTuwx2y5CkgmqnDdBL4K/bom8Katfh9adCbSScuGNIfiumlbjYDhd7j6Kv3MNtrCbODxzGb2m1x0t3uSJcdiBFQyibaImy9P2/5kN9OnsBE/4uitQJuuaxI1MOFfZCQN30jPIJgjXvu+aHEGdB+AwmgAIngoZrERqnuL/AmWD6JubPoOK3Owj/XD+cl+tOYXmF+k24KYCr7D/YwSySOFAZASRwY2WnuR5LtTxjfSkc156VUSVFq9QrCvxCMfYqU4Yal8srGPmQDkyFEdzMypYYhM/ehd7dAAV5ll/6PWfMUgWeEpvT/nT8lt25nBOkm7G9cZvf0y53jYKewMyhex3r3b7djLl2lltJaAGfKDz++RcC3V+xQXCaJpxzAYAyyYv9tVghH4vifbgv9RczwVJRPth0vBg+RvXSyrDDd
  template:
    metadata:
      name: backblaze-creds
      namespace: nextcloud
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgo-s3-creds
  namespace: nextcloud
spec:
  encryptedData:
    s3.conf: AgDLyKdKFkJXcx6NEJcb1szR+d+PgApaG2ItCbiQ5NEyuHKQ+smK1rypyk5DrRtIIVPTtY7sg54UfXwhwqOvibQWFzffBopljceyF7q4E5o5Udu4Veh6rTp+mx1K1NocF76GeBhN7Km3XhnhkcQf+0LgHtAsDmk68zimelZDCC07/JDTPIBxYG5c/Fw7/aymQ6U05orsZHtoMucDvfaBTvFEjvZCDDK1g37UQcHtg+dvaHLo17bxVA4XXhmVj/iX/ISbO0balAzn4vIegAUZxda8DwabjpEXuJejFUwHlyRGzgfSdST+QqRZfc2zK45F/LhmOM+HAYqAvG+HUg4PbHjOxTSp250FDOQanFkI1GIJL1En55z9nYu3/LApsyWH3aCTF2pj0/SzDkETpJzmgI9xeITR/Dj1wq6GKu7JELKFI6p+m9etvRSbcy/xcKpcXkrCiBlaho25kZnNXiWWBr1zXmfIY6+iv2nO+RbryMLiX+J76xzL8nC8pMXup9z9Q35qGEyU74p7nmn6YixM4dTPjugHEDpfs8ziqaXBEsihQbJA8wjJFbfJ1uiiuA+52CcvnkFTZRjxbEVSEGalflIiHijt4QXXteBzRnEJxgG5PWC/aiUCcodlZEaSbUYud7KiH413eN1vBpUdE3c8bJuFnlQUVTf1ZcfwwicQ3sK5YWi5CGTqYkUNlft+ZBPpDgWkiTKo/2LMhVj8PUYeQA23NELSD+ew8BIctblFsqUv6dt1F6InoAe3UujWDFdwuepW3Q4T5UJ3NGNz+Zs8b038va/l3Q2lc2bAywYq8q1ZZX7jZkfS611KlhYnV5879mmEVmU=
  template:
    metadata:
      name: pgo-s3-creds
      namespace: nextcloud
    type: Opaque
