---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-values
  namespace: immich
spec:
  encryptedData:
    values.yaml: AgCeKH5N+mwMigO/LD5OYkr1tFDpFXAF+xqBKdNu8zUcMxqeuvKKuTYT8tjaUMbTvcLXcc34eDJYUysxk6L3KQSWmPaZZTd4tiQdO4saIzO1Gj0O3ZoZo8X8LjBYH4+NZeYjpYPHdiauiSwlSSVcvdtfY7fXb76WeLxL+Gwz78cipPHM8esHGT4hp9ZyTk235JUDIrZE/bSnFfGz7u6mptKL5apPHJt45BWsVUbYY3WG40wIbIgCr6ZFCV5B1x3UrKk7X/6jvUfvtjo4mNORWDIB0p90/0/Ja4vXg86SO7/j44iLGURxJ0DX6Z03ZO+wMsIMFIvHy3LOONcH80oleinaE5igB1dNt0lTbRr2cbAYrprRFsn+r9/7qEwgr+cG94r0HEYrqmYKR+bOaWLHH+hNGrJTT6T14AJUk/8w8Hp09SqfXNGD3NhUlHoLcrrXRKHFQRSSmjmhIkcqobkXfIcNb2K2yi2sFhA8yl8LW97mG6hXLAosy4UuHOXuApTdsMGld5ntoi1LrwIfophOZBqryrmfoLqh7dd41yyK5+KJH4k5AgLXygOWRF55VoUkbEZbPiXhMYxZzkYmE47LTEeyWNert848rewpLG7gtGFVA/m30VUJBW0dKIRpkM54O3je55FtqfRDjjYGGU0B5XcwipNBFLeqjw9Cp9bJm2Va6WBZ+dY/8wFgeA6fsK9ESMlGu7OlGKh+c3uB41wfY0bir0OOlPDzq7ebFhtb0M5sCZohpgaJ1BAcBEbZNx7OdQoABiIT0Jr91hVGfhXxeMbZ6VZ6213ypd5WwPR6w9UHc9zHiwqcoYXpRz+88USrpi/sYRY8g7a8gpvTcJBzq8MUiAhH
  template:
    metadata:
      name: immich-values
      namespace: immich
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-user-immich
  namespace: immich
spec:
  encryptedData:
    password: AgARgZGTr0B6Sgq0BYLtXSh4XlXpPp7lDciknkzDfkklmZpJ6KgB5ooYDTwhLkt/LQQDfFW3Frk1R4XiDiXCa4YuXtQ4VgUByONWcqSj03crfMtxumiB2S+obYSK1xfYF8a7NmCZpvtO5twor1bPZc4CKup2QjN1xKT2ZasivkQgwOqOjaoy2jQv2kq31+Hj7BYLb7iOlK0utEw6/Q2JsMHEYyPg2hSc+fINkRkBhMhwdjWqGCOFzf11jfOeEXa/i+32YtcvZxXgnaWtltMF8ELc/ZzLL06Mk+RG7C2OUxUPZ9+McT1m+Ce8vlxviSrjLM4cDDt0xchFJ3M2TWbz+J3xPafN+CBwHkTUhVRqdhNLSmd2I/qbaYF5HcDphPb1VFgE2IQKdeC8K8b5Ya+foeAHosTUtHwFs9DG4u9cxxlCxjlnW/fKUDj5gRWcDB/yssRcbUKHY+bvPdjEwm6AGsXysZaO25ZN4wdJcxve5qOlmRdjahVTte3yMfdX4Lf91LUSvp3eYrIUaSitj85/XPvRa1MgEgs4Huc5SyJAi7J5ls350+bqUzMipOvzWiIYh1FWc+lO7axzwpgkbdwFnhNI5wIWHcPUdBWuVnfgpGYmvmPtgN+8I/2XhfVoqM4JKihWfeWdjYkZSHqsAgan49h+ESblOX4VDcv0ChfTKrpSrwA0WfIl6f6Xej87ZyRoBQmgL1SExv3i8+tAm2+qcZ7llWR4Bn/sGRs=
    username: AgC1iEPiSuYNaBPmHH3/eBEul+Nlem4PWax9ZZ2JORztps8v2ONC/PIVcQDSzSJtVnv+Y909DLeWectNH/deIHcbQJjzUHwnk/2fs+0qH5k+e/vDJKmiiJ/XbjCaqFuZMn7l7AtSquJ9ZVZQE6Z+uZecZoKcEAElVAN8U4UIvxS0GOsErGzcQ85aBWtlomPKWULeNd80YCJ4n644Dse/YTqSb/Tu0efpiXfhCAokXE38CS1Tyos0Cs5WD9WqOb2pmYltuCUFOvH/+FYxagFoLMWlR4c3Nkd1lPDRxgzfrhteGvggIy+iawmkBekb6hKouRuYzorHGDv41r3OkUAmy/5wdVWhlrighpwIOhYQ/ciejLTmeYb6KZB2b1gmaMu1HGRrVH8uubSYBXAyeIUpyxXEXI+Dru5hA9fWs3M0eRFEt7qiCOTO/GWGGQZAUl4FeSjErEmRxEHhkGw0ndcQQXZhHi6wBuQ2vy8Y2T9qa/fIOj6DftUqEVYFKniMZ7DaG7nR2tUfqNPKurRf/ilaPkCcnkWkC4nFwgMge4U8AFzeLuBogJBhZG1oSZDr+PqbMGDAZ0HMjn6bBhgLSEz1dEy+Mkw3aWuSRgAqzgcRGP44hbUdevZsVYU9i2LCtBHG1vNBvwuLSgc1OSJpOP1Dt4Ybp0RUP7kuhSTDkAf63rhsuT07kxilhwJzMHVEEMcJ0lbJc9wjuwQ=
  template:
    metadata:
      name: immich-postgres-user-immich
      namespace: immich
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: immich
spec:
  encryptedData:
    ACCESS_KEY_ID: AgA93oOjDOHkKzGK+xZqxYz++4lgfN6t8kEMmyeJJZ6z4yiGsfb9o9UrlwjmliRlTM2AVVkLcF2Rl00ygwdlUmsLRtQ9mR+9siS3cqBFuL+rgQ/Cd66MPlijCWpxBR+P5rDrYpHduiZP8JW8gmAAstQWt8d1rJh2kTtR5I25bAF0ItsMRznTeuWMn989vaXoKx6dMpwfeVAAK26wqHJEfcEPmL8EE3F4bFnTWpxGLLE2EkSnMfHeD3ZOOaUpbviVJ/4sG0Yc5d7PTXj0q0rFRyvdGKsQAgboRvkY+4EOQr6n2JW4RgWWqqPoS/X9ZoGICqdXlrOPZrzGTDSl5sKrKoA1bVjqVnPsKOMEgES1CwGjwr6/zzfAH+8CSes+oyzYU7QU9poe7qC/PIAmwO5fDnBsK8BaPWKycUbXU/OBpELFgI+HFPk61wAt0fHPWcX9YLPKJYkyw/ysZAhlsY3HygFHiRlAuGQ7monCSatqAis03TBwQzZ9PRqhKvHeLTL5RXtaaU4f0k9vpCSGTxbLlVTXKeVkRrRg9ejeWgqFKX0PCjeCnzqfzIIFEh88QjB63SxzGLggEkvoXlfo3BRUoHwiecBq1rGlbWY3gyixyqTM781xZTP45Mx/FPDf6AaHCIH16qKSSU7Yp4NDMG1nkG6RXsGpne8rH548y/6wbiz4W4hsB/jYYGqlif7xBHv8qkXr00z4fK2fhvyfP1dnkTy2AKizQS1ci3Jl
    ACCESS_SECRET_KEY: AgArVatPMXYcLBO9Sgjl7UkgKTE90svoviiLyOOs03rB+NOEc8TmKJqpcxDdrtxkYROr1YdHfg9gZQSR2rgANACf882cdKMueD2oCquPf6p7909SrDy0M58+ss4olEWQHbGzSS1tQiMO+4nTTjPBfyYErC8zkxLnui7m9pXN9h62WspNvof/VTKBS4Cx5HBRHm3/JaGD7nhrEkWDkvxD8DJ90e7tT1XNGSJDwtlrxY8IiEe+9IbzehHGKer4Lp4ZwE8UIrhmZ1yRaU7XqMNO2qC/WDmWfvO+T2QSoJNRTtNmjm4nJanmFmnepJuddkmpAzzenOFhyQZTqQJB6cjXN2zQi0m1YQoDNTLLYyagZqT8SLxSFM6peOdBWvdAxxyavDzJ9upuXekZZPDX5KCMvaC3ZXMSl9T9VinxmniVtuoyQqxGcRl5KdO312qguvBGT2r5lbGDtlODKcbDce5+6RlPxwRa7x7k1o6xo0yMgdgGfvFbgjR1ogVMb3Jyhf/CztmcA/aP4pUGVXJE8KKe5R+AllyTyrQWoHyI+S1altzZx2Y80o8PpDnmBx3skOdl81BSsJ4BhAlsTytvNlwwTUlVQ7S71MWpPmTnjcdj4yIp8PyB0pES+TMuWsA38sUqzu89z+oWz04D5r7s8Erb/qP2FgArEZV2rjwGKWWmMZ0bWmz8puJFdDdLSgc98WVrPBo5AGzbHR7UZwW6rY4do5/r0jutKvmXCwennj4/uP4Y
  template:
    metadata:
      name: backblaze-creds
      namespace: immich
    type: Opaque
