---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-values
  namespace: immich
spec:
  encryptedData:
    values.yaml: AgBsHedhpZ4TNWU109DzlXbhZuAn0lTUumwv2dbvyJIVAlE3Xk9swffBPVWxPhtKuP+pxj01UqPZPWPNYwovLp8bb0rOpQ+YHEXklSe9szMg2ss9EbVYb9ES6cuB9q9r8EZxijcUlHZymwsaIdYJy5kW5r3PaViHi6dWxmDrKnGJg2bvZo5RRoGBcEmVcB+0uwBMD16rWR2E/DRuR+v1zFBhouUO+G/0WjUMYpSVqyj40HdaBltRf8kDTgUUF9sQLw6pltO/NGw0zuTwVu4an7CH5lOTfUiEMhXh/QfkAPJ1RQJ+OhzGU0chkZWYOzDHdVUUZ6mSCdIxSrL7Xx0OHCsnDJh2XLfh1/L7w4DfHzgR7OT4BFmvPXoNMg157xzKYnTDgvTtUs6pMkSBcjbcJ4z15E/tU61wRcO/PeppVsfGZ6gyoOVH4g+BPytWvrhJ4beFj4s9er8Of+u17d5x/dChDtW89YTG0W6YeROe0DDgFaVvrpkTrLln6HGxzfGEeZSL06QrZ/wiwDC88xwolWVvVXitfqJPxFSh5uYqk5A/4caKczrUPXJdbkeYufG8PSFzrDkKRmJm+Rusr+Kk/BVpaFo4dHI3UG5rM1bfemGpm7YzxV9/3ZJF4p2W0vno/I++9gA3Ygkv8J1PHV9KgDbtqkSYoHnXreyfebvtt8L3cQAgn4L6m5mbgej6xBUinqxyNCjC9/4hcAQYnGehXgE+6M3wWcizpnFoIFM+c9jSaDlKFIqWnkLsh6t4+LaobsfXbfYtx+F6RmQgzKuz8eRP9elGZro5P71J+sKdY8SO51D0f0EagFRoTFQ5wn7ol5ARZhuBa+EK9zMnS8kd2fIgpe0F
  template:
    metadata:
      name: immich-values
      namespace: immich
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-user-immich
  namespace: immich
spec:
  encryptedData:
    password: AgBZcgHmmmRoV8t9xlOi6XIOX7mRVJdFSEqwB3HdX3PR+tAFTd0lAiEb34pxDvN8DyV8M14Emoo3ucKNIjSRjXRkteh3mxNUbSH8ZOC6qMYhYNcisguZ/dTxt8wc4FgxGWoS0pvdeXM/jV2fH80u73WxA4u1zbiZj0QsFPPVBEeF1AMuRClK1HdYyR0gCDj/B+aGqQnUdgwCihoUnUjXZxFAILYJRCWNN8ZKSSlp5Hk6KRnBD2oyX4fY8fIHls3yogWh4hk8tOKe8CQ1Dp8X8P0cY5BUkUFl6pEPeYp29xEgDH5veGUGbJINDfnoCsPZsaK+gWpjOfL8x7qXOJU4rNR7aOckjKCfznIx7IualHG2xggoZyMJSv5qRdbYHsOpRXdntULvEA3G1Oxb1DjumQ58JnJfb6zruwgBtlucYPAWPTQsPlXLSwdYCYt2KX8/s/lmMfmUvONL20IOFx+0qMKtsQnsUohlC3vi/yEHOfhLOp5MhhZPy8V/MST3YZlF73SNRBMMdmrCFbuGrdVX8vUbFz0VZqNdQb3TGXYdhuDwiNmTw6RY71iJGJ0d6dRTZ2y1HP+FmO8GkhTOXXqCTKjT8E1Id4UetebmZ/nn/8e5uEUjVIw2cL/SBE0tIxe+OKwnPRIrTWvcaVjQbkSV4oQ3wPUTGJYZsVgulWNmSga2S4xZB0kMad/I2XaxYnyHcRSTnX1Q1yGNUIndj2eUvZGvAY/q/vwXXf0=
    username: AgCEtr3RbBKBU5/Rv/cdIRHHj16fo5qlY9cBwfHxwsoC3j8+wjZr0lS+Spm1umJmwzj1fo3pRB88uQdQIOMBqY6IshpENfcMMO4X7QYidqRzq9qFSIIm8Y90dIkBpFhCnkyUi+240qRhOD4us6ZMLwE5d84/y0XHImmjgMbmRKgVZ29z0V775i36fcaa7EMb55Y/5kVy0EkxTinGGNM+yhJ67A5N6RqTYeL4ZPHu7/9/ISPCXip6Vwd/wcfZLpL0yGvIMSGhgjpwnNAXDuN55vBeZyvnK2O3IGvZ+Cd/NOUQ9dVh0EDyRugxyYAlR2OMu03Kh1gfAa5W/r2ySijJCE1W0bvoeGqHvCOMW/D2CT82ZBS3GjCIu3SbTOrJbwISzsCd1EgA8FNoxHRvekuJgTuQ/W/ORXeeB5OklJjwIMwq0fk8xtu6QSxa3nGEia56Cap2iadHTgvxc3xkuzzC5rk/VEitZN7IFzMAJjUNAIUn3dwNeKFpqCATpXoTcBW1uFexaBdgEynwRqdGFDhhaX1YszOkVXV0JJY8byrNFOvYw750VMOzxqqLK4q6JU2eiFYA2TrHkiOzpC95ldtq6Y2M+5WprDwXJ0bTiVv3RJzygMOgeJffXSBxxQtMNu5HQLWt8vnnBivz38I2bgCs2iLqDFz0zlWKADoq+X0hPjCUeYLimnoz6SRxdXYAOSXZ2W4i92RmlH0=
  template:
    metadata:
      name: immich-postgres-user-immich
      namespace: immich
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: immich
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAK8Cf6OcT/fT3srbEdIJrVlTy5lV3t758Wzhlrbhqb3ntGZ4hHk+c3xwH1iG2x/CjkA9QzRFuKWbgVfbXlPp7CKlgt9FAoqnianeliYW9MHTEg/pRxMhBzvHISAy3v9QVg1pgIlXXmedC6usM5TTDn3wgO5J+jJTm7dVZgBH8wEsz1CUn9ioBwsXMUcKuiZeAM1lz0NZTGkjRz+QPtQLqkLoOB0MoyTyjpGOR8tdMPKVxLoZGuw/Xxjc8Zkd4/IgBxv7MZT98+P8hEE4C86WNDmDNBEji73MLCmCVed4/wioOz6pEHIbNIdRCs2qNP08gKdFBdJnTKT5K+Z3P2L9OYYnSUYbdFq5sHejbX0ZszJcYLbFVko8HJodf8YwdrXCCgvVDfM/+UJNWmpmCVY6SNJThS2q3FMBODq1xeSKKDZaftpMIBEvn88F+73qQ/7j/0qnbFkUnpvS2CAepfiKX3Vg4vT8V0y/Sfv+MdCh54epYSF3CdnPEujPYQB8sxtbV90se9qOJ5yC9jCtKqTLqQST9tUT5bl1bwoI8AmwBqKHhIysWZx/KN2BW9QDWixIwA95nfDsvVFLs4Gb9XMLz3icMEH2/81cAdNGkHhhm5ePUShRKIpU43VJOstnHBj55YwuVmF5UkL878bi35ORGTLbcbIaz1Dw1DTqVUfr/TGNWjuaoAV73mETAfvxDBHjGT9PVcL8lMnw3gQaIBNWTG40ITTurHjAc9
    ACCESS_SECRET_KEY: AgC968tvG582KtjXXwFWitEMYci4aDOyWUmixwXb0Fwq9wThUg45T92D9dvm6lhDBMbO+laPUb4XZdWQZiJaFQ8ZNZOFXS5ukwqTjx2LQpJZaWAK4W8nnl308FmxqgrHGU8aFjcHQbyY/3V8eDX+oUlFs2H3T18lfuZvaYDTZfXNCMxz7RtVVl6h7h84bLz3Vllbf3x2gXQ/sAH/vgqEVDPZ3otjQozixCXuEADknwGOBtghFFL1v7oVGMDH0RwLqypIV0HG5i7ANqj0TKbpvfICbhhymtWi2RLVSz6fXpjZfAELpdf1ioQW4PSj5uR1SCeD1XxVYrkhKZr+k4d/1Fwhz1iNgu2oAGuBSto3lUrZKfGdx/6uj74XAz2c4ocwHsvPhdeOjrBVdeB8XebDK1jF6lg7JC3HprpBcV4Lxn0Kc9NozT1PNpUsjTwpPGjFwsbHt92qGe5RIRiaepRw2a4xTyy9woKVLpXX+utzpNHBL1+hFMXObVibJdW2A2/bqhzaf4cRUHTE7etThHqM3PJcFlb9U4A8HPmBXUdQzZOb11Vqgv5ncFH3F9okSDAdGqlI+z5/aIuSBYlvGY0xC7YV644GU+FwWJGHthYOz/UUvwjXAeDOtnHM+iClZW8MmWUJKMION28QbYGqtm3c/uu/s9Ai61Mk8LXVhhgLGRSmwxCbhEs5+8vR7RNEpyBkfSWdYkFRAGr1nzJXMfBFNSl4v0qYvny4mpdfGMGaaTpW
  template:
    metadata:
      name: backblaze-creds
      namespace: immich
    type: Opaque
