---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-values
  namespace: immich
spec:
  encryptedData:
    values.yaml: AgCjxGR8FoHXkd6hCNLpinAF1XccT9K5ZM/EhQtr8bxk52uCQO0VfquVmtDqRbF3rC+6KHI6Cxjh8VwfpgnR57Gs/gCuI8/xoL+WHsUMWvcOX9KNwnflRHplU+yfaz/qMx63rkKdGlYBf031WfDNDud6oXKILNX7OmD4VuxJZAhsil4XPx5r6GDw3uVRTkSHAasxfqtG4CAvt9j+ANSKJFuBkVQicTir2KoJQeGsoQrSXZA4fDOGqFPVxfuV8+eGKTAnBUh9uxX9w+Sk28aZkJukOJGkLxqtsnrf/Z5EU6SsCdqwkGZJIsOTr9sNAsjawFMd6EWP+w98VoB8IZ+yAy04QWP5UE0IciIpf02ztOmRHIjDVsDp1ThuhFYCt+nc8GCPhkLTkobTspZWHO1mxpRrtDV4FXH5suv/9LWM2Oa34Wfzs86HThg7o1bocsYNU2IRwCKXxUo1olo3Q6cguow5xkk6KTb+q4AOgNsdwnVshvKxetQndPAoDQWuQBSH2qO6R2AHe8o9bQrBPxyEI7d3GUPLAqTV9hRcc+N7D2hNd8/T6zPGn+vAHKtJ5P9ZGlcJPgb8/T7truYdK3r3UAidjLPxvYCW6gwHH06GxTyKfyN6IkC80VL/l/ISyMia3FkTfvW8rowk1NGtVSo06eaAFg/dT7TQ8bjTCbSqbb023QMIw38o9CQ1AuUHxnMw37R1yHdDFUINUgNihUijT7mdsiUxHLyWo9wGIkdPtJ2cZilYr9ikTHZLiXwiz53SXllxoy9bqAW59StH9iQDt3cNekd3nExCrg0Z2LcLKy08eujVvwd88nFQ8Yx8oGQWVLClnis1MwT+w1xUcZjjV5OiTD+e65IFsdwjtyziGQZSWHAVPEy80SLtGa+D6pQl4aiAbhRFoyemLfkwBtrO/J5Rq7J3Y7yReGzEzeGueHFJBiyukMa31aVx4Ebn9g==
  template:
    metadata:
      name: immich-values
      namespace: immich
    type: Opaque
