---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-values
  namespace: immich
spec:
  encryptedData:
    values.yaml: AgC+ZaVc3vyyBHXFPzcrysiF66TS8eTCrmBs6vRJolRcpp7ZMMJZCseINy3G6BLSjGovICGp78ZDTm/eIajte52HqLJxZeW0jNSLzvk1zCiXUN4aj/Ontf+3bo9LDaWEBqjrqa3C/XNapi/kcCMx+KexjxJVHPkrMw4bH8sZjO5UiVXKK9bBEN08nJe/L9ndnHV34je0U93tfAQ3iu26SEsUjOOaWt/RYH8IqpHwPFrMwjNWzMAUFtDYQI7izxBNC1kY9To2cUyCjvtOXSTj/Gbz8Cfxj8u3VgljIJM5o0VtDVSFIqpqcAtc6FA9wZDurJa0lW4CVCijHvwpLLHhQYsW/NmdCP8JvFvU2lGOEYf6YkpNiud0ltSkZXcRDnVUkW4AiWHoeIYw+gVE6YO9WlbC1Z0vRelnVSN8+U9VUQcD0B6YJy7SbaO0GWapRfGjEZPpYRxlWY9vOSPADebmELCOFp8NQzwDFJQF0ZiSUsF6J7LqwGYGIE3NiXdJzikp9wAL+U3POaFQTV+itgwvTKOvVIgz3rU7zSu7fhIfHiL+gMPI8V7AQTn2zvjcWokGsdrModdXBOaIitNemJupi6gCZYJ1UUkEPwFd9c7jzVVIb2b8/xP2luR/wubQ8V9WgR39JjrHf0U3t9aJJG57IQwBJBs28menHUaLUeM7A0kFmYsTvR2SslzhlLpCyR41P3prLHc9T2rMou9ah0J5Q7Yx6vxWRTtx0htRFh+7yEYWdla505G2zbVsJvLkRSOpHCjb2ag8t/8y2pe3ACP+f2mN6LeKhgEYYPPbe1w0va6j2McCOa7Yj3U2c+FUgelZvSjil/cK9xSqjhOUg7Z+LyKntUPa
  template:
    metadata:
      name: immich-values
      namespace: immich
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-user-immich
  namespace: immich
spec:
  encryptedData:
    password: AgAfLsNWqGT+nkNbOw6cO73TkSP6IdEvTZJZNm+XKmp/OXYi1Z0YO6d+a2iif0Vsf+HX7gOMqIe2oJzMi1RWipsXZWECYxSekdiGVHCSyM5/SZvOUEoQLAWAYvF0vaxBChGBndYRLRBZVr+egbUilMTfiq2CyJ8yObcGq55zEgNwCmZQcQvaPvKEDR20vs8FtrW0B5DvJxS8FOUM84SryWlwVqJd0rzUg9bULmPA5adLtoC+IAfMSCm/T8Aq9/VL3Uq1hfYHR3XJEga1HWTo2jEl2aIftW26ZQDXw+GFyHsfnbbU536rpaWb2lW10vzgzWxwEP4d17cLRutHxY+imGO5UNxPD2n3eDRmRx07BDy11lTgnk85UOXfWD3GbsgwyVVpfG2I4qPz4M8z0pVuG3KodxyquChxBCglC4tlqSWgxa1silqSfrAzo164BtuSnU6BD/fWr1YQ3I7ulHVhyc0naujwfDmEfxDiJ0sXgDAAyzkvjcEAAQMby1UYVtz1AVPnMhAdOyZbCRNHyrT5Du62CsCDEgfLQUe9MPQVA8Lstnbxcayc0fVVFjhn8ezc53A2ZakXpejkxDZndB5Xypb3prvYmWY+LbLafKDjug2Z/2cyS6sOE/bGBLP7AU+7rmaVUaDEB5Hz03Ms6oSn+z/XhavpO3dK2Pl/c0Dnp9yxOvcA2QAIGjBtEMjv6fEPdpQRABmQRkXvWkTam+k4atSBYr5l8zeMJFA=
    username: AgDLMXtE4u4O8fIPOEMIxCItJTmhACnkpdY4Przba1EDmtaI83T5jSC2JlVr8uzLKsNdSzrpazBzajbz7Vwow/S55WbWy6N+HCZQZTKP7/5wLWIkqkFhWU5PLguizTkix8aA2VVtv7KQpjzNZ/YB/evTKk0mlljrZapbIwYvvt282QgyLWeXyLgnrnGl63WwlMBF4n4NyKfbphmHyscEDXIZBiCRF7qiMFoZMMR4FlCdojHi8W8gkJmabp9HBDWazRicKsdqGC7DpYZTk/0Axl0dfW5WeUAtkkdnRDCIY6OUI7Q7T8sduhCu5XpB3ABzibEsRzBYS3rz2urqMOiq/d8QfbweACxm/0cOYgsXyDWgQDJDCO4Zmg5BUfN6zxz4OPAvb8zBTAgXUX+yn8CQtMDQ4YMr+3xN2jt17eGPmG6CKY7V9k3skamhKu4g0LBXozC0hFwj7maCI9kOI9NhQb84VCWLkYgReUjI5sAFzntquDxkTbFHGyxymEFzBtQ/NXgC5vI+CmbeoAwYg7/zJuvL/4tcE+w4A5+tXejf2ysVDoAI13vlPYhEKauVdiTaa8NoG/DP0LsGI8wshqi2vCGNkajzFVA5tSNAp3R1bEDCymV1jtw8ccp0uMERWmLdGhfWVwS3ZEDp+0ZydRORPJGhUJIugk7t0DTry2fHgrfZZ+ooDCdyAWU7PBpqfThriplds1KBk60=
  template:
    metadata:
      name: immich-postgres-user-immich
      namespace: immich
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: immich
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAjAszpiy/U0geJzECIzYKmCeg0prBblAIDVx7AryM4orpRKzhsqc2A0DvRy90RXw72Wv0Gucuug98c8YJEDYYy1YkfetcgXdOPOTGGdpiC+Qy/ZtNpLZRHhht59fu5TXRu1rKjgnWKGrOLC2xoQFsu0G3VtHPBN3X2L+GsSJ2ULBxVdonsv1vxHsjuS00SFpxH4CMYD9sRKt1zzY/AhHwMIjR4n5H/n3xkamDx7yU0whZ1w3ufc6NnJoZeV4oGzTuo2nsmu4PTkgqxYpu3NlgogSCYI5o6wKObLHm7bfGLJSxqbE/6ab4f8NHhPTjw61idLpgjzQ5EaMNhp1HpOFgPTDPfn5OE8dRcrBJcif7vRS9q0llC1sBcf3kTQntBDIeJBDjR+2hX5cC9A5rjdl3KlNlpMNhGzzTL5Z5HJlB5U7n01GkbvKfAfzUf8OQi7ZmmDbbDThZLODSy+97W8PLmmdwpjcSqBu4M0AXDhaasQJ9c1MqpuDytGkOM2cYC4aWmgC+6pYulHMZatSU9yL1kHh3ddQSgg0Y/mPHDIiysvyKGUp0Vp/56C8bf8aPJFFS3C2nFnrxycfaAPLo9N4qx5MQRQ5lvTOqNBSansY1jPo3iwUvYsoNkWr5fzRSGLPFi0otuusshOlQuO0T9xACMOc6EaOMpNDTiffnNYzZI+BV0rJ2ZseubcIrLFj0uopH4l5dVFciuojHUpHSQg4kvC/rqmfoS5vSy
    ACCESS_SECRET_KEY: AgCxt0h0SFJYnsahg9M3i4dulxoi4//HMgB/RziyW4/QXnCOhFWP1c7ATtVKnE4NvV3TefYbTanVA+Xyz9+8MUN6/IC2MDr8sSP7MOEFn3FzcS9BavScoRKPlzn6zXrXrBANxvzeyXAiK7zxaA/j3d4UsYeI1QZFWL5N5c6ESDPRcidT60qPGmGZ0q5DWiZrDgDD7Cgo/nLWS/medywg87/eZ4Af5ziRb/q9ZJwMTCE0cgOnszaCboF+NPnej5wByrKhpyhJdGKK8vG4ErBjc5m4clqEV3jNpGy35RDc/UKE3ZSeFuiANz5SBJhaVPDbGI2x/T33Y0OCyFylLtmvyrfYLVJf/jO/Yw1iny5H4BOQ5bWiLyvYZizUIbunVe8/zw+bdkB82V35fx2WQzu8NMzpuGMAZk7EOpfgM0GTnevKwW3LrmKieU/hvOljSzdGmeKlaBXOG+a6TWVwa71aawd6izXPfJIogNOfkv4CJ4QTXS4AwAYNNp1vcv1l2MmSh+oCmB/tfw1TAW3pKrHTDpp8PiChZKkE2n/5ylJDM0KXlUhJ643ITiffX6MnT8O/ks/AAtWKx8Qt2vsXfgAMFlB+ggomb4sL9TuKme6ptpBDqyG1JYPsVB+d6HbWwEDsL4KNTXtxVbIXuGl/xtL3z28RcRO8g0SfgimJTEg7qDShC2tl5OWXLF3VnHaMl6nY/y+D16yalJL3alC6loLMXhCMA+LLIdYZ9YpCdYFmQOpR
  template:
    metadata:
      name: backblaze-creds
      namespace: immich
    type: Opaque
