---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-values
  namespace: immich
spec:
  encryptedData:
    values.yaml: AgAKUxwF3I3aSKdTYR0FrCg4E16Lt1Pc/TGRV6W46PUoCjT0rfMe9MYHRp6dbvdSR2hdq/RYWKiX+GiEAhMr18pAyWvGEWsVsc3shMsFtZyuv1bdVsNH+59ymqv+IqssROH0j0myfwTX7jj7naD2ERtyhF6Rkgxwf0LdgBMQuZcZXGoVBbEVaOm2lzCBPTRMOMmWHEXvHOXdEWZZbx8k9HOdLX0uK1khlOg01TwSW+J1ibB7QcvJNGYjquV07GBW/mD9zhvIUP0n3K6hBfnUXQ+XE35wxW+fXtBmXlJJLpVrEs4Jzfgu5PlgGeyXr3huTIuWECcI4Slz5pCmIGVm00UFhC5elRhtKHnZId6ro9xVDnfTztxMBkoivGjuJfXXTS1d4Q5ZNrWPUbOPsh+ILyVzDdQtxMytAILrPEnJb0Tb5Du+CvxLKKm0orwKMIHAVdkK6olKlmx3FR/7nqksDbRfq0tNjxwde1Nd/RGUbB9WjWTfv3grD7IBcJtvRA1Eh1rTGUeLci/0txR0P5C3+JOWojt2Zcm5VczVrDnQ1+IbABUmm+bMTD5zQGsoh8L98cwa+RgRwk2KDY4qWDpFVNXaAtkRRWWEEYgPbdY4YT402v26GpNzZCu31VJkd0722WdFSQ9Upn87GHkokIFwFGN6UchaHEcNnGsYG6Xz1rboIAb5TDDRdRvDY3QIJmrKNYo9JmhAvdd4+x6ioqf5bjkqAitqHMAa3s5PrRwxmNEMGt3NuhhUXi58/90hhEfYT7zaN3aBRi1QqOKmKH3hPkMxqmhpYlBB2NrQ3ueMuEuz7sdt2TSqYIIvVnOtUNlDwNUphfAgXu4a6irh+V7un/jz5JBu
  template:
    metadata:
      name: immich-values
      namespace: immich
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-user-immich
  namespace: immich
spec:
  encryptedData:
    password: AgDIWDo45xUY8IB76Dz4OMXrK2c0A+hh2PhWFAKa9lLw05t0kPgc9m0W+z2x6tIS0giSpsKEcTVjzymCPAcoU/2EFgHm3BT2T0VMBQ4gnS2DJjWuX+IzQdKMqfLKpdCeYTPNUdpANaRoV0t+e320uIySiAAq98CwY+urCCZLafjO4+VUy03bvTw4e9eT8VAMCqfz9qrKCmBUOzC3I6o95UPjTmRzxW8CzSoUrF8miZw0yu1+Hao5UKhs88B47SuJrwa9cZROHuwpRR9EDJ239elCpPOo8X3sze6dntWQ7Aiq0MKOU5FAk9iQ+v1AkdQgt7wRSubQ00pLrGUcYuSjNKhKLjVHpev6AfUBi/vq4r5nJf+dT9z8kAuPAYiL1fXdO+dkcDh2GyLwa6Mdz2fu/0aCtl/FTNK7ZKjqHwue5nVdSy02X8FHr2SwoGcgp4DmDlmHdHSPA9qE7HYFsZNOS9MwClMDCfcsOoeld7o8jtK4jxhBth7qW2DEaGwN2fDHsYO5pTruaB9WW7GaFe2211g5ODxg+6ba/A1DOrNiibWYrEn8RVCHK2Vld2a3wvY4FTrpXmR0ogjm5TlIQef6OXkxVYYzdQdSCnpdrKy7GpKk+OdGrZbcy4/4mCSeC7/TV2NBDnToZZpV7jFfjq8IPP0BHhiYjjoTrc52WOmteZ5eaVmtlFJzbZih7cxM5/83X+hNxS/T2LFj5X0Su4hk7hLNXALpucLPapQ=
    username: AgB+HW/s33FP9/8IPRTYEMKUSdQghJdo0EY7SJK/QQqUCgCgATRrOu72oJW0ZfthTQOEJFPw1zTCn7O75aTT+ej7QYnefRDzUf+riabzVA7y5ZXKUBpJD46ndZaAEcYCribvboLj/56fBPT7wcwSqFbAUg7wQokBBO8/LdxGJjvdyw75PBzDavqEZrWVbrkDyah6aD403aPt1gVpMVRajv9o3b77IYW8FBh1hkgeLR7VOncMdaffBqE7EAHsBGDxkpcCVPx/0P3FdaVr9trJtjqjqCkI20J73vRRJfpmBhjdZYrXMxtMmdImZwNS6ZwP0GTFMXuCq7tu/rUhcYflrAr6mTJF6Py6waBFGWltS/3VqWHAwVLjGsJUja/LHUR9pUXsXSd9XQTN+R6x8mrbRHMTWzhS6wef4lpABWk1HzKcyZK53wEtemCPtMvOIt+ziWZ/h7XxTjIfp4YkFfK/4S6k/JFgdpgjkd1IQ5KU6mXJIyH8mw7dkBaIcLQ2+qKUO5Y8R7jkH+tcfwuam8r8E0PNNhFOT4LcU3sP6Qdcvm0PD8FFp4rkzmwC3uzZlcDBNc3MYJL3QRK5zhPYFEGcGzjZYUDDMdELqmpWZe1wbiUbTGFRC8shK+pMRk3fWcu/NAEnyCgGEmK59XjCn/Tln4/t6iqCAv9ikadk4b/DI/WZeyRuJ7C3W0fj5fGi6qqiWPTSD+puKhE=
  template:
    metadata:
      name: immich-postgres-user-immich
      namespace: immich
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: immich
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCTKlV5joZEUHvL1nz2aQXumpdMLsD7UCQ8sVitd4DrHIUY1cDDe45VA8oKVtXbmxikZdouI2iOqlMU66ciqokM6v4ahOti1UMqbcXbs3WAnmJTHCSauQRTi+wMLO7O7sMy1SGP+MwYfoBIh5Dx4KttyEntXsRMSOdMZgpvCcqzSDrZIENAfWxxxzPf2bbwFB+7Lq45po44PHTirHjEc7niuYGXfPzPOSGyep21M6rOU9ZiU0LcL4UPzsHQAKkORqqGmeB4oDDfZVuDrP68QgXObVhx5afFqX/WOoUWyS49Omp4rNococ5IGUJyJE2w9kxya+LlgzJ2TkaiHWWNU+oVFU3gVSoePW0jJ79X60zYJ7W1DDgpcvZbs7beMiOQH32l8m//FL2ucG8Yqso0TXUzuC4F8u1zHRvy6hw7Z7x75x77VVR4078ZY0uIpGkXuiYjuM/VSkaVIKVyyzw9Kg0F+hIrdL5FLrsAzJunjk296LlKwo18g1fxyYHhxpHsP8ihyfU2MKXSVL6W35IDyREY3o1dB5IiaxBZ9VDCbXrMp1HtmNMH3gjOKXy1EJt/Ok183kTi+eTo7b88APO3QG643Yqb5JJxbWpOHypzMbJb4aCyZXz0gXRtedtO/EImOtDvISIeZ9BiXkWBieI/q7ZDAXYeAZIgxCtfcPFRzZEoyk1Qyfv7gupjgaQdRJeXFC/vrKFKQCP1WkydwGKMgUricAE0fRd515xs
    ACCESS_SECRET_KEY: AgChcfPa2bKVu4z9Dw52Aa7Q2U5atEf4A8V3Ydq2/jVhHZo5O2El6Xd/xJlUxCezPp493LSlJXC9CU7V/L4G4+C3Mn9IxvtaJOeEgz+xaHoNtac732iNrWMd/78MxicD/U1nGHv6HA5Y68xo1hZU23kfIlUin/Q6fKz9N86YZpAY1TBgcieLwSZfWzqd01bzvYgEjbCRcs4h29wfFr/07AJVdoY07mkDUPem9v6wWuo+dmEYs1P/JUvL7yxXOboTbIkZuGsG56AwLKa1ArCjUHsRweQ7h6x4/MIAS9NBp+fP6C5TWrK606v80kAgVwfdWCFoBuTS/o7WB02hqEE3jOkN0TdJ3kxzyBznuz8v9Wd9Gui1IOYmZqKsxEU6Wqr0mASeiJLBBh1jhrGbD7zTHCHhdacmzUToKgPcRaPIR7WZ/XYo0ss0SqGDncq/4PFtKCkMJomiwy7FYLScQldNz2/ZwYDeZKrKiaN37v6FipBng0aFskpkdvTLUcnnlYcaD2lmW8kq9me9wTw+8AUQSDiI2O9JCb41O2L7+PvN7gtQ3/zp3RMRao5HXK1AxvfZyTFWHSVuPAfP+iemuSjqln8C5Fi5aRMBfM8BQsKgesqvmKsOCuMk+UjJoB9MUWAVW4ESNttgdQvw+5uv3oubV94WonaPv+gqzGSov1Fo30PmThd7ahcCc5MjcZhjmt48ERtKLKr0WJQ4/IjqXBU6JQaKjbPUjVy09V/6/j441fKN
  template:
    metadata:
      name: backblaze-creds
      namespace: immich
    type: Opaque
