---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-values
  namespace: immich
spec:
  encryptedData:
    values.yaml: AgALlXtr3xIaTtA02jiLVbdCwSWfaFG3ErIjwCMI5zPgJ1ibjPrwL9/RV1g8kH+HuK1ugWQi3xKAaiZzn92vvfLJf9mA4HbOqT8snEMYQx8tdCeh8UAag0iWJ4aaf8fGTCwL7ORU+K5Sqcv6IeNShmMpFS5jNtBHEhwj2NeuqCGl4L75jIE370sPBqbHF3gE1ZK2hQ36Z/7rFG2aUp3jfvc7VuL8FHs4nQoi1fmEYo3xWEy8AZaIs7DuX3Fo38MQezH+hm8tDUaKWjb+l3j2bKFHNHAWemo9o6TaJAVfaW5XGo27T1sRyJRpnQF773F7YWqaeAWHFwT3c/IqDlv7S/7SWlsq30u5cWTyWDG8MuHglwcVeK5jSGJr2CGDiVR3EepukErSnsLlmLe6ZZ9zlphe1ZdQijw49d9dE3VWXEEBZfoJUJEUIfjzccgc+hAUU4Rjy01FMjSRn5XmjkChXySCbspxx//GOXBP4xVwxQorTAqWRH1umSuAToitN5dB4eW9z2INV4SoPRFFVyYlXEXr7dpJ80NxPS87kDJ7zHOZKvGqPRG4UDkPuoFY2z+cG5TJhVGLafQLBiwNN8rfQEMxd9xEyc3oDYCzptv/XFm4u+IQedrZJ287XevRBNOcHn6jg8qPI2h1ZoK7L4y9dedzpDyFgdKzmgQIGCw0yc+FtMWoQUXTLHLpXhvoZSR6K1kg4IcJNmi52Klj+7a1k7RqphL4FdfeqhqkUNDCthOKVIVJXnZaDV+Pq2mT0uTDqv4mZn8FPs7ghe50K+mG7fCqY3qwbJSJ0esVWq3UUc5KiXaIXqd5Pp84i2Q2PuaaOCSrF+L039PVPXnbqYzpsYC4MrF2
  template:
    metadata:
      name: immich-values
      namespace: immich
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-user-immich
  namespace: immich
spec:
  encryptedData:
    password: AgART5axnvbqCMLvW9L5zXhvfDhoe9CmRL4XjBeC8KTnlMx9as465RtObf5GMPKpmWJSAa9o33iIRkP6om5B9jIJ4iutrWCTiITbnFKDiL3NbYfkzHO123QdbOWFzY8CgyttyyqyAo2uJewjVQ9IvNElg4RZByKAEVynHNcKQ5yXEPxnX1BFj7CtfXBIvP5f4zN3AMzpCrQsvg+a3fQRMI06cCLSFiloGymLEz1OUP87+h4UxMsao2KxMQmqD4RHAzo4KpijsArOP5A6FPSGrUUZg1lGm7G7+2GmvTk78gLrZORkO7sIc8/V7bfxcxi7/3PejbmZy/0sepQif6P/vg0F1b2QnOktynZT+W3TLq7Jpqa8mjzwNwa6EnfU7wm2kXf7hNMGWc9CDgvQHY9gmX8Hkthcy5VxRB07Wzfv5XkHITh49ziEt3gdeWXDN2lnoOkcuFg1cnQumlL9G6eXWEXkDnJPmJ0gb1RwJNyf/6Htw8pQfYyV1wwCIHNDFBHAKzd7XBZ0oZVKuh0MjKm+806Gw+2U4yhS8jRjN3WSQXpgWk8OgN/RMZPn7xjfwWrJw2STMGbVPstzgQvi78jxqZrSREx5Hf3iCwVpGlbChQq/pp/+wuJpd2vk6bhZfdPdQV5orgEPwD5IsgJyAmE5DW5HkKOFEXgZX0bEmvSI0/oYCMqT1T1zXVe6RcAfhNR+YhoC+fzWORN2ViwDylr2XGAF+2Od1QpOj7s=
    username: AgCZNek2CcBv7rquNVPlA3BL2qaKu+YO7sFlNmU6JKFoVO8ql7R+/cCiMQGRFGcRgTE0qsBzMfVwfB/1GYU4kef1ZaJioEzZeu20Ir+rhs9qAOxLJr7NoMsHDricD0ZA8LpH826dWx0C4qUxYS3yUGkCiGEkxt9nctr3DOxno3zD0zzb7JPsgnDin/JYdGSdAV4I1tgNp2NylGl8oGRJCmgDPiM6W85s8hrWcj3//16JR0jIjtpUn9mSLHKL9xUbvMGIbrzL1EtxjqQH2V30Q3KGKtnAyXZqyOFlcaijK/35XtoRS08FQjy5O7YkTQoRgAfXuRVqSa6XUo19GiQyuRLwDiXY7GKDQwczo9GnO3UNOZhCNQQD8GzJQ5K7jzle+LmejCPxG3JwhW4EA2r9/L6NHzGC0lQhbDNLb2utt1vWsF5kcXavIy9/rdXqTXrqpM8bu/MjT96DV8Gb4Yfe+YKH4BHtJ8SSVDmOAFCco/ZneYmfnzbgYlRxE+iv2bCEU/t5HAwdH52RIrrn9HPzAjTeQefDazrW7WVooBSEd5l5B6PwSsI6rlkpRIxeAVQojmhOFzl/2OBBzqP8tBegZq1dPk7+2zM9ISCSRTHRrcRh+AcMXEcHWujGsOxUGHEbHhLmXuHrnBRZ7ZPYQI4W89RQPoaQ6gqVpX9nczCF4Ue8Kf6gIm0NlNfCc3lT72Ava1nDkUdVI5Q=
  template:
    metadata:
      name: immich-postgres-user-immich
      namespace: immich
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: immich
spec:
  encryptedData:
    ACCESS_KEY_ID: AgC7il/88Uh78aLm0ABWCWY2pBuAI5k2rPzdiZc0BUp+0JcbwM8rofEdla+is3o6Q5K3IVqbSdBq9jIPf4xiQVuyB0Um7OqZQPARYQMKTJLIXqaQjhrZ0BuB881a85tSP5SLuEuBy4bC8YhaAFmbGpvaXHcAbRzYGKXTzDb1e3amXTNqg4ilRtPBAtZsY9/WpmD61vK7mDH+49y6kP4jlBV3D1/zqFgcMRNHJf9m98z9R0pwv44In6rlX6qLSJCssqwTkc/XmdxjC82nb09XCIjErLUTg/XEewPeSVSCS2TyhOIP7oSCvvaCY+hImJvxed/TYaFmio6/uDYMYMbtf2F1QtcryXPAFJx5i8bhYEgr6tp031uaFQe32v5k5IFRk6T3EIpLweRSQrhAbQcffQag4EkSmTKvKxsyJNSzJ7mAnAeXkvrAGgZwgYBw56mFhmtlIXpevaaxqEVShW44y1c0KHoe/fGbRvCggdMw6JOj883rYTvwKbGpwGWxBlkiunApifHTfmdrKdIuvjLKS92+n0HNL2qQaJRqR6tz0RZ9xCWiA0IMkezKmufobD+27HIW/hCUUGpSysVTBbKn0lk56Hl6buiYLOLUirfPxiwfEgcONCfe6xINo/k5Vc8Q4j0uF1coSf4OUjqNh9htXTS/iUVNTIDDAB6h9vgs9bQwkr9CGPamiJfD898dixuDoecZCEqya7I97qMMq7IZ5DJ7xcxmWzc/Xh/q
    ACCESS_SECRET_KEY: AgCKMGy4RzQ6xQPIDMD/iiQex7m9NwFN+LEWMtS8426e7UgLo4SSjFfd7tj5Ck+pbeLNwoIs1S9xt7oZ+a36pGC5D+azBpA67E0NxZd4HbuA8kYGF3V13BxhoEinPwmXbL+VFXIqgRRMv8GBmj8+mGXuKuzVa1aqXqr4iIHaQIbCKWz8qhzWaRSoqR/IIiAc/X9DHMJGYhwJZ1si09Je9JLAfPZQJURhKvZzUCjg/0b68XbnBriJqzfWdFwTTZ29M0/PoDrjLrAMwkXQruqAjW9bv7zyV31TJfHl6KfhQI3xEmiRHa6sRiU22sicn6PStc4q1eMk2718Iqs9cXlk9UjxQGG2OtSlxCuoJOivOfUx12BfNwqelH63xcFjEXgfXiSGOv41WMU87MINqfcUP3n3hRPmxPy428zkNqLt66VT22jY1TLrNqefz9cgG3lzI6LFTDujdkBFSmBSDiGYJQw+Z/s42ymAlChZeCF+nKnVZ4+HGOSAErfBmH6b/QE+ZCTalPPGixALh0/1mFD/PctQF7pN2U0dwpge0UvwAuIT+BEjxPBHDwk8hFugJ7JomjxdASv0Gz/Dv04H7EzqC+HICUxc6DdW6ecqPsgZ62muHq7kspZB+nETlx0HvfwF4FwDNUzMeZDg0lyvk+Zc4YlTT73Yy4gcaeoVrKNN6JukwMuxKUaHgGPkNKBND1ANQX3gYcbowfWdleEzzSRAcu223yHb3+WyPl6t81KccSPO
  template:
    metadata:
      name: backblaze-creds
      namespace: immich
    type: Opaque
