---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-values
  namespace: immich
spec:
  encryptedData:
    values.yaml: AgClm0m9TWvYdVv+Z48ez+Z8Ot5GklhaLEnek8UvSTxSo8VQg8S+AUEjKRrrFVqO45qP0VXWszGe7/3wfE5/9PA9i6R1wYvvK/Ve13NyNxNfb/ks+6lYUCUhn3wClEiGCwHep2khiRVvt5idhRHaRbs4/O9QgOaR+7YDKEFKoyojCB2sZdq+cb8K+To5/OD4oo7xX1Ag02N4BAKvKYEJLIXr+kqh6XF0z2D/rSCkZLbsN6a7+V1t+Y6PfdF+nPpew7MjDQSlv+Sx7HJLaHwbHbeNh3y7PUP2JizxxKhRkOLvS6OZU6+tPqb0VBu3/4jyISxlIGYvwDhs3gIfziUBcknjmSuabAEe/TOuJvb+lXnR7nADpfHAr4Qecl5NxNhe7m6ik7AaFSPwBD5Oz6COG5dqIvUr0faOVutn0WBKcZDGgMxk5XfNnOXC2B2UENUfTUaR1BGHxtcxlmQeG/gQ3gZBeYcx0LiN9/E6k/Rsy2pZNOSKkpXVhNi2NU2H+xlRO0zh/LYxwK2rpAn29K3m40H6rZHNe/02o8YsY0SV5cogHviehl9FLbGsCKfcxhgnm2yk3u5SuW2C+SYC+KrnBUcnTQjA9ErMTzIjSNMduhx7uqfbPnsKbXsDWYy1E/uHHKoH5Jd98hUOYPkhY4S9hJ6mICI1N5G8PzkxWyfxsOVDPkJNogB0CQb6rrQ7W0C9eVVEE70fTkwyPsnsyV6jkSXtnsFG6rSHKd+KR1Fbctq6jZYZ3/dVRS8EhSq2MYQdWou+cnTMnckHJRWfLNhc7wnrH2N13TzpQm7NXOH1R9FKE1vm0yVP5MMNMOpmKsOJjvOdHySk1/W7mXaAhF8rI434LyUM
  template:
    metadata:
      name: immich-values
      namespace: immich
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-user-immich
  namespace: immich
spec:
  encryptedData:
    password: AgDKnYF376ICrAdxLUEPuYI36QevqClo/VwYvGAYKm1RTNUk25GW7IxuJNFvJJUwjXqDlAAU6tyRAAQj1rJYfANGrQTi3vr5PEb04fLermffi98j/+4v4wdVE37zPvq+OrjPRdYhYdZ0hKqe2XhKAKcJjs6KvvQRsw82zjyNGQ5w6ND7qbbkiI0/2dqXT0iF7G6P7nJsJUVOEdmz0yma7f/Nf9C8ujciCr0lnRmT/2mT4bK0z1zOmqKHFwMswQ8r2KPAvb3WrYEflJlcT2+9nskPBE5uV53N4i8PYvobqJAjrZi1qs9PGFrKc00m/fABaAhK3K8d3PI0MWa2t6oWjN6/fD/XXjdIj3f1odfgF8a3jo5EyB5OwBx2ZjMHjbUpY7ok4UQG1m9oNsOfQ4sndswKroS02NF9HkpO+QJVqw6UHCA5gBmpwPhTVOfc4ZdwV9etzp1w9c07ijEoSDK05yo1kPwOgoQdz5IMEIugLnNz2AN8NyXNkj4IgSMcUrzZsSHtBBsZI+jNgWDzZEAGIqaSiwPci2QaUYk5m7b947aOtRaLX1DzVJELUsg1NyKwlVD5kRGRXWnor6hM6+IX4XzcxMN0JQb4OH6yVjEyco8CMGDU3EqWa54Eau6bpaDE0wGwy7GvibpBRA0R68mJPKOwdCr38q1X9PhGK2/Q268ICRT+qnBjatPzc0++N7RKRxWpeejEe7XF9EA8FfTWOYpyC8QpXGjaNvY=
    username: AgB5etgo6ymvxBLJ2jLYAxY2d8iYiKopWHENrnSgVkuXb/FWlw+x28+qeKtD8O7rIMe9ZU6xOpNjFlyAqYqjwQ91kCcFYbj+i9U64EYwsnKfIIGL092O5fq8qT9zEjWoZA06Di3ic9D5JXiKWVPnW3AXm1+aHLj6uUA99rJxt31D3QjVq682LX3ckj7/UHttkdd+XMjepGlFBCaZJZgC6AuDKCko3nIOCo3ZmPcvaEReQOjmfFPAChfBissd6ZO0tHd3Iu/JYmzULXcTMyfcT9VTdyjr4Vxcx0nXWsvj+UKz3saKgvuJeatMrWZpZjDtXbg70WZbfteYVJGXaQFd5Am6/tGDPdZGlzAY4zGuDNgOOlgjTsLkxnOh6f1FBvvC3MMGP7s8nDIVjdc1C2/ivtA8KTby/pRXexsOhkVMQIJ/SlsK9J30ciKerOxPG/B47UssxhMdqN1zjyZ+aPbbEDHFLJp/ugVFS5TvF0sA6bCgqGL/dCmo3ZlG2X7KhYzbnkDEdrm2S2XYfSeFQ9SVuFsW0cELO+JEoV1a7pdobi8984LYDIrG6IRrVxX3YkU/TfuyLrkNT/b81h776njPhpL2iJy4f4v/aSviJuRBhIv4bHZ2YNTtwiZFyHlpEtmX89mvM7Pr2cfZms75REvG0blZWByXwNVgKbEQuyEIwev+0UajmGid0EwUfFaxyZTYRmyCfEJkev0=
  template:
    metadata:
      name: immich-postgres-user-immich
      namespace: immich
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: immich
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAoA8xzC4hgPesZnKIfykphHEnhvGIwOEDsmhEQpe8dIiBC1CznMilDbHB2oIg9xA8AUpitjNMToBrTy4MsQVgfp+bvLT4uhugAq1ZVrJ0Y3483AlW9KaH2l0NwcHQwYCT3Hwf0Zt1YAz6RydSgjUuaHhicj0CkcVsIae8XB6u4wAsYcu+tKuamj4dZIDu0RQHkcbhSHIbL/anLuaV7+j7IP/Vr0iS+y58tMVQvy21s9kJqJLy2UMKgPNIudSLc24yR5LtIj3hraYlUm2zLfh7Kif8Y93vxx3a9Fn7Z+6cOReLekqeFqLgsOwS1U28peO42jMR2oGcmK3C99h6twgMR8g6ehfVXZE+2WenCAdUVGK5RX5f5OSJasJmRPPDSIGRUK+oNHU+EZl2rCmfdHW+lKBrjFuHlKlT19q70XYdA1S5qr8fb+VcGJsTT+9084iKr6liV2cEqVLZolf6V0ZDEOzwjRVBpovGvEg4tPbghdTl4+j6JlSYgFowcZXlIBfBaogSP6/DbdNf7x29LQX9cZ4bpNQ9DDB4vC0cs7P+G1bEHiMpjQoNM+mmaqY/AadzcxHHjX/GlYU+eW54LAj6xb0EqsT43qiD061zgkRLLbC/Lxm7x+zBoB0KfqcAVeMdPfAK0x1ew3EKG/eq+Q9ekQ4zLtHttrVZXlDAnDLVYrCASpKCtstl3RojJiEQ9NnYNsukjIuRPNDXO8AK50z5uccp8dzbnozQS
    ACCESS_SECRET_KEY: AgADTnp9peSXza3N73aAFScuJMiYdfrPl5XkC1cJls13dkisw5LDL9Df8hO7c58yVU0NVOSo4O/J1j+mLWVPMbZUql7+9BvKFn+7GgxM7GNMOOSdCkwqdoUnV2gtk9vvlQ/myYR/13ycn/aiXQ7oxI+eL5x7qph8XUEaAk7fPGGVTySQXE3G4MbDjvtQ591KLslgpnE2d9AfYQcdluyWy+dj7hHtcNFE+RA9RpQOSCjpxi0GWbsw1JchhQsddbe6OAvhQhb0T6Y/6DwYoY7HDb2nuGsrfTlRkEv5XK36g2rIwco4BWOI/T3bAtHE+Mxv1zGuUc3QwB3rY7OtUjNDXk3v5f4I+clUAPRXvft6y2Bv5tzlCVNwrGyVKvegF4do5sR+wEOalcO3cuJxXpYhKU0mIOb+gELBnUNHon+aP1WEw9+TrZZdfY0tq10W5FF40Wrhp5d98dLpY6FA22HLYZGUczrHRxTgAX1jh8ABvOTFhJUfZqH9cNL1uRl7ZM1K6j9d46jpqmA5+F0Er92GSGn1whnVVwJG3xJ+/yL8ql1tNClDwCPLzEOYAJUhmpI5u96B7bLWfzOlfuBhXfkGjn+vdh7IIQL4c1nYDpundMIR0rckTkwbHuNhNCKfIgW2Xl/Bxk10FXmuufCw9stJ+C7Dc6kyMSmyVY5UQhk0PaQgVu29xml+ZYN5TaMCFKCxzwmVsHGdffVD608aEy4bP+5JazMm8gLnf/LevU/diHGF
  template:
    metadata:
      name: backblaze-creds
      namespace: immich
    type: Opaque
