---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-values
  namespace: immich
spec:
  encryptedData:
    values.yaml: AgAUVXucMl9FN45Wz/a7SI+PasczPx+1pvjWGYp754ObDKxaL9X80hyWYRqsJt8pyGX0hn7LnSZ18+GJzV7vGusJDF/fF2g4qmJhzT4J0B5W7clECpP3iV5h81H+hAS8J4mZYcfLKXHVxvfXI8+79vhXSzy0LBspDGPS9ymTxKL6GMMytP/6eB1y8cxrppydDMHHKoL4CNmcqgfDY/kYa63UaG+qzYmWW3306w74RVuHeQsoweQ1q5E2jN+0we/ec2hVsil9erYOa6RRQ+xQO8yFJ09BIaYzy3lFyl5Kp4i6pDmbv7zEohUk3R7o9vuH2A0BW5cDtOH/EFnaRLXcAjXNBivA0IyME8F+NlbmUhXeE1AOLDVPFhM9e7Oh9Us26zsS1pTxd5lL1jD4AktvwUBMEG7qG3IB/jFgo33DWqVVDebHmNEn3eg3MAFrlswiYVqP452H9Iw0QqptYKR+ExYXqEkEbOfKHm5jGojYFAeZlldXaTG/0kXYjsIf4LunV3rl5BjHrUPuiFvSWpgbH2h3pBHVORml2DvBQ+eR2/oNhsJsbgJqk5ItPoHgzGJncPqn4CsMj+PP5wzfA688QthUGgSaYiY4tnRAXFkHRBuokicNzDk0YpLuUCAeKhEsHdqn+Ase+oetF28HVCIET+vUXWRKM2YtHjZeKc2SLWxWSEej5pbkb41RyfLC042VJox3a6x9PznwNz8ktSWHNrOPMdPHSdQWjt1gZLB9MkRQvJdBmvBuTsuyU//IO8fn+wrAlWeETDsKVV1JU4YNev7oTZyHvmfh22sX1UshhWwsXRNWPe4EeSaaq3qNWks/SOeqds3fcJiqPuR1i+salLoPINYH+ibAHr+v6OvbG1t/fFCO/E8JbiRPZ0e3UT7x8Fc4xHngWKdgSyoclXSE3qe70lzfyXn5E5+GEjA2K74TOGXavtfrbRZmaSSB2g==
  template:
    metadata:
      name: immich-values
      namespace: immich
    type: Opaque
