---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-values
  namespace: immich
spec:
  encryptedData:
    values.yaml: AgBkLs57POL521RcLKjRGuF31gB57tG8MGb3kSlW753f/OgT0qMm722ACBh34HOv7QsdrG8cheJPzFS804kIQXSn9P/4PxWJkUw557cGaQNLECCZIDhbBRgsqWIbY3lG7/ktTp3/+ECxL+6LBLI8IUtQ1eIi//BauR/wm0Pth+REgRd5AtqzJNkwCmqSHMQras5jqHa8aZ06TrajGrzuXmMNgcF+jSzLQoRYnJUCKiYRZFZZoJ9Y/6e8DfnbhmWnpJSKbWiLEdFs2maNMzbwvOgsZJYpk2rtFgbYV1JL45M0sahVjYY9eogTu4txxkeBzb488bfPT4Mi6vXcBP81Pr/Hmlc6Eg4viE/xvvaOvTfzLm9FZ90mB0t33Es7GIEaAEQG4SryVggDCCREC2kNuiU7gt5rcmXr8EUAsH7dX7TokeBWYnPHoRv/hfCqDG1KWoA6i6D7APOj+g5GGFmk1Kui6K9xy0L7sYMo1Y4HQ+WQzRZ74xah0U4VCntJLzInlqI8bC/Zmejc9U9+20ffVHFKF8slp1nnU5jGl9gHFN6LPsgCKckkW8muD2umNO9wJgI+HAwqP35CHQRNm1lAj/7nD29Q6JCOMVQmDUizd1buEqylU46rwGq2gVdgqgC49vDF/5JLLYzwju/fLvz5erpS48v23YOqs5UbLX//k+IrAo/ZzTMIF1nSwLfL2/JpuPpNPAPmHmk0Ao39p2Z3K7t//Q2Trv1DI0haZeR5sN6RZX8IUm0wGYdVQ7iYoM1cmiwLJDvTFWIwpmH1RJpWCe8ZumlrJvb7BltAwz/zt8RQlGY5dax2t+JdPIa5ihfMNQGNP1NmUH9BODkxZWOnkKMHmvT1picddjAoSqIEPq9oo+02fRmwcCKk2EkoLS2BIPcTwHiC1EKeQl8ptU8cYBFOkQ9X89iFRqHbo7Kgc3yGQnpg76WpUSwv8x9SVA==
  template:
    metadata:
      name: immich-values
      namespace: immich
    type: Opaque
