---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-values
  namespace: immich
spec:
  encryptedData:
    values.yaml: AgBwQFRTA2ohxe5ziTFhf9IUUAQKhPitT666BqGxbJ+nSY1CiHZFowcdrWZN3QrE3OTiq2jH2muELXwHOfvGK+MFgLzUrUCcWdBPBfhi9DFiqLcSXeX4SaYnoEhFwSxXm/nfMyAi0oqTuV/2dsIbfRuEMCMkWxY7cL62DCIOhMrYZuBjHW9/MweUTC49mW+/T1oTb6jmW7Nti++Sq/M1phcnx7dMb1r/uqTVgwz+mersKY7bUUuFZjGXgxPXNi3HyxvutHEc6xBhVgPxwEe3wFXRFE41cGuMCqidCk9k5JPSzQYnbs6dfFsbOAFAFAOcshvgfJuWY+1kNGjeRELlS4Dm6qYsHD8E+HpLRwHkvAtWdK/+cu9VgLINpPi/Be5uPq2xPTjhiNCiR6pOWR+vkAU2MAgxpPN9VGgRhmhJ6u8Z/eg9kDq+CBu0aO8CQSj8lK6SJQ2MOZQ8cbjHlPKUEXzpLDdsScwXPc4beW4diNKS8aBG7wVyI5DeJKQIgsgX1N8Ao+LlHYiKUqQPz0hbwNWSc8VNdaOiGcGBjmZX6sILr1Gu3VHUOCmrg4N2cm+onYmBIS7qYHCsUw+A2aluY4pEP7iyb6p94IMuBKzqP9mgIkoWiq1cQ529OjcG8NBZlVDBT33O5ULgizk72V36iEROhC4igvzjIJ+IOYzyP2ewTqlt0iPI0otwzXySVMSbcqPRYMrN6zVMaZmSGgiXyPQQAj9H677c3czx74O2rrRViM/+jkVnp+BSvgEKx8sOfKvRE5s64M3JRTH2zcKpt1MnXcl/hJw2dyKDArDx4+cDrI56HwiT4g8gwgKyhBqTlaDtKnLfLWMeXg8rh5GzRgpMjXuz
  template:
    metadata:
      name: immich-values
      namespace: immich
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-user-immich
  namespace: immich
spec:
  encryptedData:
    password: AgA//5zxJ6AePKSqyQzUUBDadKWNbAzzbS/t3bxoFCMNArreKBF4Ce7Eys+te+I/sWJ9SRLy+ms27d2GEkkdF//A6Gqw8+JoA1PSYOBPbdABD39Qwa2DS/CPz+w28UeCBXsSQbnxdh96NuuwXPrOTzadDrZpK0nys7sR0n2/FTN4hXcSdmcoy+Pq+MjBzL7OZEVGVUmMGOW8X7ldUNvwdOi57SutArRwh2mYG2EhikbNBBuXrknbV++OTfY8O6wHJ1LNVRxPMyYKzqlMr2n39LbN0TvzGopVoclorXeL5yptWRfxbc8lz3//kXtLdp5v7M1i6tfpZhDgcMmFd4hn8S4Y+0QLlGp90WXkhREfmTOkOll1EvmuGfRHOU449HiHtkai0apYNmdSNGcIYVH56asFW9fyHxIVP27MLNHN61ZYOtfDXjsIlA8SIcDPPv75I1HmEYMPQucjMudqNj25dHRfaeo2l8unRfA7h8ewppE7v6TU9q6EieXqmRR0di3VEaHTHXZ8QV0JK3llQXf9xccSj3cRUObEBEgGUv+s7ND9oUUKGZh3yH1KymKB8+jtVbsWLejhx3nPmu430A4hYMUdjP3nDZvjb4fUic3ywhP76Fc7SQ4etWT3UOVsd4duJZcTfsVP0qcYN6PtobylfNK9x21FuO+5Iswaq+bFfJ4QgCcYNYtRkPUgDyIvepjEj2f0DhapWAVLZqm/E9Q57FAiy380frAT+Eo=
    username: AgCY50dUnrDjfRtKCFMk+gompCi5iYSzE0GlXSh92ThHyPqXj+OFGHxKcBN9jlCxbdmsQtCpVffUsaQdFsjgfBSgJhSf+z98oe2mfh7V1xpmgOlVA/aqakUHZVo2/vOtuYvRZFYg7iOypkChibEA6o4n4fjzIIfoXVzbCAhnThmeR8DmAztWLeQK9gda2WEhXA+u/xRIeIPMm6WmbSRbNDsl3+9uib/EU+fSSkuM+qm3dm1U/M3p50u5UjDBX5EkEghICC+0kVWAcCzZ952CqMnseXnsN8ETLJZjIocf71crgTS0/Wij/tLVyld9KjM9RlECh3jQErGnUgKIaawpfGBQ2HsJq/nFizDgmSevVMrsrb2YQqpATit/76akLPe92eeEPG8gLVCTxtTeLg+N5gn8UZDNDo5eynbiw+3uKufPoDqsUuQmHo9/Fk5hVcRC6gdk2nmdVUqSZrxzE8MV60X5w2zIWk0IgrWdCy0fdDX21gL67gkG5HCFrOq7Lj5L60ARVcNji8fV5a9ZYyy82xixQo5bTZ5PpQNfsvUF9i11E5xj2XjqGvflM51JfnflTAvZ6HlvUmap7xiJhKwhraJdM6Y/ogJCnio2YhtSz7KqSNTpSr5I6+R7anFhDuZSjaHTTv9hQdGjn9gGb3ktvC+8qvZKR8vZO8RyYZtVNQebaHNLPgogGldFCmOolpsA0hs6m0Jgmis=
  template:
    metadata:
      name: immich-postgres-user-immich
      namespace: immich
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze-creds
  namespace: immich
spec:
  encryptedData:
    ACCESS_KEY_ID: AgADs2fn+rGnqXIRtDu19UvRWqyTR0kTJ1OQFbNCzIfWeQPIC6V2kQowJ43D/AQ6vHuldEFx6Rp5s0cJnxOivnzVKXj28IHA71OL/XluoIGcAEaAW0yJk39gDvZXanVG8X4nKzeO2mko5yY3ya5MZUZB9zozfXaWKvgbREjqh44CcLuo2wRJX1eE/5uJmB2k58EtJxGb2rCQjTrrFZ5LOHnR7p2h6pL7KgESa0l/U97Sj03fGtdstam/Dsjd/Vves9xXQGJimaDtrIw2gLelrBIPDPHndkjlTI+aPv9uIY/pcmjm6qt3QtCWwM0tp2dweQu6zB2z5uotsKpy/mCymtS7OdapLz+ljsx4KtSBC8i4xfYWZeEhBO3Bf2lB67FMIw295atk3vxfiUiBHDWmpmnFKky/Pmt0m9YxCEJFFTYVLFTzo8q3LG6COIFvWPFjLwpfmNCCYaZo0lx18ealq2+vtVyUZw+lnnRjDg8E4FlW9fTjNoau4iF0YLHF0A+JUkP0cLRmZ0hB5UyMi2kwusLRQ35n9AkJysRFYW8oo2/zDQvItnKmMTl96eiUibydIrqAHOV99oKZ+9FVv64dEHo3woRIHdlUDYdH0ZMCHO+FlwunJCyQxlL2c/lA/QzCkopCLplk7bpUNB7+JSvgkvpXmxJNTNeuebbCnHE9/l3BC56taW8WQyAk+ZXUPNpFuu2DMsjb5REhh2HZiX0H2qetHSZsVHFFjBzX
    ACCESS_SECRET_KEY: AgCLYjnWZ3tje4Ve5M1aGnrPwMDQtUSITevQa8WE/L7bpPAciHGlHytJQO5yhGyYze0edAmokvArX+kbcD8X/rwRFyksrNmKuAUyw4ziwtT8a2w2dartdz/vEQekUo31tPYZRaqokoOk5P8hSNnvei0jGttwnr1L8wwa/daSdbpAhYfjsGPF9xVh17+pRTM6VW1SNnIsA2SXP8Hi46Pa/EhJutHwCqxZnxXz2EqeqWG/tL1uclEFi6KuDfYJ+9ETjDItOBVAr9Iu5nC0Z027chG57FpHIkuaI7H+me6oSAEnlXYXovKjHa6hMo8sBwg4tG5sORdMe/ragY29HzX0MCWS6ssPcbZ2Ate3KFah700l4/5G7zAodzX75I8sPeqmp9UYRGTrtsiBsIP2mKqiukRB9O5LuKzdoiH3qUJvc8KiK3kLWID4bfZ8h0y4Vqm9S0nnlCxtplkZR2QBEyJ1Zw25NFeYIzJtUMoyGtNrP5yIhYSz1P6mWOaSl1zn1e/eGWol8JGOt7/oOBwzVzGABr1P0oDl2t8ne82xiqXvgrKax0JiRKwnq5JDVyY2FW6L3uK8XmfJs0D+ke3ViniQ9nJWnvR6IGfAp6b6zqiFNzvF57FSy0RX5VnJkuDjwQIdLrgKtvfFWcH6RVvlUs+Q5fmpwieAtMhJ49w6HYMs/c/5VptcbQZQanVWyAihXGPPhQPAj7Rv1Q/DtHJVLJfJK9tR5kAii4gzK8PpcN4+e0Ay
  template:
    metadata:
      name: backblaze-creds
      namespace: immich
    type: Opaque
