---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis
  namespace: redis
spec:
  encryptedData:
    redis-password: AgAVgMM8heYF3A5ChQOtfhKQ92m1WBMaIq+qF6t6e2OdGNW/Kdnins4nhGReVNlBOPt8hB6iVF9qrKJE7W3Zaq65rv0qSRhddECh5W7Cp1Ub01z2kiS/nkh1+xTTATJv+Wx673ETnMQo61c2ba1h6OLS3UT6NDAnbfIvOLQ8gGBPKX68f0wyJg7mVJ5wEobGLWTl0WWQVsRb+vRnWkIcDUqIHxUPaDphnaZKWc1EE79TZu8vtRmgAeYQgYDJtsdWoMoF6OfY0Otg/2uVET15aMNs6ObB2wsOEcBJ8pP0th7RGobCqXNqanB/vF/vPIJ/pEQOlByGgDVblYhpCGmn9VWZpIGKjLIbaSgHSpYP1XoLY1nPO4ra0YbewQ/ztwDZFiEGdoReQi3qmSHQuMk2yGW51qBwHU4q6YdpSo0nmfThGg3GNpj9NQImZaVhmaG3hCK1Z3gioMEo2DikhrJxwHZ/R7lPb1xslatY4huvpiFYtEGFDu2jF+zJNIK5yGV9bEhTYhez+20EjklTsNr+qDf6MapFL5Pb6Q0vtb//DByirmJLKpG89oYh2mC3AG/mmdr+m8mG966ujQUHnc7lgc81tj46djKWDUAtCTEOTD4GGwOrOETTr28Exts4gsdtJ9ymAQVh/MyXyJunst1nAcW1PO8gOjUOp3clg7WgoE0++Q7oNLFT5G09Iad78fXMi1sLHBKjM6FxXUg+7k8=
  template:
    metadata:
      name: redis
      namespace: redis
    type: Opaque
