---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis
  namespace: redis
spec:
  encryptedData:
    redis-password: AgCcfXm60tlnUUu0Aj+9qHxDAMth8Z30kNrvJo7uOUOYasDeGP+XCOM5ZAg8AXwONP3bSlfqeCjcWdgmvBdDOaacuoBxQHPu9THDdHzFmDIX9t4mKKoGm8yD5KoFJVrtZ3iXGlpeK/CrWjiCt5lQxzFzAVkKpR8RLcj3gdwYDDZFCBWC9VmtHGUW0ZyA3lq1B3WVRzt/qBhqBDiB/FYwaO/XyQYknNI5JRu3OoTmIZKgRSpPqCDGoV9jIOcKLjNOdfQaNygmrBPnrMoB1k7DEflIeWIuI9no13RAXZbeO1YzJ/qK7aK7vdz+sthDYzCjxls4tMFJlZZw1vkHmQcPejAVjYBt4Zr31sHi8Kku+9MdAiGLK2GyW633KpjeeBe8B/RQy/qyrrGik90gQmwuWfAyh32jsByimzLIFRSmBrIlNJY6eF+1M+ZGjR0FYppPryJeZIT9EY2F2boXgDHBGktsKOYPGi7SeYn1/N4QeR0sIZvyGjeuHh+w87L9xk5g8rDD0aCwPJJsZpFHH9qo3YVjUy9uKC2DX8lnfUw+ZjDHxJptXN/iB5lXg2gdUSqza65cTirRWSw/MZXSURYwKzyuFNjYrX1RSPax8EBIMmo9uUPmrwZ7OEun4PwSyewbp2ZynJ8c4nWkX9hWQlQdmQ93tE+FtMwpilEzoZtt2XpK0p64QuZJsChGV1CPH1L2UQCNw4/0fP3tKgFIZNY=
  template:
    metadata:
      name: redis
      namespace: redis
    type: Opaque
