---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis
  namespace: redis
spec:
  encryptedData:
    redis-password: AgAloHv9hqvjlMCEEZhmK33fp877gw2G0gRPTBhp2sHNK0PEuMrAhctGRHSIyNcl9x2QYwP3OIevSsxcdDEW3J5Qu6ZotvS8ar6yyzeei31GWk8+m0A4BipYW9WEfJk50iZUCr8Gy9PuLTbgxSUKJZUIuXzdyAnS++R2dxcgjcoojweIEj6osn/fXG9sruhr8idG/aZM/AjxoEIPsiNCdk5zzTz1Fpz1XotJi3sv1wD0pDsOil1DbQA40v4PzR8ayiz+iaIbMP+m1WJrygt/YvpPL/gJvcV1baKcp6Y5kK67YKjU6TObod8saC5RXq46hvmps9qOoxsESiZGAMduupVAxAJ+5aZQUkoOxniop+FJEWGZEhRv4VQ4WQ8R0PENGu8EiGboioyAdwh1zzX3F3piOwFe3mpbNGtFVRx+UmPr3+1f+7dhUF292SFFonY9Ay+EjwRRC6qAuRA0gnfp4RXptxJzGhdVVcc8uO9zm409R04R7IBhMr4GmmdTsDs7/1NyVnynLVc4BMgDiboL0ySpesSHCHDwLkpV2urf1Vasj887PZ+qHowXEYLa5C1GSFOKjKbw6IcXc5i3y2OyUlUcYIiDd9mOr3DXxxmJ/115KZ/y1Bb2ks3245SXQ+bZb9alOuHVZy4X4dR/KGSUhEbB8mqnSCOKx1q0azDu8FRyY55ZEngAFRFba+9HaLlXhi3z24waZXEveDeRIV4=
  template:
    metadata:
      name: redis
      namespace: redis
    type: Opaque
