---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis
  namespace: redis
spec:
  encryptedData:
    redis-password: AgAZAnq0D3F6p2Q++Y6kAwI/iwjyonIhMH1sLq32IV6nsKIwzAriS2FhAfdpifR8cLsxgts58apeXjlaRLv5iBO+oSI42hXZVdbwCizq+OGBS5+E1bEkREqz8zD/02KZwuHJ67UAkFFhnlD6WcRVbHonpWjVE17zSDKGRFjQYHOJDTLNU1g94YfcSgzg8yz5lZiWVTKNpRmyVVAHPtvnbI3+m4zo+kzn5JW13bqTakLXz6XRCxdYo7hfcpOLNbOf5THnjFThUQ7L4Q4/UWWM42K/jccE8bcmKfQg+NBYwHeVH5KH2s7MIy+H8OV6b50ONOYQc6O5Qt6nbcRLtXVBIT9PrQEI47g+Jkp3CQzmMoA4LRcW+eYprcwHCGNZpWXVb+pxbozWjHuPCRL+lTDjtB9OfIAlVMlxMqtil5FyaD1GUTvb9I/exGXivFvwVUqjLj+sEkQ7q+H+ikn98xUYa4fQB4vn66nl7NVphuevqTxQuB1tc8se1fWQDis+IbsuU89zSpqnFQSB2jBZ2EL64cRfSAO0VULEnkpL2/ibruxkXcZnfaU2nlNgm5bTRL8gn1e7D9HdR/txBXqjx3a00Jr+41jZFmrJZBiS/bYhvOLzGSUjTOgJSSpXuJjv9znVcyjSipoOrmR9VBsC497npz3DkfgrcAtA0jhivxs+oXog5bzn3YxWlhR5Z619i33ueBhNZIAw2sK/sRaRgLQ=
  template:
    metadata:
      name: redis
      namespace: redis
    type: Opaque
