---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis
  namespace: redis
spec:
  encryptedData:
    redis-password: AgBQpTa+hW6T1B5kq86jFSOLmiGF/OShS4+Kk/XLb9WNZWXl4V59X+3EYzpS8EKgYk25R6tJVQE8dnEj5wo0tymTNYjQoB8q1Tbzngtx4QYe+huFRlyejOcAAN36mIFq9KuUD30cfU0QJR3/ro+33yF7t8V6qDovuX4lkzEr8txZJYdJITX7ZMlr1eICDfkz7ayDgx/pQpq1uhXgHEJrMerKwymrl8awFOZAcWTOEeSbbfDiMh9zwe7wciPh1+aPyENOQvtbrsy2/nEqAmUymwa/fIHV5+9vWWkwIV2naalzaRmPDmAwv2kXIBVCkfh4RZkCTHqszg2CLVGBwzN9ukqFyHMYF/dlUBDlF8vK77LdlBgYG5O11MlM0aij0jA/Db0Un7uXLJ0YMwdddXomo7ulJYUKRgf4FRASENdWNvLOuYgbFjcCrKXVxkR6+Iebhzf3SIVwev/tFQ4uHAh/vFExL9KRyhEwndp8pt9DtIM9lAxhPX9xXn6yN7dRgrtkm43uCBiVH2WutTUIySgJR0Rxt2YOau6D12MurMwuIoMycuh1TEe5wN72x/WregXhuzmptg8clpLkf5xQruZfODlUiyJ3c6zOIH1i4a1+8pJQ/qAef3MEZMAq/0FqBaxvkajoFdpX+s7EHTjCP8mZ+iJvdwwp3OdbifvEBTkpy03YwKOHQo51cDUqsRjHFT6ljcxBCTyiqKbDLt1llZM=
  template:
    metadata:
      name: redis
      namespace: redis
    type: Opaque
