---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis
  namespace: redis
spec:
  encryptedData:
    redis-password: AgCS2jenujbx2U5Sp6o5r6oHUaPXfgkJR/zabOvpA7zisYXFdwmlJv/1D1GCw+HArWrClpZj5o0uwbfDG8QRK5hYicT84VTbZG68vCFMHNaaQtiLzJbNvpcHQ5Wrg8Oa/7x4LFfXjVMMnIPlG7zqICFM9jKaJ5T2pF6ctnqbeCq3fhZbSbgIUcrgLvT1smXroJ7Yrdu/Pcs2vVUCQ7sL30X0b4UOspXaJIh+/VxP0oc+6hj0oVS5v8oiKFeIRECR3ByvLfxFwmGUnsTLM2j3ahAOy25h86HFo2TH5JuNJ8dvjT2NqUzfNMu8Q7tDVfkqJV7pUYggZxm1Ljr54epYsOeTwm/XZYSlU8XLy9rWH7Z507zqvAy0N1I2dW/4t8DhugK20abhp8Nsu6fuNeM86lurJVQ6uxpigOusB4WJvKBXoSowlFe59Oh4vBOjbecquY7ncQ3xG52qXnSiXfdPsH747xxmaKMdTW3Ep8yg6+vKsH3KiiXHFxOKUu6whoUl/d4KwWynI6o6Jhur3d2Pr6+VWBilCLnm4OkA+5j2E6aiXm24EnKn5PD7gR9ujlohtQ1QCVJJ2gl77GXRZKuM3e3h/0uT9q8/DM81L0VQPxgKinNPrf6h2SGrUO93evH2OxPaEYm2Gj9t4XZFNVlQ9SUdc9RfhCiPcnsN9LKn2gFMaLz8GaKgyJQPs1AO4iUtgeVDcHFkJWf2PcIbqPU=
  template:
    metadata:
      name: redis
      namespace: redis
    type: Opaque
