---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis
  namespace: redis
spec:
  encryptedData:
    redis-password: AgCiIEFAIfMFXQTMN7E333+vfgraBOo6O3nf0hbO+IUQgFVYNEnj2hE5K1+82RLZZfZbcd/vOcyI+l+TCpiv+jV0c8lwChgTzL6ZH0RgwczbpeU4ZQLALwDW5eYh/X0sZ/tuPQP8bR+Gg4g4A33T1YO+0T7f6SY9zUTfe+qf/4241esUQmwqRPUW+0wWhByfIdP3XONkc0xSaPBr7P4Kq5hyhdT9HXVMECo6zLz1XQWfTgkgSkPhwTOIGRIUbz3iu/W1uCkKciV0265Hh5fnt5EP6/Zk7sd5MnqfDRm8xs3+O3pvMYET8DPXO1XPXy4qN+l0NbCr83ENS55ZVB3RNC7MC5EELwhlTe4M0dGtiMkYX4cJOWNVa/mj88VaDbr9eUBuCBhJcDx3xmzYpyV6RczwFAxuTMSAdmN9Z0CYMqh5QHLtE7JJtaSk+H/Mmz6u6DaEAprYj/zdSICHDzlrSmeEG4ffakMnhW66yvn6b7UVd4EGEaiNX0GFWX+jofYIsCGxnwHffbZsvVf+M0IurkFpLY/TCjm2Gg5XbTlGzaNAJMhWdzjEoO1CGzn70QiOHWnwbETqIURWN4iCNFphTi94v38Rc86q/qczaq9LNnXeFjeJxat5j12UsmP1zotrcbSnd1iSCPBJFgOL0IGubwVNkMdcr7ttzgK9XtQ3N0qMa008mkw0brwy2TZfAcQx6e2YEiLdN5fjI8kiMeE=
  template:
    metadata:
      name: redis
      namespace: redis
    type: Opaque
