---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: inadyn-values
  namespace: inadyn
spec:
  encryptedData:
    values.yaml: AgBZgSP+lvCGR8vSiG1nISLF0snmvAkKv9ax42y56tK58BE1V2T2dvxQJzY9cSfRpeF2OeJGjdnqw6lRC5UeQ9Qqx/1q6zegDSjEKwait3DYvdVXRlNDHAwY9PQEivqhMi9Z0xWgOfAZrsktOr7LrD7z0u25hTttwD2Yl9ivHYUPiYaYw5ttS6/NODAuX4w6pN6EiUs9kjpu/bw2CzBV0+P1F6geqaPjbux8Ei9TZeNET4Jkw0Lmpy1So7QicbBlmcNE38d05vyIUvI+e/eixqmkzMM23MD2Z34NLlmEtXuTTvjC1hXQ+ajNJed2cfxQ2ShaLviaW/KCspFBZyUX5CLUdXVEqIWHmy5tgWKNsQMx2MRbEPAPL9PaoWCL79L87DxqYkNkx0sje5A5QuOtmEA0wG/rbLEsEmAPDxbFrclM8kPwEMROK3Dv7bobkL/AELSIJHrKZ54jsSj1eBAEtvxRxnD4wsCK0qAl31sqYWbGjTEskI1AUByVk5YgYxWZvRDXo7/RCafyX56sMTSH7e/7w75S/yj+A/MFkU6ZgE+Ej2unzm58TKiO8kjmKxFi8jVuAIccBXwFUvy84uX0+jr62AvYldV250tvA7G2XKR0P+uChSiVZrSUT/wJwkcN+qeNzmBUktiuPP2EOEpJ5vvLT8ZhboPrSnjnzUF80WUHIONRGA+2UBvk29ebKfwNnP3RlBd9ltuFRR9ybVT5JjQ9mCD7eBnuKHpYfeclyqWrujEIgB1yfRlh2PuKpReDO3Knnlayg29gYY/HfdTbuKpkVbqWLvMZoDHbhW3Cyz4dLd8ALM4VxnLkwP7F/L2nFKmIEffarbB+G7KJQiMJkPCeYqrkjNaS2usVAE5qmakhJHI2r0n8Oc+jqmL3Fw5U6rXlfeXZfs5K8RBz5Z3ohukD72kvlW7NougM4vDn+DcQ1Ub8wXUss2cFsuqlqrIteLTNDcLWG+I+FAvJcgcJ8XoBvcn2VxWqPg3P/Z9CgNccbMxvQgnaQWxdkusyW3OmLsNTpw==
  template:
    metadata:
      name: inadyn-values
      namespace: inadyn
    type: Opaque
