---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: inadyn-values
  namespace: inadyn
spec:
  encryptedData:
    values.yaml: AgCrZ0Rbed2cA6S8SgMuXzE+mMthGHbl+sEz5Ou4Em2DtamiOGts+IMbzofpHW+HVof8c9qVOlbgCQHc5vDmllOS21V7SJDN4biOoWSZqnDP4DVAwboJWj3Uak4z1fBUApVV5ia1zIb2S1aB0f7rQ7kpy8Y13IysLfThKX1Y2ENvb6U77QyD3C3ddCmQh6caK+KRyz2et/Wr2CPHK/mvvP8iVt458PUf4U5mIPRuXo+qRGEXx16fpgoqHqADAbRM4P0roYjwUfCrzAXZTF5vw/O7BeH2Te1ThxrBGuMMVs5viIY2FouWVO3bQtSMpTaCwwX0CB7oqgaV2uc4xfZwi9TmjdUAwx2ZIh6epsTnyWA57bffIkL7KgGenTZ9yS4NnZZTvquRSMOCjcMtu8cRCfoFJ717JtgNuQVvbOygv3kcL5mKHLqHGOzhstAVfmtHXTpKPcc7dh0O3PY4pvtCnqok0sijYYHighVbm4JDgkudViIvSHau2NtdIp+OXaAY02J2aoE9ynbl1tQMI9jAc4W2U09cOnhwL2XKIKD1iioG28D5vlDf5u3YbSVWVcBlGzuatfgCgiHzqXea3hWoUKwdlletSNXg5EqHUCBwZxDoTRyBeJhygyT0vSzJguNO3/Yw5lLRSXLwo/bh5obr7c7G5Z7yeJ8Q8r4JpSFTm8nLd3g+MeN9x4z0kaLbniyFkeiuHeMRjgB1ya5VfjB+SPSMWAAmSp45A7YzEPjkk4SunlmOBl4q+JL0/sw8ML0yhQt/ddytCRjCT8l0t4eob9hLX5EiWMYXeTEQ6Ck1nu4l77fBiZbcCsQ51Rjke8JU3V9E+hNuJToB8tAAFeAtH7ieSfbl2GfEnlXIqKFoD6GuUCxwKef+dlJCi8SmU939j4LfLcjadS1b2UTcUOFTTQhmetULBnyOD0xHeT0uyUJliR/5aFMsCWRsPjUfSsx03EhMXl0RQ/yvd7CmL2xbmRHDLJuXZ0s6xlG0pU20xfKNyEWwwZVxg7ZuFVjne4GNZJflvA==
  template:
    metadata:
      name: inadyn-values
      namespace: inadyn
    type: Opaque
