---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: inadyn-values
  namespace: inadyn
spec:
  encryptedData:
    values.yaml: AgC6IlJKJDOkFQycH22iSppqQ71zB4wyNokElcx6CPReI93fAhfEohR/HsBC4IVOQXBMLOwUEdTmIxmi5vu3hflXr+IntubdiXFQ6UZsh4CCmqRMMIluMsJFskdMqR16llBsP0C1IRX6Y7Xs6KwvNHVcao2N/xMm5NMGcx2+Ud/b64ysPRa+foCwK6v0y9BQLu5zb1nOsthB6Ea14ppgGJ9WiJFsKjNyDcax2MfDK2z8N0kEP9F2v3hxYbY0g8O5vxIvMjn0sMkDbCkyK8B92tkLBE+2uP3ZodyRHokpjqd2XS7gc/et/HAXOiYatcN3EG495DGDzUaqtJXHwORaWcxOkEs2LYVhwrgWbkIBA200Ur6j9P4lYXNHR2+dgD6jowssc6YUbn6+f1wtQQjplCKmeJuY86eOZVsf7EmCCOMgytH6Pr6n+rJCmJsmqqsXWflnPZaMfV4WJL128D3LUiGrZieTC/2Vfl6YZEqS1jfEWLxQ8wM/v0BrsQzLYTSU1jaV3zBXVdSsLMIiFJMveSYOCLTlOPWX2+RN2JcMbNSItaqYznP07HVlYmA77pb8dFA4XFZjdrnbNQN3KcBot6Wpfz5yVf8p8znnOKKsWcNlR1d9saUajwCSuGtOG5n7ngG5MMJyesEpnenHy7M+T42Amsu4hFdkkYLfVpZxGB7cnPxXV6p2y/TssOUdNKSmGmNLey4BnRlpjvCZ1brRpSLOYlD6H7NArvPwkrLgK9d3/Ef9/j+6ujujaZpwuNN8vMudFrJUIOb596jN2peGQpjvP4sBaqI0l8hXo+N/ZIGQQyQHIzHAqJPIlzySBZxA9YwOw7SsMfgav2YMRedpndl5xqodoOWiArTbloLV0CCcjpOnwCefp8o7JstEkWy+yPkgrM1+ipCDjmDp/uflc7kYoytIznbbMr7mWJmXPGhb4WpMSJb98YuZ1kr439M142YdKXRK3miKkdjJ5OYy34dpfffbuknoClfXiVI0hT2FZREirXIo8nh+EM76s1ItQ91Bgg==
  template:
    metadata:
      name: inadyn-values
      namespace: inadyn
    type: Opaque
