---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: inadyn-values
  namespace: inadyn
spec:
  encryptedData:
    values.yaml: AgCW6ASpGo9NZubUWcvVpGNCBjJW12e3BJOOi2X4acukFLpAVmChDCH4NPfUjXf6Kos4x1uM9f2NOik6OmXRWj67+gJqONqtpkf+g5Bo5ntabrsBwkX/OXy6KCc1UVg3sS+lGU9FAGW+ASi1sRdfD+pQZvmi4oWGPrcT5UFT2/uwo5brRlKXAB9RD19FTt1fRdusuDXWX4wE9h9fT6HozXXsSvK4oxnW3zONzGwFOtpZHjh6Pnr7sEItu0fH3I6CvzqRRAJZ7FrQ4OEogrHsZdZea9u+TGKma9mmBPOn7F5iqcfMNyfLw4kymPnEndPz2oPPtjGEZnRMsIoDcU3bXjfO1sU4D7W9OsIi+dgqRkFSheXblJytxiz3pXAyJ9+kog5kYwQeEL6BACEQMvSVoKkhi5rDoN+kveRJWROlOhTFWN8khBCTPP+2VJe775+RLM5qPule01TUmQhflGRrSryY553KV3Mps9HBtfdyk+LjUik7SlMWtcXktJnd2HyLiMLNQdGRfatcovUUTOvmhjzkdNP8/NnxJTEfAlpdwBOd8n+a3nG5yKxhafEohxZN56VdxKA/X067BW259he+cBpmIMkegLj+ydch8exuS69n0HHFgo6Vn/1PTdkqzg+RittEkZEXfVMaLkf9qyW+4r91yEqPmY+EHFWR3olby6/DGzmTK23QkTZJw8ljmra3/tA5/RzluAQNhIvGuAW3Q5xtYsGp6lk+bJMRrkleLXkEJTrafOOX4sOVJMiK3YI8eVctH3lfC3vLlE3/SR1J8JfTmkFUhaTjPBj2xnU95QV6yolggAyMwic4IGJC+/yfBadlG/4nXLOcKYBjJDtHzBAuUkvJHH3ghnk2wSuIprPdV7QUnobdMM9IJ9CrtWE6l8KCHN/AnapMIWVis6dZ+ABf+wsyRdrle9EOsRRFUZN3rFAfZj7Pgc2mcq7vyeK2+hCgg0JtakvVQGY38BkI/lovGqmDNi6YFe3iU4UEa6oyMapl/9gq4sWJJj/q28MMgaVvBA==
  template:
    metadata:
      name: inadyn-values
      namespace: inadyn
    type: Opaque
