---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: inadyn-values
  namespace: inadyn
spec:
  encryptedData:
    values.yaml: AgCLcIlA1sN1NnTvmz1YAzzyrnJK0gUY5EzxQqOoa7Kny7o0jL7tM91du55donADh4x/ioSdC7CXEjQXeDW2mJJwTyOl9CDFNwohx9/rSyzE7nOd0cqlYBV2HCTQ4VYXEdJcmxQZ/SwhmPpCLlLNrmC6kLWSv5WbQzmUzsFP1uwDrIfX58COpi7anfeXTXTcSVpJi2PK8J75ZyvINk4167ZkJ/png1QuuIp1YUWq/k6Las4w1EnYG+sZgE6EqHAQuhUWX1onpycYD2r8EMsN7u28/nUWGYiyEgF+KWlIp9eAslSHXAxxu3VytGLl3FdhuyYZoGWZXi73zU6Wdw3/y705b7663CBoUpgW+EwoTrhyxaqcETvfe/eAh01WbLBQwRuC5A5AyQquv0TsqwJWj5iztHr2JBkASd0HlvIckGWJT0x1hPUF8rT1BVX5VLEnbVn6+eCa/yvhzJowSPp3pRbVcAqi4ZQUr2GFeBVUmZY/bJ3tW/EALAFrI+EFN4pyg85Uxx2zF2FGBRF2JSwLa651AMIPxyIQQZr4T/Qd7Vri8+CcYysdEQcZ8zjFjEyUwGIacOo/by7G4ZZDYbSns+Plbn5l0wf6K6NqBdE+ClpGwO9V4M/2HOf045BvOiKeBZnrLkBd9HuSjh5sr51zaBm0CZFvCxE9G4ZP3kGrZ2RgXPwPmxSkBFz5VVzeIALk69mDud6CFnZmHk0HtEOoO4XChGdSQbgOj5tHXITIlLaUNxq0NOuoIlMaifPNfCPnfVkDIFKEnzQgLOFdP0PLjnlpEvEdYbim/FrFrFoPBr8qgoyw/sd6OxJxCM6qU6y9hbHiH8mlJf9xPOXkEXliY4qETxb3HLI6DqSa2hZeph35tvqe8k+fyXEO/bbNb8B+8uAFSktirFB6gRPfsw5PKdHP23082bb2tdKTpCtwT2cK9W/bk67qofIuWizYiYrYwa6tyhnJ3VlTUt0WjmFSJEOwBLW0N+aRVLQY/N0ETiqpCuKhdkTiuY1xPfpqLARKue1ElQ==
  template:
    metadata:
      name: inadyn-values
      namespace: inadyn
    type: Opaque
