---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: inadyn-values
  namespace: inadyn
spec:
  encryptedData:
    values.yaml: AgCQAzCQeH1QMqRoHtf0F//TdCAGdMvyGuCxHAA82Hj/hhwpI1+v0hRFR1EpMkzzFkz0fv2vU+5DD1jTKydCuqTlAvgX9DZPBETQ9sx2MIasfHpL2BPQbp3LS7ivW4A/l9Giqm3xqF9Lu52wVftz2Jm5bLOuT8m5jE0jYlNW8965fMo5zqR5T4KHfvgFUc/t6E4CDUkVqvwL5adj0lgl3vCSs/SKvmwLem1F2qGBklotYITN2JGwc5/QgBzV4FuW28lLhEeLYL+iGZaF+CiAvd2zybbZXfsJaRF0H/fw2tZotyEHovf9zsrYQqdG0S2Q72+9cnVm24/SFboP51ePqggw0YrYguu8WliWNJpUMsj2m7tvoSfTIHjTDoYuPuNIkLJ2H8ktNtXp2wtL+2RIDnsrb3JNsA1zIPqJckR/8SWngLL29Ha8m21Egd0b75Koy3bqHArRSbTcs+Elh9RNhiNE0LU6kFUJOSn6e9nT6O0EI5R7foAWdZK7iLgmSijSIvMWKt9j0fjyyUwDxwMTfpg/JwiyvWddvbcXBcVH2o4fev17ExAqYmNWjLC5C3Wn3GIHBcYInQyYSddUsk8ntEA46DCzJ4EUpD3WlYAQKez4dnGDyxB8bWA/mFffStyDgB/NZlgrdwL8hbBGVFUFUBwvwq7t1lA9OMODOIUubYYfzUxXntCMi0XHMAsAeZF8NkDBZD0CEILQ2fvclVVrVLJyNLn0iVWDqWChERtUeerF8VaRXz/0sCJHzrArPgjqIzIJgVHOaAs1kiRMarNc4vPCDQ5gWu+bqpmR9WRa/7LJaF/ZhKA1r+8afcwdWHI/GO47gWZ9VZPIEv0sNsCPwvL4wUBK4RYSvd+hI6HPhMRe/HOZWpumC6CglpksefoE/ZUJd2GDs8thJNQb5mCuDyiNCgAJ2bHVpeyo5Az/7cjPworjZm1VzjzQ7Ftn1asq5sX9n4GqFms5aE4c49rYR7TeLwjDR3UcO354YS4JiSDCVHGNzYSx6WWQIndy5Z8I6NF5Og==
  template:
    metadata:
      name: inadyn-values
      namespace: inadyn
    type: Opaque
