---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: inadyn-values
  namespace: inadyn
spec:
  encryptedData:
    values.yaml: AgB9i5EZ/1VBQ5U+R3J1nDrG8ayehfwi1PfGHeWavLb8NDDrn3bj48kxmHVP4o8dqGL9AriGKoikUgTw44OoezpFPzfY+YwlPNT6Svw6oCIhPME/HA2+fLs74kZGt8eFw34ATVvXhVztcuAXh99jsJxxAIyiMhDOwzoVh0sgqWmn6A6TIe5biU9HWumCF0S60opF8zIfrqoTYXdOofUy0nKuK0c/P/UXNUiHoCJiItZjMLc54BkncSHyPfItZVNwx36NXVT58SLJxT4GtA7UTNjmet+o2YJlMKRGAxKLLD0RPdj5F+j9krccROJk3cXFe+lRPL12DubaGrAgUlqaSguN26ESOFNvENf8F0OBkOhPu2TvJTWsLGDTbQnqbzAi5uM2Wh1fLhKuVbOx1DYTL7BcEbkKHm7VIgITpD9fjawRkCZQkKtrUTTwrrXkugEx6SsiKfx3ABXvjjrkI9QVCnYhetduiailZuw/hpZBFqlHuoKlG6nKYTUt0xtsGthA3NiOgX+TfhJS/v1hgk5VBMuts21vVEVQtQJJ103luKrhZnlK1KK3Y8AgXxpDxstQm+6NKmwNl7dTdlz5EyZLyP/b+54IU2p0DA17d+KZcfWtUEg9nI/QhgoBoxCh6PxwIuJDpjM6isqtkDCj3uz1X91n/91/rvJ3kprly8ykyc28VqwH7NkBYOKlt9XACtE+Mj31GLGOYVXKboL0wo3ds4bJLxwv0PFYzzRfsdUEVeRnv3L7DGY5qzotZUqZZ1jUW+wtRAeF/ekE5O7wSzXLpN9mWa6yMfviOwfkKFLZIJjYrb6gl8huZfAATsqZKkrsytAO7+KORDgyRFf8FtPNbdSq2KY6F5C3gIkWaFeomF64lpgtQVt1QFwK3QDJoA9BYyXeS/lvqefn9WnejlttHkjH74Iu5D29Ew6PmOX5RTVPOCxNJBmcLGAEwwf8MvM8K3+uhNj0eQ5XqLeOI5tC3j+tKJNaNNiXY1jfrZYo5R+n88jo2akHoiYj6gJQ3th9TEedkA==
  template:
    metadata:
      name: inadyn-values
      namespace: inadyn
    type: Opaque
